### ISSUE TITLE
Criação de grupos (papéis)

### ISSUE THREAD

**Issue by jacksoncastro** [mapasculturais/mapasculturais#1010]
Níveis de acesso diferentes (visualização, edição etc) por grupo;

 - [ ] Cadastro de editais: curadores só podem ter acesso de visualização aos projetos inscritos. Hoje eles também podem editar, e isso é perigoso. Solução geral para a ferramenta: colocar níveis de acesso diferenciados (visualizar, editar, criar/excluir) para agentes dentro dos projetos, eventos, agentes e espaços

 - [ ] Editais: inscrições rascunhos só devem ser visualizadas e editadas por administradores. Hoje aparece para todos os agentes do projeto;

**Comment by leogermani** [comment]
@jacksoncastro apenas como curiosidade se vc tiver essa necessidade, dá uma olhada nesse plugin https://github.com/LibreCoopUruguay/ProjectCuradores
