### ISSUE TITLE
Ajustes Selos

### ISSUE THREAD

**Issue by marylly** [mapasculturais/mapasculturais#1050]
- [x] A validade será exibida na caixinha de informações do certificado do selo na entidade;
- [x] Ao expirar, o selo será exibido com uma imagem opaca e data de expiração na caixinha de informações do certificado;
- [ ] Um e-mail/notificação será enviado para ao portador do certificado informado que o selo expirará em n dias;
- [x] A quantidade de dias antes da validade do certificado será configurável, quando será notificado o portador do certificado antes da data de expiração;
- [x] Botão de "Renovar selo" será exibido na caixinha de informações do certificado ou na página do mesmo para o responsável pelo selo;
- [x] Botão de "Solicitar Renovação" será exibido na caixinha de informações do certificado ou na página do mesmo para o responsável pela entidade certificada.

Prazo: 20/01/2017

**Comment by leogermani** [comment]
Está pendente esse email de notificação de expiração? Fechamos essa tarefa e fazemos outra, se for o caso?
