### ISSUE TITLE
Desvincular módulo de editais da entidade projetos: fazer ser "plugável" em projetos e eventos

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1052]
depende de #1051

**Comment by Andreqlp** [comment]
ficou massa, a oportunidade pode ser vinculada em qualquer entidade (projeto, evento, agente e espaço).

**Comment by Andreqlp** [comment]
Só um ajuste no texto dos campos de configuração.

**Modelo atual (configurações padrão):**
Utilizar a aba de oportunidades?: 1
Nome da aba: Deixe em branco para utilizar a padrão

**Sugestão (configurações padrão):**
Utilizar a aba de oportunidades?: Sim
Nome da aba: Oportunidades
