### ISSUE TITLE
Desvincular módulo de editais da entidade projetos: migração dos dados dos editais atuais

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1054]
criar os editais baseados nos projetos com inscrições online e vinculá-los aos projetos existentes

depende de #1052

**Comment by Andreqlp** [comment]
No ambiente de desenvolvimento essas oportunidades não abriram:
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/341/
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/220/
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/338/

**Comment by rafaelchavesfreitas** [comment]
@Andreqlp testar novamente após os métodos de avaliação estiverem habilitados
