### ISSUE TITLE
migração dos editais atuais para este método de avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1065]
instanciar o método de avaliação simples para cada edital existente, relacionar o owner e os agentes relacionados ao projeto como avaliadores e instanciar as avaliações colocando como avaliador o owner do projeto.
depende de #1064

**Comment by Andreqlp** [comment]
No ambiente de desenvolvimento essas oportunidades não abriram:
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/341/
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/220/
http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/338/
