### ISSUE TITLE
Implementar método de avaliação "Avaliação Documental"

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1066]
colocar para cada campo da inscrição um checkbox e um textarea com preenchimento obrigatório quando o checkbox não for preenchido.

depende de #1060 #1061

**Comment by Andreqlp** [comment]
Não consegui fazer o teste. Criei uma oportunidade com do tipo ["avaliação documental"](http://mapas.culturalivre.org/oportunidade/16/), adicionei um avaliador, mas quando logava no [perfil desse avaliador](http://mapas.culturalivre.org/agente/62/) e tentava abrir a oportunidade aparecia o seguinte erro:

![erro inesperado quando tenteu entrar na oportunidade que era avaliador](https://user-images.githubusercontent.com/14170372/28443720-412b4e24-6d8e-11e7-8134-6c362fcc2ad7.png)

Um erro inesperado aconteceu

ErrorException: Invalid argument supplied for foreach() in /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php:51
Stack trace:
#0 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php(51): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/srv/mapas.cult...', 51, Array)
#1 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entities/Registration.php(739): MapasCulturais\EvaluationMethod->canUserEvaluateRegistration(Object(MapasCulturais\Entities\Registration), Object(MapasCulturais\Entities\User))
#2 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(286): MapasCulturais\Entities\Registration->canUserViewUserEvaluation(Object(MapasCulturais\Entities\User))
#3 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/Theme.php(2110): MapasCulturais\Entity->canUser('viewUserEvaluat...')
#4 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/views/opportunity/single.php(14): MapasCulturais\Themes\BaseV1\Theme->addOpportunityToJs(Object(MapasCulturais\Entities\ProjectOpportunity))
#5 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas.cult...')
#6 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(267): MapasCulturais\Theme->partialRender('opportunity/sin...', Array)
#7 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(217): MapasCulturais\Theme->fullRender('opportunity/sin...')
#8 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('opportunity/sin...', NULL)
#9 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('opportunity/sin...', NULL)
#10 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(755): Slim\View->display('opportunity/sin...')
#11 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(297): Slim\Slim->render('opportunity/sin...', Array)
#12 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(275): MapasCulturais\Controller->render('opportunity/sin...', Array)
#13 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\EntityController->GET_single()
#14 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'single', Array)
#15 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'single', Array, false)
#16 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#17 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#18 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#19 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#20 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#21 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
#22 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
#23 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#24 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#25 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(518): Slim\Slim->run()
#26 /srv/mapas.culturalivre.org/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#27 {main}
(GET) /oportunidade/16/ - executed in 0.1288 seconds. (MEM: 4MB)

**Comment by Andreqlp** [comment]
Fiz uma segunda tentativa com uma [nova oportunidade](http://mapas.culturalivre.org/oportunidade/17/) e [outro avaliador](http://mapas.culturalivre.org/agentes/edita/63/) e o erro persistiu.

Um erro inesperado aconteceu

ErrorException: Invalid argument supplied for foreach() in /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php:51
Stack trace:
#0 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php(51): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/srv/mapas.cult...', 51, Array)
#1 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entities/Registration.php(739): MapasCulturais\EvaluationMethod->canUserEvaluateRegistration(Object(MapasCulturais\Entities\Registration), Object(MapasCulturais\Entities\User))
#2 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(286): MapasCulturais\Entities\Registration->canUserViewUserEvaluation(Object(MapasCulturais\Entities\User))
#3 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/Theme.php(2110): MapasCulturais\Entity->canUser('viewUserEvaluat...')
#4 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/views/opportunity/single.php(14): MapasCulturais\Themes\BaseV1\Theme->addOpportunityToJs(Object(MapasCulturais\Entities\ProjectOpportunity))
#5 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas.cult...')
#6 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(267): MapasCulturais\Theme->partialRender('opportunity/sin...', Array)
#7 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(217): MapasCulturais\Theme->fullRender('opportunity/sin...')
#8 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('opportunity/sin...', NULL)
#9 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('opportunity/sin...', NULL)
#10 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(755): Slim\View->display('opportunity/sin...')
#11 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(297): Slim\Slim->render('opportunity/sin...', Array)
#12 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(275): MapasCulturais\Controller->render('opportunity/sin...', Array)
#13 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\EntityController->GET_single()
#14 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'single', Array)
#15 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'single', Array, false)
#16 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#17 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#18 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#19 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#20 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#21 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
#22 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
#23 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#24 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#25 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(518): Slim\Slim->run()
#26 /srv/mapas.culturalivre.org/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#27 {main}
(GET) /oportunidade/17/ - executed in 0.1060 seconds. (MEM: 4MB)
