### ISSUE TITLE
gerente da oportunidade deve poder EDITAR uma avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1074]

**Comment by Andreqlp** [comment]
Consegui editar uma vez, mas depois que [apareceu o erro para o avaliador](https://github.com/hacklabr/mapasculturais/issues/1066#issuecomment-316864151) deu ruim para o gerente também. Ficou assim:

Oportunidade: http://mapas.culturalivre.org/oportunidade/16 
Gerente: http://mapas.culturalivre.org/agente/59/

![erro-gerente](https://user-images.githubusercontent.com/14170372/28444540-4f2370be-6d94-11e7-874e-bcbe228f5d97.png)

Um erro inesperado aconteceu

ErrorException: Invalid argument supplied for foreach() in /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php:51
Stack trace:
#0 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/EvaluationMethod.php(51): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/srv/mapas.cult...', 51, Array)
#1 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entities/Registration.php(739): MapasCulturais\EvaluationMethod->canUserEvaluateRegistration(Object(MapasCulturais\Entities\Registration), Object(MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\User))
#2 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(286): MapasCulturais\Entities\Registration->canUserViewUserEvaluation(Object(MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\User))
#3 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entities/Opportunity.php(282): MapasCulturais\Entity->canUser('viewUserEvaluat...', Object(MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\User))
#4 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/Theme.php(1994): MapasCulturais\Entities\Opportunity->getEvaluations(true)
#5 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--admin--table.php(1): MapasCulturais\Themes\BaseV1\Theme->addOpportunityEvaluationsToJs(Object(MapasCulturais\Entities\ProjectOpportunity))
#6 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas.cult...')
#7 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(387): MapasCulturais\Theme->partialRender('singles/opportu...', Array, true)
#8 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations.php(3): MapasCulturais\Theme->part('singles/opportu...', Array)
#9 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas.cult...')
#10 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(387): MapasCulturais\Theme->partialRender('singles/opportu...', Array, true)
#11 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/themes/BaseV1/views/opportunity/single.php(82): MapasCulturais\Theme->part('singles/opportu...', Array)
#12 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas.cult...')
#13 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(267): MapasCulturais\Theme->partialRender('opportunity/sin...', Array)
#14 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(217): MapasCulturais\Theme->fullRender('opportunity/sin...')
#15 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('opportunity/sin...', NULL)
#16 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('opportunity/sin...', NULL)
#17 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(755): Slim\View->display('opportunity/sin...')
#18 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(297): Slim\Slim->render('opportunity/sin...', Array)
#19 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(275): MapasCulturais\Controller->render('opportunity/sin...', Array)
#20 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\EntityController->GET_single()
#21 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'single', Array)
#22 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'single', Array, false)
#23 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#24 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#25 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#26 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#27 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#28 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
#29 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
#30 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#31 /srv/mapas.culturalivre.org/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#32 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(518): Slim\Slim->run()
#33 /srv/mapas.culturalivre.org/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#34 {main}
(GET) /oportunidade/16/ - executed in 0.1364 seconds. (MEM: 4MB)

**Comment by rafaelchavesfreitas** [comment]
aparentemente é o mesmo erro relatado na #1066 e já corrigido
