### ISSUE TITLE
formulário para recurso em cada fase do edital

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1075]
Implementar formulário para o responsável pela inscrição entrar com recurso ao término de cada fase do edital. Será baseado na funcionalidade de Denúncia/Sugestão.

**Comment by Andreqlp** [comment]
Existe o botão mas não está funcionando. Clica mas não sai do canto.
Oportunidade: http://mapas.culturalivre.org/oportunidade/19/
Agente: http://mapas.culturalivre.org/agente/63/

![erro - botao solictar recurso](https://user-images.githubusercontent.com/14170372/28447073-fc5f4ec8-6da4-11e7-89d7-2f8cd7c98cb0.png)
