### ISSUE TITLE
definir texto da seção "oportunidades" da home

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1082]

**Comment by marylly** [comment]
@Andreqlp

**Comment by Andreqlp** [comment]
TEXTO DA PÁGINA PRINCIPAL:

OPORTUNIDADES:

Faça a sua inscrição ou acesse o resultado de diversas convocatórias como editais, oficinas, prêmios e convocatórias. Você também pode criar o seu próprio formulário e divulgar uma oportunidade para outros agentes culturais.

**Comment by Andreqlp** [comment]
Categorias para entidade oportunidade: https://docs.google.com/spreadsheets/d/1gL0QpGkVLqc5QSqnXiKCRgOApeE1BQt4p2DRt_E3qI4/edit#gid=0

**Comment by Andreqlp** [comment]
Uma pequena alteração no texto:

Faça a sua inscrição ou acesse o resultado de diversas convocatórias como editais, oficinas,  prêmios e concursos. Você também pode criar o seu próprio formulário e divulgar uma oportunidade para outros agentes culturais.
