### ISSUE TITLE
definir ícone para oportunidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1083]

**Comment by marylly** [comment]
@Andreqlp

**Comment by Andreqlp** [comment]
Cor de fundo da home: #ED2CD4

Logo no formato png:
![logo oportunidade branco](https://cloud.githubusercontent.com/assets/14170372/23503914/4d936c86-ff1c-11e6-86fd-a5f8effe3ca7.png)
![logo oportunidade preto](https://cloud.githubusercontent.com/assets/14170372/23503915/4d93c758-ff1c-11e6-9f1d-4ab5e61de0ca.png)
