### ISSUE TITLE
Usuário comum não recebe feedback quando cria ou salva nova entidade

### ISSUE THREAD

**Issue by ricardopoppi** [mapasculturais/mapasculturais#1106]
Também acontece quando adiciona novo administrador a uma entidade.

Para replicar:
1) Cria uma nova entidade (agente ou espaço)
2) Preenche os campos obrigatórios
3) Publicar (aparece mensagem de "Um erro inesperado aconteceu"
4) Clicar no botão cancelar e ok para sair da página
5) Liste os agentes e verá que o novo agente foi criado

Na prática pela ausencia de feedback, os usuários criam dezenas de agentes iguais, por ficar apertando o botão de publicar insistentemente

Ao adicionar um administrador a um agente existente, o mesmo problema se repete. Ao clicar no avatar do novo admin ao adicionar, ele não dá feedback mas adiciona, o que pode ser comprovado salvando o agente e recarregando a página

area:USER-EXPERIENCE
instalação:RedeLivre
tipo:BUG

**Comment by daphnemartinsba** [comment]
Na atual versão, v5.1.47, o comportamento está diferente do descrito.
Criação de agente:
![CriacaoagentePeek 16-02-2022 12-23](https://user-images.githubusercontent.com/75261677/154297001-3217bf3e-03c3-4252-a5ce-467baf473c0b.gif)
Criação do Espaço:
![criacaoespacoPeek 16-02-2022 12-23](https://user-images.githubusercontent.com/75261677/154297040-75c3e851-83bc-4a3d-8944-fb2b94cf28ab.gif)

Adicionando Administrador ao Agente com perfil de Admin/Superadmin:
![adicionandoadmadmPeek 16-02-2022 12-33](https://user-images.githubusercontent.com/75261677/154300403-04c75bf4-2efb-4cf6-8410-db642cd20cb6.gif)
Adicionando Administrador ao Agente com perfil de permissão Normal:
![adicionandoadmnormalPeek 16-02-2022 12-36](https://user-images.githubusercontent.com/75261677/154300466-d77c2177-0a4a-48ab-9cc4-8c0ee2e9c428.gif)
