### ISSUE TITLE
Opção "sair" de subsite do saas não reflete logout no login cidadão (id.org.br)

### ISSUE THREAD

**Issue by ricardopoppi** [mapasculturais/mapasculturais#1108]
Quando usuário clica em "sair" no subsite (ex: http://quebradasp.mapas.culturalivre.org/) esse ato não reflete no login cidadão, mantendo-o logado no id.org.br.

Isso gera confusão se o usuário quer logar com outro usuário

area:INFRA
instalação:RedeLivre
tipo:AJUSTE

**Comment by uira** [comment]
Essa demanda tem a ver com essa outra: https://github.com/hacklabr/mapasculturais/issues/1246
