### ISSUE TITLE
formulário de avaliação: botão finalizar avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1130]
define o status da avaliação como avaliada

entao teremos os seguintes status da avaliação:
  - RASCUNHO (quando for salva automaticamente, antes de clicar o botão)
  - AVALIADA ( botão finalizar foi apertado )
  - ENVIADA (depois do botão enviar avaliações ter sido enviado - deve bloquear a edição)

**Comment by Andreqlp** [comment]
Rafa, foi um erro meu pq não tinha percebido que o botão de avaliação só aparecia depois que o período de inscrição tivesse sido finalizado.
