### ISSUE TITLE
Ativar SSO

### ISSUE THREAD

**Issue by uira** [mapasculturais/mapasculturais#1246]
Galera, não dava pra ter uma condição no mapas pra detectar se a pessoa está logada no Login Cidadão ou no ID-Cultura-velho, e aí já carregar a sessão logada?

É um cookie talvez?

**Comment by leogermani** [comment]
@guilhermednt

**Comment by guilhermednt** [comment]
O Session Management ainda está em draft: https://openid.net/specs/openid-connect-session-1_0.html

**Comment by uira** [comment]
up

**Comment by uira** [comment]
@guilhermednt, alguma novidade sobre isso?

**Comment by guilhermednt** [comment]
Ainda em draft... :/
