### ISSUE TITLE
A aba de oportunidade não apareceu na entidade espaço

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1256]
Mesmo configurando a oportunidade, a aba não aparece na entidade espaço. Testado em: http://mapas.culturalivre.org/espaco/12

![mapa_aba no espaco nao aparece](https://user-images.githubusercontent.com/14170372/28212924-250c503a-687a-11e7-91d2-fcbcd358ed25.png)

![mapa-nao apereceu a aba oprtunidade no espaco](https://user-images.githubusercontent.com/14170372/28212974-5450680e-687a-11e7-9133-038dda294425.png)

**Comment by daphnemartinsba** [comment]
No ambiente de dev do PA, na atual versão do Mapas [v5.1.47], a aba oportunidade aparece no Espaço quando uma oportunidade é criada com vínculo neste Espaço:
![image](https://user-images.githubusercontent.com/75261677/153056436-4a25fe5e-afb3-4d30-8262-4256198a00e5.png)
