### ISSUE TITLE
Retirar o padrão de tipo e título da criação da oportunidade

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1257]
Ao criar uma oportunidade o sistema já seleciona por padrão o tipo "Festival" e o nome "Nova oportunidade". Modificar para o padrão utilizado no mapas:

Selecione um tipo
Nome de exibição

![mapa_preenchimento automatico do tipo de oportunidade](https://user-images.githubusercontent.com/14170372/28213036-b2780b3a-687a-11e7-81b2-5a696472d0d5.png)

**Comment by rafaelchavesfreitas** [comment]
é possível que não seja possível por enquanto :/

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.47](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.47) do Mapas Culturais, na criação da Oportunidade, não há nome de Oportunidade pré-setado. O tipo agora vem setado em abaixo-assinado (a primeira opção do campo de seleção, cuja organização é  em ordem alfabética):
![image](https://user-images.githubusercontent.com/75261677/153058368-be284b49-9193-4ef7-bb53-75d639ac62ad.png)
