### ISSUE TITLE
Incluir no cabeçalho da tabela de avaliação a opção todas opções

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1258]
Esta faltando o cabeçalho a opção "Todas opções" e ela deve estar marcada com padrão.

![mapa_opcao de exibir todas as categorias](https://user-images.githubusercontent.com/14170372/28213329-f3a14954-687b-11e7-9f84-0c7d01a41a9b.png)

**Comment by rafaelchavesfreitas** [comment]
apreveitei e corrigi a exibição da lista de cactegorias
