### ISSUE TITLE
Sequência de confirmações de salvar

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1260]
Estava mexendo nas notas e uma hora apareceram várias confirmações de salvar, praticamente um combo do mortal kombat kkk. Depois elas sumiram e o sistema voltou ao normal.

![mapa_bugou no salvar](https://user-images.githubusercontent.com/14170372/28213661-77ff4dc6-687d-11e7-9f22-89134b3ad6b7.png)

**Comment by rafaelchavesfreitas** [comment]
este comportamento se repete em todos os lugares não  só nos editais.
