### ISSUE TITLE
coluna com o resultado consolidado da avaliação na planilha de inscrições

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1264]

**Comment by Andreqlp** [comment]
ver #1258

**Comment by rafaelchavesfreitas** [comment]
@Andreqlp não entendi. Esta issue se trata de uma coluna com o resultado final das avaliações, consolidado das avaliações de todos avaliadores, na planilha exportada das inscrições. Para testar tem que exportar a planilha com as inscrições.
