### ISSUE TITLE
Salvar as configurações da oportunidade ao clicar o botão criar oportunidade

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1267]
Sugestão de salvar automaticamente as configurações da aba oportunidade quando clicar no botão "criar oportunidade" do contrário vai aparecer um lembrete perguntado se o usuário quer realmente sair página aberta sem salvar as configurações.

![erro-configuracao nao salva automaticamente e se clicar vai questionar](https://user-images.githubusercontent.com/14170372/28447493-715d9872-6da7-11e7-9ba4-39408113be71.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.47](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.47) a criação da oportunidade se dá pelo painel de controle, alterando esse fluxo, portanto, o comportamento descrito não ocorre mais.
