### ISSUE TITLE
A opção de filtro nas abas inscritos e avaliações estão integradas

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1287]
Se você selecionar um status da inscrição (pendente, inválida, não selecionada...) na aba inscrições o resultado da aba avaliações deixa de aparecer. É preciso desvincular o filtro nessas duas abas.
http://dev-mapa.cultura.ce.gov.br/oportunidade/149/#tab=evaluations 

![2-2](https://user-images.githubusercontent.com/14170372/29843835-9b0ef142-8ce3-11e7-8507-76241dd95b41.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.47](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.47) do Mapas, no ambiente de desenvolvimento do PA, ocorre comportamento adequado, diferente do descrito na Issue ( que foi o comportamento de quando a issue foi criada). Segue o gif do comportamento atual:
![Issue 1287Peek 09-02-2022 12-50](https://user-images.githubusercontent.com/75261677/153238262-499f1540-d2be-4aca-8702-32f0f37fb791.gif)
