### ISSUE TITLE
O gerente do projeto não deve avaliar se não estiver na lista de avaliadores da oportunidade

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1288]
O gerente do projeto pode ir na aba inscritos, clicar sobre o número de inscrição e fazer uma avaliação do projeto, mas a sua avaliação não aparece na aba avaliações. 
O gerente só pode avaliar uma inscrição se estiver na lista dos avaliadores.

![2-3](https://user-images.githubusercontent.com/14170372/29843913-ea8eb1ee-8ce3-11e7-8d40-04be516dc45b.png)

**Comment by daphnemartinsba** [comment]
Essa issue está relacionada a definição do fluxo: Se gestão poderá ser também avaliador. Contemplada pela issue: #1870.
