### ISSUE TITLE
Na tabela está aparecendo a palavra “responsável” quando deveria aparecer os nomes dos agentes inscritos

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1315]
Tela: http://dev-mapa.cultura.ce.gov.br/oportunidade/771/#tab=evaluations 
Inscrição: http://dev-mapa.cultura.ce.gov.br/inscricao/1915564090/ 

![07](https://user-images.githubusercontent.com/14170372/33136236-83b51dc2-cf83-11e7-8482-cf5195014980.png)

**Comment by Andreqlp** [comment]
Na verdade deveria aparecer em baixo da palavra "responsável" o nome do agente da inscrição. A exemplo de como aparece na tela do coordenador

![avalidaro](https://user-images.githubusercontent.com/14170372/34262095-13fdec10-e64a-11e7-86fa-c3891563def7.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.48](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.48) do Mapas, os nomes dos Agentes Responsáveis aparecem tanto na tabela da aba de inscritos:
![image](https://user-images.githubusercontent.com/75261677/154740095-bc331678-c190-4bab-abd6-5e6c1e3eed37.png)

quanto na tabela da aba de avaliações:
![image](https://user-images.githubusercontent.com/75261677/154740139-824a054b-6d7b-4124-a03b-e7a8c53d6234.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.48](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.48) do Mapas, os nomes dos Agentes Responsáveis aparecem tanto na tabela da aba de inscritos:
![image](https://user-images.githubusercontent.com/75261677/154740095-bc331678-c190-4bab-abd6-5e6c1e3eed37.png)

quanto na tabela da aba de avaliações:
![image](https://user-images.githubusercontent.com/75261677/154740139-824a054b-6d7b-4124-a03b-e7a8c53d6234.png)
