### ISSUE TITLE
Aceitar qualquer tipo de URL no cadastro de Link

### ISSUE THREAD

**Issue by valessiobrito** [mapasculturais/mapasculturais#1343]
Atualmente o ambiente esta filtrando/aceitando somente URLs comum;  Porém, agora com domínios onde o primeiro nível não é mais o popularmente conhecido como .com, .net ou .org um usuário poderia consegui cadastrar qualquer URL.

Tentei cadastrar bit.ly  ou  cnpq.br  e ambos não foram permitidos.

**Comment by asaferamos** [comment]
Fiz um teste aqui e está ok. O link está sendo cadastrado com o 'http://' no início?

**Comment by daphnemartinsba** [comment]
Na versão v5.1.49 do Mapas Culturais a inserção dos links citados com o http (ou https) funcionam. 
Contudo, se, ao realizar a inserção de um link digitar somente "cnpq.br", de fato, o link não será inserido. Para que dê certo sua URL deve ser pelo menos copiada.
