### ISSUE TITLE
Definir visibilidade dos campos em um perfil ou dados do equipamento

### ISSUE THREAD

**Issue by valessiobrito** [mapasculturais/mapasculturais#1344]
Atualmente alguns campos são invisível por padrão e outros exibido, porém, como usuário gostaria de definir o que deveria esta visível ou privado.

Exemplo: atualmente o telefone esta padrão visível para todos, porém gostaria que fosse privado.  Já o email esta invisível e em meu caso utilizar ele é melhor forma de comunicação, ou seja, gostaria que fosse público.

**Comment by marcus2703** [comment]
Existe opção de telefone e e-mail público na edição das informações já, bem como as mesmas informações privadas.

![image](https://user-images.githubusercontent.com/12901157/36424335-b3876f2a-1621-11e8-9937-942fb34e0155.png)

**Comment by valessiobrito** [comment]
@marcus2703 a proposta é por exemplo, como usuário clicar nesse icone de cadeado (privado) e abrir para visibilidade ou fechar;  Enfim, a administradora do ambiente ou um usuário definir a privacidade dessas informações;  Podemos avaliar como uma flag até para uso na extração de "dados abertos" respeitando a privacidade do usuário;

**Comment by daphnemartinsba** [comment]
A Issue será contemplada na adequação do Mapas Culturais, que está em andamento, de acordo com a Lei Geral de Proteção de Dados.
