### ISSUE TITLE
Faltando Oportunidades no customizador do Tema

### ISSUE THREAD

**Issue by uira** [mapasculturais/mapasculturais#1351]
![captura de tela 2018-03-19 as 14 26 41](https://user-images.githubusercontent.com/89998/37611684-c6f697e6-2b81-11e8-90ab-73c5dc3e853a.png)

**Comment by uira** [comment]
@rafaelchavesfreitas vi isso resolvido... teria sido um sonho?

**Comment by daphnemartinsba** [comment]
Na versão v5.1.49 do Mapas Culturais as oportunidades estão inclusas no customizador do Tema. Segue a imagem do ambiente de desenvolvimento do PA:
![image](https://user-images.githubusercontent.com/75261677/155603181-4012f205-2f4c-4af1-868e-f418c4206489.png)
