### ISSUE TITLE
Inserir campo de texto no módulo de avaliação simplificado

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1367]
Falta no módulo de avaliação simplificada um campo de texto para a pessoa inserir observações sobre a avaliação. 

![s02 inserir campo de texto](https://user-images.githubusercontent.com/14170372/38623936-4464e298-3d7d-11e8-8c0b-cb73832cbb94.png)

No lado direito da imagem só tem a opção de caixa de seleção. A sugestão é ter uma caixa de texto logo abaixo.O campo deve ser de preenchimento opcional, ou seja, a pessoa pode avançar a avaliação com ele embranco.

![s01](https://user-images.githubusercontent.com/14170372/38624157-ce6b0f94-3d7d-11e8-9902-81c31cd3b31e.png)

Lembrar de alterar o texto de apresentação para esse:

**Avaliação Simplificada**
Consiste numa caixa de seleção para indicar o resultado da avaliação e uma caixa de texto para observações.

**Comment by daphnemartinsba** [comment]
Na versão v5.1.49, no ambiente de teste do Pará, a avaliação simplificada possui campo de texto para inserir justificativa:
![image](https://user-images.githubusercontent.com/75261677/155732108-31f0a582-19b3-4ec6-844d-7715440d717d.png)
Quando ao texto da avaliação simplificada, já há uma issue aberta: #1305
