### ISSUE TITLE
Erro na atualização do horario de acesso

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1451]
Fui acessar as atividades do Agente Individual Talita Maciel (https://mapacultural.secult.ce.gov.br/agente/5326/), a informação do ultimo login feito é 13/06/2017, sendo que ontem ela acessou o seu perfil para fazer a inscrição para jurado e presidente de mesa do ceará junino 2019. O registro só aparece na lista de atividades. Segue o print onde a informações aparecem diferentes. Outra coisa é que a data aparece estranha ex.: 06 - 46 - 2019

![image](https://user-images.githubusercontent.com/39064345/59377743-3ee6cf00-8d29-11e9-84f7-e0744e4639d0.png)

**Comment by daphnemartinsba** [comment]
Na atual versão do Mapas Culturais, v5.1.50, foi observado, pelo ambiente de dev do PA que os horários estão de acordo com o comportamento esperado:
![image](https://user-images.githubusercontent.com/75261677/155986811-95d1ed08-d8c1-4dfd-a2da-d0a28c328385.png)
Um outro registro:
![image](https://user-images.githubusercontent.com/75261677/155987225-37076029-2ba0-4372-97b0-d6310e2b111d.png)
