### ISSUE TITLE
[AJUDA] Trying to access array offset on value of type null (DocParser.php)

### ISSUE THREAD

**Issue by bbicudo** [mapasculturais/mapasculturais#1461]
Estou tentando fazer rodar o sistema, porém recebo este erro do Slim quando acesso o servidor:

[Slim Application Error.pdf](https://github.com/mapasculturais/mapasculturais/files/5029230/Slim.Application.Error.pdf)

(Fiz upload em PDF pra facilitar a leitura)

Podem me dar uma luz?

**Comment by victinizekrom** [comment]
Você está utilizando a versão 1.7.0 do Doctrine/Annotations ? 

https://github.com/doctrine/annotations/issues/273

Aparentemente eles arrumaram o erro na versão 1.7.0.

**Comment by bbicudo** [comment]
@victinizekrom Não tenho palavras pra agradecer amigo! Consegui finalmente ver a carinha linda do index da aplicação.

Agora só preciso descobrir porque está carregando as outras páginas assim:
![Capturar](https://user-images.githubusercontent.com/22198380/89562466-5ec03880-d7f0-11ea-9d36-576617891840.PNG)

**Comment by bbicudo** [comment]
Verifiquei que os arquivos js da pasta assets/js não existem (ou não foram criados na instalação). Como posso proceder?

**Comment by Leordo** [comment]
Bom dia, também estou com esse problema, na instalação, alguém saberia como proceder ?
