### ISSUE TITLE
[login - Google] - Utilizar o nome do usuário do google para o usuário do mapas

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1504]

**Comment by daphnemartinsba** [comment]
Na atual versão do Mapas Culturais, [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50), no ambiente de teste, há a utilização do nome do usuário do google para o usuário do Mapas, segue o gif do funcionamento:
![issue loginPeek 28-02-2022 11-45](https://user-images.githubusercontent.com/75261677/156003174-b851fd05-6acc-4d95-a21f-bbd815f389a3.gif)
