### ISSUE TITLE
Oportunidade não é Excluída da Lixeira

### ISSUE THREAD

**Issue by edsongs** [mapasculturais/mapasculturais#1521]
**Slim Application Error**

The application could not run because of the following error:
Details
Type: Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException
Message: An exception occurred while executing 'DELETE FROM opportunity WHERE id = ?' with params [2]: SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "opportunity" violates foreign key constraint "fk_209c792e9a34590f" on table "registration_file_configuration" DETAIL: Key (id)=(2) is still referenced from table "registration_file_configuration".
File: /var/www/html/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
Line: 48
Trace

#0 /var/www/html/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/html/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1063): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM opp...', Array)
#3 /var/www/html/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(656): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM opp...', Array, Array)
#4 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(598): Doctrine\DBAL\Connection->delete('opportunity', Array, Array)
#5 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1186): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(MapasCulturais\Entities\ProjectOpportunity))
#6 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(409): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#7 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
#8 /var/www/html/protected/application/lib/MapasCulturais/Entity.php(720): Doctrine\ORM\EntityManager->flush()
#9 /var/www/html/protected/application/lib/MapasCulturais/Entities/File.php(503): MapasCulturais\Entity->delete(true)
#10 /var/www/html/protected/application/lib/MapasCulturais/DoctrineProxies/__CG__MapasCulturaisEntitiesOpportunityFile.php(368): MapasCulturais\Entities\File->_preRemove(Object(Doctrine\ORM\Event\LifecycleEventArgs))
#11 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php(102): MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\OpportunityFile->_preRemove(Object(Doctrine\ORM\Event\LifecycleEventArgs))
#12 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1843): Doctrine\ORM\Event\ListenersInvoker->invoke(Object(Doctrine\ORM\Mapping\ClassMetadata), 'preRemove', Object(MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\OpportunityFile), Object(Doctrine\ORM\Event\LifecycleEventArgs), 2)
#13 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2391): Doctrine\ORM\UnitOfWork->doRemove(Object(MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities\OpportunityFile), Array)
#14 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1828): Doctrine\ORM\UnitOfWork->cascadeRemove(Object(MapasCulturais\Entities\ProjectOpportunity), Array)
#15 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1799): Doctrine\ORM\UnitOfWork->doRemove(Object(MapasCulturais\Entities\ProjectOpportunity), Array)
#16 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(615): Doctrine\ORM\UnitOfWork->remove(Object(MapasCulturais\Entities\ProjectOpportunity))
#17 /var/www/html/protected/application/lib/MapasCulturais/Entity.php(718): Doctrine\ORM\EntityManager->remove(Object(MapasCulturais\Entities\ProjectOpportunity))
#18 /var/www/html/protected/application/lib/MapasCulturais/Traits/EntitySoftDelete.php(110): MapasCulturais\Entity->delete(true)
#19 /var/www/html/protected/application/lib/MapasCulturais/Traits/ControllerSoftDelete.php(39): MapasCulturais\Entities\Opportunity->destroy(true)
#20 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\Opportunity->GET_destroy()
#21 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(168): MapasCulturais\Controller->callAction('GET', 'destroy', Array)
#22 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'destroy', Array, false)
#23 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#24 /var/www/html/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#25 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#26 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#27 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#28 /var/www/html/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): Slim\Middleware\MethodOverride->call()
#29 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#30 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#31 /var/www/html/protected/application/lib/MapasCulturais/App.php(556): Slim\Slim->run()
#32 /var/www/html/index.php(4): MapasCulturais\App->run()
#33 /var/www/html/router.php(27): include_once('/var/www/html/i...')
#34 {main}

**Comment by rafaelchavesfreitas** [comment]
resolvido no commit: https://github.com/mapasculturais/mapasculturais/commit/85a900f5f8ba1969297b6490120426fc93a65191
