### ISSUE TITLE
impedir que a barra que exibe mensagem de erro / sucesso cresça quando exibe a mensagem

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1552]
![barra (editable-entities) que muda de tamanho](https://user-images.githubusercontent.com/1181261/93130917-a6689880-f6a9-11ea-8a62-01da19d1cab0.gif)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, no ambiente de dev do ES, PA e MS, a barra que exibe a mensagem de erro não cresce conforme aparece a mensagem.

No dev do MS, a mensagem de erro:
![image](https://user-images.githubusercontent.com/75261677/156041877-b0db511e-eaf0-4f0a-8dc7-98a69b5b3542.png)

No dev do MS, a mensagem de salvo:
![image](https://user-images.githubusercontent.com/75261677/156042320-87cb88f0-ed77-4a9f-a19a-b1d1f4f69c1f.png)
