### ISSUE TITLE
O campo opções (Categoria) não está funcionando.

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1557]
O campo opções não está funcionando. A listagem configurada é exibida para o usuário mas após selecionar uma opção o questionario não muda, de modo que só são apresentadas campos assinalados para aparecerem em todas as opções.

> https://homolog.mapacultural.secult.ce.gov.br/oportunidade/2335/

![Captura de tela de 2020-09-17 09-39-17](https://user-images.githubusercontent.com/14170372/93471619-f9b93180-f8c9-11ea-90af-6e0cd8a2106b.png)

**Comment by Junior-Shyko** [comment]
Em um teste que eu fiz, nem mesmo os campos para todas as categorias estavam funcionando.

**Comment by benrainir** [comment]
Não sabemos reproduzir o erro. Aguardo mais detalhes @Andreqlp

**Comment by AleffBruno** [comment]
Este correção foi em homolog

**Comment by VaneCabral** [comment]
Acessando a previsualização da oportunudade (https://homolog.mapacultural.secult.ce.gov.br/inscricoes/preview/opportunityId:2335/) ao tentar escolher as opções de categoria (um dois tres) a plataforma não aceita e voltar a deixar o espaço em branco.

**Comment by benrainir** [comment]
Previsão 23/09

**Comment by AleffBruno** [comment]
> 
> 
> Acessando a previsualização da oportunudade (https://homolog.mapacultural.secult.ce.gov.br/inscricoes/preview/opportunityId:2335/) ao tentar escolher as opções de categoria (um dois tres) a plataforma não aceita e voltar a deixar o espaço em branco.

Corrigido, favor, verificar novamente.
