### ISSUE TITLE
Os campos de troca do agente responsavel, instituição responsável e coletivo não estão funcionando.

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1558]
Dentro da inscrição não aparece nenhuma opção para a troca do agente responsável, seleção da instituição ou coletivo, mesmo vc você tenha estes tipos de agente no perfil ou que possa indicar no caso da instituição ou coletivo outros perfis existentes na plataforma. 

> https://homolog.mapacultural.secult.ce.gov.br/oportunidade/2335/

![Captura de tela de 2020-09-17 00-06-57](https://user-images.githubusercontent.com/14170372/93472829-99c38a80-f8cb-11ea-932f-2b06cec7222b.png)

**Comment by benrainir** [comment]
![image](https://user-images.githubusercontent.com/750277/94014038-5cef0c00-fd81-11ea-8f37-214de52aa950.png)

**Comment by benrainir** [comment]
O sistema esta buscando os agentes normalmente

**Comment by VaneCabral** [comment]
Issue revisada e testada, tudo ok!
