### ISSUE TITLE
[Bug] Erro ao escolher o quadro do inciso I quando o usuário só possui um agente coletivo.

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1559]
![image](https://user-images.githubusercontent.com/71461460/93513825-c9d75180-f8fc-11ea-8f62-03eff254168e.png)
![image](https://user-images.githubusercontent.com/71461460/93513857-d8256d80-f8fc-11ea-869a-997b1669922a.png)

**Comment by DanylloArajo** [comment]
Contexto:
Um usuário que possui apenas um agente coletivo entrar no Ambiente de Inscrição LAB e tenta fazer sua inscrição no quadro do inciso I. Ao clicar no quadro, é exibido o erro.

Comportamento esperado:
Quando um usuário novo cria uma conta e entra diretamente no Ambiente de Inscrição LAB, ao escolher o quadro de inciso I, por baixo dos panos já é criado um agente individual para ele. O comportamento esperado para o caso de ser um usuário que possui apenas um AGENTE COLETIVO deve ser mesmo, ou seja, deve ser criado um agente individual para este usuário, seguindo o mesmo padrão citado.

**Comment by VaneCabral** [comment]
@AleffBruno nao esquece de colocar aqui nos comentarios a previsão de solução para esse bug relatado. Obrigada

**Comment by willowmagrini** [comment]
Solução no repositorio do plugin: https://github.com/mapasculturais/plugin-AldirBlanc/commit/11a418f33ab21b5f16b708928d558226aaedf9c4#diff-44e2c1f78b9202a4525aacb600784b29
