### ISSUE TITLE
[Login] Usuários novos que fazem o login sem validar o email são direcionados para o cadastro base de agente.

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1560]
Criar novo usuário a partir do link de cadastro do plugin LAB.
Na mesma tela, sem validar o email, fazer login.
O usuário é direcionado para o cadastro do agente, ao invés de ser direcionado para o ambiente de inscrição LAB.

**Comment by VaneCabral** [comment]
Teste feito!
