### ISSUE TITLE
[Inciso 2] O sistema está permitinado a inscrição antes da data de início

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1568]
Fortaleza configurou o início das inscrições do inciso 2 para o dia 21/09 e fez a [publicação da oportunidade (2215)](https://mapacultural.secult.ce.gov.br/oportunidade/2215). Quando entro na inscrição da lei Aldir Blanc a cidade aparece na listagem e vc consegue selecionar e avançar no formulário. [Aqui o link da inscrição inicada](https://mapacultural.secult.ce.gov.br/aldirblanc/formulario/2082180707/)

O sistema deveria informar a data de abertura para o usuario assim que ele selecionasse a cidade e clicasse em avança, sem deixá-lo continuar com a inscrição. Diferente do que aconteceu na imagem abaixo.

![Captura de tela de 2020-09-18 14-29-17](https://user-images.githubusercontent.com/14170372/93627981-2b122a00-f9bc-11ea-8488-bfd4b60bee06.png)

**Comment by benrainir** [comment]
Previsão - 22/09/2020

**Comment by benrainir** [comment]
![WhatsApp Image 2020-09-22 at 11 55 06](https://user-images.githubusercontent.com/750277/93899454-b6483400-fcca-11ea-9b06-11d31ea476ee.jpeg)

**Comment by VaneCabral** [comment]
Bug revisando e está ok!
