### ISSUE TITLE
[Bug] Erro na validação do campo "Área Cultural de Atuação".

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1570]
- Contexto:
No inciso II, escolhendo a categoria CPF sem Espaço Físico, selecionar apenas uma opção de Área Cultural de Atuação.

- Erro:
Na validação, o sistema diz que o campo não foi preenchido, porém se o usuário escolhe mais de um item, o sistema aceita como campo preenchido.

- Comportamento esperado:
É esperado que o sistema aceite como preenchido se pelo menos um item for selecionado.

**Comment by VaneCabral** [comment]
Novamente, vamos colocar uma previsão de resolução do bug apresentado
@benrainir @AleffBruno

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, no ambiente de teste do Pará, ocorre o comportamento esperado ao se inscrever em um edital do Inciso II:

![issueincisoIIPeek 28-02-2022 17-22](https://user-images.githubusercontent.com/75261677/156053412-69a7e9b1-ced4-4b48-a53e-bc25bf2c8316.gif)
