### ISSUE TITLE
[Avaliação simplificada] Problemas na ficha de avaliação.

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1571]
O sistema está apresentando os erros listados abaixo no tela de avaliação. Isso inviabiliza a o trabalho de uma comissão, pois está sendo exibido para o avaliador todas as inscrições, incluindo as que ele não tem permissão de avaliar. 

- [x] na coluna da esquerda, o sistema lista todas as inscrições, quando deveria exibir apenas o intervalo que foi configurado para o avaliador.
- [x] na coluna da esquerda, não está mudando a informação do status da inscrição de modo que o avaliador não pode clicar no botão para visualizar somente as inscriões que estão pendentes.
- [x] a coluna da esquerda não listou as inscrições
- [x] na coluna da diretia, o botão de "salvar e avançar" está apenas salvando. Após clicá-lo ele volta fica na mesma inscrção que já foi avaliada, quando deveria avanaçar para a próxima inscrição pendente do avaliador.

**Comment by VaneCabral** [comment]
Gente não vamos esquecer de colocar a data de previsão para a solução desse problema.

**Comment by benrainir** [comment]
Verificamos que o edital do inciso 1 da Lei Aldir Blanc encontra-se com inscrições abertas. O mapa cultural possui uma regra de negocio que não permite avaliações durante o período de inscrições. Por isso os comportamentos descritos neste erro estão acontecendo. O que devemos fazer ? Alteramos a regra ?

**Comment by VaneCabral** [comment]
_na coluna da esquerda, o sistema lista todas as inscrições, quando deveria exibir apenas o intervalo que foi configurado para o avaliador._
Aparece apenas as incrições do intervelado configurado

_Na coluna da esquerda, não está mudando a informação do status da inscrição de modo que o avaliador não pode clicar no botão para visualizar somente as inscriões que estão pendentes._
Ao clicar na marcação apenas inscrições pendentes, aparece só as inscrições pendentes

_a coluna da esquerda não listou as inscrições_
Incrições listadas 

_na coluna da diretia, o botão de "salvar e avançar" está apenas salvando. Após clicá-lo ele volta fica na mesma inscrção que já foi avaliada, quando deveria avanaçar para a próxima inscrição pendente do avaliador._
Ao clicar no botão o avaliador avança para a proxima inscrição

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, no ambiente de dev do PA, é possível:

- Avaliar as inscrições durante o período de inscrição;
- Observar a listagem somente das inscrições distribuídas para a avaliadora;
- Na coluna a esquerda, na página de avaliação, utilizar o filtro de pendente e realmente filtrar as inscrições que não possuem avaliações;
- Ao clicar em finalizar e avançar, a avaliação é salva e ocorre o direcionamento para a próxima inscrição, caso hajam avaliações pendentes, havendo também, a atualização do status cuja inscrição obteve a avaliação finalizada.

É possível verificar tais comportamentos no gif abaixo:
![issuesimplificada](https://user-images.githubusercontent.com/75261677/156428748-f24e8f8e-81c8-435a-b5b1-9c5b20fd56ea.gif)
