### ISSUE TITLE
[Oportunidade] O botão de baixar inscritos está sem funcionar

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1574]
- Contexto: Após iniciadas as inscrições o administrador da oportunidade gostaria de baixar a lista de inscritos para avaliar o perfil de quem ja enviou as inscrições ou gerar um relatório com o resultado.

- Erro: Apos clicar no botão de "baixar inscritos" nada acontece. Provavelmente os novos campos criados no formulário quebraram esta função.
![image](https://user-images.githubusercontent.com/14170372/93887245-d7098d00-fcbc-11ea-842f-0491dc506b6e.png)

- Comportamento esperado: após clicar no botão o sistema deveria gerar uma planilha com todas as informações das inscrições enviadas.

**Comment by Andreqlp** [comment]
Investigando o erro, existem oportunidades em que o botão funciona:
https://mapacultural.secult.ce.gov.br/oportunidades/report/2355/

E em outras oportunidades que não funciona/
Insico 1: https://mapacultural.secult.ce.gov.br/oportunidades/report/2059/

**Comment by benrainir** [comment]
Previsão dia 02/10

**Comment by Andreqlp** [comment]
#1555

**Comment by VaneCabral** [comment]
Na aba de inscrição os botões de Baixar rascunnho e inscritos não funciona. Ao clicar, o usuario é levando para uma tela branca. 
Na aba avaliações o botão baixar avaliação funciona

**Comment by VaneCabral** [comment]
Teste feito e funcionado! 
Consegui baixar na aba de inscritos as inscrições em rascunho e inscritos.

**Comment by Andreqlp** [comment]
Lembrando que só está funcionando para o inciso 1
