### ISSUE TITLE
[Bug] Campo "Valor Estimado da Ação" salva o valor errado.

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1580]
- Contexto:
Na inscrição para o inciso II, escolhendo a categoria CPF sem Espaço Físico, digitar no campo "Valor Estimado da Ação" o valor "3.000,00", usando ponto e vírgula, inclusive.

- Erro:
Ao validar a inscrição após o preenchimento do formulário, os zeros são ignorados e o sistema salva só o valor "3".

- Comportamento esperado:
Ao validar, o valor salvo e apresentado na tela de revisão deve ser o mesmo que foi digitado, incluindo as casas decimais.

**Comment by willowmagrini** [comment]
Solução: https://github.com/mapasculturais/mapasculturais/issues/1613
Criamos um tipo de campo para moeda em Reais.
Esta no branch feature/currency-field ( branch atualizado com o dev e pode ser testada a feature nele) enquanto aguarda aprovação do PR

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, no ambiente de dev do PA, ao realizar uma inscrição em uma oportunidade do Inciso II, o campo "Valor estimado da ação" aceita o formato "0,00", no caso, o valor "3000,00": 
![image](https://user-images.githubusercontent.com/75261677/156584429-57720d7c-c45a-4389-943f-da34a08c7311.png)
