### ISSUE TITLE
[Oportunidade] Não aparece a lista de inscritos para o administrador

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1584]
CONTEXTO: o administrador da oportunidade, assim como a equipe de suporte, precisa ver a lista de inscrições para acompanhar a evolução da oportunidade.

ERRO: o sistema não está listando as inscrições.
https://mapacultural.secult.ce.gov.br/oportunidade/2095/#/tab=inscritos

COMPORTAMENTO ESPERADO: o sistema listar todas as inscrições em rascunho e finalizadas. 

![image](https://user-images.githubusercontent.com/14170372/94054338-eb7b8180-fdb1-11ea-9f3b-0cf1bce8b2ba.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50), foi observado no ambiente de teste do PA que a listagem das inscrições possui o comportamento esperado:
![image](https://user-images.githubusercontent.com/75261677/156589614-d4f3eada-82f1-4825-93e9-522f6a014229.png)
