### ISSUE TITLE
Pesquisa de agentes por cpf

### ISSUE THREAD

**Issue by benrainir** [mapasculturais/mapasculturais#1586]
Pesquisa de agentes por cpf no menu gestão de usuarios

**Comment by VaneCabral** [comment]
Teste feito. Reforcar que para fazer a buscas precisar colocar os caracteres com o número no campo de pesquisa **. -** .
EX.: 010.101.010-10 

Uma duvida, isso tbm serve para CNPJ @benrainir e @AleffBruno

**Comment by Andreqlp** [comment]
Isso mesmo, o admin da plataforma precisa entrar neste local e informar o número de cpf com . e - 

![image](https://user-images.githubusercontent.com/14170372/94944131-2dda4800-04af-11eb-84e5-1730e7177712.png)
