### ISSUE TITLE
[Layout] Textos errados na tela de Login.

### ISSUE THREAD

**Issue by benrainir** [mapasculturais/mapasculturais#1589]
-Contexto: 
Entrar na tela de Login. 

-Erro:
Textos de instruções com erros de português e incoerências.

-Comportamento esperado:
Verificar com os POs os textos adequados. Como sugestão: 1. Substituir
"Se você já possui uma conta. Comece pelo login. Caso tenha esquecido a senha é só clicar em "recuperar senha""
por
"Se você já possui uma conta no <nome_do_mapas_do_estado>, comece pelo login. Caso tenha esquecido sua senha, clique em "esqueci a senha"."

2. Substituir
"Preencha os campos abaixo e confirme sua conta por email para ter acesso à solicitação dos benefícios."
por
"Se ainda não possui conta no Mapa Cultural de Pernambuco, preencha os campos abaixo."

**Comment by benrainir** [comment]
Prazo 25/09

**Comment by Andreqlp** [comment]
Falta aterar essa página:

## Texto

Em qual cidade?

Indique a cidade onde o beneficiário do subsídio está instalado ou tem desenvolvido, atualmente, suas atividades culturais. 

*Se sua cidade não aparecer na lista, é porque o município ainda não publicou a ficha de cadastro (veja a lista completa de cidades que realizarão o cadastro por esta plataforma) ou ela está operando a Lei Aldir Blanc por outro sistema. 

![image](https://user-images.githubusercontent.com/14170372/94440073-935cca80-0177-11eb-8918-b7f8dbd6a91a.png)

Lembrando que esse texto; "*Se sua cidade não aparecer na lista..."   possui um link que pode ser configurado pelo gestor da plataforma e que esse trecho aparece na região assinalada de vermelho na imagem.

ps: para o Ceará utilizaremos o seguinte link: https://leialdirblanc.secult.ce.gov.br/municipios-do-inciso-ii/

**Comment by VaneCabral** [comment]
O prazo para resolução do problema venceu (Prazo 25/09), temos uma nova data pra a resolução?
@benrainir @AleffBruno @mariocm1981

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) a substituição dos textos na autenticação foi realizada:
![image](https://user-images.githubusercontent.com/75261677/156594039-9ab68469-0d65-4be6-8e52-f16dea2b41f3.png)
Quanto ao texto, ele permanece o mesmo, contudo, além do Inciso II da lei Aldir Blanc ter encerrado em 2020, o plugin Aldir Blanc deu lugar ao plugin StreamlinedOpportunity, cujos textos são configuráveis em sua aplicação, que ocorre via código.
