### ISSUE TITLE
[Bug] Selecionar Instituição Responsável na Oportunidade

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1592]
Oportunidade: https://mapacultural.secult.ce.gov.br/inscricoes/preview/opportunityId:2363/

Problema: Ao tentar selecionar a Instutuição responsável para a oportunidade, a ação de clicar na instituição selecionada não acontece. Ficando na mesma tela 

![image](https://user-images.githubusercontent.com/39064345/94160131-b2e3b280-fe5a-11ea-81c8-3e99a082d75a.png)

**Comment by VaneCabral** [comment]
Mais uma oportunidade apresentou o mesmo problema relatado acima
Link da oportunidade : https://mapacultural.secult.ce.gov.br/inscricoes/preview/opportunityId:2369/

Esses editais estão previstos para liberação das inscrições hoje (24/09)

**Comment by benrainir** [comment]
Estamos verificando. Prazo 25/09

**Comment by VaneCabral** [comment]
@benrainir publicamos o edital da COEC como combinamos na conversa que tivemos a pouco. Esse campo realmente não funciona no modo de pre visualização. Depois que a ficha fui publicada, fiz o teste e consegui selecionar e adiciona a instituição responsavél. 

O erro mesmo no acontece quando esta em pre vizualização

**Comment by benrainir** [comment]
Prazo 25/09. Recomendamos liberar as oportunidades

**Comment by benrainir** [comment]
O campo não funciona SOMENTE em pré-visualização.

**Comment by benrainir** [comment]
Pausado para corrigir #1601
