### ISSUE TITLE
[Bug] Número de inscrições não está correto

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1594]
- Contexto:
Ao verificar quantidade de inscrições cadastradas na oportunidade, filtrar pelas inscrições em rascunho, exibir em tela todas as inscrições (de 50 em 50), anotar a quantidade total. Fazer o mesmo procedimento para a quantidade de inscritos.

- Erro:
As quantidades rascunhos e inscritos somadas não bate com o total. Exemplo:

Total de 1605
995 rascunhos
571 inscritos
571 + 995 = 1566

- Comportamento esperado:
Exibir valores exatos de inscritos, rascunhos e total.

**Comment by Andreqlp** [comment]
Um outro exemplo na oportunidade: https://mapacultural.secult.ce.gov.br/oportunidade/2253 o sistema mostra 39 e diz que possui 30 inscritos.

![image](https://user-images.githubusercontent.com/14170372/94945115-9249d700-04b0-11eb-8bef-ecdd9d7788e8.png)

**Comment by daphnemartinsba** [comment]
Foi testado no ambiente de desenvolvimento do PA e do MS na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais.
Em todos os casos o total de inscrições coincidiu com a soma das fichas de inscrições pelos valores dos status.
