### ISSUE TITLE
[Bug] Erro ao selecionar inscrição

### ISSUE THREAD

**Issue by DanylloArajo** [mapasculturais/mapasculturais#1595]
- Contexto:
Na tela de listagem das inscrições, selecionar determinadas inscrições no quadro lateral.

- Erro:
Algumas inscrições quando selecionas, exibe tela de erro.

- Comportamento esperado:
Exibir as informações referente a inscrição selecionada.

![image](https://user-images.githubusercontent.com/71461460/94184246-0285a680-fe7a-11ea-8efc-d18e3f784fbc.png)

![image](https://user-images.githubusercontent.com/71461460/94184159-df5af700-fe79-11ea-83f8-be8f955d47f4.png)

**Comment by VaneCabral** [comment]
teste feito
