### ISSUE TITLE
[BUG] Problema ao tentar enviar a inscrição do Edital 

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1601]
Depois de preencher os campos obrigatorios do Edital Cidadania Cultural e DIversidade, ao tentar enviar a inscrição a plataforma não realiza a ação, e não mostra se existem algum erro na ficha que possa ser corrigido pelo proponente. Apenas aparece a informação de  que foi salva. 
Link do Edital: https://mapacultural.secult.ce.gov.br/oportunidade/2347/
Inscrição: on-1508686514 

Ps.: Usei o meu Agente Individual para fazer o teste de envio da Ficha de inscrição

Depois de clicar no botão salvar, o mapa informa que tem campos que precisa ser preenchindo por são obrigatorio, sendo que esse campos não tem espaço/caixa para colocar a informaçoes como na imagem abaixo. 

Isso precisa ser resolvido com urgencia, pois temos um prazo para inscrição e avaliação desse eddital. 

![image](https://user-images.githubusercontent.com/39064345/94722074-2723c780-032d-11eb-9d87-36c09d006a1d.png)

**Comment by benrainir** [comment]
Previsão dia 01/10 a tarde

**Comment by benrainir** [comment]
![opportunidade 2347](https://user-images.githubusercontent.com/750277/94814911-4889bf80-03d0-11eb-9ee4-485cb04bcfc6.png)

**Comment by benrainir** [comment]
Não é um bug. Os campos nao funcionaram porque nao tem configuração correta.

**Comment by VaneCabral** [comment]
Massa ben! Expliquei aqui para o setor responsável por esse edital o que aconteceu. Eu ja fiz um teste e consegui enviar uma inscrição sem problemas. E os campos estão funcionando depois da sua orientação.
