### ISSUE TITLE
[BUG] - Erro ao solicitar exportação de inscrições no Inciso II

### ISSUE THREAD

**Issue by edsongs** [mapasculturais/mapasculturais#1605]
Last commit (todos do branch DEVELOP): 

- Mapas => 2968f3312df45208d832ac27ac7c0c79b7584f89
- LAB => 94de012205dd914c9b852eeae9aaa0defc3f181e
- MultipleLocalAuth => 5ae2fedaa255946c3572b64a2c4305ec9f721690

**Sempre que se tenta realizar a exportação das inscrições, aparece o seguinte erro na console de execução (em foreground):**

_mapas_1  | ErrorException: Object of class stdClass could not be converted to string in /var/www/html/protected/application/themes/BaseV1/views/opportunity/report.php:102
mapas_1  | Stack trace:
mapas_1  | #0 [internal function]: Slim\Slim::handleErrors(4096, 'Object of class...', '/var/www/html/p...', 102, Array)
mapas_1  | #1 /var/www/html/protected/application/themes/BaseV1/views/opportunity/report.php(102): implode(', ', Array)
mapas_1  | #2 /var/www/html/protected/application/lib/MapasCulturais/Theme.php(360): include('/var/www/html/p...')
mapas_1  | #3 /var/www/html/protected/application/lib/MapasCulturais/Theme.php(215): MapasCulturais\Theme->partialRender('opportunity/rep...', Array)
mapas_1  | #4 /var/www/html/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('opportunity/rep...', NULL)
mapas_1  | #5 /var/www/html/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('opportunity/rep...', NULL)
mapas_1  | #6 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(755): Slim\View->display('opportunity/rep...')
mapas_1  | #7 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(312): Slim\Slim->render('opportunity/rep...', Array)
mapas_1  | #8 /var/www/html/protected/application/lib/MapasCulturais/Controllers/Opportunity.php(156): MapasCulturais\Controller->partial('opportunity/rep...', Array)
mapas_1  | #9 /var/www/html/protected/application/lib/MapasCulturais/Controllers/Opportunity.php(91): MapasCulturais\Controllers\Opportunity->reportOutput('report', Array, 'oportunidade-6-...')
mapas_1  | #10 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\Opportunity->GET_report()
mapas_1  | #11 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(168): MapasCulturais\Controller->callAction('GET', 'report', Array)
mapas_1  | #12 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'report', Array, false)
mapas_1  | #13 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
mapas_1  | #14 /var/www/html/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
mapas_1  | #15 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
mapas_1  | #16 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
mapas_1  | #17 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
mapas_1  | #18 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\MethodOverride->call()
mapas_1  | #19 /var/www/html/protected/application/lib/MapasCulturais/App.php(569): Slim\Slim->run()
mapas_1  | #20 /var/www/html/index.php(4): MapasCulturais\App->run()
mapas_1  | #21 /var/www/html/router.php(27): include_once('/var/www/html/i...')
mapas_1  | #22 {main}_

**Comment by rafaelchavesfreitas** [comment]
resolvido
