### ISSUE TITLE
[Bug] O card do Inciso I se mantém como no primeiro acesso, porém criando inscrições em rascunhos.

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1607]
- Contexto:
Com um usuário que possui diversas inscrições geradas no inciso I, criadas possivelmente por bug, entrar no ambiente de inscrição LAB.

- Erro:
A tela apresenta o card do inciso I como se fosse o primeiro acesso.

- Comportamento esperado:
Apresentar o card associado a inscrição já iniciada.

**Comment by Andreqlp** [comment]
@DanylloArajo sabe dizer se isso está acontecendo com todas as inscrições que foram iniciadas e depois a pessoa tenta retomar a inscrição? Se ele finalizar a inscrição isso tb acontece?

**Comment by willowmagrini** [comment]
@Andreqlp podemos juntar a issue com essa:
https://github.com/mapasculturais/mapasculturais-aldirblanc/issues/8 ?

**Comment by Andreqlp** [comment]
sim @willowmagrini

**Comment by RodrigoBaltazar** [comment]
@Andreqlp podemos juntar a issue com essa:
mapasculturais/mapasculturais-aldirblanc#8 

Foi juntada com essa #8
