### ISSUE TITLE
[Bug] Opção "Filtrar Inscrições" não funciona

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1608]

**Comment by Andreqlp** [comment]
@DanylloArajo qual desses dois não está funcionando?

![image](https://user-images.githubusercontent.com/14170372/94942601-eb177080-04ac-11eb-801b-1ddf95101780.png)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, no ambiente de dev do PA, os filtros das inscrições da aba de inscritos estão com o comportamento esperado:
![issuestatslistaPeek 04-03-2022 11-39](https://user-images.githubusercontent.com/75261677/156783338-9157ac73-8a17-4845-91b4-4ed55f4ba780.gif)
