### ISSUE TITLE
[Bug] Criação de BD com Erro na Instalação com DOCKER

### ISSUE THREAD

**Issue by edsongs** [mapasculturais/mapasculturais#1612]
Quando da primeira execução, as instâncias sobem, mas logo na sequencia aparecem erros de Banco de Dados. **Várias são as tabelas não criadas** (confirmado pelo PG-Admin).

As mensagens apresentadas são:

> Starting dev-scripts_db_1 ... done
Starting dev-scripts_mapas_1 ... done
Attaching to dev-scripts_db_1, dev-scripts_mapas_1
db_1     | 2020-10-05 19:00:23.044 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2020-10-05 19:00:23.044 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2020-10-05 19:00:23.048 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-10-05 19:00:23.087 UTC [21] LOG:  database system was interrupted; last known up at 2020-10-05 18:53:02 UTC
db_1     | 2020-10-05 19:00:23.752 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
db_1     | 2020-10-05 19:00:23.756 UTC [21] LOG:  redo starts at 0/1635048
db_1     | 2020-10-05 19:00:24.215 UTC [21] LOG:  invalid record length at 0/1F5DAF0: wanted 24, got 0
db_1     | 2020-10-05 19:00:24.215 UTC [21] LOG:  redo done at 0/1F5DA98
db_1     | 2020-10-05 19:00:24.215 UTC [21] LOG:  last completed transaction was at log time 2020-10-05 18:53:10.285049+00
db_1     | 2020-10-05 19:00:25.471 UTC [1] LOG:  database system is ready to accept connections
mapas_1  |
mapas_1  | aguardando o banco de dados subir corretamente...
mapas_1  | conectado com sucesso ao banco pgsql:host=db;port=5432;dbname=mapas;user=mapas;
mapas_1  | nohup: appending output to 'nohup.out'
mapas_1  | PHP 7.2.33 Development Server started at Mon Oct  5 19:00:26 2020
mapas_1  | Listening on http://0.0.0.0:80
mapas_1  | Document root is /var/www/html
mapas_1  | Press Ctrl-C to quit.
**db_1     | 2020-10-05 19:00:30.395 UTC [29] ERROR:  relation "subsite" does not exist at character 809**
db_1     | 2020-10-05 19:00:30.395 UTC [29] STATEMENT:  SELECT t0.id AS id_1, t0.name AS name_2, t0.create_timestamp AS create_timestamp_3, t0.status AS status_4, t0.agent_id AS agent_id_5, t0.url AS url_6, t0.alias_url AS alias_url_7, t0.verified_seals AS verified_seals_8, t0.namespace AS namespace_9, t0.agent_id AS agent_id_10, t11.id AS id_12, t11.type AS type_13, t11.name AS name_14, t11.public_location AS public_location_15, t11.location AS location_16, t11._geo_location AS _geo_location_17, t11.short_description AS short_description_18, t11.long_description AS long_description_19, t11.create_timestamp AS create_timestamp_20, t11.status AS status_21, t11.user_id AS user_id_22, t11.update_timestamp AS update_timestamp_23, t11.subsite_id AS subsite_id_24, t11.parent_id AS parent_id_25, t11.user_id AS user_id_26, t11.subsite_id AS subsite_id_27 FROM subsite t0 LEFT JOIN agent t11 ON t0.agent_id = t11.id WHERE t0.url IS NULL AND t0.status = $1 LIMIT 1
**db_1     | 2020-10-05 19:00:31.983 UTC [29] ERROR:  column t0.update_timestamp does not exist at character 149**
db_1     | 2020-10-05 19:00:31.983 UTC [29] HINT:  Perhaps you meant to reference the column "t0.create_timestamp".
db_1     | 2020-10-05 19:00:31.983 UTC [29] STATEMENT:  SELECT t0.id AS id_1, t0.type AS type_2, t0.name AS name_3, t0.short_description AS short_description_4, t0.long_description AS long_description_5, t0.update_timestamp AS update_timestamp_6, t0.registration_from AS registration_from_7, t0.registration_to AS registration_to_8, t0.create_timestamp AS create_timestamp_9, t0.status AS status_10, t0.subsite_id AS subsite_id_11, t0.parent_id AS parent_id_12, t0.agent_id AS agent_id_13, t0.subsite_id AS subsite_id_14 FROM project t0 WHERE t0.id = $1

Para repetir o erro, basta acessar o diretório docker-data e renomear o diretório "postgres-minc" (nome do _docker.local.yml_) e iniciar a execução com _docker-compose -f `arquivo-de-config` up_

**Comment by willowmagrini** [comment]
@edsongs você tentou rodar o docker-compose -f docker-compose.local.yml down -v na pasta dev-scripts?

**Comment by edsongs** [comment]
Após a execução do comando apontado, obtive a seguinte mensagem:

> dev-scripts_mapas_1 exited with code 137
db_1     | 2020-10-05 20:40:06.706 UTC [1] LOG:  received smart shutdown request
db_1     | 2020-10-05 20:40:06.727 UTC [1] LOG:  worker process: logical replication launcher (PID 27) exited with exit code 1
db_1     | 2020-10-05 20:40:16.799 UTC [42] FATAL:  terminating connection due to unexpected postmaster exit
dev-scripts_db_1 exited with code 137

E ao re-iniciar a execução dos containers DOCKER, com _docker-compose -f ~/mapasculturais/dev-scripts/docker-compose.local.yml up_, surgiram estas mensagens:

> Creating network "dev-scripts_default" with the default driver
Creating dev-scripts_db_1 ... done
Creating dev-scripts_mapas_1 ... done
Attaching to dev-scripts_db_1, dev-scripts_mapas_1
db_1     | 2020-10-05 20:41:59.545 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2020-10-05 20:41:59.545 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2020-10-05 20:41:59.564 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-10-05 20:41:59.642 UTC [21] LOG:  database system was interrupted; last known up at 2020-10-05 19:10:32 UTC
db_1     | 2020-10-05 20:42:00.467 UTC [21] LOG:  database system was not properly shut down; automatic recovery in progress
db_1     | 2020-10-05 20:42:00.480 UTC [21] LOG:  redo starts at 0/1F84A78
db_1     | 2020-10-05 20:42:00.480 UTC [21] LOG:  invalid record length at 0/1F84B58: wanted 24, got 0
db_1     | 2020-10-05 20:42:00.480 UTC [21] LOG:  redo done at 0/1F84B20
mapas_1  |
mapas_1  | aguardando o banco de dados subir corretamente...
mapas_1  | conectado com sucesso ao banco pgsql:host=db;port=5432;dbname=mapas;user=mapas;
mapas_1  | nohup: appending output to 'nohup.out'
db_1     | 2020-10-05 20:42:00.523 UTC [1] LOG:  database system is ready to accept connections
mapas_1  | PHP 7.2.33 Development Server started at Mon Oct  5 20:42:01 2020
mapas_1  | Listening on http://0.0.0.0:80
mapas_1  | Document root is /var/www/html
mapas_1  | Press Ctrl-C to quit.
db_1     | 2020-10-05 20:42:03.318 UTC [29] ERROR:  relation "subsite" does not exist at character 809
db_1     | 2020-10-05 20:42:03.318 UTC [29] STATEMENT:  SELECT t0.id AS id_1, t0.name AS name_2, t0.create_timestamp AS create_timestamp_3, t0.status AS status_4, t0.agent_id AS agent_id_5, t0.url AS url_6, t0.alias_url AS alias_url_7, t0.verified_seals AS verified_seals_8, t0.namespace AS namespace_9, t0.agent_id AS agent_id_10, t11.id AS id_12, t11.type AS type_13, t11.name AS name_14, t11.public_location AS public_location_15, t11.location AS location_16, t11._geo_location AS _geo_location_17, t11.short_description AS short_description_18, t11.long_description AS long_description_19, t11.create_timestamp AS create_timestamp_20, t11.status AS status_21, t11.user_id AS user_id_22, t11.update_timestamp AS update_timestamp_23, t11.subsite_id AS subsite_id_24, t11.parent_id AS parent_id_25, t11.user_id AS user_id_26, t11.subsite_id AS subsite_id_27 FROM subsite t0 LEFT JOIN agent t11 ON t0.agent_id = t11.id WHERE t0.url IS NULL AND t0.status = $1 LIMIT 1
db_1     | 2020-10-05 20:42:04.413 UTC [29] ERROR:  column t0.update_timestamp does not exist at character 149
db_1     | 2020-10-05 20:42:04.413 UTC [29] HINT:  Perhaps you meant to reference the column "t0.create_timestamp".
db_1     | 2020-10-05 20:42:04.413 UTC [29] STATEMENT:  SELECT t0.id AS id_1, t0.type AS type_2, t0.name AS name_3, t0.short_description AS short_description_4, t0.long_description AS long_description_5, t0.update_timestamp AS update_timestamp_6, t0.registration_from AS registration_from_7, t0.registration_to AS registration_to_8, t0.create_timestamp AS create_timestamp_9, t0.status AS status_10, t0.subsite_id AS subsite_id_11, t0.parent_id AS parent_id_12, t0.agent_id AS agent_id_13, t0.subsite_id AS subsite_id_14 FROM project t0 WHERE t0.id = $1

**Comment by edsongs** [comment]
Na criação do banco de dados, as mensagens são (**veja o erro no final**):

> Creating network "dev-scripts_default" with the default driver
Creating dev-scripts_db_1 ... done
Creating dev-scripts_mapas_1 ... done
Attaching to dev-scripts_db_1, dev-scripts_mapas_1
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     |
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     |
db_1     | Data page checksums are disabled.
db_1     |
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting dynamic shared memory implementation ... posix
mapas_1  |
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
db_1     | performing post-bootstrap initialization ... ok
db_1     | syncing data to disk ... ok
db_1     |
db_1     | WARNING: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     |
db_1     | Success. You can now start the database server using:
db_1     |
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     |
db_1     | waiting for server to start....2020-10-05 20:47:58.928 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-10-05 20:47:58.963 UTC [41] LOG:  database system was shut down at 2020-10-05 20:47:57 UTC
db_1     | 2020-10-05 20:47:58.980 UTC [40] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | CREATE DATABASE
db_1     |
db_1     |
db_1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/0.schema.sql
db_1     | SET
db_1     | SET
db_1     | SET
db_1     | SET
db_1     | SET
db_1     | SET
db_1     | SET
db_1     | CREATE EXTENSION
db_1     | COMMENT
db_1     | CREATE EXTENSION
db_1     | COMMENT
db_1     | CREATE EXTENSION
db_1     | COMMENT
db_1     | SET
db_1     | CREATE DOMAIN
db_1     | CREATE FUNCTION
db_1     | CREATE FUNCTION
db_1     | CREATE FUNCTION
db_1     | CREATE FUNCTION
db_1     | CREATE FUNCTION
db_1     | SET
db_1     | SET
db_1     | CREATE TABLE
db_1     | CREATE FUNCTION
db_1     | CREATE FUNCTION
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | ALTER SEQUENCE
db_1     | CREATE TABLE
db_1     | CREATE TABLE
db_1     | CREATE SEQUENCE
db_1     | CREATE SEQUENCE
db_1     | CREATE TABLE
db_1     | COMMENT
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | CREATE INDEX
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | ALTER TABLE
db_1     | REVOKE
db_1     | 2020-10-05 20:48:03.721 UTC [65] ERROR:  role "postgres" does not exist
db_1     | 2020-10-05 20:48:03.721 UTC [65] STATEMENT:  REVOKE ALL ON SCHEMA public FROM postgres;
db_1     | psql:/docker-entrypoint-initdb.d/0.schema.sql:2221: ERROR:  role "postgres" does not exist
dev-scripts_db_1 exited with code 3

**Comment by edsongs** [comment]
Ao final o problema ficou identificado como sendo derivado da idade do esquema de definição do banco de dados.
Foi necessário parar a execução, substituir o arquivo de esqhema e dados iniciais por este: [https://github.com/mapasculturais/mapasculturais-base-project/blob/master/compose/local/dump.sql](url)
Depois de baixado o novo "esquema", foi necessário substituir, nas definições do arquivo docker, as linhas com os dados e o esquema no container "db". Apagar o diretório do banco corrompido, subir o docker, entrar no container "mapas" e executar o script "db_update.sh".
Isto feito, tudo em ordem.
