### ISSUE TITLE
Importação entre fases com erro

### ISSUE THREAD

**Issue by benrainir** [mapasculturais/mapasculturais#1616]
Importação entre fases com erro.

Corrigir a importação de inscrições para próxima fase.

**Regra de Negocio**
Importar  somente os selecionados ( status = 10)
Não bloquear a função de importação
Importar apenas as inscrições que não estão na próxima fase ( Pesquisar se o (number) número da inscrição não existe na próxima fase)

**Comment by benrainir** [comment]
Utilizar o edital codigo 2059 ( Inciso 1 da Aldir Blanc)

**Comment by joaovitorcavalcante** [comment]
Esperando permissão no projeto para pushar a solução

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.50 ](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.50) do Mapas Culturais, a importação foi testada no ambiente de teste do PA e demonstrou o comportamento esperado da regra de negócio. 
O gif abaixo não foi realizado no Inciso I para que dados pessoas não fossem apresentados:
![segundafaseissue](https://user-images.githubusercontent.com/75261677/156792562-31f7026b-bb47-4cd1-b77d-b4aee9ced81c.gif)
