### ISSUE TITLE
Em todas as caixas de filtro permitir escrever. Enquanto se escreve ir filtrando o resultado. Isso para agilizar e minimizar o tempo de busca via scroll

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#162]
Em todas as caixas de filtro permitir escrever. Enquanto se escreve ir filtrando o resultado. Isso para agilizar e minimizar o tempo de busca via scroll

**Comment by daphnemartinsba** [comment]
A melhoria além de implementada será repassada com o redesign e/ou refatoração das libs.
