### ISSUE TITLE
[Bug] Avalidor não consegue ver o campos

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1627]
No edital Edital Territórios Culturais e Tradicionais coordenador pela CODAC - SECULT CE, o avaliadores estão realizando a avaliação documental dos projetos enviados. 
Quando o avaliador acessar a inscrição enviada, nos campos _Informações sobre o Agente Responsável ou Proponente_ as respostas: Nome, Data de nascimento, numero do CPF, Telefone e email que são informações obrigatorias aparece a informação **Campo não informado**
![image](https://user-images.githubusercontent.com/39064345/96146072-4a797580-0edc-11eb-99af-3a1c0e7c8cb4.png)

Fiz o acesso da mesma inscrição como o meu usuario de super adm, e as informações aparecem 
![image](https://user-images.githubusercontent.com/39064345/96146169-64b35380-0edc-11eb-96cc-46693e7293dc.png)

No inicio da ficha onde Agentes (proponentes) as informações aparecem para os avaliadores. 
![image](https://user-images.githubusercontent.com/39064345/96146618-df7c6e80-0edc-11eb-8914-f459e9060885.png)

O bug seria pq as informações aparecem logo no começo da ficha e por isso eles não aparecem no campos de resposta? E pq eu como super adm consigo ver essas informações?

**Comment by rafaelchavesfreitas** [comment]
resolvido
