### ISSUE TITLE
[Bug] Adminstrador da Oportunidade não consegue ver as informações

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1630]
No Edital Territórios Culturais e Tradicionais (https://mapacultural.secult.ce.gov.br/oportunidade/2355/) o agente individual Lilian Lustosa (https://mapacultural.secult.ce.gov.br/agente/8991/) acessou as inscrições desse edital e as informações respondidas pelo proponente não apareceram, só os campos em anexo estavam com as informações. O restante das informações os campos aparecem: "Campo não informado".

Fiz um teste entrando com o meu perfil de super adm, onde todas as informações aparecem, tbm acessei com um perfil comum que foi colocando como avaliador onde tbm as informações aparecem.

Acesso com usuario comum, que está como avaliador do Edital 

Reforçando aqui, que o agente individual da Lilian é admistrador do Agente Coletivo CODAC (https://mapacultural.secult.ce.gov.br/agente/7298/) que publicou esse edital

**Comment by rafaelchavesfreitas** [comment]
corrigido
