### ISSUE TITLE
[Bug] Baixa Lista de Avaliações 

### ISSUE THREAD

**Issue by VaneCabral** [mapasculturais/mapasculturais#1634]
No Mapa cultural do Ceará ao tentar baixar a Lista de Avaliações do  ARTE LIVRE - EDITAL DE CRIAÇÃO ARTÍSTICA (https://mapacultural.secult.ce.gov.br/oportunidade/2369/) ficar enternamenta carregando tentando gera a planilha. 

Acontece o mesmo problema no Inciso I - Renda emergencial aos trabalhadores e trabalhadoras da Cultura (https://mapacultural.secult.ce.gov.br/oportunidade/2059)

**Comment by rafaelchavesfreitas** [comment]
acredito que já foi resolvido
