### ISSUE TITLE
[Bug] O relatório de inscritos não mostra todos os campos para o administrador da oportunidade

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1640]
### Contexto:
O administrador da oportunidade que tambem é  avaliador precisa baixar a lista de inscrtios para operacinalizar o edital, por exemplo encontrar a lista de e-mails para enviar o resultado.

### Erro:
O adminsrador da oportunidade que também é avaliador baixa  a lista de inscritos mas na lisagem só aparecem as informações das inscrições que são distribuídas para ele avaliar.

### Telas e exemplos:
![captura_20201104-161452](https://user-images.githubusercontent.com/14170372/98157951-edf4ef00-1eb8-11eb-889c-a78361c3f8b9.png)

### Comportamento esperado:
Deveria vir para os adminstradores da oporrtunidade todas as respostas das fichas de inscrição, independente se ele é avaliador ou não.

**Comment by rafaelchavesfreitas** [comment]
resolvido
