### ISSUE TITLE
[BUG] - Sem Acesso, via Painel de Controle a Gestão de Administradores

### ISSUE THREAD

**Issue by edsongs** [mapasculturais/mapasculturais#1645]
### _**Ambiente:**_
Core => develop
Docker
VM com 5GB de RAM; 150GB de HD; e 4 CPU alocadas; rede em modo DHCP.

### _**Problema:**_
Acesse Painel de Controle =>Administradores, e via receber esta mensagem de erro:

---------------

*Gerenciador de usuários*

( ! ) Fatal error: Uncaught Error: Cannot use object of type MapasCulturais\Definitions\Role as array in /var/www/html/protected/application/themes/BaseV1/layouts/parts/user-management/info-admin.php on line 38
( ! ) Error: Cannot use object of type MapasCulturais\Definitions\Role as array in /var/www/html/protected/application/themes/BaseV1/layouts/parts/user-management/info-admin.php on line 38
Call Stack
\#	Time	Memory	Function	Location
1	0.0001	390328	{main}( )	.../router.php:0
2	0.0002	390624	include_once( '/var/www/html/index.php' )	.../router.php:27
3	0.3502	9265344	MapasCulturais\App->run( )	.../index.php:4
4	0.3504	9265376	MapasCulturais\App->run( )	.../App.php:569
5	0.3504	9265352	MapasCulturais\Middlewares\ExecutionTime->call( )	.../Slim.php:1300
6	0.3507	9266920	Slim\Middleware\MethodOverride->call( )	.../ExecutionTime.php:44
7	0.3508	9267248	Slim\Middleware\Flash->call( )	.../MethodOverride.php:92
8	0.3509	9267624	MapasCulturais\App->call( )	.../Flash.php:85
9	0.3622	9287480	Slim\Route->dispatch( )	.../Slim.php:1355
10	0.3622	9287856	call_user_func_array:{/var/www/html/protected/vendor/slim/slim/Slim/Route.php:468} ( )	.../Route.php:468
11	0.3622	9287872	MapasCulturais\RoutesManager->MapasCulturais\{closure:/var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php:41-123}( )	.../Route.php:468
12	0.3624	9291696	MapasCulturais\RoutesManager->callAction( )	.../RoutesManager.php:106
13	0.3625	9292480	MapasCulturais\Controllers\Panel->callAction( )	.../RoutesManager.php:168
14	0.3630	9293832	MapasCulturais\Controllers\Panel->GET_userManagement( )	.../Controller.php:274
15	0.3636	9293832	MapasCulturais\Controllers\Panel->render( )	.../Panel.php:352
16	0.3639	9294064	MapasCulturais\App->render( )	.../Controller.php:297
17	0.3640	9294064	Subsite\Theme->display( )	.../Slim.php:755
18	0.3640	9294064	Subsite\Theme->fetch( )	.../View.php:243
19	0.3640	9294064	Subsite\Theme->render( )	.../View.php:255
20	0.3640	9294064	Subsite\Theme->fullRender( )	.../Theme.php:217
21	0.4604	10097976	Subsite\Theme->partialRender( )	.../Theme.php:267
22	0.4622	10116696	include( '/var/www/html/protected/application/themes/BaseV1/views/panel/user-management.php' )	.../Theme.php:360
23	0.9388	10133376	Subsite\Theme->part( )	.../user-management.php:30
24	0.9388	10133376	Subsite\Theme->partialRender( )	.../Theme.php:387
25	1.0600	10154392	include( '/var/www/html/protected/application/themes/BaseV1/layouts/parts/user-management/info-admin.php' )	.../Theme.php:360

**Comment by rafaelchavesfreitas** [comment]
resolvido
