### ISSUE TITLE
[Bug] Botão de aplicar avaliações não está funcionando

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1647]
### Contexto:
O administrador da oportunidade precisar alterar o status das avaliações da habilitração documental ou simplificada para publicar o resultado.

### Erro:
O adminsrador da oportunidade clica no botão de "aplciar avaliações", que deveria definir o status das inscrições de acordo com o resultado consolidado das avaliações, mas aparece um erro fatal após confirmar a ação.

### Telas e exemplos:
Oportunidade utilizada no exemplo: https://mapacultural.secult.ce.gov.br/oportunidade/1563

![image](https://user-images.githubusercontent.com/14170372/98735175-b9ce7200-2381-11eb-9686-2e816b42c9aa.png)

Erro:
![image](https://user-images.githubusercontent.com/14170372/98735225-cd79d880-2381-11eb-81fe-21d9dc801eca.png)

### Comportamento esperado:
O botão deveria definir o status das inscrições de acordo com o resultado consolidado das avaliações, mas aparece um erro fatal após confirmar a ação.

**Comment by rafaelchavesfreitas** [comment]
resolvido
