### ISSUE TITLE
[Bug] Relatório dos inscritos não está mantendo os dados do perfil no momento da inscrição

### ISSUE THREAD

**Issue by Andreqlp** [mapasculturais/mapasculturais#1648]
### Contexto:
O administrador da oportunidade precisa gerar o realtório de inscritos para obter as informações cadastrais do proponente (CPF, endereço,e-mail...) e realizar o conveniamento com os selecionados.

### Erro:
Os campos da ficha de inscrição que estão vinculados ao perfil são atualizados automaticamente no relatório de inscritos. Por exemplo, um inscrito pode fazer alteraçõs no perfil, depois de ter enviado a inscrição, trocando o número de cpf (mesmo sem sentido aconteceram casos da pessoa trocar o cpf do perfil), endereço e-mail e telefone.

### Telas e exemplos:
![image](https://user-images.githubusercontent.com/14170372/99073059-f5408a80-2593-11eb-944e-c66477f97165.png)

### Comportamento esperado:
A lista de inscritos devem trazer as informações que foram registradas no momento da inscrição, como se fosse uma fotografia da inscrição.

### Melhoria futura
É interessante ter a opção da ficha mostrar os dados que foram atualizados no perfil, como é o caso de campos de e-mail, endereço, telefone. Contudo é necessário manter a informação que foi inicialmente cadastrada. Uma sugestão seria vir os valores nov entre parênteses dentro do campo de informação por exemplo no número de telefone: (85) 98546-4526 (atualizado no perfil para: (85) 99935-8988

**Comment by rafaelchavesfreitas** [comment]
resolvido
