### ISSUE TITLE
[bug] Links do histórico não estão funcionando

### ISSUE THREAD

**Issue by Uragawa** [mapasculturais/mapasculturais#1663]
Ao tentar acessar o link gerado pelos itens do histórico dos registros, o sistema gera um erro.

**Comment by daphnemartinsba** [comment]
Na versão v5.1.55 do Mapas Culturais, foi observado nos ambientes de teste (PA, MS e ES) que os links dos históricos funcionam:
![image](https://user-images.githubusercontent.com/75261677/161612155-8b6a061e-ab06-4453-85fa-7162abf58757.png)
![image](https://user-images.githubusercontent.com/75261677/161612217-92713533-40ce-4bd2-b871-187ea6a6eca0.png)

![image](https://user-images.githubusercontent.com/75261677/161612339-9c09dd1f-80c3-45a3-aa94-19f23444556b.png)
