### ISSUE TITLE
reorganizar a página de edição de oportunidade em duas abas, uma principal com os campos editoriais e outra para a configuração do formulário

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1671]
# Aba Principal
- introdução
- regulamento
- vídeos
- galeria
![image](https://user-images.githubusercontent.com/1181261/108417584-eb6f9880-720e-11eb-93ef-c1a92d2e7501.png)

# Aba Configuração do formulário
- importar formulário
- Opções
- Agentes
- Espaço Cultural
- Campos
- Exportar formulário
- Formulário para recursos
![image](https://user-images.githubusercontent.com/1181261/108417209-71d7aa80-720e-11eb-9111-825c022fc8d0.png)

**Comment by JoseCage** [comment]
Em progresso: #1681
