### ISSUE TITLE
Nova caixa de criação de fases das oportunidades em duas etapas (módulo OpportunityPhases)

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1672]
- adicionar campos radio para selecionar o tipo de avaliação.
- adicionar botão avançar que leva para a segunda etapa da criação da fase, onde o usuário poderá selecionar se a nova fase é a última fase.

no template da segunda etapa colocar um `applyTemplateHook` para possibilitar plugins adicionarem novas opções na criaçào da fase. (será utilizado para adicionar o checkbox `utilizar prestação de contas`)

### primeira etapa
![image](https://user-images.githubusercontent.com/1181261/108725805-86b18800-7505-11eb-9e29-f09ebcc74c25.png)

### segunda etapa
![image](https://user-images.githubusercontent.com/1181261/108725828-8c0ed280-7505-11eb-887f-f5638460d047.png)

**Comment by JoseCage** [comment]
Implementação feita em https://github.com/mapasculturais/mapasculturais/commit/39f7c610dda76b247cdf93c5df16af81f94f1ba0
