### ISSUE TITLE
corrigir lista de inscrições para avaliadores na tela de avaliações versão v5.0.0

### ISSUE THREAD

**Issue by benrainir** [mapasculturais/mapasculturais#1685]
Após atualização para ultima versão do Mapa Cultural do CE para [versão 5](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.0.0-rc10) (atualmente em produção a [versão ](https://github.com/govce/mapasculturais/commit/fdfc6a1)), todos os editais em avaliação reportaram o mesmo problema, os avaliadores perderam acesso a várias inscrições.

Após verificação da equipe de suporte  concluímos que o sistema (backend) retorna para o usuário quantidade inferior de inscrições do que deveria após a atualização

Verificar a rota https://mapacultural.secult.ce.gov.br/api/opportunity/findEvaluations

**Comment by rafaelchavesfreitas** [comment]
já corrigido
