### ISSUE TITLE
Resolver problema de importar inscrição para segunda fase. Só deve ser importada as inscrições marcadas como selecionada.

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1729]
A suspeita é que esteja importando as selecionadas da primeira fase e não a da ultima (prestação de contas)

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.55](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.55) do Mapas Culturais as únicas inscrições importadas para uma próxima fase são as selecionadas, como mostra no gif abaixo realizado a partir do ambiente de teste do PA:
![1729Peek 05-04-2022 12-31](https://user-images.githubusercontent.com/75261677/161790767-7c01503a-0dcd-4818-ba6c-72c392346ad1.gif)
