### ISSUE TITLE
verificar botão de aplicar avaliações do método de avaliação simplificada 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1782]
deixando o checkbox desmarcado:
![image](https://user-images.githubusercontent.com/1181261/115042492-eb57e600-9ea9-11eb-8376-89879fc63104.png)
![image](https://user-images.githubusercontent.com/1181261/115042516-f27ef400-9ea9-11eb-9c75-291c480aca8c.png)
![image](https://user-images.githubusercontent.com/1181261/115042544-fa3e9880-9ea9-11eb-8b62-94d502bff831.png)

deixando o checkbox marcado:
![image](https://user-images.githubusercontent.com/1181261/115042635-12161c80-9eaa-11eb-80e7-d7c5a2501077.png)
![image](https://user-images.githubusercontent.com/1181261/115042666-18a49400-9eaa-11eb-9b17-4217a0511055.png)
![image](https://user-images.githubusercontent.com/1181261/115042700-20643880-9eaa-11eb-9dae-812b942fcbdb.png)

**Comment by daphnemartinsba** [comment]
A funcionalidade foi observada no ambiente do MS e no ambiente do ES. Em ambos os ambientes houve o comportamento esperado.

No MS: 
![Peek 31-01-2022 17-41](https://user-images.githubusercontent.com/75261677/151870121-cfa877ba-c627-40aa-ae09-5b1734a95961.gif)

No ES:
![Peek 31-01-2022 17-46](https://user-images.githubusercontent.com/75261677/151870437-410cada9-3a39-4656-8a36-489242bd714c.gif)
