### ISSUE TITLE
QA Prestação de Contas - Publicação do resultado antes de criação da Prestação de Contas

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1785]
- [x] Um erro na Oportunidade 1, por falta de conhecimento do usuário (eu), os resultados da primeira fase foram publicados quando as inscrições tinham sido enviadas por apenas um dos avaliadores, por conta disso, apenas as avaliações de um avaliador foram enviadas. 

- [x] E o mais importante para a criação de prestação de contas, por conta desta publicação ter sido realizada antes da criação da prestação de contas, as inscrições não foram:
- Automaticamente importadas para a prestação de contas como rascunho, a importação foi manual;
- Os projetos não foram criados;
- Os e-mails com o link do projeto não foram enviados;
- A plataforma não apresentou os projetos (isso ocorreu inclusive, com as oportunidades criadas adequadamente);
- A plataforma apresentou o formulário da prestação de contas o qual pôde ser preenchido e enviado independente de projeto;
- Como não há projeto, não é possível vincular evento.
- Para os pareceristas, Botões de Finalizar e Avançar e Finalizar e Enviar o Parecer Técnico não funcionam.

_Originally posted by @daphnemartinsba in https://github.com/mapasculturais/mapasculturais/issues/1774#issuecomment-822755644_

**Comment by erleibiazzio** [comment]
Nessa issue a dúvida gerada inicialmente, era se a possibilidade de se publicar os resultados de uma oportunidade seja possível quando na mesma exista 2 avaliadores mas só um deles tenha avaliado.

Em Daily foi definido que SIM, a decisão de publicar o resultado é uma decisão do gestor, sendo feita essa avaliação por ele.

**Comment by daphnemartinsba** [comment]
- Foi confirmado que o envio das avaliações ser realizado apenas pelo avaliador que avaliou está de acordo com o fluxo.

- Por conta da necessidade da criação da prestação de contas antes da publicação da fase anterior à prestação, para que inscrições sejam importadas para a prestação e rascunho dos projetos sejam criados, essa issue será reaberta sob a propostra de:

- [ ]  Colocar um aviso na prestação de contas afirmando que a publicação dos resultados é um evento irreversível;

- [ ] Colocar um aviso: Caso a próxima fase seja uma prestação de contas, deve-se criar a prestação de contas antes de publicar o resultado da fase atual.

**Comment by daphnemartinsba** [comment]
Ao clicar em Publicar Resultado a mensagem de aviso, quanto a irreversibilidade da publicação e o cuidado em criar a prestação de contas antes desta publicação, aparece:
![image](https://user-images.githubusercontent.com/75261677/120332962-9fc89280-c2c5-11eb-8a2c-459f56e82565.png)
