### ISSUE TITLE
QA Prestação de Contas - Só é possível o Gestor de uma Oportunidade fazer o campo de evento como campo editável do formulário

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1788]
- [x] Na prestação de contas só foi possível fazer um campo editável para mandar mensagem (o campo de evento). O que quer dizer que caso o Agente Responsável não seja obrigatório, não dá para adicionar ou editar o Agente.

![Captura de tela de 2021-04-19 17-53-15](https://user-images.githubusercontent.com/75261677/115302155-7ea64b00-a138-11eb-8fe0-b3829fd9d288.png)

- [x] E ao deixar o campo de evento editável, somente é possível criar um novo evento, ao invés de utilizar um já existente.

_Originally posted by @daphnemartinsba in https://github.com/mapasculturais/mapasculturais/issues/1774#issuecomment-822779162_

**Comment by erleibiazzio** [comment]
Analisando junto a Daphne o fluxo do problema informado, identificamos que o campo do agente coletivo, se comportou de forma correta. Sendo possivel editar normalmente. Quanto ao evento, ficou a dúvida quanto ao flow.
Nã**o seria ideal que o proponente importasse um evento já criado anteriormente?**
Exemplo
Durante a fase anterior o proponente cria um evento, e publica na plataforma. O evento acontece e na prestação de contas o mesmo tem que prestar contas desse evento. **Ele deveria ter uma forma de importar esse evento a prestação ou criar o evento novamente na prestação?**

**Comment by daphnemartinsba** [comment]
O campo de Evento deve somente criar novos eventos vinculados à prestação de contas (caso queira vinculá-lo a um evento previamente publicado no Mapas Culturais, deve-se vincular o evento previamente publicado ao projeto da prestação de contas).
