### ISSUE TITLE
QA Prestação de Contas - Os rascunhos de projetos, criados pela prestação de contas, não aparecem no painel de controle

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1789]
Os rascunhos de projetos que foram criados pela prestação de contas não aparecem no painel inicial, deve acessar Meus Projetos e ir em Rascunhos para ter acesso à eles. Mesmo após publicá-los, continuam não aparecendo no painel.

_Originally posted by @daphnemartinsba in https://github.com/mapasculturais/mapasculturais/issues/1774#issuecomment-822787971_

**Comment by erleibiazzio** [comment]
Commit que resolvem o problema estão na issue #1802

**Comment by daphnemartinsba** [comment]
Os rascunhos dos projetos aparecem em ‘Projetos Contemplados’ antes do prazo de prestação de contas e antes da publicação do projeto.
