### ISSUE TITLE
Criar nova sessão no painel principal que liste os projetos após a criação do projeto de prestação de contas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1802]
A sessão deverá se chamar **Projetos contemplados**

A sessão deve mostrar
Nome da oportunidade, Se está em rascunhou ou não, número da inscrição, o nome e tipo do projeto se já estiverem definidos.

Utilizar a classe ApiQuery para achar os projetos.
```PHP
$query = new ApiQuery('MapasCulturais\\Entities\\Project', [
    '@select'=>'id', 
    'isAccountability' => 'EQ(1)', 
    'owner' => 'IN(lista de ids dos meus agentes)', 
    'status' => 'GT(0)'
]);

$ids = $query->findIds();
```

**Comment by daphnemartinsba** [comment]
Os projetos em rascunhos (ou publicados) não estão mais aparecendo em projetos contemplados antes do prazo da prestação de contas:
![validaçãoQA_listaDeProjetosContemplados 01-06-2021](https://user-images.githubusercontent.com/75261677/120336265-8e34ba00-c2c8-11eb-85b4-0c46b516a6fa.gif)

**Comment by daphnemartinsba** [comment]
Os projetos constam no painel do proponente em "projetos contemplados" antes do prazo da prestação de contas:
![image](https://user-images.githubusercontent.com/75261677/121585184-aadb9b00-ca08-11eb-94f7-ceddbed074a5.png)
