### ISSUE TITLE
QA Prestação de Contas - Após a Reabertura do Parecer o Parecerista não tem Acesso à Aba Prestação de Contas do Projeto

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1809]
Ao clicar em Reabrir pareceres, após os pareces já terem sido enviados pelos pareceristas, os pareceristas não tem acesso à página de realização do parecer.
Ao acessar:
![image](https://user-images.githubusercontent.com/75261677/117174172-d2a16880-ada3-11eb-885f-843a8043c226.png)
E clicar no número de inscrição, o direcionamento será para a página do projeto, que estará desta forma:
![image](https://user-images.githubusercontent.com/75261677/117174284-f2389100-ada3-11eb-8a86-43eb67bf56c2.png)
Impossibilitando que o parecerista realize os pareceres novamente.

**Comment by Uragawa** [comment]
[Commit da implementação](https://github.com/mapasculturais/mapasculturais/commit/c0aaac1dfde998f751c678220eff6a38e33c9073)

**Comment by daphnemartinsba** [comment]
O botão “Reabrir parecer” funciona, tendo seu texto e cores alteradas, de verde vai para "bege", e o texto "Reabrir Parecer" volta a ser "Desabilitar". Independente se foram ou não aplicadas as avaliações nos status, é possível que o parecerista reabra a prestação, reavalie e reenvie.
