### ISSUE TITLE
implementar limpeza das tabelas auxiliares para as entidades que são apagadas por cascade no banco

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1812]
exemplo:
quando apagamos uma oportunidade, as inscrições são apagadas pelo cascade da FK no banco de dados.

ficam resíduos nas tabelas `file`, `agent_relation`, `pcache`

as tabelas auxiliares são:
- term_relation
- meta_list
- pcache
- file
- agent_relation
- space_relation

**Comment by edsongs** [comment]
Um contorno temporário a esta situação é a limpeza manual/script destas tabelas.

Para isto pode ser incluído no **crontab** do usuário (_crontab -e_) que está executando o banco de dados (no padrão é o "_mapas_") o seguinte:
`0 * * * * /usr/bin/psql -c "DELETE FROM term_relation  WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM evaluation_method_configuration)"`
`0 * * * * /usr/bin/psql -c "DELETE FROM metalist       WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM evaluation_method_configuration)"`
`0 * * * * /usr/bin/psql -c "DELETE FROM pcache         WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM SELECT * FROM file WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM evaluation_method_configuration)"`
`0 * * * * /usr/bin/psql -c "DELETE FROM agent_relation WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM evaluation_method_configuration)"`
`0 * * * * /usr/bin/psql -c "DELETE FROM space_relation WHERE object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND object_id NOT IN (SELECT id FROM evaluation_method_configuration)"`

Desta forma, a cada hora cheia vc estará confirmando que as tabelas auxiliares estão "limpas".
**Obs:**
    Você pode executar uma vez ao dia e/ou em horários diferentes. Basta mudar as configurações pertinentes no **crontab**
