### ISSUE TITLE
No modal de liberação de permissão, fazer com que seja possível liberar permissões em massa

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1814]
- [x] A ideia e que exista um campo que o usuário possa selecionar o campo, e em seguida setar uma determinada permissão para todos os selecionados.

**Imagem do Modal**
![image](https://user-images.githubusercontent.com/39862175/117465667-4bc9c880-af28-11eb-9fb9-cea6c9d6fa3b.png)

**Comment by daphnemartinsba** [comment]
Do jeito que está agora: É necessário configurar o formulário, salvar e sair do modo de edição, para que aqueles campos criados na "configuração do formulário" estejam disponíveis para configuração da permissão do suporte em "configurações de suporte".
Se não sair do modo de edição após a configuração do formulário, os campos criados no formulário não ficam disponíveis para configuração no suporte. Isso pode gerar confusão.
