### ISSUE TITLE
Implementar forma que seja possível de filtrar o status ao gerar os gráficos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1818]
O Gráfico hoje trata somente de registro com status de inscrições enviadas.
A ideia e que seja possível também pegar o status rascunho também.

Inserir um parâmetro `$_GET` passando o status desejado e fazer o filtro na query com esse parametro passado.

**Comment by JoseCage** [comment]
**Update**:

- [ ]  Assegurar que os gráfico estáticos são gerados ao escolher um filtro (estado)
- [ ] Depois que terminar de carregar a página. buscar o eatado salvo na sessão e renderiza os gráficos dinamicos

**Comment by daphnemartinsba** [comment]
Ao clicar no botão de ver somente rascunhos, os gráficos dinâmicos agem de acordo, contudo, os gráficos fixos permanecem os mesmos.

**Comment by daphnemartinsba** [comment]
Os gráficos fixos, além dos dinâmicos, constam com o comportamento adequado ao filtrar por rascunhos, fornecendo o resultado da avaliação dos rascunhos.
![image](https://user-images.githubusercontent.com/75261677/119559121-a2ccfb80-bd78-11eb-9933-aa23ff263d4e.png)
