### ISSUE TITLE
Remover gráfico fixo de linha caso seja uma portunidade de segunda fase ou superior

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1819]
Quando se faz a importação dos dados para uma fase posterior, a data da criação sempre será a mesma para todas as inscrições . Por isso o gráfico estático de linha fica inviável

**Comment by daphnemartinsba** [comment]
Nas oportunidades observadas que possuem mais de uma fase, não há gráfico de linha da segunda fase em diante.
