### ISSUE TITLE
Alterar texto nos selects de seleção de dados para "Dados a serem exibidos na linha" e Dados a serem exibidos na coluna"

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1820]
Os textos estão iguais, a ideia e referenciar na label o tipo de dado que será mostrado na coluna e o o tipo de dado que será mostrado na linha
![image](https://user-images.githubusercontent.com/39862175/117710335-6316e900-b1a8-11eb-8903-b1d237644a61.png)

![image](https://user-images.githubusercontent.com/39862175/117710508-92c5f100-b1a8-11eb-8845-d632521290ee.png)

**Comment by daphnemartinsba** [comment]
Agora consta como "Dados a serem exibidos na linha" e "Dados a serem exibidos na coluna":
![image](https://user-images.githubusercontent.com/75261677/118690396-66305b80-b7de-11eb-97aa-8d132a95cc39.png)
