### ISSUE TITLE
Trocar nome do "Gráfico de Barra" por Gráfico de coluna

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1821]
O gráfico que essa opção gera é o de coluna não o de barras.

![image](https://user-images.githubusercontent.com/39862175/117710718-cf91e800-b1a8-11eb-873b-de036e78ca40.png)

![image](https://user-images.githubusercontent.com/39862175/117710746-d6205f80-b1a8-11eb-9385-31d2ef857b4b.png)

**Comment by daphnemartinsba** [comment]
O gráfico com barras dispostas na verticais consta com nome de gráfico de coluna e as barras dispostas horizontalmente consta como gráfico de barras.
