### ISSUE TITLE
Incluir opção para criar gráfico de barras

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1822]
Hoje não se é possível criar gráficos de barras. Fazer com que no modal seja exibida opção para gerar e implementar gráfico. 
Exemplo 

![image](https://user-images.githubusercontent.com/39862175/117711002-1d0e5500-b1a9-11eb-9a1a-615f2a0c41e6.png)

**Comment by daphnemartinsba** [comment]
É possível gerar gráficos de barras com o adensamento.
