### ISSUE TITLE
Permitir que o cruzamento no gráfico de barra apareça o resultado em uma única barra e não somente barra

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1823]
Exemplo
![image](https://user-images.githubusercontent.com/39862175/117711157-462ee580-b1a9-11eb-9d63-febc99ee2b0f.png)

**Comment by daphnemartinsba** [comment]
O adensamento funciona somente no gráfico de barras (que é o comportamento esperado) ao selecionar dados diferentes na linha e na coluna.
