### ISSUE TITLE
Criar template de impressão para o módulo de relatórios

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1825]
A ideia e criar uma página, distinta da oportunidade. Que seja possível fazer a impressão em PDF de todos os gráficos gerados.

Tentar usar o proprio navegador para isso.

**Comment by daphnemartinsba** [comment]
Ao clicar em imprimir, abre uma nova página e é possível salvar o PDF com todos os gráficos gerados, os quais estão visíveis e corretos.

**Comment by daphnemartinsba** [comment]
O gráfico não é quebrado nas quebras de páginas, contudo, as informações estão quebrando nas quebras de páginas.
![image](https://user-images.githubusercontent.com/75261677/118699024-700a8c80-b7e7-11eb-8fa0-54ade9aceb6f.png)

**Comment by daphnemartinsba** [comment]
Ao clicar em imprimir, ocorre o direcionamento para uma outra página onde gera o arquivo a ser salvo em pdf. 
Os gráficos que possuem muitos dados e precisam de barra de rolagem são quebrados de modo que suas partes aparecem em sequências, no pdf, e assim, disponibilizam todos os dados.
