### ISSUE TITLE
Num projeto de prestação de contas e o mesmo estando em rascunho, deve-se existir uma mensagem na tela do projeto informando o que deve ser feito.

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1829]
Ao publicar o resultado em uma fase anterior  e a próxima fase for uma prestação de contas, é criado um projeto para o proponente, para que ele faça sua prestação de contas. Como esse projeto e criado de forma automática e vinculado ao proponente e deixado em rascunho. Deve-se inserir um passo a passo na tela desse projeto para auxiliar o proponente o que deve ser feito. 

![image](https://user-images.githubusercontent.com/39862175/118535383-c8c32200-b720-11eb-8cad-0cb11ba13b74.png)

**Comment by daphnemartinsba** [comment]
A mensagem instrutiva está disponível no rascunho do projeto criado:
![image](https://user-images.githubusercontent.com/75261677/120338137-5169c280-c2ca-11eb-9143-40c4c8b68a72.png)
