### ISSUE TITLE
Ao se clicar no botão de ver somente rascunhos, deve-se aplicar essa opção também para a tela de impressão.

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1830]
Foi feita uma implementação na issue 1818, para que seja possível visualizar os gráficos também das inscrições com status 0 (Rascunho). Essa alteração deve-se ser aplicada também na tela de impressão dos gráficos.

**Comment by erleibiazzio** [comment]
Modificação foi executada juntamente com a issue #1818

**Comment by daphnemartinsba** [comment]
Os gráficos gerados após um gráfico de tabelas são cortados da impressão.

**Comment by daphnemartinsba** [comment]
Ao clicar em imprimir, todos os gráficos apareceram e apareceram de acordo com o filtro de rascunhos
