### ISSUE TITLE
Nos gráficos de barra e coluna, inserir botão que seja possível visualizar o gráfico com os dados agrupados em uma so barra ou disperso em barras diferentes

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1831]
**Exemplo de visualização agrupada**
![image](https://user-images.githubusercontent.com/39862175/118514221-c35add00-b70a-11eb-837d-c026767adc66.png)

**Exemplo de visualização dispersa** 

![image](https://user-images.githubusercontent.com/39862175/118514439-ed140400-b70a-11eb-8522-40f1c87e7a16.png)

Esse estado deve ser salvo em banco de dados para que em um carregamento futuro, o grafico volte a ser exibido no ultimo estado setado.

**Comment by daphnemartinsba** [comment]
O comportamento esperado está acontecendo. Quando seleciona o agrupamento os dados são adensados, quando não seleciona os dados são dispostos em barras dispersas.
