### ISSUE TITLE
Fazer pesquisa para inserir biblioteca de textarea com opções de edição de texto

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1837]
A ideia é buscar uma lib que seja open source e de simples implantação e uso para inserir no text area do parecer técnico da prestação de contas.

**Comment by daphnemartinsba** [comment]
Consultado na Daily, a biblioteca é open-source e necessita apenas da chave de autentificação provida pela biblioteca e implementada no uso da biblioteca.

**Comment by daphnemartinsba** [comment]
O editor de texto tem que ser trocado do tinymce para um editor de texto que não precise da chave para o uso e que o código seja acessível. 
Uma outra opção de editor de texto foi o Quill.
