### ISSUE TITLE
Possibilitar que o parecerista envie os pareceres mesmo que a data da prestação se encontre fechada

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1838]
A ideia e que o parecerista possa manipular qualquer parecer, mesmo que a prestação de contas esteja fechada. Hoje essa manipulação só acontece enquanto o prestação de contas está com prazo vigente.

**Comment by daphnemartinsba** [comment]
O envio do parecer após o prazo da prestação de contas está ocorrendo perfeitamente, inclusive quando reabre o parecer. 
Contudo, o envio durante a prestação de contas não é possível:
![validaçãoQA_enviodeparecernoprazodeQA](https://user-images.githubusercontent.com/75261677/120511315-af68d980-c3a0-11eb-918f-fc7f6aef1511.gif)

**Comment by daphnemartinsba** [comment]
O fluxo do envio do parecer ocorre após a conclusão do prazo de prestação de contas, portanto, quando o prazo constar como concluído e as avaliações de todas as prestações constarem como realizadas, o botão "enviar pareceres" estará disponível e funcional.
