### ISSUE TITLE
Publicação do resultado por inscrição ao invés de em lote

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#1840]
Os projetos acontecem em diferentes períodos de tempo, alguns duram um mês, outros meses e outros podendo durar até um ano.
Resposta Técnica: Isso apresenta uma complexidade, por isso tem que pensar bem em como fazer. Para isso, tem que analisar as permissões e talvez ignorar o botão atual para fazer um botão por proponente.

**Comment by daphnemartinsba** [comment]
A publicação por inscrição está funcionando somente com o cadastro de superadmin. O gestor da oportunidade que possui permissão normal não consegue publicar as inscrições individualmente.
publicação pelo Gestor com permissão normal:
![validaçãoQA_publicaçãoporinscriçãopermissãonormalgestor](https://user-images.githubusercontent.com/75261677/120508921-7f203b80-c39e-11eb-8c4d-0e210f3f020f.gif)
publicação pelo cadastro superadmin:
![validaçãoQA_publicaçãoporinscriçãopermissãosuperadmin](https://user-images.githubusercontent.com/75261677/120508971-89dad080-c39e-11eb-9372-c70a1f0d8ee4.gif)

**Comment by daphnemartinsba** [comment]
A publicação por inscrição está funcionando e não é mais possível para o parecerista reabrir o parecer após a publicação da inscrição
