### ISSUE TITLE
Na tela do parecer, no textárea do parecer técnico. Inserir um editor de texto como por exemplo CKEDITOR

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1841]
A ideia e que seja possível abrir e fechar a conversa do chat para que a tela fique mais clean.

Antes de seguir, analisar issue #1837 para entender estudo feito

**Comment by JoseCage** [comment]
Configurado e implementado no PR #1845 //Commit: https://github.com/mapasculturais/mapasculturais/commit/f2ad1eed1ff04b036165e776ce5c5ee0c3797b6e

**Comment by daphnemartinsba** [comment]
O editor foi implementado e suas funcionalidades estão se comportando corretamente, as funcionalidades são: Desfazer; refazer; negrito; itálico; cor do fundo (grifa o texto); alinhamento à esquerda; alinhamento central; alinhamento à direita e alinhamento justificado.
