### ISSUE TITLE
Verificar excesso de requisições para o servidor no carregamento automático de mensagens do chat da prestação de contas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1843]
Percebido que ao enviar a primeira mensagem, o chat faz diversas requisições seguidas ao servidor e que quando se enviar mais de um texto, as querquisições vão aumentando

![Peek 25-05-2021 10-51](https://user-images.githubusercontent.com/39862175/119509800-561cfc80-bd47-11eb-9157-d5826508ea62.gif)

**Comment by daphnemartinsba** [comment]
Quando o foco está no textarea as requisições são de 10000 milissegundos e quando está fora do textarea são de 60000 milissegundos.
![image](https://user-images.githubusercontent.com/75261677/120493979-cce27700-c391-11eb-98c5-f29ea9c74551.png)
