### ISSUE TITLE
Na atela de gestão do usuário inserir aba que liste e mostre as inscrições vinculada ao usuário

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1852]
![image](https://user-images.githubusercontent.com/39862175/127175476-14d4c37e-5da6-4736-af39-16abca0fd7a9.png)

**Comment by daphnemartinsba** [comment]
A aba além de disponível está com a listagem correta. Contudo, a aba de não selecionadas não possui a quantidade de inscrições como as demais abas: 
![image](https://user-images.githubusercontent.com/75261677/152036322-c35c0ce4-9726-47b6-81c8-e6c7cbc8e872.png)
