### ISSUE TITLE
@campos do Agente Responsável de seleção única ou múltipla não possuem opções de preenchimento

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1865]
@campos do Agente Responsável de seleção única ou múltipla, como os campos de Raça/cor, gênero, área de atuação e orientação sexual, não vem com a possibilidade de configurá-los ou com as informações pré-configuradas, assim não é possível selecionar opções durante o preenchimento da ficha de inscrição.

Comportamento adequado:  Nos campos de seleção múltipla ou única do @campo do Agente Responsável, deve-se ter a possibilidade de preencher a lista do campo criado com as informações do cadastro pré setadas

Exemplo da configuração de criação do campo:
![image](https://user-images.githubusercontent.com/75261677/138951775-074c3f06-7ab2-4ad8-80e5-8aa6735ecc1f.png)

Exemplo de como o campo aparece no formulário:
![image](https://user-images.githubusercontent.com/75261677/138951915-1c3691ff-b84a-415b-8e57-3d61dac0d793.png)

**Comment by daphnemartinsba** [comment]
Os testes foram realizados nos três ambientes dev (ES, MS e PA) e ocorreram os mesmos comportamentos.
Os campos do Agente, supracitados na issue, sempre são atualizados conforme a opção selecionada no @campo do Agente Responsável de uma ficha de inscrição. 
Segue a demonstração no gif abaixo:
![Issue 1865 ES](https://user-images.githubusercontent.com/75261677/152204657-f6098399-843b-46f5-99d9-103e42da773d.gif)

**Comment by daphnemartinsba** [comment]
**Sobre a Issue:**
Foi conversado na reunião diária do dia 03 de fevereiro de 2022 que o fluxo adequado para os @campos do Agente Responsável abarcados na resolução aqui implementa deva envolver uma validação dos valores dos @campos do Agente Responsável de modo que não seja possível inserir opções no @campo do Agente Responsável que não estão presentes no campo relativo ao perfil do Agente.

Campos de Raça/Cor do perfil do Agente:
![image](https://user-images.githubusercontent.com/75261677/152409493-5571bb21-bed3-4630-9250-a266edd8da64.png)

**Comportamento atual da criação do campo:**
![image](https://user-images.githubusercontent.com/75261677/152409614-398ac856-fc3c-4348-b04c-87c27f52c13a.png)

**Comportamento esperado:**
Elencar talvez checkbox para serem selecionados durante a criação do campo como seus possíveis valores, como por exemplo:

- [ ] Não Informar
- [ ] Branca
- [ ] Preta
- [ ] Amarela
- [ ] Parda
- [ ] Indígena

**Comment by rafaelchavesfreitas** [comment]
feito
