### ISSUE TITLE
Avaliação Técnica: Avaliadores não conseguem utilizar o filtro "filtrar pendentes" durante a avaliação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1867]
Na tela do Avaliador, durante avaliação em um edital que possui avaliação técnica, o filtro das avaliações pendentes não está com o comportamento adequado.

Tela do Avaliador antes de aplicar o filtro:
![image](https://user-images.githubusercontent.com/75261677/139069402-abaf3c56-f40f-4ae4-a138-1764d5575faa.png)

Tela do Avaliador quando o filtro está aplicado e as inscrições ainda não foram avaliadas:
![image](https://user-images.githubusercontent.com/75261677/139069731-cfb20149-db0f-4fab-8135-ec2d7b9d63bd.png)

**Comment by daphnemartinsba** [comment]
O commit relacionado não trata do problema relatado

**Comment by rafaelchavesfreitas** [comment]
resolvido
