### ISSUE TITLE
Conflito de Permissões de Agentes que são Avaliadores e Suporte ou que são Avaliadores e tem permissões de edição na Oportunidade

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1870]
Quando um Agente é cadastrado como Avaliador e possui permissão de edição na oportunidade, ao acessar a tela de avaliação ele não consegue emitir a avaliação porque a tela fica assim:
![image](https://user-images.githubusercontent.com/75261677/139094565-408fbeff-3ac9-414d-9dbf-9577c2a1631f.png)

Quando o Agente é Avaliador com permissão normal e é adicionado no suporte ao clicar na inscrição na página de suporte:
![image](https://user-images.githubusercontent.com/75261677/139095953-8be5f91e-c4be-4027-bc9e-173e8cba388d.png)
ele é direcionado para a tela de avaliação:
![image](https://user-images.githubusercontent.com/75261677/139096081-84a30ae8-46b2-4366-b96e-ae49bc1a0287.png)
Mas se clica em Acessar página de suporte, ele é direcionado para a página de suporte

**Comment by erleibiazzio** [comment]
**Seguem abaixo observações feitas no teste local**

1) - Nos testes executados localmente, no caso 1, como motra **GIF1**  e **IMAGEM1**. Criei uma oportunidade como usuário normal e inseri esse usuário como avaliador. O formulario de avaliação apareceu normalmente para o agente.


**IMAGEM1**
![image](https://user-images.githubusercontent.com/39862175/150455181-236f192e-af71-4635-a668-01e4615c3194.png)

**GIF1**
![agente-editor-e-avaliador](https://user-images.githubusercontent.com/39862175/150455339-facff1bd-77f1-4214-9d96-5ddb70af5af9.gif)

2) - Ao entrar com um agente comum sendo ele avaliador +suporte. Na aba de suporte quando clicado na inscrição o agente é levado para área de suporte como mostra **GIF2**

**GIF2**
![agente-editor-e-avaliador-e-suporte](https://user-images.githubusercontent.com/39862175/150456170-77ff10be-62e7-4a44-a593-261197aec055.gif)
