### ISSUE TITLE
Filtro pelo nome do agente na tela de avaliação não funciona

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1873]
**O Problema:**
Na tela de avaliação, com perfil do avaliador. Ao tentar filtrar no campo do nome do agente não exibi o nome filtrado

![Peek 08-11-2021 16-57](https://user-images.githubusercontent.com/39862175/140809272-505b7dd4-c9ae-4636-8b64-1f8c3134dff0.gif)

**Comment by daphnemartinsba** [comment]
O teste foi realizado nos três ambientes de dev (MS, PA e ES). Mas o comportamento esperado só ocorreu no MS.

**Comment by rafaelchavesfreitas** [comment]
feito
