### ISSUE TITLE
lista de avaliações no formulário de avaliação não aparece nas fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1875]
como deveria ser:

![image](https://user-images.githubusercontent.com/1181261/143460983-2ef3b094-8ec5-47a6-8ff5-7b7bba4c841a.png)

como aparece:

![image](https://user-images.githubusercontent.com/1181261/143461094-5fa33eaf-2f55-4d76-a1ca-671aef39122d.png)

**Comment by daphnemartinsba** [comment]
O teste foi realizado nos três ambientes de dev: PA, MS e ES. Em uma segunda e uma terceira fase, o comportamento foi o esperado, sendo possível visualizar a lista de inscrições de ambas as fases e em ambos os ambientes.
PA Segunda Fase:
![Captura de tela de 2022-01-26 17-07-24](https://user-images.githubusercontent.com/75261677/151241260-a17730a5-f759-4b84-a355-793f39ff7699.png)
MS Terceira Fase:
![image](https://user-images.githubusercontent.com/75261677/151241294-b6a7df4e-918f-424d-bdd1-9d3c42ce2b36.png)
ES Terceira Fase:
![image](https://user-images.githubusercontent.com/75261677/151241346-0d9084e1-5359-43df-b31b-d2d31ea0a629.png)
