### ISSUE TITLE
formulário de avaliação aparece após o envio das avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1876]
Após o avaliador enviar as avaliações, como na imagem abaixo
![image](https://user-images.githubusercontent.com/1181261/143463778-e4126104-5afc-4485-99dc-7d507d280046.png)

ao entrar na ficha de inscrição ele nào deve ver o formulário de avaliação.

como deveria aparecer:
![image](https://user-images.githubusercontent.com/1181261/143463647-8d6f8d6d-314c-426a-abfe-f2ac1315668b.png)

como aparece:
![image](https://user-images.githubusercontent.com/1181261/143463710-30aecdd6-dcd0-4c40-b21b-79f51ce99195.png)

**Comment by daphnemartinsba** [comment]
Foi testado nos três ambientes de teste (PA, MS e ES) e em todos o funcionamento é o mesmo, após o envio das avaliações o avaliador não consegue mais editá-la a não ser nos casos em que a gestão reabre as avaliações na configuração das avaliações.
PA:
![image](https://user-images.githubusercontent.com/75261677/151233587-4d955b23-dcfa-47b2-9b7c-647f6e51a17c.png)
ES:
![image](https://user-images.githubusercontent.com/75261677/151233618-c98c917b-1ad4-45b1-9535-3b39924a6e24.png)
MS: 
![image](https://user-images.githubusercontent.com/75261677/151233649-1617c223-d62c-47dd-8200-bfbcacf71a98.png)
