### ISSUE TITLE
criar versão de impressão do formulário de inscrição

### ISSUE THREAD

**Issue by Uragawa** [mapasculturais/mapasculturais#1882]
Deve ser adicionado um botão no formulário de inscrição para gerar uma versão de impressão do mesmo, bem como os estilos e alterações necessárias para que o botão funcione.

**Comment by Uragawa** [comment]
Generalizar da implementação do IberCultura, feita no próprio tema específico.

**Comment by rafaelchavesfreitas** [comment]
feito
