### ISSUE TITLE
componentes para listagem das entidades no painel

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1893]
- [x] panel--entity-actions - botões deletar, arquivar, publicar, etc
- [x] panel-- entity-tabs - abas e listagens de entidades

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/781a51fb-3d6a-4e7b-aac2-e38a39a60125)
