### ISSUE TITLE
omitir campos não permitidos para os avaliadores

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1955]
na fixa de inscrição exibida para o avaliador, só exibir os campos permitidos, que estão salvos no metadado `availableEvaluationFields`

será algo como um `ng-if="opportunity.availableEvaluationFields[field.id]"`

**Comment by daphnemartinsba** [comment]
Quando a configuração é:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fcfa6553-2919-4c84-808a-b9f2289f78a8)

O avaliador visualiza:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a89037f6-7eef-4759-a99b-a5cd1ddb090a)
