### ISSUE TITLE
Reorganização da tela de cadastro para adequação à LGPD

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1961]

**Comment by daphnemartinsba** [comment]
Segundo a LGPD, no artigo quinto: 
I - dado pessoal: informação relacionada a pessoa natural identificada ou identificável; *
II - dado pessoal sensível: dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; **

Para informar ao usuário qual o caráter do dados que estão fornecendo, os campos dos agentes devem ser sinalizados se são de preenchimento de dados pessoais ou de dados pessoais sensíveis.

Campos dos Agentes que solicitam Dados Pessoais: Nome Completo, CPF, E-mail privado, E-mail público, Telefone Público, Telefone 1, Telefone 2, Endereço.

Campos dos Agentes que solicitam Dados Pessoais Sensíveis: Data de Nascimento, Gênero, Orientação Sexual, Raça/Cor.

Os demais campos podem aparecer no cartão de visita.

obs:

- [ ] A confirmar com a advogada no que tange ao direito da imagem, referente aos campos de banner, avatar, downloads, galeria e vídeos.
