### ISSUE TITLE
Reorganizar a tela de cadastro do agente INDIVIDUAL agrupando em 3 blocos: Cartão de visita, Dados Pessoais e Dados Pessoais Sensíveis

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#1962]
Cartão de visita:
informações públicas

Dados pessoas e pessoais sensíveis:
Informações sigilosas

**Comment by daphnemartinsba** [comment]
Lista de Campos do Agente:
- Tipo do Agente

- Banner
									
- Avatar
					
- Nome de Exibição
					
- Área de Atuação
			
- Descrição Curta
				
- Site
				
- Nome Completo
				
- CPF/CNPJ
					
- Data de Nascimento/Fundação
					
- Gênero
				
- Orientação Sexual
				
- Raça/Cor
				
- Email Privado
				
- E-mail
				
- Telefone Público
				
- Telefone 1
				
- Telefone 2
			
- Endereço (CEP, logradouro, número, complemento, bairro, município, estado, localização [Pública ou Privada])
				
- Descrição
				
- Vídeos
			
- Galeria
			
- Downloads
		
- Links

**Comment by daphnemartinsba** [comment]
Dados Pessoais sumiram:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d9029537-a909-414e-9669-f3fff38ce8c6)

**Comment by daphnemartinsba** [comment]
No modo de edição:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/88472364-8b6d-49f3-a245-b4fbed747103)

Quando uma informação pública é preenchida, fora do modo de edição:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/acca33ce-9691-4645-9437-d78811741f9f)
