### ISSUE TITLE
remover o owner do endpoint findEvaluations quando o avaliador não tiver permissão de ver o resumos dos agentes

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1966]

**Comment by daphnemartinsba** [comment]
Ao remover o owner do endpoint findEvaluations os avaliadores não podem ver o nome do agente nem o resumo das informações do agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9f39f0ae-c09b-458a-ba92-d559c5af2eae)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b1893888-fb36-462d-a782-e6a3f0466c11)
