### ISSUE TITLE
para os avaliadores, remover do jsonSerialize do Registration os campos que os avaliadores não puderem visualizar

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1967]

**Comment by daphnemartinsba** [comment]
Ao ocultar os campos, caso o jsonSerialize não seja removido ele deve ser listado no console da inspeção ao digitar MapasCulturais.entity.object.
Conforme gif, nenhum campo oculto foi listado:
![CT - Permissão dos Avaliadores - 06-05-2022 10-30.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/10fb5bd5-56ca-4049-b6f3-b5aa974ef171)
