### ISSUE TITLE
criar a interface de configuração das políticas afirmativas na aba de configuraçao das avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1970]
- campo para definição da porcentagem máxima (ou teto) que o proponente pode receber.

- se basear na implementação da tabela de critérios de uma seção
- para cada nova regra das políticas afirmativas o gestor deverá informar 3 valores:
1. a porcentagem que será aplicada aos inscritos que se encaixarem na política
2. um campo de seleção (múltipla ou única) ou um de checkbox dentre os campos da ficha de inscrição;
3. quais valores desse campo selecionado receberão a porcentagem da política afirmativa. No caso do campo ser de seleção, exibir os valores em checkboxes; no caso do campo ser um checkbox, mostrar um select com as opções "Sim" ou  "Não";

 ex: Se o gestor escolheu o campo raça, exibir as raças disponíveis ao lado de checkboxes; Se o gestor escolheu um campo do tipo checkbox "Pertence a uma comunidade ribeirinha", exibir o select.

- enviar para o backend da mesma maneira que são enviados os crittérios

**Comment by daphnemartinsba** [comment]
Resumo:  
A interface permitiu:
Criar Seção de Políticas Afirmativas;
Escrever a porcentagem limite; 
Adicionar critérios;
Selecionar os campos do formulário da fase em questão;
Marcar os valores dos campos do formulário que serão computados conforme a porcentagem atribuída, quando preenchidos na ficha de inscrição; 
Escrever os valores percentuais por critério adicionado.
