### ISSUE TITLE
aplicar o resultado das porcentagens na consolidação do resultado da avaliação.

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1971]
implementar no métdodo `EvaluationMethodConfiguraion\Plugin::_getConsolidatedResult`

**Comment by daphnemartinsba** [comment]
Resumo: Foi verificado que o resultado da avaliação na aba de inscritos refere-se à soma das porcentagens aplicadas nas notas, conforme o preenchimento da ficha de inscrição, com os valores das notas atribuídas. Portanto, somou-se o valor da nota, com a porcentagem vezes a nota dividida por 100. Em ambas avaliações a nota apresentada estava correta.
