### ISSUE TITLE
Ajustar visualização na listagem dos campos permitidos dos avaliadores na tela de configuração de avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#1972]
- Dar quebra de linha nos checkbox
- Inserir ID dos campos do formulário

**Comment by daphnemartinsba** [comment]
Visualização dos ids dos campos: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/59704897-82cc-4a7c-8465-8ad9bd275c7a)

Visualização da configuração das permissões:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/40f00a01-f61e-4244-9862-49b188fe618a)
