### ISSUE TITLE
Reorganizar tela de cadastro de ESPAÇO adicionando a lógica do cartão de visitas*

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1974]
* como foi implementado no cadastro de agente INDIVIDUAL

**Comment by daphnemartinsba** [comment]
Foi conferido que os elementos do cartão de visita se enquadram na tela do evento, constando as informações: nome, subtítulo, descrição, curta, avatar, banner, tags, linguagens. Não houve sobreposição de elementos na tela de exibição do evento.

- [ ] Conforme ocorre no Evento e no Projeto, a Descrição Curta do Espaço também está sem o estilo igual a do Agente.

- [ ] Faltou o site

**Comment by daphnemartinsba** [comment]
O cartão do Agente está como do Espaço:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9e8a3026-864f-45a1-9abc-65212207c211)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c61f72e0-ebcb-48da-9825-c91d9bab1253)
