### ISSUE TITLE
 Reorganizar tela de cadastro de EVENTO adicionando a lógica do cartão de visitas* 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1975]
* como foi implementado no cadastro de agente INDIVIDUAL

**Comment by daphnemartinsba** [comment]
os elementos, como a descrição curta, diferem da formatação realizada no Agente:
	Formatação do Agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fe0c3ad4-e75d-4d90-98a9-e399f9837e4b)
	Formatação do Evento:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/068acfae-290a-481d-b788-313fb4c56c26)

**Comment by daphnemartinsba** [comment]
O cartão do Evento está como o cartão do Agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c0956efa-409d-4add-a02f-82e36717b3b4)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/28a290d9-a486-4045-acc2-74c9f31a52f8)
