### ISSUE TITLE
 Reorganizar tela de cadastro de PROJETO adicionando a lógica do cartão de visitas*

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#1976]
* como foi implementado no cadastro de agente INDIVIDUAL

**Comment by daphnemartinsba** [comment]
O cartão do projeto está como o do agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ff25506b-a83a-4695-99df-0b4f7abd5337)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c621b8cd-d16f-4bd3-b16f-d8519fd0d243)
