### ISSUE TITLE
Aplicar um Limite de 400 Caracteres na Descrição Curta do Cadastro do Agente

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1991]
Comportamento Atual: O limite de caracteres está maior que 400.
Comportamento adequado: Limitar o campo em 400 caracteres e emitir um aviso quando o usuário exceder.

**Comment by robedj** [comment]
Correção realizada no agente.

**Comment by daphnemartinsba** [comment]
O campo contém um contador de caracteres, que conforme se preenche o campo com um caractere consta como: 1/400, ao constar 400 caracteres inseridos não é possível preencher o campo com mais caracteres e o contador consta como 400/400.
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/75c47067-7f6c-4f97-8144-977245997ee7)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7f06c456-7e16-4c3e-a5d6-9f9db63e30ed)
