### ISSUE TITLE
QA: Cadastro de Agentes

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#1993]
- [x] Ao marcar o endereço como público em um agente, quando um usuário visualiza esse agente ele não consegue visualizar o endereço ou o mapa.

- [x] Quando um usuário visualiza um agente que não preencheu os dados pessoais, consta apenas o título "Dados Pessoais" sozinho na tela do agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/31141ceb-c4c8-4b99-a45e-6df7fd111713)

**Comment by daphnemartinsba** [comment]
O endereço não aparece quando está marcado como privado e aparece quando está marcado como público.
O bloco de dados pessoais ainda está aparecendo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d7e8f778-e2a7-4744-93f5-74a3c92cbeb9)

**Comment by erleibiazzio** [comment]
Apos verificar, percebi que o ambiente nao estava atualizado corretamente com as novas alterações. Apos hoje 13/05 foram aplicadas corretamente.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/d26eea03-02ed-4442-9183-3129740e2e47)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/4d1f8546-e8f9-42b6-a6c9-c6291d8f1235)

**Comment by daphnemartinsba** [comment]
Relatório de Reteste:

- [ ] O campo de e-mail público é automaticamente preenchido durante o cadastramento (pela tela de autenticação) no Mapas. Como é um dado pessoal, o e-mail público deve ser preenchido posteriormente ao cadastramento. De modo que o dado pessoal não é fornecido e exposto por vício de consentimento.

- [ ]  Sobre as informações públicas dos Agentes Coletivos: Como portadores de CNPJ, ou grupos coletivos sem CNPJ não possuem dados pessoais, ou dados pessoais sensíveis, todos os dados do Agente Coletivo podem ou devem ser públicos.

- [ ] Ficha de Inscrição: Ao configurar o formulário em uma oportunidade com o campo de endereço, do campo @ do agente responsável, e não habilitar se o inscrito deve optar ou não pelo endereço ser público ou privado, o endereço ao ser preenchido é setado automaticamente como público.

**Comment by erleibiazzio** [comment]
Item da ficha de inscrição, em todos os testes feitos o agente foi cadastrado com os dados de endereço de foma privada. Para garantir...

**Comment by daphnemartinsba** [comment]
- [ ] Alterar texto da contagem dos caracteres.
Texto atual:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/10682fc0-2d23-4496-8298-69cbc89a6de8)

Textos que podem ser adequados:

- (41 a 400 caracteres):

- 41/400

**Comment by erleibiazzio** [comment]
Item sobre os dados públicos ou privados do coletivo, aguardo definição do que fazer na tarefa.

**Comment by daphnemartinsba** [comment]
Antes do reteste ser feito foi observado o comportamento onde os caracteres inseridos são realmente 400, mas o sistema reconhece 13 a mais, por conta de caracteres múltiplos:
![caracteres.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/4ea9a199-3081-499c-b68e-5c94ddd7df41)

**Comment by daphnemartinsba** [comment]
Cartão de Visita do Agente Coletivo:

- [ ] Retirar o título Dados Pessoais

- [ ] Deixar apenas data de fundação

**Comment by daphnemartinsba** [comment]
O cartão de Visita do Agente Coletivo consta com os campos de Nome Fantasia e Data de Fundação: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/db43a601-1f53-49a2-a934-a386422bb70c)
