### ISSUE TITLE
Na lista ou no mapas dos eventos, filtrar a data do evento por período anual

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2006]
No momento o filtro da data de evento é mensal, isto é, lista ou mapeia somente os eventos que ocorrerão naquele mês:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2a5f5596-db70-4b00-8318-9e4155674b0b)

Como hoje é dia 11/05/22, o mapas está filtrando de 11/05/22 até 11/06/22. Seguindo esse exemplo, o ajuste deve passar a filtrar do dia 11/05/22 até 11/05/23, se os eventos fossem acessados amanhã, o filtro deveria ser 12/05/22 até 12/05/23.

**Comment by daphnemartinsba** [comment]
A lista e o mapa estão com filtro por período anual:
![lista de evento.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/785f8bb4-c7e2-47f3-aee1-f2e8eb9e3ca8)
