### ISSUE TITLE
Gestão do usuário: Não pesquisa por evento

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2007]
Mesmo que hajam eventos cadastrados, a gestão do usuário não pesquisa:
![Peek 11-05-2022 10-42.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b5e72287-3232-42a8-8ae2-38ec9f408eae)

**Comment by daphnemartinsba** [comment]
Os eventos são listados na gestão de usuário, mas apenas os que possuem espaço vinculado. O comportamento adequado é que todos os eventos sejam listados, com ou sem espaço.
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/77a1cc04-5b4b-4957-9202-3af742108b8b)

**Comment by daphnemartinsba** [comment]
Todos os eventos, contendo espaço ou não, são listados:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/91cd85cd-935d-488a-9aeb-3612ba2c1ad9)
