### ISSUE TITLE
Botão ok da seleção do tipo do sub espaço não funciona

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2010]
No momento, ao criar um subespaço, selecionar seu tipo e clicar em ok, o tipo não consta como selecionado:
![Peek 11-05-2022 10-25.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1d33a13a-e5b1-4831-aa6c-fa5384bfac4d)

**Comment by erleibiazzio** [comment]
Aparentemente seja um problema de resolução dos monitores, aqui testando diretamente no ambiente de DEV do mapas estava tudo OK como mostra imagem abaixo.

![Peek 16-05-2022 14-42.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e93594f2-883d-44b2-bbf2-ebc218de4ae5)

**Comment by daphnemartinsba** [comment]
O botão está funcionando de modo intermitente, sempre que é clicado funciona, contudo, não é sempre que é clicável ao posicionar o mouse em cima:
![tipo espaço.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f28e7401-90c9-45c9-855f-a9c7efb3ed01)

**Comment by daphnemartinsba** [comment]
O botão ok da seleção do tipo do espaço funciona:
![tipoespaco.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1141fa75-ae04-4543-a0f6-fca6bebd2986)
