### ISSUE TITLE
QA: Políticas Afirmativas

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2012]
- [x] Comportamento inesperado na extração da planilha. A planilha apresenta uma coluna que informa:

1 - Qual o valor do campo das políticas afirmativas que foi selecionado
2 - A porcentagem a ser aplicada na nota cujo produto será somado na nota
3 - o valor da nota
4 - o valor que será somado a nota (avaliação x porcentagem)
5 - O resultado final da avaliação

Verificado: Os itens 2, 3, 4, e 5 conferem.
Comportamento inesperado: No item 1 o valor dos campos não correspondem ao selecionado pelo proponente na ficha de inscrição.

- [x] Comportamento inesperado:
Em uma oportunidade com duas fases, a primeira fase sendo documental e a segunda fase sendo a técnica.
Ao aplicar o status das inscrições na primeira fase, para importá-las para a segunda, configurar os campos da política afirmativa na segunda e avaliá-las na segunda fase, e então, **ao alterar na inscrição da primeira fase, via suporte, o campo da política afirmativa selecionado, o percentual não é contabilizado na nota final da segunda fase.**

**Comment by daphnemartinsba** [comment]
- [ ] Alterar nome do botão para "Utilizar políticas afirmativas"
O botão que deve ser alterado:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/636380f2-c033-4b72-a8e7-6a360c61b408)
- [ ] Alterar texto: "Configure abaixo as políticas afirmativas"
O texto que deve ser alterado (cortado):
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/22376c76-6acc-4f94-85b2-bc4ad5cd821b)![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/aa75d253-9f7e-4ae2-b429-90a08e9221c8)

- [ ] Adicionar ID dos campos:
Onde está as opções dos campos, deve constar também os ids dos campos
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c1e3da7e-5cc2-435e-ab7e-f882fc60b3e7)

- [ ]

**Comment by robedj** [comment]
Eu e erlei atualizamos a master com as correções

**Comment by daphnemartinsba** [comment]
**CT01- Configuração da Avaliação**
**Issue:** https://github.com/mapasculturais/mapasculturais/issues/1970; https://github.com/mapasculturais/mapasculturais/issues/1969
**Comportamentos Inesperados**

- [ ] HTML da configuração da avaliação extrapola a seção:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/576d1578-ba92-437b-962b-c3606daf9621)

- [ ] Campos com nomes grandes extrapolam a tela:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/836dc6b3-6640-49f0-bd4e-88aa44d12bd9)

- [ ] Campos condicionados a outros campos não são listados no campo da configuração das políticas afirmativas:
![campoformulariocondicionalpoliticas.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/696d4fcc-28c3-4644-a692-24c7ab0a40a5)

**Comment by daphnemartinsba** [comment]
2° Reteste:

- [ ] Foi possível enviar as avaliações antes do término da segunda fase;

- [ ] Quando um campo possui três valores E (&&) cada valor desse campo possui seis campos diferentes condicionados a eles. E (&&), um proponente preenche seis campos condicionados a um valor, E (&&) altera o valor, preenchendo seis campos novamente, são contados doze campos de porcentagens.

- [ ] Quando altera o limite da soma das porcentagens, a nota também não é atualizada.
- [ ] Caso atualize o limite dos campos, atualizar a planilha

- [ ] O texto política afirmativas atribuídas possui um erro de portugues no “Afirmativas”, está escrito: Políticas afimativas atribuídas, sem o R no afirmativas.
