### ISSUE TITLE
Inserir opção de sair quando agente é redirecionado para edição para completar os dados mínimos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2016]
Ao efetuar login, e o sistema de redirecionamento para completar a edição do agente estiver ativado. O agente fica travado, sem opção de deslogar.

Comportamento esperado é que exista opção para o usuário escolher deslogar no manu

**Comment by daphnemartinsba** [comment]
É possível deslogar quando o agente ainda não foi publicado:
![agentenaopublicado.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a13c627e-e6cd-48a6-a36d-de52cd9d665b)
