### ISSUE TITLE
QA: Permissão de Avaliadores

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2019]
Na configuração da permissão dos avaliadores o ID do campo deve ser da mesma classe que o ID do campo da configuração do formulário (tem que ficar verde).

**Comment by daphnemartinsba** [comment]
Na configuração da permissão dos avaliadores deve:

- [ ] Ter checkbox de marcar todos e desmarcar todos

- [ ] Ter um campo de busca que servirá como filtro para buscar o campo pelo id ou nome

**Comment by erleibiazzio** [comment]
Correções referentes ao relatório
https://docs.google.com/document/d/1MkI7LFQtXuq6rqnGvsmEsw7v9NwyKG1zYPLB1EjQ8TQ/edit#

- [ ] No filtro, ao marcar somente um campo vinculado a categoria, o campo não fica visível na tela da avaliação.
- [ ] O campo do Projeto fica escondido para proponente e gestor.

**Comment by daphnemartinsba** [comment]
Quando é configurado somente do campo vinculado a categoria:
![categoriapermissão.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a94ff677-e8e3-4a25-9b25-40c405242b2e)

**Comment by daphnemartinsba** [comment]
O campo do projeto fica visível para o gestor quando oculto para o avaliador:
![projetopermissãoavaliadores.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e67cdddb-5bf1-436a-b3c2-152e75fc1454)

**Comment by daphnemartinsba** [comment]
Quando é configurado somente o campo condicionado ao outro, somente ele se torna visível para o avaliador:
![campocondicionadopermissao.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c20a5db1-458a-47e9-a048-62227de2b789)
