### ISSUE TITLE
implementar header do tema BaseV2

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2024]
- a implementação deve ser feita num novo template part dentro do tema BaseV2: `layouts/parts/main-header.php`
- quem chama o main-header é o arquivo de laytout `layout/default.php`, que ficará assim:
```PHP
<?php
$this->part('header', $render_data);
$this->part('main-header', $render_data);
echo $TEMPLATE_CONTENT;
```

- os itens Início, Oportunidades, Agentes, Espaços, Eventos e Projetos devem ter um estado ativo, que fica com a cor definida para a entidade
- a definição de qual item está ativo pode ser obtido com `$this->mainHeaderActiveItem`, ou seja `<?php if($this->mainHeaderActiveItem == 'agents') ?> class="active" <?php endif; ?>`
- a parte de notificações será um componente desenvolvido no módulo Components, por enquanto deixar só um placeholder

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/30b2e013-7916-46b5-8395-6f1ba2ec7bdc)

**Comment by Raul-vlb** [comment]
![image.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/5b7b4df4-31ae-444a-9bc0-9ea9e2d1cc1f)
- [ ] Refatorar o header do tema BaseV2

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/098e1821-c354-4a21-8df0-ae8f38ce4246)
