### ISSUE TITLE
implementar footer do tema BaseV2

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2025]
- a implementação deve ser feita num novo template part dentro do tema BaseV2: `layouts/parts/main-footer.php`
- quem chama o main-footer é o arquivo de laytout `layout/default.php`, que ficará assim:
```PHP
echo $TEMPLATE_CONTENT;
$this->part('main-footer', $render_data);
$this->part('footer', $render_data);
```
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/4b7038c4-2317-45e9-b798-70e348bbae60)

**Comment by rafaelchavesfreitas** [comment]
precisa usar as funções de internacionalização

**Comment by rafaelchavesfreitas** [comment]
link do Acesse deve levar para o painel (`$app->createUrl('panel', 'index')`)

**Comment by Raul-vlb** [comment]
![image.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/6a3d28f1-82f8-47ae-b544-1d70d15b31aa)

- [ ] Remoção dos links não existentes (faq e como utilizar)
- [ ] Como configurar os links das redes sociais
- [ ] botão sair apenas quando estiver logado

**Comment by robedj** [comment]
Só faltam os termos de uso, vou colocar no review.

**Comment by rafaelchavesfreitas** [comment]
@robedj na parte dos termos de uso, política de privacidade, autorização de imagem, utilizar o código abaixo:
```
<?php foreach($app->config['module.LGPD'] as $slug => $cfg): ?>
    <li><a href="<?= $app->createUrl('lgpd', $slug) ?>"><?= $cfg['title'] ?></a></li>
<?php endforeach ?>
```

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/130b2e24-1018-4c32-a4fa-0f251663e768)
