### ISSUE TITLE
implementar modo de ediçao no componente entity-terms

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2029]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/01f3d490-bb53-4b19-8517-fd6cd6e1bdb2)

- adicionar propriedade `editable`, que quando for verdadeiro muda a interface para a o modo de edição

**Comment by rafaelchavesfreitas** [comment]
estilizar popovers de acordo com o Figma

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/cee277a3-7023-4a1a-9772-ac74c1cd8593)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/5fa5f93d-039d-4989-bc36-d8d25ace9132)

**Comment by daphnemartinsba** [comment]
Tirar negrito dos options (áreas de interesse selecionadas).
