### ISSUE TITLE
implementar modo de edição do <entity-seals>

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2030]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/67d995d5-7407-46a4-9f7c-38d06d76f91c)

- adicionar propriedade `editable`, que quando for verdadeiro muda a interface para a o modo de edição

**Comment by Raul-vlb** [comment]
Faltam as imagens, será tratado em outras issues!
