### ISSUE TITLE
Impossibilitar o envio e a visualização de inscrições pelo proponente em fases excluídas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2039]
**Visualização do problema.**
1) Criar uma oportunidade de 2 fases
2) Fazer 1 inscrição na fase 1 enviar e deixar ela com status de selecionada
3) Importar a inscrição para segunda fase e deixar como pendente
4) excluir a segunda fase
5) entrar no perfil do proponente e tentar enviar a inscrição relacionada a segunda fase

**O Problema**
Quando se segue os passos acima, é possível o proponente fazer o envio da inscrição da segunda fase mesmo que a mesma esteja excluída.

**Solução**
Retornar ```false``` nas permissões ```canUserSend``` e ```CanUserView``` impossibilitando o acesso a inscrição caso a fase que ela esteja esteja com status  ```<1 ```

![Peek 31-05-2022 17-28.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/528883a3-e8f4-4e63-9923-736c94c7a0e0)

![Peek 31-05-2022 17-28-2.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/26ddaaf8-d843-45ab-b1b6-37cb65e7dc6c)

**Comment by daphnemartinsba** [comment]
Quando a 2° fase é excluída, ao tentar acesso à ficha de inscrição da 2° fase, o proponente é direcionado para uma mensagem de permissão negada.
