### ISSUE TITLE
[Base V2] Edição da single-1 do Agente 

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2044]
Edição da tela single-1 do Agente na base V2.

**Comment by robedj** [comment]
issues referentes:
- [83aa792](https://github.com/mapasculturais/mapasculturais/commit/b165eedf18ec4407469f936bc5e42b16d83aa792)
- [9505f39](https://github.com/mapasculturais/mapasculturais/commit/ee23df1cdac87e9f347eda21f591e41509505f39)
- [f8a55b1](https://github.com/mapasculturais/mapasculturais/commit/0287be7c18a1fa0f1c8dddea95a4a4c0cf8a55b1)
- [1b060af](https://github.com/mapasculturais/mapasculturais/commit/48518971af5fba7cee0ca71303c921d011b060af)
- [f819260](https://github.com/mapasculturais/mapasculturais/commit/5dd06b5d606bdd4ffd20b2171b30d971ef819260)

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ff401675-a93e-44fd-9f23-a86a635099c5)
