### ISSUE TITLE
Implementar o componente do grupo de agentes entity-related-agents

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2051]
Essa issue pode ser realizada após a issue #2054
- Assim como nos adms os agentes estão no objeto agent related;
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/47a4897e-cd2d-4148-8ab3-86bbf10a0a7c)
- nesse caso não passa pelo group admin;
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/9e3ae358-9855-4090-a991-d371023c66ca)

**Comment by daphnemartinsba** [comment]
Implementar :
- [ ] botão de Adicionar Agente

- [ ] Botão de adicionar grupo

- [ ] Botão de Remover Agente

- [ ] Botão de Remover Grupo

**Comment by rafaelchavesfreitas** [comment]
@patricknobre12 precisa desenhar os botões de editar e remover grupos. por favor colocar print dos botões aqui

**Comment by patricknobre12** [comment]
Atualizei lá com o print
