### ISSUE TITLE
Criar tela de edição do Evento

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2053]

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ea14a6b8-6c42-48f2-8739-13317a43f20b)

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ea14a6b8-6c42-48f2-8739-13317a43f20b)
