### ISSUE TITLE
Implementar o componente map

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2056]
- [x] criar componente placeholder para que possa ser utilizado no componente `entity-location`

- vai receber um array de entidades:
- se for entidade tipo agente mostra o ícone de agente
- se for entidade tipo espaço mostra ícone de espaço
- se for vários espaços ele vai agrupar, tem o leaflet cluster

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f59815d1-2137-4a6f-be6c-2c33bb515f28)

essa biblioteca parece ser uma boa opção
https://www.npmjs.com/package/@vue-leaflet/vue-leaflet

**Comment by cesardelucca** [comment]
Investigar pq o PIN desaparece qdo é feito um zoom no mapa
