### ISSUE TITLE
Implementar componente create-agent

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2061]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5300bebe-86e7-4f35-a1cf-bfc47449ef62)
- todas as modais de criação de entidades devem conter todos os campos obrigatórios, dinamicamente
- os campos obrigatórios podem ser obtidos nessa estrutura de dados:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/761f17fc-d1b1-4283-b5a5-bf7fe9a90b99)
- utilizar componente `<field>` para os campos
- cada modal deve fazer um new Entity passando o tipo da entidade
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/4e1b391f-2673-420e-bc2b-f2967f50802d)

## orientações para o desenvolvimento:
- o componente deve ser implementado no módulo entities
- o componente deve usar o componente `<modal>`
- o data() do componente deve conter um entity que recebe uma nova entidade do tipo agente 
```
    data() {
        return {
            entity: new Entity('agent')
        }
    }
```
- criar 2 métodos para as ações:
    - `createDraft`: para o botão "Criar Rascunho"  - define o `this.entity.status = 0`
    - `createPublic`: para o botão "Criar e Publicar" - define o `this.entity.status = 1` 
- ambos os métodos vão salvar a entidade e depois disparar 2 eventos: "created" e "createdDraft" ou "createdPublic"
- os botões criar rascunho e criar e publicar devem chamar métodos criados acima
- para a área de atuação utilizar o componente `<entity-terms>` com `editable=true`

**Comment by robedj** [comment]
Foram realizados ajustes para exibição da tela de salvar em rascunho na modal do componente.
