### ISSUE TITLE
Estilização do componente messages

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2076]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/72d93639-b112-4634-bdd5-8cebb42a0d1a)

as mensagem devem ficar por cima do conteúdo, cetralizado abaixo de main-header.

o componente está incluído no `main-header.php`

**Comment by robedj** [comment]
Vi agora, hoje eu e o pessoal do dev discutimos sobre a centralização falaríamos contigo sobre. Já tinha acabado meu horário.
