### ISSUE TITLE
Implementar os diversos tipos de campos no componente entity-field

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2078]
- [x] `checkbox` 
- [x] `CPF` (aplicar máscara)
- [x] `CNPJ` (aplicar máscara)
- [x] `brPhone` (aplicar máscara)

- [x] `time` - datepicker só com horário *
- [x] `datetime` - datepicker com horário *
- [x] `date` - substituir por datepicker *

\* utilizar o `@vuepic/vue-datepicker` que já está incluso global no projeto.

Essa issue é a MVP da #1895. Em algum momento do futuro haverá um registro de tipos de campos para possiilitar a criação de novos campos via plugin. Por enquanto, para isso, se utilizará um hook.

**Comment by rohilario** [comment]
Utilizado Maska para implementar as mascaras e vuepic/vue-datepicker para os campos date, datetime e time.
