### ISSUE TITLE
Padronizar botões de ações da entidade  

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2082]
Os botões devem ficar de acordo com os botões de ações da entidade no painel.
- [ ] Tirar prints e colar como comentário nesta issue;

**Mobile**
Edição de entidade publicada
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/a3bda7b2-f30d-497f-a856-85b98db4f35d)

Edição de entidade não publicada
![Group 1280.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/2843b22b-e7d0-4307-9ca3-f566e649137f)
---------------------------------------------------------------------------------
**Desk**
Edição de entidade publicada
![Group 1282.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ffa391dd-969a-4e94-9cbd-28ddc804ca66)

Edição de entidade não publicada
![Group 1281.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/74a98b84-ab62-4855-97f1-e1065d7a236b)

**Comment by robedj** [comment]
A permissão publish não consta no theme.php do MapasCulturais, para estilização utilizamos o modify.

**Comment by robedj** [comment]
Reduzimos  o tamanho do botão publicar e sair para ajuste do conteúdo ao botão.
Para o botão publicar ser acessado, somente quando utilizamos o  entity.currentUserPermissions?.modify
Para acessar um agente não publicado : utilizar na query do v-if "entity.currentUserPermissions?.modify && !entity.status"
