### ISSUE TITLE
Ajustes finais do componente entity action

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2090]
- [x] Tirar posição fixa no mobile. Posicionar embaixo do formulário e em cima do footer.

- [x] Confirm button nas ações de alteração de status da entidade: Excluir, arquivar e publicar.

**Comment by robedj** [comment]
Foi adicionado o confirm-button e feito os ajustes da posição dos botões na versão mobile e web.
