### ISSUE TITLE
Montar página de Edição dos Projetos

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2093]
Utilizar somente componentes que já estão prontos:

- [ ] Fazer control C e control V dos Agentes, mudar a classe e excluir os componentes que não são dos Eventos. Assim, será possível que a mesma estrutura funcione para todas as entidades depois.

**Comment by rafaelchavesfreitas** [comment]
@robedj  remover o mapa pois projetos não tem endereço/localização

**Comment by robedj** [comment]
Removido.
