### ISSUE TITLE
Implementar componente home-map

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2103]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e44fa67d-9c4a-4f78-8eca-52cb75a5d535)

**Comment by robedj** [comment]
Na tela da Home, como aplicar o mapa para multiplas entidades?

**Comment by rafaelchavesfreitas** [comment]
- fazer 3 consultas na API, uma para pegar agentes, outra para pegar espaços e outra para pegar eventos; 
- fazer uma propriedade computed que fará merge dos 3 arrays
- no template iterar em cima desse array computed colocandos os componentes `<mc-map-marker`
- para pegar os eventos, ver no inspector da busca de eventos atual como é feito. não é utilizado o endpoint `/api/event/find` mas sim o endpoint `/api/space/findByEvents/?&@from=2022-08-08&@to=2022-09-08&@select=id,name,location`

**Comment by rafaelchavesfreitas** [comment]
precisamos refatorar o mapa para resolver a questão da performance quando o mapa tem milhares de pins

**Comment by rafaelchavesfreitas** [comment]
colocar uma propriedade para o texto e só exibi-lo se informado
