### ISSUE TITLE
Refatorar componente files lists e implementar em todas entidades

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2106]
- [x] Renomear componente: entity-files-list;

- [x] O componente deve receber a entidade e o grupo de arquivos que deve listar;

- [x] Implementar modo de edição.

**Comment by Raul-vlb** [comment]
Falta exibição dos erros

**Comment by Raul-vlb** [comment]
Captar o retorno dos erros para mostrar em tela
