### ISSUE TITLE
Permitir criação de fase sem avaliação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2111]

**Comment by daphnemartinsba** [comment]
- [ ] Verificar se precisará refatorar o entity.js para enviar o object_type

- [ ] Confirmar: descrição curta é ou não obrigatória

**Comment by erleibiazzio** [comment]
- [ ] No controller Opportunity, no endipoint ```POST_index()```, foi feito uma verificação de qual thema enviou o request e no caso do Basev1 se manteve o hook que setava o método de avaliação, caso Basev2 ele cria sem avaliação. Veja imagens abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/4d9a05fa-6c2f-4ad3-b9a8-190fa8eb1d33)


- [ ]  Na Entidade Opportunity, foi alterada a permissão canUserViewEvaluation Caso seja uma verificação oriunda do thema BaseV1, tudo segue como antes, ele verifica se a pessoa tem controle sobre a avaliação e checa se ela pode ver os dados da avaliação, caso contratio seja no oriunda do BaseV2, ela verifica se tem Avaliação configurada e so depois verifica se a pessoa tem permissão para visualizar os dados de avaliação.

Caso a pessoa tenha controle sobre a oportunidade automaticamente ela tem a permissão para ver no BaseV2

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/9c21aa61-958e-4b76-98e0-cd4a6914c873)

- [ ] O Entity.js não estava enviando o objectType, então eu setei ele como mais uma propriedade das relations como mostra imagem abaixo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e982d4ae-a3a0-47b9-a561-4ae1a6383b95)

**Comment by rafaelchavesfreitas** [comment]
refatorei os 3 trechos de código. 
nos 2 primeiros um dos motivos é que não quero que tenha referência às classes dos temas. 

## Trecho 1
a criação da avaliação fiz via hook no `BaseV1\Theme`:

o controller ficou assim:
```PHP
    function POST_index($data = null)
    {
        $classes = [
            'agent' => Entities\AgentOpportunity::class,
            'event' => Entities\EventOpportunity::class,
            'space' => Entities\SpaceOpportunity::class,
            'project' => Entities\ProjectOpportunity::class,
        ];

        $this->entityClassName =  $classes[$this->data['objectType']];
        parent::POST_index($this->data);
    }
```
e o hook no tema ficou assim:
```PHP
        /**
         * Cria o método de avaliação na criação da oportunidade
         */
        $app->hook('POST(opportunity.index):before', function () use($app) {
            /** @var \MapasCulturais\Controllers\Opportunity $this */
            $data = $this->data;
            $app->hook('entity(Opportunity).insert:after', function () use ($data, $app) {
                /** @var Entities\Opportunity $this */

                $definition = $app->getRegisteredEvaluationMethodBySlug($data['evaluationMethod']);

                $emconfig = new Entities\EvaluationMethodConfiguration;

                $emconfig->opportunity = $this;

                $emconfig->type = $definition->slug;

                $emconfig->save(true);
            });
        });
```

## trecho 2
Além disso, no canUserViewEvaluation deixei o resultado como false quando não tem evaluatonMethodConfiguration, já que não haverá avaliações, faz sentido que o usuário não tenha essa permissão.
```PHP
    protected function canUserViewEvaluations($user){
        $em = $this->evaluationMethodConfiguration;

        if($em) {
            return $this->evaluationMethodConfiguration->canUser('@control');
        } else {
            return false;
        }
    }
```

## Trecho 3
fiz específico para a propriedade ownerEntity em vez de para qualquer relação que não seja o parent:

```JS
for (let prop in this.$RELATIONS) {
    const relation = this.$RELATIONS[prop];

    if (skipRelations.indexOf(prop) > -1 || !relation.isOwningSide) {
        continue;
    }

    // para a criação de oportunidades
    if(prop == 'ownerEntity' && this[prop]) {
        result[prop] = this[prop]?.id;
        result['objectType'] = this[prop]?.__objectType;
    }
}
```
