### ISSUE TITLE
Adicionar data de início e término das avaliações

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2112]
Os avaliadores devem ter permissão de avaliar somente durante o período de avaliação (da data de início à data de término da avaliação).

**Comment by rafaelchavesfreitas** [comment]
remover os setters da entidade Opportunity. Toda a manipulação na avaliação será feita diretamente no `evaluationMethodConfiguration`. Inclusive o `evaluationMethodConfiguration` é opcional e pode não existir, quebrando o setter. remover.

**Comment by rafaelchavesfreitas** [comment]
sobre remover os setters, inclusive já tem esse hook no BaseV1 para manter a compatibilidade
![image](https://user-images.githubusercontent.com/1181261/215936730-e0f29157-11cd-41f3-8fe8-98b34ce4ecad.png)

**Comment by rafaelchavesfreitas** [comment]
- [ ] validar as permissões dos avaliadores

**Comment by daphnemartinsba** [comment]
A avaliação só pode ser realizada durante o período de avaliação:
![#2112.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/04ae6300-89f2-415d-8907-9781809c14ed)![2112 parte 2.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c6393522-172b-4808-8abe-0b4453c63960)
