### ISSUE TITLE
Criar campo de nome para fase de avaliação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2114]
A criação deve ser feita na classe e no banco de dados (evaluation_method_configuration).

**Comment by erleibiazzio** [comment]
- [ ] Criado Campo evaluation_phase_name na tabela evaluation_method_configuration

- [ ] Criado campo evaluationPhaseName na entidade EvaluationMethodConfiguration

**Comment by rafaelchavesfreitas** [comment]
pare seguir o padrão de todas as entidades do Mapas, renomear a propriedade / coluna para `name`
