### ISSUE TITLE
Criar endpoint para retornar o resumo das informações da fase

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2117]
Na página da gestão da oportunidade, consta:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f686b8f0-afaa-451a-b615-7fe49bf77ec5)

# Descrições para execução

- [ ] Criar um getter na entidade EvaluationMethodConfiguration `src/protected/application/lib/MapasCulturais/Entities/EvaluationMethodConfiguration.php` pna linha 289 que devolva se a avaliação esta aberta ou fechada. Caso esteja aberta o método retorna `true` caso esteja fechada retorna `false`

Um exemplo de criação do método seria

```
  //criar método getEvaluationOpen
    public function getEvaluationOpen()
    {
        // se hoje for >= $this->evaluationFrom && hoje <= $this->evaluationTo retorna true se nao retorna false
    }
```

- [ ]  Com o método criado, no arquivo  `src/protected/application/lib/modules/OpportunityPhases/Module.php` Criar endpoint na API via hook chamado `opportunity.phase` Que ira retornar o os status das inscrições, quantidade de inscrições em na opportunity e o status a avaliação.

Para acessar o endpoint use http://localhost/api/opportunity/phase?@opportunity=ID_OPORTUNIDADE`

Obs.: ID_OPORTUNIDADE = Id da oportunidade que quer ver os dados

Exemplo do hook

```
$app->hook('API(opportunity.phase)', function() use($app) {
});
```

O endpoint ira receber o id da oportunidade pelo parametro @opportunity com esse id será possível pegar a oportunidade e aprtir da oportunidade terá acesso a tudo que precisa ser retornado no endpoint

Ver exemplo de como pegar o parametro @opportunity na imagem abaixo e pegar a oportunidade
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/6a0ead38-edc6-46b6-93a3-6dbe05f5a697)

Com a oportunidade em mãos, usar o metodo `$opportunity->simplify()` para devolver os metodos. O metodo criado na entidade EvaluationMethodConfiguration tambem deve constar no simplify.  Veja exemplo na imagem abaixo

### Simplify da Oportunidade
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/75c3b19c-18e8-41db-bfce-9604a830d860)

### Simplify da avaliação
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/c7b6877d-c88a-4e68-a3db-4f4e7dedde21)

Por fim, retornar um json com os dados Exemplo abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/40cace6a-621e-47e7-bbe1-cabab86caadb)

No navegado o resultado vai estar muito próximo ao exemplo abaixo

```
{
    "@entityType": "opportunity",
    "summary": {
        "Draft": 2213,
        "registrations": 2213
    },
   "publishedRegistrations": true,
   "evaluationOpen": null
}
```

**Comment by LimaSystem** [comment]
- [ ] Resolvido na issho 2115.

**Comment by rafaelchavesfreitas** [comment]
retornar o summary da oportunidade/fase
