### ISSUE TITLE
Criar flag para ativar fase de avaliação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2118]
É um metadado que ficará oculto. 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/91f2a10d-bc78-4a0e-8c2c-1a3f92f61e94)

## Orientações basicas
- Registrar metadado ```active_evaluation_phase```
- Fazer registro no arquivo ```src/protected/application/lib/modules/Opportunities/Module.php``` usar mtétodo 
- Usar método ```$this->registerOpportunityMetadata()``` para fazer o registro
- O metadado deve ser do tipo boleano

## Ver exemplo de como registrar o metadado
- Para ver exemplo de registro ver o arquivo ```src/protected/application/lib/modules/OpportunityPhases/Module.php``` na linha 871
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/5dab53cd-dc16-4404-b58f-b36255d79007)

**Comment by rafaelchavesfreitas** [comment]
essa flag é desnecessária
