### ISSUE TITLE
Refatorar a condicionalidade de um campo em relação a outro

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2121]
O novo funcionamento será: Não precisa marcar um campo como obrigatório para que ele seja condicional.

- [ ]  adicionar duas colunas novas (campos) na tabela de configuração de campo, para representar o campo relacionado e seus valores.

Obs: Lembrar de refatorar a verificação da obrigatoriedade!
Obs 2: db-uptade para pegar a configuração atual e aplicar na nova configuração!!! (para não quebrar o legado)

**Comment by rafaelchavesfreitas** [comment]
implementado em #2548
