### ISSUE TITLE
Criar endpoint para retornar a configuração do suporte

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2124]
# Tarefa 1
- [ ] Criar um entpoint chamado `GET_settings()` dentro do arquivo `src/protected/application/lib/modules/Support/Controller.php` próximo a linha 82

#### Atenções
- O método deve receber o id da oportunidade via GET Exemplo: `http://localhost/support/settings/1` assim o id estrará disponível no atributo `$this->data` do endpoint
Exemplo
```
$_GET_settings(){
       var_dump($this->data);
}
```
- Com id da oportunidade em mãos, usar o `$opportunity = $this->getOpportunity();` para pegar a entidade da oportunidade para só depois conseguir verificar as permissões e checagem de usuário autenticado
- O método só deve retornar os dados para o dono da oportunidade, administrados e o ambos devem estar logado. 
#### Exemplo para pegar oportunidade
para pegar oportunidade olhar arquivo `src/protected/application/lib/modules/Support/Controller.php` na linha 39

#### Exemplo para criar um enpoint Olhar na linha 36 do arquivo 
`src/protected/application/lib/modules/Support/Controller.php`
 
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/d180c5a2-da98-497f-b34e-fa448a28becf)

####  Exemplo para autorizar somente quem tem controle da oportunidade usar o endpoint 
Usar a checagem de permissão `$opportunity->checkPermission("@control");` olhar no aquivo `src/protected/application/lib/MapasCulturais/Controllers/Opportunity.php` na linha 128

####  Exemplo para autorizar somente quem esta logado
Olhar arquivo `src/protected/application/lib/modules/Support/Controller.php` na linha 88
Usar o método `$this->requireAuthentication();`

# Tarefa 2

- [ ] Criar um array `$relation_groups = []` com todos os usuários que a oportunidade tem relação na oportunidade separadas por grupo

- Para criar esse array você deve use o método `$opportunity->getAgentRelationsGrouped()`, esse método retorna um array com todos os grupos relacionados.

- Fazer um foreach no array  `$relation_groups`  Ex.: `foreach($relation_groups as $group => $relation)`

dentro do foreach se o `$group == '@support'` vc deve pegar os dados do `$relation->metadata['registrationPermissions']` para montar seu resultado

# Resultado esperado
A ideia é retornar um array com as informações das configs  de support da opportunidade Exemplo:
```
$result =  [
    'agent1' => [
        'field_1' => 'modify',
        'field_2' => 'view',
        'field_3' => 'view',
        'field_4' => 'modify',
    ],
    'agent2' => [
        'field_1' => 'modify',
        'field_2' => 'view',
        'field_3' => 'view',
        'field_4' => 'modify',
    ],
    'agent3' => [
        'field_1' => 'modify',
        'field_2' => 'view',
        'field_3' => 'view',
        'field_4' => 'modify',
    ],
];
```

**Comment by rafaelchavesfreitas** [comment]
> Foi criado um endpoint GET_settings() dentro do arquivo `src/protected/application/lib/modules/Support/Controller.php` ![image.png](https://camo.githubusercontent.com/5066dd48fd9924eb56417cf0314d12a7830a3a11545a720cfd24064bfa55f768/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3633333164353464363064656166643939323137323164632f65353033373939332d666465362d343931372d383965652d363231346262613334643333)

- [ ] o controller já possui um método para retornar a oportunidade (https://github.com/mapasculturais/mapasculturais/blob/feature/BaseV2-opp/src/protected/application/lib/modules/Support/Controller.php#L50) . fazer o mesmo padrão, retornando um 404 caso a oportunidade não seja encontrada:
```PHP
        $opportunity = $this->getOpportunity();
        if (!$opportunity) {
            $app->pass();
        }
        $opportunity->checkPermission("@control");
```

Notar que o getOpportunity espera um parâmetro `opportunityId` via url (ex: `/support/settings/opportunityId:33/`). 

- [ ] refatorar o método `getOpportunity` para aceitar o parâmetro por GET tb, substituindo o `urlData['opportunityId']` por `data['opportunityId']`
