### ISSUE TITLE
[QA] Relatórios: Gráficos não são gerados

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2125]
Quando o filtro dos gráficos está em "Mostrar todas" ocorre um erro no console ao clicar no botão Gerar Gráfico:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2b8d7ae2-f55c-45b4-ab8c-3ba9669614f4)

Quando o filtro está em "somente aprovadas" o gráfico consta como gerado, mas não aparece na interface e, também, da erro no console:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/951fba32-d6d9-4fc7-b091-dc712f908c8d) 

- [ ] O filtro que agora se chama "somente aprovadas" deve se chamar "somente enviadas". Como especificado na issue #1862

**Comment by rafaelchavesfreitas** [comment]
já foi resolvido
