### ISSUE TITLE
Criar esqueleto das páginas de Busca das Entidades

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2134]
- [ ] página de busca Agente (`agents.php`)
- [ ] página de busca Espaço (`spaces.php`)
- [ ] página de busca Evento  (`events.php`)
- [ ] página de busca Projeto (`projects.php`)
- [ ] página de busca Oportunidade  (`opportunities.php`)

Implementar no Módulo Search (#2133)

Todas as páginas devem conter o header e as abas quando tiver (agentes, espaços e eventos)

- para as abas utilizar o componente `<tabs>` e `<tab>`

**Comment by rafaelchavesfreitas** [comment]
colocar os links no main-header

**Comment by robedj** [comment]
Sobre o uso da <tabs></tabs> como será feito nas paginas de busca?
Pois a forma que encontramos iria quebrar a estilização no mobile.
