### ISSUE TITLE
Implementar componente do filtro de Oportunidades (search-opportunity-filter)

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2136]
nome do componente: search-opportunity-filter

Colocar no slot `header` do componente entities da listagem

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/fdf318fb-902b-4def-8a8f-661bcd990a21)

**Comment by Raul-vlb** [comment]
Falta implementar seleção dos tipos e áreas de interesse
