### ISSUE TITLE
Implementar componente do filtro de Agentes (search-agent-filter)

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2137]
nome do componente: search-agent-filter

Colocar no slot `header` do componente entities da listagem

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/dac78acc-6d69-4d48-902e-7fd4706d48b8)

* Não possui data inicial nem final
* No agente é "Área de Atuação", e não "Área de Interesse"

**Comment by Raul-vlb** [comment]
Falta implementar seleção do tipo do agente e áreaa de atuação

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/485104dc-2ccc-4146-bc93-181d7db59519)
