### ISSUE TITLE
Implementar componente do filtro de Evento (search-event-filter)

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2138]
nome do componente: search-event-filter

Colocar no slot `header` do componente entities da listagem

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/fee51b57-9896-4478-8081-c59c54f5a221)

*Não implementar dos campos de data inicial e final pq a seleção de data está na imagem abaixo.

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/a20825ca-bef8-4976-a80c-211fa21d93b7)

**Comment by rafaelchavesfreitas** [comment]
@robedj precisa finalizar a estilização. ver no figma a versão atualizada.
