### ISSUE TITLE
Implementar componente do filtro do Espaço (search-space-filter)

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2139]
nome do componente: `search-space-filter`

Colocar no slot `header` do componente `entities` da listagem

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/99ed1663-4e7b-4498-a60c-29927381ab74)

*Não tem data inicial e final
* Não é "Liguagem". É "Área de atuação"

**Comment by Raul-vlb** [comment]
Falta implementar seleção dos tipos e linguagens culturais
