### ISSUE TITLE
Implementar componente do filtro do Projeto (search-project-filter)

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2140]
nome do componente: search-project-filter

Colocar no slot `header` do componente entities da listagem

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/d72e66f6-f69d-4f6a-b830-50902186def4)
* Não colocar data inicial e final

**Comment by Raul-vlb** [comment]
Falta implementar seleção dos tipos
