### ISSUE TITLE
Implementar listagem de Espaço da página de Busca

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2145]
Utilizar o componente `entities`, colocar colocar o campo Pesquisar e o componente de filtro `search-space-filter` no slot `header`.

Carregar 20 oportunidade por página (@limit=20)

Atenção! As abas "Agenda" e "Mapa" (visualizar como) não fazem parte dessa issue.

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/118863f6-b34e-4b1b-a7de-386a5f19d37c)

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a99f328b-749c-4385-8be4-472086e92ab7)
