### ISSUE TITLE
Implementar listagem de Projeto da página de busca

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2146]
Utilizar o componente `entities`, colocar colocar o campo Pesquisar e o componente de filtro `search-project-filter` no slot `header`.

Carregar 20 oportunidade por página (@limit=20)

Atenção! As abas "Agenda" e "Mapa" (visualizar como) não fazem parte dessa issue.

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/4b72baa6-4e10-412b-abcd-7308f9099cdc)

**Comment by rafaelchavesfreitas** [comment]
duas questões:
1. a paginação não foi observada (@limit=20)
2. a consulta tem que pedir (@select) todos os campos que serão utilizados na listagem, acho que pode colocar um prop `select` com um valor padrão, pois para cada entidade terão alguns campos específicos.

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ced1bb01-3334-476e-9ba6-5f18f6305ab8)
