### ISSUE TITLE
Implementar mapa da busca de Agente

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2147]
A listagem de eventos da esquerda não faz parte dessa issue.
![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/4840fb35-d7ea-4946-a944-2c512a32ea79)

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/3331e153-136e-4f4d-80e8-022a1a0f5f49)

Atenção! Não implementar os botões de Eventos e Espaços.
![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/2aa118ff-8e8f-440c-a2d1-ecb8e8baa498)

**Comment by rafaelchavesfreitas** [comment]
@robedj chama o nome do arquivo de visão de `agents.php`
