### ISSUE TITLE
Erro na permissão dos avaliadores que quebra o carregamento dos Selos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2153]
Erro acontece ao entrar na edição de uma entidade, e a estrutura de selos não é carregada pois o Js quebra na implementação da permissão dos avaliadores

**Comment by daphnemartinsba** [comment]
![selopermissao.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/120f7dd9-31a5-43f5-9415-5249ee404810)
