### ISSUE TITLE
criar página de visualizaçao de agente coletivo

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2156]

**Comment by robedj** [comment]
O breadcramb não se sobrepõe a imagem de capa, isso é o correto?
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/4ac9bdca-4cca-4959-9dd9-bb6d1c1651b4)

**Comment by robedj** [comment]
Os ajustes segundo o figma no estilo foram realizados e os componentes testados para exibição se não preenchidos
