### ISSUE TITLE
Aplicar o componente de abas em todas as singles

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2165]
As singles são as páginas de visualização de 
- [ ] Agente Individual
- [ ] Agente Coletivo
- [ ] Espaços (remover a aba agenda)
- [ ] Projetos
- [ ] Eventos

Fazer **SOMENTE** a aba Informações das singles. **NÃO FAZER** a aba Agenda.
Conforme a imagem abaixo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b93288fb-a063-4667-a9b4-e25b6cab85f5)
O conteúdo da aba informações é tudo que está abaixo da linha. Conforme o **exemplo** do Agente Individual:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/77dcd2fd-74f0-4da8-9c31-8209b944f44f)

**Comment by rafaelchavesfreitas** [comment]
remover as abas Agenda de todas as singles
