### ISSUE TITLE
Criar componente entity-list 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2166]
Implementar no módulo Components.
Por enquanto, componente deve ser aplicado **somente nas páginas de visualização** dos Agentes Individuais, Agentes Coletivos, Espaços, Projetos e Eventos. 
Segue a regra de exibição nas entidades:
entity-lists
- Exibição nos Agentes:
    - Agentes assinados pelo agente (parent)
    - Espaços assinados pelo agente (owner)
    - Projetos assinados pelo agente (owner)
    - Oportunidades do agente (owner ou ownerEntity)

- Exibição nos Espaços:
    - Subespaços (parent)
    - Oportunidades (ownerEntity)

- Exibição nos Projetos: 
    - Subprojetos (parent)
    - Oportunidades (ownerEntity);

- Exibição nos Eventos:
    - Oportunidades (ownerEntity)

Em todos os casos **só exibir o label quando tiver algo para ser exibido**.
o componente individualmente:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/692882d1-d0ec-4fed-97f2-f7de0ee87a9c)

O componente fica na barra lateral direita da página de visualização, conforme o **exemplo** do Agente Individual e Coletivo. 
Segue a imagem dos componentes nos Agentes:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2e1bfce0-2a56-46b1-9a4f-87de4e373660)

Obs: Visualizar o Figma.

**Comment by robedj** [comment]
Faltam só os ajustes pra vincular a oportunidade e exibilas nas propriedades das entidades.

**Comment by rafaelchavesfreitas** [comment]
os labels não devem aparecer se não há entidades para serem listadas, como neste exemplo de um projeto que não tem subprojetos nem oportunidades:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/2dd3ceac-6ad2-4ecc-93f9-3689ce273807)

**Comment by robedj** [comment]
Foram ajustadas as exibições das propriedaes nas singles do agente coletivo, individual, projeto, espaço e evento

**Comment by rafaelchavesfreitas** [comment]
@robedj 
o segundo e terceiro checkboxes 
> não fazer a consulta se não houver ids na propriedade informada, se não quebra e fica assim:
e
> os labels não devem aparecer se não há entidades para serem listadas, como neste exemplo de um projeto que não tem subprojetos nem oportunidades:

não foram feitos
