### ISSUE TITLE
Implementar modo de visualização do componente entity-admins. Aplicá-lo em todas as entidades. 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2167]
**Deve ser aplicado em todas as entidades.**
Na barra lateral direita, segue a imagem do componente no modo de visualização da entidade:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/19049e4e-4863-4e6b-a54f-e64791cb2921)

Colocar propriedade label com valor padrão "Administrado por". Ao invés, de como consta na imagem acima, "Este agente é administrado por".
Consultar o Figma.

**Comment by robedj** [comment]
Ajustei o css para o avatar do componente.
