### ISSUE TITLE
Criar e utilizar o componente agent-related-entities na página de visualização dos Agentes (Individuais e Coletivos) 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2168]
Implementar no módulo Entities.
Segue a imagem do componente, ele fica localizado no canto inferior da barra lateral direita dos Agentes:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6d54c12b-f725-4554-b6c9-7416b122c646)

**Comment by rafaelchavesfreitas** [comment]
feito
