### ISSUE TITLE
Criar componente de lista de tags

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2170]
Utilizar no modo de visualização do componente entity-terms.  
Será aplicado, também, no modo de visualização do recurso de acessibilidade, como na imagem abaixo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d13fae28-4850-4c55-8149-320b8892a152)

**Comment by rafaelchavesfreitas** [comment]
- chamar de `mc-tag-list`
- recebe uma lista de tags (Array de strings)
- colocar no módulo Components
