### ISSUE TITLE
Criar componente para seleção múltipla baseado no funcionamento do entity-terms

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2171]
- [x] Refatorar componente entity-terms para utilizar esse componente. 
E, nos campos de seleção múltipla da busca:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cf552022-341e-4044-b149-a89b9cb3e5b6)

- [ ] Na página de busca, em Espaços e Agentes é área de atuação, em Eventos é linguagem, em Projetos e Oportunidades é Tipo.

**Comment by rafaelchavesfreitas** [comment]
levar para este componente a lógica de sublinhar a lista de resultados da busca
