### ISSUE TITLE
Implementar componente create-occurrence para criar ocorrências no Evento

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2173]
Criar o botão Adicionar nova ocorrência, o qual abrirá a seguinte modal das imagens abaixo.
Estudar comportamento da modal do BaseV1.
Exemplo da modal, versão desktop:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/94d5d2a1-3e97-44ba-8946-187a12ab963c)

Sequências das modais mobile (na ordem de execução após o clique):
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cd72881d-ec9d-483d-b25e-97a66da65769)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/03139bef-b6b9-45fd-93ca-cba2293789c4)

 ![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/74761460-9b3f-4682-9e05-192598e4bb61)
 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/db4baa86-83cd-4a2e-9e57-d778e8dfb920)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f5773de4-88a8-4279-b8c0-b3aa664698e2)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/88f4dd4c-caab-4837-b442-a3c1c673832e)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a7a25721-c619-4c26-9e1b-65cbffc9052f)

**Comment by Raul-vlb** [comment]
Falta para finalizar:
 - [ ] Finalizar a criação de uma nova ocorrência
 - [ ] Métodos para edição e exclusão das ocorrências
