### ISSUE TITLE
Implementar componente que lista ocorrências do Evento

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2174]
Incluir o componente create-ocurrence (issue #2173)
No modo de edição:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5f142c69-bb89-4358-82cc-e12310701a3d)

No modo de visualização:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fe277d1d-f493-42dd-8db6-b51b8370c8e0)

**Comment by Raul-vlb** [comment]
Falta para finalizar:
 - [ ] Finalizar o componente <create-occurrrence> (#2173)
 - [ ] Puxar e listar ocorrências do evento 
 - [ ] Métodos para edição e exclusão das ocorrências
