### ISSUE TITLE
Implementar panel--card-registration

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2177]
É o card de inscrição do painel. Dependendo de onde o card for usado, será na versão resumida ou não. Nas descrições recentes do painel, por exemplo, é a versão resumida.

- O componente deve ter uma propriedade que indicará se é a versão resumida ou não. small = true.

- Utilizar componente `panel--entity-card`.

Confirmar no figma antes de implementar.
Versão resumida:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d6dd9f0c-a2ba-4496-b34b-ca68103b4523)

Versão:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9c858bc9-f41b-4584-a80c-a375b366e0e2)

**Comment by rafaelchavesfreitas** [comment]
acho que foi implementado no componente `registration-card`
