### ISSUE TITLE
Implementar tela do painel: Minhas Inscrições

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2183]
**Não usar o componente panel--entity-tabs**, porque ele foi pensado para as outras entidades que tem status como rascunho, publicado e afins. 
As Inscrições tem status diferentes como enviadas e não enviadas.
**Utilizar o componente tabs em conjunto com o componente entities**

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/58e0dbbc-d26f-4421-9534-a23d2facc77b)

**Comment by daphnemartinsba** [comment]
Falta o back-end: problema na API Query

**Comment by rafaelchavesfreitas** [comment]
- [ ] a consulta deve pegar pelo `user=EQ(@me)` e não pelo `@permissions=@control`

**Comment by cesardelucca** [comment]
[ ] Inverter a ordem das abas Enviadas e Não enviadas. Ficará assim: Não enviadas e Enviadas
