### ISSUE TITLE
Implementar componente de edição entity-parent 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2187]
Ele apresentará as entidades na qual a entidade visualizada foi vinculada. Por exemplo, no projeto, na barra lateral direita:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fccbdd1c-59f2-4366-b555-87974a0c474f)

**Comment by daphnemartinsba** [comment]
Definir layout

**Comment by daphnemartinsba** [comment]
Duplicar o entity-owner. O componente deve receber um tipo.

**Comment by robedj** [comment]
Não está salvando o parent. O problema parece estar no Entity.js
