### ISSUE TITLE
Implementar componente create-event

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2204]
- [x] Utilizar como base a criação do Agente, create agent #2061
Após realizar, retornar para a daily e para o sprint backlog
- [x] Utilizar o componente listagem de ocorrências e o de criação de ocorrências

Modal de criação do evento:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a2f0d1f0-a1c3-4739-a895-64aed7d02c26)
Ao implementar a modal de criação de evento, após o clique em criar e publicar, deve ocorrer o direcionamento para a opção de criar ocorrência ou de listar ocorrência:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/03fac924-78c5-4af5-adc8-be27b56f3cbb)

**Comment by robedj** [comment]
Falta inserir o componente de ocorrencias e a opção de seguir editando

**Comment by rafaelchavesfreitas** [comment]
após a criação do evento a modal está quebrando no componenge <entity-occurrence-list>
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/df3d2028-d710-4915-9a21-7eeb027756da)
