### ISSUE TITLE
Implementar componente panel--available-evaluations

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2210]
O filtro será pela permissão do usuário de avaliar oportunidades (usando `@permissions = evaluate` [**confirmar o nome da permissão**]).
Ordenar por ordem alfabética.
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d58cac95-2ce6-47f0-87d6-c68cf4483f16)

**Comment by rafaelchavesfreitas** [comment]
foi feita em outra issue
