### ISSUE TITLE
estilização do menu do usuário

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2213]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/4e086a46-dab4-437d-b3c5-854954c0a764)

deve ser assim (NESTE MOMENTO SEM OS BOTÕES DE ADICIONAR):
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/30f9f272-8665-4399-bd95-b60b1dce57b2)

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/0359cf4b-366c-46a2-b55c-d743d830fa88)
