### ISSUE TITLE
Implementar tela do painel: Gestão do usuário

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2223]

**Comment by daphnemartinsba** [comment]
Componentes com classes alteradas por essa issue:

- [ ] user-management--ownership-tabs

- [ ] panel--entity-actions

- [ ] tabs-component

**Comment by daphnemartinsba** [comment]
Obs:
Não foi realizada a aba "concedidos"
Nas propriedades do usuário não foi realizada a aba "atividades"

**Comment by robedj** [comment]
Coloquei em review,
Itens: Qual a cor das inscrições?
Aba Concedidos inexiste.
