### ISSUE TITLE
Implementar tela do painel: Conta e Privacidade

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2225]
Utilizar a tela da gestão de usuário como base da tela Conta e Privacidade:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/64db8f50-5947-4ea1-a6f7-81284a753c8e)
Ao desenhar a tela se atentar a:

-  Tirar o botão de adicionar a função

- Em vez de excluir o usuário vai ser excluir conta: Ver funcionamento atual do mapa, no base V1 porque a exclusão de conta permite transferir entidades a uma outra conta

- Colocar data e ip de aceite dos termos de uso e política de privacidade

**Comment by patricknobre12** [comment]
Link do frame: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2327%3A60879&t=7Bxw8vbHFeT3j8fj-1

**Comment by robedj** [comment]
Coloquei como W.I.P o commit referente a essa issue pois não ta finalizado.
