### ISSUE TITLE
[QA Redesign] Edit do Agente Individual: Alterações não são salvas

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2235]
Mesmo com os campos obrigatórios do Agente preenchidos, a saber, o nome de exibição, descrição curta e área de atuação. 
Ao clicar em salvar, a tela apresenta uma mensagem de erro e as informações preenchidas não são salvas:

![editagentensalva.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f191e12a-0f9c-47a0-8ae8-da0b6016f9d9)

**Obs:** Isso só ocorre com o Agente principal do cadastro, com subagentes o salvamento acontece normal

**Comment by robedj** [comment]
O botão concluir e sair, retorna a outra página que não a editada [Na tela de edição]

**Comment by robedj** [comment]
QA: Caso o usuario esteja na single do agente 1, acesse a edição do Agente 2, ao concluir e salvar a edição não retorna ao painel, retorna pro agente 1.
