### ISSUE TITLE
[QA Redesign] Edit do Agente Individual: Área de Atuação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2236]
- [x]  Alterar Área de Interesse para Área de Atuação:

O modo de edição do agente individual consta como área de interesse: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/94e44c46-89b6-4aca-acaf-40f167a10609)

**O correto é que conste como Área de Atuação**:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8a132c6b-f620-4f2f-8f18-5375d2118d60)

**OBS:** como o exemplo foi de uma single, o botão adicionar nova não aparece segunda imagem na imagem, mas no edit do Agente, deve constar o botão Adicionar nova + a alteração do label para Áreas de atuação. 

-  Funcionamentos inadequados do componente:

- [x] Ao adicionar uma nova área de atuação, o clique no botão confirmar não faz nada

- [x]  A área de Atuação é Adicionada mesmo sem clicar em confirmar

- [x]  Ao clicar no x de uma das áreas de atuação adicionadas, as duas são excluídas

![áreadeinteresse.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/be21a576-e78a-4a9c-ae21-aaaca7d79b70)

**Comment by Raul-vlb** [comment]
Sobre o 2º e 3º item
>2º - Ao adicionar uma nova área de atuação, o clique no botão confirmar não faz nada
>3°- A área de Atuação é Adicionada mesmo sem clicar em confirmar

No modo que está implementado os componentes mc-multiselect e mc-tag-list, basta selecionar o valor que ele será alterado diretamente em ambos. Assim o botão 'confirmar' serve apenas para fechar o popover (corrigido).

É possível alterar esse comportamento, mas será preciso refatorar o componente mc-multiselect (novamente).

**Comment by Raul-vlb** [comment]
Botão Confirmar será agora o botão Concluir.
Mantém o comportamento de adicionar as áreas ao seleciona-las
