### ISSUE TITLE
[Redesign] Telas do Cadastro Único no Base V2 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2248]
Telas dos Agentes: Definir local dos campos do Cadastro Único e a Carteira do Cadastro Único da Cultura (Cartão de Visita)

**Comment by patricknobre12** [comment]
As opções e exemplos podem ser vista no seguinte link:

https://www.figma.com/file/Y6WvtPOZYrtdS7xYx00hYu/Redesign---Mapas-Culturais?node-id=7214%3A38606
