### ISSUE TITLE
Implementação da modal de criação de oportunidade

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2249]
- Se basear nas outras modais de criação, por exemplo a de Agente (modulo `Entities`, componete `create-agent`). **Incluindo botões de "criar em rascunho" e "criar e publicar", tal qual o print abaixo**:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7ab03c07-e3e8-4645-928d-4d896495bdfc)

Primeira tela da modal de criação rápida de oportunidade:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/86340c00-0ad8-4bac-b5c2-9c3a40b1a91d)

Segunda tela da modal de criação rápida de oportunidade (a sequência da primeira):
- Já existe componente pronto para o popover de busca e seleção da entidade: `select-entity`

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9c6014c2-b3a3-4d4d-b28a-cd2c7f36fcc6)

Terceira tela da modal de criação rápida de oportunidade (a sequência da segunda):
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7efa12ff-9e99-48c0-92d8-e94462c7d72f)

Quarta tela da modal de criação rápida de oportunidade (a sequência da terceira)
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/db9ddb1e-0ec4-4640-9a26-51b7be2b6b2f)

Obs: 

- A entidade selecionada no `select-entity` deve ser utilizada para definir a propriedade `ownerEntity` da `entity` (a entidade oportunidade).

**Comment by rafaelchavesfreitas** [comment]
essa modal SEMPRE cria as oportunidades como rascunho.
- [ ] remover do script.js opções de criar como rascunho / publico
