### ISSUE TITLE
Renomear o componente <entity-parent> para <entity-parent-edit>

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2267]
1 - Esse componente será apenas para a edição do parent da entidade. 2 - A listagem do parent deve acontecer no header da entidade <entity-header>

- [x] Esse é o componente (o nome supraespaço ainda não foi definido por isso está com os asteriscos):

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/525db1d5-b502-47e0-b1d4-119d928ccc06)

- [x] No caso da listagem, não precisa ser um componente. Pode ser adicionado direto no entity-header. Aqui é a listagem, esse **"Espaço integrante de:"**

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/17724fcb-423e-4c9c-9739-78813743bdc1)

**Comment by robedj** [comment]
Segundo item do checkbox ok.

**Comment by robedj** [comment]
O botão não tem um nome definido ainda, o label que consta é "Adicionar SupraEspaço"
