### ISSUE TITLE
aba de notificações no dashboard do painel

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2271]
- [x] adicionar aba via hook a partir do módulo Notifications
- [x] implementar listagem utilizando o componente `<entities>` 
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/a824fe6e-cab0-4005-bdb1-63248a0ed917)

**Comment by rafaelchavesfreitas** [comment]
- [ ] quando a notificação tiver o `request`, exibir o avatar do profile do usuário que iniciou a ação `notification.request.requestUser.profile.files.avatar` e houver
- [ ] revisar botões das notificações de acordo com a seguinte regra:
  - se a notificação não tiver a propriedade `request`, só deve ter o botão `[ok]` que chama o método `delete()` da notiicação.
  - se a notificação tiver o `request` e o `notification.request.requestUser.id` for IGUAL ao `$MAPAS.userId` (ou seja, quem iniciou a ação é o usuário autenticado) colocar os botões `[cancelar]` que chama o `reject` e o botão `[ok]` que chama o `delete()`
  - se a notificação tiver o `request` e o `notification.request.requestUser.id` for DIFERENTE do `$MAPAS.userId` (ou seja, quem iniciou a ação NÃO É o usuário autenticado) colocar os botões `[rejeitar]` que chama o `reject` e o botão `[aprovar]` que chama o `approve`

**Comment by rohilario** [comment]
Adequado conforme descrito, contudo a query de retorno do template é diferente, logo nao consegui "testar".
