### ISSUE TITLE
Verificação das Telas de Busca do Redesign

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2274]
- [x] Verificar se os textos explicativos condizem com a entidade da tela:
![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/28dc8717-a745-42c5-bd33-32f76002e46f)
- [x] Verificar se os filtros da busca condizem com a entidade da tela, por exemplo, se o filtro do tipo do Evento possui as opções que realmente condizem com o Evento. Verificar **todas as entidades**

- [ ] Verificar componente dos cards: se todas as informações presentes devem realmente aparecer e se existem informações que deveriam aparecer mas não aparecem

- [x] Se atentar ao thumbnail e ao footer, para identificar se da lista para o mapas a tela permanece como deveria.

- [x] Verificar se os checkbox e botoes ou abas estão de acordo com o design planejado

**Comment by patricknobre12** [comment]
Segue link com registro de inconsistências encontradas: https://docs.google.com/document/d/1t9iBhe3cNoDbRXQtzCiRlnDPjhywmh_OiZX5mE5mOyw/edit?usp=sharing

Obs: por equanto não consegui editar agentes nem inserie ocorrências para verificar dados dos cards da lista
