### ISSUE TITLE
Criar componente para exclusão de conta da tela de Conta e Privacidade

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2276]
- [x] Fica no módulo de gestão de usuário.

- [x] Utilizar o componente select entity para selecionar entidade. 

- [x] Criar uma nova página de exclusão de usuário (não usar modal!)

- [x] Criar rota da página de exclusão de usuário.

![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/f0677ab8-271c-4384-8212-6e451e54b81a)

**Comment by robedj** [comment]
Nome do componente: user-management--delete-account
pode-se utilizar uma modal.

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/8c437a25-b58c-46ca-a8db-5e2122b0f184)

**Comment by rohilario** [comment]
Verificar como selecionar o usuário

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/caeaa3f9-7160-4adc-a7de-eb9a5a7d3d78)

**Comment by rafaelchavesfreitas** [comment]
o botão excluir na página "Conta e Privacidade" não está funcionando.

**Comment by rafaelchavesfreitas** [comment]
#2328
