### ISSUE TITLE
implementar página single dos selos

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2284]
- a rota já existe no controller do módulo seal
- [x] criar arquivo na pasta do módulo `Seals/views/seal/single.php` baseado na página de outra entidade, removendo tudo o que não fizer sentido para os selos, mas mantendo o que faz, como por exemplo: avatar, imagem de header, administradores, owner, links, downloads

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/0855d33e-b3c4-4cc6-bfda-9683f9c32266)

**Comment by rafaelchavesfreitas** [comment]
- [ ] remover botão "Reivindicar Propriedade"

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/bc525df0-9371-49b2-87ce-4b6a53f834b2)
removido botao de Reivindicar Propriedade
