### ISSUE TITLE
implementar página de edição de selos

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2285]
a rota já existe no controller do módulo seal
- [x] criar arquivo na pasta do módulo Seals/views/seal/edit.php baseado na página de outra entidade, removendo tudo o que não fizer sentido para os selos, mas mantendo o que faz, como por exemplo: avatar, imagem de header, administradores, owner, links, downloads

**Comment by rafaelchavesfreitas** [comment]
refatorar campo do texto do certificado utilizando o componente `<entity-field>`. será um textarea simples.

**Comment by rafaelchavesfreitas** [comment]
remover histórico de revisões

**Comment by rohilario** [comment]
Ajustado histórico de revisao
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/c09abc94-0ea3-4faf-a133-1f518f165438)

**Comment by rohilario** [comment]
Ajustado campo do selo para um textarea
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/e9f01a5b-ba47-43a3-ac9e-8ed583604d2b)
