### ISSUE TITLE
implementar página de visualização do certificado (seal-relation)

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2286]
a rota já existe no controller do módulo seal
o arquivo deve ficar na pasta do módulo Seals/views/seal/sealrelation.php

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/f206fe5e-f8be-4cf3-b8b0-4c014b2c6310)

**Comment by rohilario** [comment]
No bloqueio de campos, ao adicionar os campos no array e envio, como indicado no v1 (seal.name ou agente.shortdescription) e salvar, o mesmo nao permanece no array quando a pagina é recarregada. Verificar por onde retornam estas informacoes, afim de deixar o checkbox marcado no carregamento da página.

**Comment by rafaelchavesfreitas** [comment]
substituir o texto hardcoded pelo texto que vem na propriedade `certificateText` do `requestedEntity`

**Comment by rohilario** [comment]
Ajustado

**Comment by rafaelchavesfreitas** [comment]
- [ ] remover os botões de compartilhamento e de impressão

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/4f3f42a4-cbfe-4f2c-884d-4f2acfb5c202)
Comentado os botoes de impressao e compartilhamento, pois os componentes/funcao para isso já existe e serao implementados futuramente.
