### ISSUE TITLE
substituir o campo documento pelos campos CNPJ e CPF

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2288]
no agente individual (edit-1 e single-1) colocar os 2 campos 
- CPF
- CNPJ (MEI)

no agente coletivo (edit-2 e single-2) colocar o campo CNPJ

**Comment by robedj** [comment]
o @patricknobre12 adicionará o campo no figma com o estilo, em sequencia farei a adição do campo CNPJ no agente coletivo.

**Comment by robedj** [comment]
o @patricknobre12 adicionou o campo CNPJ - MEI no figma com o estilo, e fiz a adição do campo CNPJ no agente coletivo, caso exista.

**Comment by rafaelchavesfreitas** [comment]
a implementação está incorreta: foi colocado o CNPJ (MEI) no edit-2 (agente coletivo) e não no edit-1

reforçando a descrição da issue:
- o agente individual deve ter 2 campos: **CPF** e **CNPJ (MEI)**
- o agente coletivo só deve ter o campo **CNPJ**
