### ISSUE TITLE
implementar máscaras para os diversos tipos de campos no componente entity-field

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2292]

**Comment by rohilario** [comment]
Codigo em nova branch pois o entity field é utilizado em todo o mapas, poderia quebrar algo.
Branch: feature/BaseV2-entity-field-mask

**Comment by rafaelchavesfreitas** [comment]
implementar utilizando a lib [Maska](https://beholdr.github.io/maska/#/)

**Comment by rohilario** [comment]
Utilizado Maska para implementar as mascaras

**Comment by rohilario** [comment]
Utilizado Maska para implementar as mascaras

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/3553e928-d4f6-4867-8071-2d560626b085)
