### ISSUE TITLE
Implementar tela do painel: Meus apps

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2299]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/efd78dd7-c51b-423a-976b-7569405a1261)

fazer no branch `feature/BaseV2-apps`

**Comment by rafaelchavesfreitas** [comment]
imlementar utilizando o <panel--entity-tabs> passando um template customizado para o slot

**Comment by rafaelchavesfreitas** [comment]
enviar mensagem avisando o usuário de que a chave foi copiada para a área de transferência

```
const messages = useMessages();
messages.success('mensagem');
```

**Comment by robedj** [comment]
Ajuste feito.

**Comment by robedj** [comment]
@patricknobre12 atualizou a tela
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/c5b3c463-21db-4073-bcfe-c7ff7195f30b)

**Comment by rafaelchavesfreitas** [comment]
- [ ] o botão de copiar chave pública está copiando a chave privada
- [ ] os caracteres das chaves não podem ser UPPERCASE, pq as chaves são case sensitive, ou seja, M é diferente de m, mas não dá para ver.

**Comment by robedj** [comment]
Ajustes realizados.
