### ISSUE TITLE
Criar flag que definirá se a opportunity possui ou não coleta de dados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2301]
usada para fases que tem somente avaliação, exemplo: avaliação técnica feita após uma avaliação documental sem que tenha coleta de dados entre elas

## Orientação base
- [ ]  Registrar metadado ```is_collect_data_phase``` dentro do Module.php dentro do módulo Opportunities 
```src/protected/application/lib/modules/Opportunities/Module.php```

O metadado deve ser do tipo Boleano e deve ser registrado na entidade Opportunity

Usar método ```$this->registerOpportunityMetadata()```  para fazer o registro

## Ver exemplo de como registrar o metadado 
```src/protected/application/lib/modules/OpportunityPhases/Module.php``` Na linha 871 
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/631b5155-47ac-42a9-b7fe-d788117ddea0)

**Comment by erleibiazzio** [comment]
- [ ]  Registrar metadado is_collect_data_phase dentro do Module.php dentro do módulo Opportunities 
```src/protected/application/lib/modules/Opportunities/Module.php```

O metadado deve ser do tipo Boleano e deve ser registrado na entidado Opportunity

Usar método ```$this->registerOpportunityMetadata()``` 

Ver exemplo de como registrar no arquivo ```src/protected/application/lib/modules/OpportunityPhases/Module.php``` Na linha 871 
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/631b5155-47ac-42a9-b7fe-d788117ddea0)
