### ISSUE TITLE
Criar componente create-apps para criação de aplicativos

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2304]

**Comment by rafaelchavesfreitas** [comment]
- [ ] melhorar o texto da modal. "Crie um aplicativo com informações básicas
e de forma rápida" não faz muito sentido para uma entidade que só tem u campo.
- [ ] o botão [OK] está levando para uma página que não existe. a ideia é só fechar a modal.

**Comment by robedj** [comment]
Foi retirado o label da modal o botao criar aplicativo substituido por criar, pois estava como titulo: Criar aplicativo.
