### ISSUE TITLE
Criar tela de aceite de termos: quando o usuário já possui login

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2307]
**Implementar no módulo LGPD**

https://www.figma.com/file/Y6WvtPOZYrtdS7xYx00hYu/Redesign---Mapas-Culturais?node-id=2200%3A12942&t=pHHh42i3Cl0LHnnd-0

![Página de termos e condições.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7a8b2174-cd93-4c97-8e44-6ff54e8b8591)

**Comment by rafaelchavesfreitas** [comment]
- [ ] colocar tela na página de entregas finais com UX Writing
