### ISSUE TITLE
Transformar o caixa de "configurações da conta do usuário" em componente

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2309]
Transformar essa caixinha chamada de "configuração da conta do usuário" em um componente, não esquecer de usar nas duas páginas, a saber, gestão de usuários, user-detail.php,  e conta e privacidade, my-account.php.

- [x] Colocar os templateHooks no template deste componente. 

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/0acd50c2-8f6d-4129-b73f-43c00aa798b8)

**Comment by robedj** [comment]
O Componente foi criado, segunda vejo com a equipe como colocar os template hooks
