### ISSUE TITLE
nas modais de criação, incluir a entidade criada na listagem de entidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2310]
nas páginas que tem listagem, após criar a entidade pela modal de criação, a entidade deve ser incluída na listagem do status correto, por exemplo, se um agente foi criado como rascunho, deve aparece automaticamente na aba rascunho e da mesma forma aparecer na aba de publicados se for criado como público.

implementar em todas as modais:
- [x] Agentes
- [x] Espaços
- [x] Eventos
- [x] Projetos
- [x] Apps

o código para fazer isso é mais ou menos esse, precisa testar:
```JS
const lists = useEntitiesLists(); // obtem o storage de listas de entidades
const list = lists.fetch('agent:publish'); // obtém a lista de agentes publicados
if( list ) {
    list.push(this.entity);  // adiciona a entidade na lista
}
```

**Comment by robedj** [comment]
Foi criado um método : addEntity(stat), quando o método sabe(modal) é chamado
-> stat = this.entity.status;
                this.addEntity(stat);
verifica o status e enfileira.
