### ISSUE TITLE
corrigir estilo da modal de notificações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2312]
ela está assim hoje:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/fc4d0eca-917f-413a-8fe3-a8e18b5d980a)

deve ser assim:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/84135e06-b1f6-48f4-a03d-d2da899acea8)

lembrando que NÃO tem botão de "marcar todas como lida" nem existe card com a cor vermelha, mas no restante a modal deve ser idêntica ao do segundo print

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/315c6fd9-15c9-4943-b366-3249d51fb351)

**Comment by rafaelchavesfreitas** [comment]
- [ ] a modal continua diferente da versã do figma
