### ISSUE TITLE
corrigir ordenação das listagens do painel

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2314]
![Peek 2022-12-30 20-00.gif](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/fdd0a6cd-c2a6-4126-8937-5627dd883a10)

o `@order` não está sendo definido na query.

**Comment by daphnemartinsba** [comment]
Se espelhar nos filtros da página de busca, tem métodos lá que altera a query para definir a ordem que você quer que busque.

**Comment by robedj** [comment]
- [ ] Observação do UX Desing: o campo de ordenação deve ter uma label indicando, algo como “Ordenar por”:  Similar ao campo de busca ao lado com a label: "Buscar por palavras chaves. " adicionar "Ordenar por " no espaço em branco.

![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/1d0e17ce-a99d-4abd-bef2-34e79311b58c)

**Comment by rafaelchavesfreitas** [comment]
não me parece uma boa ideia o label ser uma opção do select (uma tentativa de placeholder que não tem em selects).  se é necessário um label, ao meu ver tem que estar fora do select, pois numa lista sempre há uma ordem, nem que seja aleatória... Então é melhor pré estabelecer uma ordenação e eu sugiro que seja dos últimos modificados primeiro.

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/f871ac45-ba78-4239-b049-6bb48779f422)
Setado valor default e adicionado um label
