### ISSUE TITLE
QA - Redesign - Home

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2316]

**Comment by robedj** [comment]
- [ ] Correção da cor do card - High Pure

**Comment by robedj** [comment]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/d2f88900-86f7-400c-9ad3-95ff2627a641)
- [ ] Corrigir botão

**Comment by patricknobre12** [comment]
Pelo menos na versão que eu vi do testes, o último checkbox ainda não havia sido consertado

**Comment by rafaelchavesfreitas** [comment]
- os cards parecem diferentes nas diferentes abas
![Peek 2023-02-22 17-47.gif](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/18301cfd-1aad-47b4-8a17-66ed6fa0dfdb)

**Comment by robedj** [comment]
-[ ] Alteração das fontes nos botões 
- [ ] Alteração do botão confome o figma
