### ISSUE TITLE
criar modal/modais de criação de entidades somente com campos obrigatórios

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#232]
Criar modais para criação de entidades somente com os campos obrigatórios para ser usado em vários lugares do sistema. 

Exemplos: ao adicionar um agente relacionado que não existe;  Criar um espaço na hora de criar uma ocorrência de evento, etc.

Inclusive pode ser usado no painel e deixarmos de usar a single para criar entidades.

**Comment by marylly** [comment]
- [ ] criar a directive angular do modal para exibir o template do formulário de inclusão de cada entidade

**Comment by marylly** [comment]
@ariadnemelo ficou faltando o modal de inclusão de novos selos certificadores

**Comment by rafaelchavesfreitas** [comment]
feito
