### ISSUE TITLE
QA: Card do agente - Texto e disposição do card

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2325]
- [x]  Alteração Ux Writer 
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/0cd83b21-f07e-42b7-bf99-9902190b35d0)

**Comment by rafaelchavesfreitas** [comment]
https://github.com/mapasculturais/mapasculturais/blob/feature/BaseV2/src/protected/application/lib/modules/Search/components/search-list/script.js#L17

Os textos precisam estar internacionalizados
