### ISSUE TITLE
QA: Correção do background das telas do painel: Área toda deve ser preenchida com cinza.

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2348]

**Comment by robedj** [comment]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/defc853b-8fe0-490b-845a-1660d3f70665)

**Comment by patricknobre12** [comment]
O header fica sempre acima daquela linha preta rabiscada

Abaixo disso, o background todo deve seguir o tom de cinza já utilizado para backgrounds

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/b50850fd-dbfb-4cc5-a0a0-1075fc2d85b6)

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/f3e76f32-bb75-4d40-900e-555ded8c1a78)

**Comment by patricknobre12** [comment]
ainda não realizado: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ff263242-7a24-4168-a25f-ca97c8e9e2a6)
