### ISSUE TITLE
QA: Ajustar o link nas singles - entity-header : Aparencia clicável e semibold

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2364]

**Comment by rafaelchavesfreitas** [comment]
não está ajustafa
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3215f92e-8de5-467e-ab33-a717baf3f7ed)

**Comment by robedj** [comment]
Foi alterado em reunião com Ux para font-weight 600.
