### ISSUE TITLE
Componente Stepper para a lista de fases - Oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2366]
- [x] lógica
- [x] estilização
Link do Figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A78210&t=dLhzKGptgjxJuTAZ-0
Link da Documentação:
https://ishadeed.com/article/stepper-component-html-css/

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/aea4859e-fb25-4bca-9161-5ed89039f83f)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/0d51ed1d-dde4-4096-af31-b96ae8da8185)

**Comment by robedj** [comment]
Foi realizada a estilização dos componente contidos no stepper-vertical utilizados configuração de fases:
- Opoortunity-phases-config
- opportunity-create-evaluation-phase
