### ISSUE TITLE
componente modal de criação de fase de avaliação 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2369]
- [x] nome do componente deve ser `opportunity-create-evaluation-phase`
- [x] o tipo do Entity é `evaluationmethodconfiguration`
- [x] o componente deve receber a oportunidade como propriedade e usá-la para definir a propriedade `opportunity` da nova entidade
- [x] o campo `tipo de avaliação` é o type da nova entidade
- [x] o valor da data inicial deve ser maior igaul ao valor inicial da fase anterior e menor que a data da publicação do resultado final (POR ENQUANTO ESSA VALIDAÇÃO SERÁ FEITA NO PHP, NÃO SE PREOCUPAR) 
- [x] o valor da data inicial deve ser menor igaul ao valor da data final configurada (utilizar a propriedade max do entity-field)
- [x] o valor da data final deve ser maior igaul ao valor da data inicial configurada (utilizar a propriedade min do entity-field)
- [x] essa modal, diferentemente das de criaçao de entidades, FECHA A MODAL depois de emitir o evento `create` após a criação com sucesso. 

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/ee4d2e5f-9577-4898-91e1-f413749cb5ab)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/6f1c707f-94c3-4f73-84e4-1d531fbe1cdf)

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/4fa4dbb5-cb64-4bab-b990-eb624335be90)
Verificar as datas do payload

**Comment by rafaelchavesfreitas** [comment]
- [ ] implementar a liitação de datas da mesma maneira como foi feito nos compoentes da listagem das fases

**Comment by rafaelchavesfreitas** [comment]
- [ ] implementar a liitação de datas da mesma maneira como foi feito nos compoentes da listagem das fases

**Comment by rafaelchavesfreitas** [comment]
- replicar na modal a regra do componente de configuração de fases da lista, ou seja:
    - a data inicial deve ser maior ou igual a data inicial da fase anterior SE a fase anterior for uma fase de coleta de dados.
    - a data inicial deve ser maior ou igual a data final da fase anterior SE a fase anterior for uma fase de avaliação.

**Comment by rohilario** [comment]
Ajustado datas.

**Comment by daphnemartinsba** [comment]
- [ ] Foi possível criar uma terceira fase com a data anterior ao término da segunda:
[Uploading... 2369.gif]
