### ISSUE TITLE
desenhar conteúdo de fase de coleta de dados concluída

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2371]
na aba **Inscrições e Resultados** não há um exemplo de fase de coleta de dados concluída aberta.

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/69769771-f729-4121-acdc-d691c7421808)

**Comment by patricknobre12** [comment]
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/1357532c-5e82-4cea-8f0a-c2d5bbc1cb2b)
