### ISSUE TITLE
complementar resumo de fase de avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2372]
o resumo da fase de avaliaçao deve conter:
- status da avaliação 
- quantidade de inscrições
- quantidade de inscrições não avaliadas
- quantidade de inscrições avaliadas
- quantidade de inscrições avaliadas como selecionada
- quantidade de inscrições avaliadas como suplente
- quantidade de inscrições avaliadas como não selecionada
- quantidade de inscrições avaliadas como inválidas

- quantidade de inscições pendentes
- quantidade de inscições "não pendentes" (tem que pensar no label)
- quantidade de inscrições selecionadas
- quantidade de inscrições suplente
- quantidade de inscrições não selecionadas
- quantidade de inscrições inválidas

**OBS: os status das avaliações podem mudar de acordo com o tipo de avaliação. para avaliação simplificada, há os 4 tipos listados acima. para avaliação documental, só há selecionada e inválida. para avaliação técnica são ranges de notas.

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/d9e81d48-46ab-4b21-bea0-a35ccae79183)

**Comment by patricknobre12** [comment]
Os ajustes estão registrados aqui: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=3923%3A84636&t=5iMuDjCUp6avpli6-1

Ainda é importante ser validado e também não entendi como poderia ficar no caso das avaliação técnica
