### ISSUE TITLE
remover filtro por data e adicionar filtro por avaliador da tela de listagem de avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2373]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/a9c77bad-1a3b-4e51-8524-2053d374675e)

**Comment by patricknobre12** [comment]
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/07d2f797-85a2-49fb-8030-8424e7e46659)
