### ISSUE TITLE
adicinar componente de resumo das avaliações na listagem de inscrições para o avaliador

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2374]
adicionar este componente
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/c17d9c33-05ca-4654-be9e-a7519a4a8c68)

nesta listagem
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/c3e13f9a-a676-4dd0-ae65-3150a3e75610)

- **aproveitar e remover filtro de data"

**Comment by patricknobre12** [comment]
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/c2d9a5f9-031c-45ed-9139-50805dce5dab)
