### ISSUE TITLE
modificar componente de listagem de inscrições do proponente na single de oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2389]
- [x] adicionar número da inscrição e agente responsável (talvez um card)
- [x] adicionr status da inscrição
- [x] mudar o label do botão de acordo com o status???

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/00ebce8d-e983-4452-b60f-7a9ae92d0d4c)

**Comment by patricknobre12** [comment]
**Precisa validar**

**Comment by patricknobre12** [comment]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=4048%3A88413&t=qnVE3XvZMTd9qtx3-1

**Comment by rafaelchavesfreitas** [comment]
- [ ] ajustar os cards nas telas das diferentes versões com o mesmo card da tla 
- [ ] componentizar o card e utilizar em todas as páginas.

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/d98120a9-a2bc-446e-9b80-6d9ac9702434)
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/ae3cb46c-7cba-483f-9ea7-026386ccc909)
