### ISSUE TITLE
desenhar versão do componente de inscrição da single de oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2392]
- [x] versão de antes da abertura das inscrições
- [x] versão após o término da abertura das inscrições
- [x] versão para quando o usuário possui somente 1 único agente (não precisa de um select neste caso) (mudar o tezto acima dos selects)

Como está atualmente
![image.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/e9e9e807-5b41-4140-a451-8fae3c1f52b3)

**Comment by patricknobre12** [comment]
**precisa ser validado**, segue o link para visualizar os ajustes: 

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=4051%3A89053&t=qnVE3XvZMTd9qtx3-1
