### ISSUE TITLE
base da página de inscrição em oportuidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2394]
implementar base da página de inscrição em oportunidades contendo:
- [x] stepper (os campos do tipo título de seção)
- [x] seleção de agente coletivo (`select-entity`)
- [x] seleção de instituição responsável (`select-entity`)
- [x] seleção de espaço (`select-entity`)

- [x] para o MVP o botão continuar será substituido por um botão enviar
- [x] botão salvar para depois 
- [x] botão sair com a mesma implementação do `entity-actions`

talvez seja uma boa idea criar um arquivo de layout específico para as inscrições

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/08a17da6-25c0-47d3-b069-371475148d58)

**Comment by daphnemartinsba** [comment]
Os botões enviar, sair e salvar para depois estavam disponíveis e funcionaram. Foi possível configurar a solicitação do vínculo com agente coletivo, instituição responsável e espaço, foi possível configurar o campo título de seção e enviar a ficha de inscrição após o preenchimento dos campos:
![2394.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/143a25b6-d3ba-43cd-aa49-f370ec88da76)
