### ISSUE TITLE
completar página de edição do formuário de inscrição

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2395]
estão faltando:
- [x] número da inscrição
- [x] categoria da inscriçào
- [x] aproveitar e mudar o título deixando explícito que é o nome da oportunidade
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/2c9d899b-c0ac-4e68-a634-52aafd4f6f7e)

**Comment by patricknobre12** [comment]
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/694c23e4-bd6f-4cfa-bb5d-7c7312c8f6b6)
