### ISSUE TITLE
configuração min e max dos datepickers das datas das fases na aba de configuração das fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2396]
- criar métodos `getMinDate` e `getMaxDate` que recebem uma fase e o índice da fase dentro do array de fases no componente `opportunity-phases-config` e retornam o valor máximo/mínimo para a fase, seguindo a seguinte regra:

- criar métodos auxiliares para retornar a fase anterior e a fase posterior a uma determinada fase;

- para fase de coleta de dados, as datas sào as propriedades registrationFrom e registrationTo
- para fase de avaliação, as datas são as propriedades evaluationFrom e evaluationTo

### `getMinDate` retorna:
- [x] se for a primeira fase, retorna undefined
- [x] se for fase de coleta de dados, retorna a data final (registratonTo ou evaluationTo) da fase anterior 
- [x] se for uma fase de avaliação:
    - [x] se a fase anterior for uma fase de avaliação, retorna a data final da fase anterior
    - [x] se a fase anterior for uma fase de coleta de dados, retorna a data inicial da fase anterior

### `getMaxDate` retorna:
- [x] se a próxima fase for a última fase da oportunidade (isLastPhase), retorna o publishTimestamp da última fase
- [x] se a próxima fase for de coleta de dados, retorna a data inicial da próxia fase (registraionFrom)
- [x] se a próxima fase for de avaliação:
    - [x] se a fase atual for de coleta de dados, retorna a data final da próxima fase (evaluationTo)
    - [x] se a fase atual for de avaliação, retorna a data inicia da próxima fase (evalutaionFrom)

**Comment by rohilario** [comment]
componentes refatorados para seguir estas regras.
