### ISSUE TITLE
adicionar a fase criada a lista de fases na aba de configuraçao de fases da oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2397]
no template do componente `opportunity-phases-config` utilizar o evento `@create=` para capturar a entidade criada (pode ser uma fase de avaliação ou uma fase de coleta de dados e adicionar na penúltina posição.

exemplo:
```
const countries = ["Ghana", "Nigeria", "Rwanda"];
countries.splice(1, 0, 'Kenya');
console.log(countries); // ["Ghana","Kenya","Nigeria","Rwanda"]
```

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/09975644-5659-4cb0-ab28-79b66489a3bf)
Capturado evento com a response e adicionado no array, com o slice na peneultima posicao (arraysize -1)
