### ISSUE TITLE
adicionar cofiguração dos textos para os avaliadores na configuração de fase de avaliação no componente opportunity-phases-config

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2400]
- somente para fase de avaliação
- deve-se utilizar `textarea` com `v-model` normal e não o entity-field, pois não funcionará.
- os campos populam a propriedade `infos`, que é um objeto, da fase de avaliação
- no primeiro textarea "para todas as fichas de inscrição" o `v-model="infos['general']"`
- os demais devem estar dentro de um v-for que itera em cima das categorias (`registrationCategories`) da primeira fase, mais ou menos assim:

```HTML
<div v-for="category in phases[0].registrationCategories">
    <textarea v-model="infos[category]">
</div>
```

para as categorias Música, Teatro e Dança a pripriedade info da fase ficaria assim:
```JS
phase.info = {
    'general': "texto que aparece para todas as inscricões",
    'Música': "textos que aparecem para as inscrições de música",
    'Dança': "textos que aparecem para as inscrições de dança",
    'Teatro': "textos que aparecem para as inscrições de Teatro"
}
```
o payload fica assim:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/068843f1-03e3-4d64-a0be-97302b3e819e)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/69765032-a851-46a6-89bd-23171b879b16)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/28a01739-40c9-4788-bf46-c3e07168816e)

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/fd7cf7ed-001e-4662-b19d-48cf34adc6fa)

category in phases[0].registrationCategories -> undefined

![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/61eb9664-e5ec-4ee2-b288-cd3b00170696)

**Comment by rafaelchavesfreitas** [comment]
não está mais fucionando...

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/7d69f549-d2e3-408c-a3d9-ca1a14bc456b)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/ce0d2721-0188-4284-a9d7-f41a6847e6b9)

**Comment by daphnemartinsba** [comment]
Está funcionando adequadamente, como mostra o gif a seguir:
![2400.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a2cd1fbe-33a1-4bd3-8056-781c63f05464)
