### ISSUE TITLE
remover opção de criação de agente individual

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2407]
- [ ] verificar permissão `canUserCreateIndividualAgent`

**Comment by erleibiazzio** [comment]
Implementado e rodando para teste no link https://testes.map.as/

**Comment by daphnemartinsba** [comment]
Comportamento Esperado: A opção da criação de agente individual deve ser removida somente para agentes que possuem permissão Normal. 

Fluxo Inesperado: 

- [ ] Agentes com permissão de Administrador e Super Administrador não conseguem criar Agentes Individuais pela modal da tela do painel, ou pela modal de Meus Agentes. 

- [ ] Pela criação de agentes na home ou na tela de busca dos agentes é possível criá-lo como individual. Contudo, o agente é salvo como individual durante sua criação somente quando se clica em "salvar rascunho" mais de uma vez.

**Comment by daphnemartinsba** [comment]
Os seguintes locais de criação de agente criam subagentes por modais: Painel de Controle, Meus Agentes, Busca de Agentes, Menu do Avatar
Modal de criação de sub agente por agentes com permissão Normal:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8fa7563b-b311-4627-8525-44c8d0828ca4)
