### ISSUE TITLE
adicionar nova fase na lista de fases após a criação da fase

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2410]
- [x] fase de avaliação
- [x] fase de coleta de dados

**Comment by rohilario** [comment]
Adicionada na fase de coleta de dados, pois o backend está salvando corretamente, o que nao corre na fase avaliacao.

**Comment by rohilario** [comment]
Adicionado na lista após a criacao da fase.
