### ISSUE TITLE
listagem de erros do formulário de inscrição perto do botão contiuar|salvar para depois

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2414]
- ver como foi implementada na versão BaseV1 (#2404)
- [x] desenhar as telas no figma para o BaseV2
- [ ] implementar no BaseV2

**Comment by patricknobre12** [comment]
fiz um exemplo, mas precisa validar: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=4405%3A88219&t=m8emhEKDem84ZEhZ-1
