### ISSUE TITLE
Base da página de visualização de inscrição em oportunidade

### ISSUE THREAD

**Issue by Raul-vlb** [mapasculturais/mapasculturais#2415]
![image.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/678a861b-e50f-424e-a7ab-06914e09ec46)

![image.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/5462e24c-9f66-4c76-b546-ba29bf6ac3a8)

**Comment by rafaelchavesfreitas** [comment]
- [ ] Nome do projeto é um metadado da inscrição `projectName` que só vem na inscrição se for confgurado na oportunidade.
