### ISSUE TITLE
base da página de edição do formulário de coleta de dados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2421]
- [x] criar a rota chamada `formBuilder` módulo Opportunity (se basear no `GET_edit` do `Traits\ControllerEntityViews`).
- [x] criar o arquivo de visão para a rota (views/opportunity/form-builder.php)
- o `entity` nessa página será a fase de coleta de dados e a oportunidade (primeira fase) será o `entity.parent` quando houver o entity.parent, se não a oportunidade será o entity mesmo. 
- [x] o título do header deve utilizar as infos da oportunidade (`entity.parent`)
- [x] o botão voltar deve ser um `<mc-link` para a rota de editação do `entity.parent` e o hash da aba de configuração de fases.
- [x] o nome da etapa é o `entity.name` quado não for a primeira fase. 
- [x] o nome da etapa deve ser "Período de inscrição" quando o entity.parent for null (isFirstPhase)
- [x] a data de inicio é o `entity.registrationFrom` e a data de término é o `entity.registrationTo`
- [x] categorias de inscrição será um componente a parte e só deve aparecer na configuração do formulário da primeira fase (entity.isFirstPhase ou `!entity.parent`)
- [x] os demais campos do print, ver no $DESCRIPTIONS.opportunity quais são. utilziar o `<entity-field` (useAgentRelationXXXX, useSpaceRelationXXX, projectName
- [x] não colocar os 2 botões (importar e salvar)
- [x] utilizar o coponente `<entity-actions`

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/1b63a745-42c5-4916-8bab-f66aa90a378a)

**Comment by rohilario** [comment]
Verificar como colocar o botao de voltar no entity header (slot ou hook)

**Comment by rohilario** [comment]
Grupos de categorias, descricao do grupo e categorias de inscrição -> Qual campo popular;
McHeader -> nao possui slote para botao de voltar;

**Comment by rohilario** [comment]
Ajustar os campos para entity-field

**Comment by rafaelchavesfreitas** [comment]
- [ ] utilizar o componente `<entity-field` para a configuração dos campos

**Comment by rohilario** [comment]
Ajustado.
Os campos useAgentRelationXXXX, useSpaceRelationXXX, projectName manda uma mensagem que nao é uma entidade

![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/a472e244-e622-477d-bfd1-a2e81074b6ce)

**Comment by rohilario** [comment]
No form builder, nao vem a prop isfirstfphase quando passa o entity;

**Comment by rohilario** [comment]
isfirstphase está sendo retornado agora, pagina carregando conforme as regras acima
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/0ca3189d-dc95-4415-b399-cb58f52ee510)

**Comment by rohilario** [comment]
- [ ] Remover configuracoes de números maximo(deixar o de projetos);

![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/4e00ffdc-552d-4433-bab1-d7d535eb918f)

**Comment by rohilario** [comment]
- [ ] O Id da fase deve ser o id do item do array na aba de configuracoes de fase(addOpportunityPhaseToJS) checar no edit.php;

![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/4e00ffdc-552d-4433-bab1-d7d535eb918f)

![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/870286a1-76e9-4e26-998c-92a7d079b70e)

**Comment by rohilario** [comment]
Ajustes realizados pelo @rafaelchavesfreitas
