### ISSUE TITLE
Tela de edição da oportunidade - Ajustes e correções 

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2423]

**Comment by robedj** [comment]
- [ ] Abas do tabs devem ficar no header
- [ ] Nome da oportunidade deve aparecer no lugar de edição da oportunidade, e no breadcrumb deve colocar "edição da oportunidade"

**Comment by rafaelchavesfreitas** [comment]
@robedj revisar o que já foi feito e marcar os checkboxes

**Comment by robedj** [comment]
Foi feita a revisão, porém o botão Reivindicar propriedade não é aplicado nas paginas da edição da oportunidade
