### ISSUE TITLE
Single da Oportunidade - Ajustes e correções

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2424]

**Comment by robedj** [comment]
- [ ]  alterar a "Apresentação" para longDescription
- [ ]  É padrão das entidades exibir Descrição Curta e Descrição Longa
- [ ]  Tags não aparecem na single
- [ ]  Areas de Interesse não aparecem na single
- [ ]  Redes sociais não esta clicavel como nas outras entidades

**Comment by rafaelchavesfreitas** [comment]
@robedj revisar o que já foi feito e marcar os checkboxes

**Comment by robedj** [comment]
A oportunidade não tem long Description.

**Comment by robedj** [comment]
Foram realizadas as correções porém a taxonomy pra "Áreas de interesse" Ainda não foi definida. Será criada uma outra issue para isso.

**Comment by daphnemartinsba** [comment]
Foi criada a issue #2853 para a demanda da área de interesse

**Comment by daphnemartinsba** [comment]
- Apresentação permanecerá sendo shortDescription, porque não possui longDescription no backend
- Oportunidade possui somente descrição curta:
 ![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/85cf89d8-bbdc-4d52-a22a-26a618e956c7)

- [ ]  tags não são salvas na edit e portanto não aparecem na single:

![2424.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/06ab1038-238a-4a67-9064-02c316474e58)

- Redes sociais estão clicáveis. Como exemplificado no gif abaixo:
![rede.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8156c250-7590-47ea-8441-df7b35c306fb)

**Comment by robedj** [comment]
Área de interesse foi uma proposta mas não existe no atual desenho do mapas.
