### ISSUE TITLE
garantir que todas as oportunidades tenham uma última fase

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2430]
- [x] criar a última fase, com o metadado isLastPhase = true, automaticamente quando criar uma nova oportunidade (somente BaseV2)
- [ ] db-update para criar as fases de publicação do resultado

**Comment by daphnemartinsba** [comment]
Todas oportunidades criadas vem com uma fase de inscrição e uma fase final que podem ser configuradas:
![#2430.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/aa9b61cd-3bcb-4da9-8f9e-66f78822008a)
