### ISSUE TITLE
Criar estrutura base da aba de Inscricoes e Resultados - Edicao de Oportunidade

### ISSUE THREAD

**Issue by rohilario** [mapasculturais/mapasculturais#2438]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/0c8af74c-85e1-4876-b422-2e0354c87019)

**Comment by rohilario** [comment]
Criada estrutura base.
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/4cbb1358-686c-41a6-8062-ee5d92ff439e)

**Comment by daphnemartinsba** [comment]
Refatoração na issue #2918
