### ISSUE TITLE
separar em compontes as diferentes fases da aba de configuração de fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2453]
**propriedades dos componentes**
- `currentIndex`
- `entity` (o objeto Entity da oportunidade que está sendo editada)
- `phases` (a lista de fases)

**orientações**
- implementar nos componentes que forem necessários os métodos getPreviousPhase e getNextPhase
- as regras dos valores min e max das datas de cada fase devem ser levadas para dentro dos componentes, removendo o que não fizer sentido, por exemplo no componente de publicação de resultados não precisa verificar se a fase atual é uma fase de avaliação ou coleta de dados, 

**componente que serão criados**

- [x] componente para a fase de avaliação (`opportunity-phase-config-evaluation`)
- [x] componente para a fase de coleta de dados (`opportunity-phase-config-data-collection`) (deve ter uma prop `isFirstPhase`)
- [x] componente para a fase de publicação de resultados (`opportunity-phase-config-results`)

**Comment by rafaelchavesfreitas** [comment]
o componente `opportunity-phase-config-results` não está funcionando, quando tenta expandir a o stepper da fase acontece o seguite erro:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/05ecd131-13a7-459f-960e-3af8ef226107)

**Comment by rafaelchavesfreitas** [comment]
o componente `opportunity-phase-config-evaluation` tb não está 100%, quando tenta abrir as fases de avaliação também estão aparecendo vários warnings:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/0b72a302-4eaa-43ab-a50e-3dbf05540e66)

**Comment by rafaelchavesfreitas** [comment]
o componente `opportunity-phase-config-data-collection` também está disparando vários warnings:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/dcdd8ed9-abf5-4ca2-88ce-7017a5567848)

**Comment by rohilario** [comment]
retirado waenings e ajustado o opportunity-phase-config-results

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/7e38f992-9013-4fbb-bec8-e2070516e81c)
