### ISSUE TITLE
implementar os botões da timeline da página de acompanhamento da inscrição (ESPECIFICAR MELHOR)

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2458]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/9df12fa2-be3e-481d-a187-60907f983ed7)

**Comment by daphnemartinsba** [comment]
issue duplicada, trabalhada e/ou resolvida na issue #2736
