### ISSUE TITLE
Retirar o scroll dos cards do componente panel--entities-summary__card na versão web

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2460]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/0524a6a9-4da2-4398-87f0-1d4e8de6c67c)
Se não for possível, diminuir a largura x altura do card para que fique próximo do Figma

**Comment by rafaelchavesfreitas** [comment]
diminuir o tamanho dos cards para telas menores que 1440. fazer funcionar para telas de 1280px de largura
