### ISSUE TITLE
Ajustar menu scroll do menu do painel no mobile

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2463]
Não consegui scrollar o menu do painel até visualizar o item de sair... ou seja, não consigo sair
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/d0fb5196-82d4-452f-8b2c-aecdbea13625)

**Comment by robedj** [comment]
O celular esconde o botão de sair na resolução mobile.
