### ISSUE TITLE
Ajustar scroll do filtro de listagem de entidades no mobile

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2468]
No filtro de eventos não tá scrollando a ponto de não mostrar o "Limpar filtros"
https://images.zenhubusercontent.com/16917978/21e3b6bc-f19c-4ed3-89bc-79de76e2e91d/filtro_n_o_scrolla_e_mostra_bot_o.mp4

**Comment by robedj** [comment]
na versão mobile o celular esconde a parte de baixo da tela de filtros.

**Comment by robedj** [comment]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/0b5fa327-4e64-499a-be7e-0a640b50762a)
Acontece adicionando várias opções nas tags.

**Comment by robedj** [comment]
Ajuste Realizado
