### ISSUE TITLE
implementar autosave nos campos das fases da aba de configuração de fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2482]
- [x] utilizar a propriedade `autosave` do componente `entity-field` 
- [x] remover os botões save dos componentes
- [x] no textarea das informações para os avaliadores, colocar um `@change="savePhase()"`. implementar o método no componente `opportunity-phase-config-evaluation`. o método deve fazer um timeout igual ao do componente `<entty-field>`

**Comment by rohilario** [comment]
Verificar o text-area -> como implementar o entity-field textarea com a prop dinamica, ex: prop="infos['general']", prop="info['Teatro']"

**Comment by rohilario** [comment]
Ajustado datepicker
