### ISSUE TITLE
remover indicação de obrigatório nas modais de criação de fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2483]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3d3cde83-00e7-456d-beb6-22b45e77e50b)

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/8a614fe5-622b-4aef-8411-23dce537f945)

**Comment by rohilario** [comment]
Nao identifiquei props que facam o campo ser obrigatório ou nao.
 o entity-field valida o que vem do backend pra poder exibir a msg de obrigatoriedade.
src/protected/application/lib/MapasCulturais/Entities/Opportunity.php

**Comment by rohilario** [comment]
Usada prop hiderequired do entity-field

**Comment by daphnemartinsba** [comment]
modal de fase de avaliação:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/680b20ff-db9b-4cd7-9c77-aaed360b4b2e)
modal de fase de coleta de dados:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fc57d218-0185-48ab-90c4-e4e8105f30fe)
