### ISSUE TITLE
chamar o método `$this->addOpportunityPhasesToJs()` na página de configuração de oportunidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2484]
o método `$this->addOpportunityPhasesToJs()` coloca as fases da oportunidae no objeto $MAPAS.opportunityPhases.

- [x] refatorar o componente `opportunity-phases-config` para utilizar o `$MAPAS.opportunityPhases` caso este esteja disponível e só fazer a requisição à API caso este não esteja disponivel.

- [x] implementar a configuração da data final de publicação DA ABA INFORMAÇÕES utiilizando o componente `<entity-field>` com autosave=300 utilizando a a última fase (isLastPhase) do array `$MAPAS.opportunityPhases`

**Comment by rafaelchavesfreitas** [comment]
- [ ] no campo data final de publicaçã foi colocado o `entity` e não a last phase do $MAPAS.opportunityPhases

**Comment by rohilario** [comment]
Ajustado. Agora, ao salvar na aba de informacoes, atualiza também na aba de configuracoes de fases, na ultima fase.
