### ISSUE TITLE
remover placeholders da aba `Informações` da página de edição de oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2485]

**Comment by rohilario** [comment]
Removido botoes e deixado a estrutura base do html/template para futura implementacao.

**Comment by rafaelchavesfreitas** [comment]
na single de oportunidade
- [ ] remover botões de deuncia, contato reivindicar propriedade
- [ ] remover abas de projetos e suporte

**Comment by rafaelchavesfreitas** [comment]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/0b57b3d9-0034-44bd-8cbe-e1477b7b8462)

**Comment by rohilario** [comment]
Removido configuracao de formulario pendente ou nao da aba de configuracoes de fases

**Comment by rohilario** [comment]
Ajustado também a aba de avaliacoes e resultados, para deixar aparecendo somente aquilo que tiver funcionando de fato.

**Comment by rohilario** [comment]
removido link para ver as
