### ISSUE TITLE
revisar configuração de agentes relacionados na configuração do formulário de coleta de dados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2486]
o correto é que para vinculação de espaço, agente coletivo e instituição responsável tenham as opções
- não utilizar
- obrigatório 
- obcional

precisa revisar os textos tb pq "permitir inscrição de agente coletivo", por exemplo, não representa a funcionalidade.

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/5cf72828-9e20-4c18-b376-ed9762305aa8)

**Comment by patricknobre12** [comment]
ISSUE COM ATUALIZAÇÃO. 
Link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A79112&t=WkfqXD08BT6lOLy1-1

Ajustes realizados e mostrados na imagem abaixo
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/e4ef25aa-3cb8-4634-81f0-75831af7858a)

**Comment by daphnemartinsba** [comment]
Alterações já foram implementadas no ambiente de teste:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cf8026c9-d456-45e8-b4d6-cbedd408e456)
