### ISSUE TITLE
implementar autosave no campo de data de publicação de resultado na aba informações da edição de oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2487]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/ee6f789c-b7af-4a10-8906-2ae9367ec57b)

**Comment by rohilario** [comment]
Retirado implementacao do datepicker, adicionado com um entity-field.

**Comment by daphnemartinsba** [comment]
Campo com autosave:
![2487.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/17ab090a-164b-4c13-8d52-2692ec7d02f6)
