### ISSUE TITLE
implementar rota opportunity/registrations e página lista de inscrições

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2488]
- [x] o link "lista de inscrições da fase" de qualquer fase deve levar para esta rota.
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/08cb488f-3640-4c00-91df-7cf8577a0083)
- [x] implementar na página até o que aparece no print abaixo
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3fa86059-7097-4fb8-ad3f-686520a7335c)
- [x] utilizar o componente v1-embed-tools com a rota `registrationmanager` passando o id da oportunidade (fase) que renderizará a parte do print abaixo:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/5d6339c0-d583-4ed8-b40d-c78177550aef)

- [x] a página ficará mais ou menos assim:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/f3db198d-ef05-49b2-9044-d9ba7ed8cac8)

**Comment by rohilario** [comment]
entity retornando o controller(evaluationmethodconfiguration) errado para o mc-link 
http://localhost/evaluationmethodconfiguration/inscricoes/5/
entity.opportunity vindo null
