### ISSUE TITLE
criar componente base da aba relatórios

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2489]
- [x] nome do componente `opportunity-phase-reports`
o componente deve listar as fases e incluir o embed tools para cada fase
- [x] quando houver uma fase de avaliação após uma fase de coleta de dados, ou seja, o opportunity da fase de avaliação for igual ao id da fase anterior, juntar as 2 fases num card só, exemplo: se após a fase de inscrição houver uma fase de avaliação documental, o card se chamará **Período de Inscrições / Nome da fase de avaliação**
- [x] utilizar o componente v1-embed-tools com a rota `opportunityreport` passando o id da phase de coleta de dados. se a fase for uma fase de avaliação, passar o phase.opportunity.id, se for uma fase de coleta de dados, passar o phase.id
- [x] colocar o componente na aba de relatórios

**Comment by rohilario** [comment]
Verificar pq não existe a propriedade opportunity e opportunity.id

**Comment by rohilario** [comment]
Componente v1-embed-tools com erro no OpportunityAccountability/Module.php

**Comment by rafaelchavesfreitas** [comment]
- [ ] modificar a rota do embedtools para `reportmanager

**Comment by rohilario** [comment]
Ajustado, mas continua com erro no embedtools

**Comment by rafaelchavesfreitas** [comment]
o item abaixo não está funcionando:
> quando houver uma fase de avaliação após uma fase de coleta de dados, ou seja, o opportunity da fase de avaliação for igual ao id da fase anterior, juntar as 2 fases num card só, exemplo: se após a fase de inscrição houver uma fase de avaliação

para testar criar uma oportunidade nova com uma fase de avaliação, com a seguinte estrutura na aba de configuração:
1. Período de Inscrição
2. Avaliação Documental
3. Publicação Final dos Resultados

na aba de relatórios deve ficar assim, contendo apenas uma instancia do embed tools por linha:
1. Período de Inscricão / 2. Avaliação Documental
3. Publicação Final dos Resultados

**Comment by rohilario** [comment]
Ajustado conforme descrito acima
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/d108510a-763b-4a62-9096-c9744144eefa)
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/2249fe45-b12b-4b0e-8a59-f0fa1808f423)
