### ISSUE TITLE
rever páginas de lista de inscrições

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2490]
- essas 3 versões desta página não fazem sentido pois o fluxo pode de avaliação e aplicação de resultado pode ser contínuo, então os botões aplicar resultado das avaliações, baixar rascunhos, baixar lista de inscrições precisam coexistir.
- o título "inscrições concluídas" não funcionam para fases exclusivamente de avaliação.

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3ad41769-3eef-4891-8fff-62ba05e6f148)

- esta info tb parece que não faz sentido por causa do fluxo contíuo
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/6d318b12-c226-4f0f-8e8b-64eb66571fd9)

**Comment by patricknobre12** [comment]
As alterações foram realizadas no figma: 
link 1:https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A79343&t=eJInZHEfFHEBERFO-1

link 2: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A78002&t=eJInZHEfFHEBERFO-1
