### ISSUE TITLE
implementar checkboxes de configuração de publicação automática do resultado

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2493]
- [x] em fases de coleta de dados, colocar um `<entity-field` para o campo `phase.autoPublish`
- [x] em fases de avaliação, colocar um `<entity-field` para o campo `phase.opportunity.autoPublish`
- [x] em todos os casos cofigurar o entity-field com autosave = 300

**Comment by daphnemartinsba** [comment]
Os checkboxes foram implementados. Foi possível publicar o resultado da fase automaticamente. Mas não foi possível publicar resultado da fase final automaticamente:

![#2493.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/608b194f-564d-4f15-9056-36e0ec6732c5)

**Comment by daphnemartinsba** [comment]
Issue será resolvida na #2797
