### ISSUE TITLE
implementar botão `publicar resultados` das fases das oportunidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2495]
- [x] o botão deve ser um `<confirm-button`
- [x] para fase de coleta de dados, o botão deve executar o método `phase.POST('publishRegistrations')`
- [x] para fase de avaliação, o botão deve executar o método `phase.opportunity.POST('publishRegistrations')`

**Comment by rohilario** [comment]
adicionado na aba inscricoes e resultados, pois vi que no figma toda fase tem o botao e aqui na issue nao foi especificado em qual aba.
