### ISSUE TITLE
Correção no componente entity-social-media: inputs não salvam as redes 

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2500]

**Comment by robedj** [comment]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/ca2a8c96-5bbc-4f1e-a2de-86032e7c476f) formatos aceitos

**Comment by robedj** [comment]
Formatos aceitos:
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/511dd277-ca01-423a-bd7e-4cc26e68b0cc) 
Correções realizadas.

**Comment by daphnemartinsba** [comment]
As demais redes sociais estão salvando. 

- [ ] Erro no campo de instagram ao tentar salvar o arroba:
![2500.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/11fe5757-ab6e-4f70-b1c7-90530ab29719)

**Comment by robedj** [comment]
O usuario pode adicionar o user dele : user
ou adicionar @ user 
Foi retirada a validação anterior.
