### ISSUE TITLE
criar componente para a configuração de categorias do formulário de inscrição

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2505]
- ver no $DESCRIPTIONS.opportunity os campos
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/156ed040-fd0b-4ba3-8b01-96bf4b6be55c)
- utilizaro entity-fields para os 2 primeiros campos

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/69d98c7c-257f-4947-b021-efc30bf3d1d0)

**Comment by rafaelchavesfreitas** [comment]
- a data inicial deve ser maior ou igual a data inicial da fase anterior SE a fase anterior for uma fase de coleta de dados.
- a data inicial deve ser maior ou igual a data final da fase anterior SE a fase anterior for uma fase de avaliação.

**Comment by rohilario** [comment]
Usado componente popover e mc-tag-list quando adicioando item no array
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/dabf5e06-5bc8-4db6-a736-96088ac64658)
