### ISSUE TITLE
corrigr validação errada da data final da fase de avaliação OU correção da oportunidade dona da avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2520]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/7d28a6e7-2d65-4db9-881e-4f0b90cc0db8)
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/d7be8b0f-59b3-4300-8eea-5aa33daf51e3)

parece que esse erro foi na definição da oportunidade dona da fase de avaliação

**Comment by daphnemartinsba** [comment]
Mensagem errada de validação não aparece mais:
![2520.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/09ae7140-d6ed-43f7-a838-0a76d97903e4)
