### ISSUE TITLE
implementar modal para a configuração do suporte na aba inscrições e resultados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2521]
- [x] o botão de abrir a modal só aparece nas fases de coleta de dados
- [x] o conteúdo da modal é um embedtools

**Comment by daphnemartinsba** [comment]
A imagem a seguir mostra a modal de configuração do suporte:
![suporte.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b425fc41-5d23-482f-8d18-94aeefdd958e)

A imagem a seguir mostra o suporte disponível em fases de coletas de dados:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/dd7b1911-4fe7-45c7-bb75-3a02b73c9505)
