### ISSUE TITLE
definir regra e implementar botões da página de acompanhamento de inscrição

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2523]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-75882&t=yZZdtwSELjytNuAV-0

**Comment by daphnemartinsba** [comment]
issue contemplada e/ou atualizada pelas issues #2736 e #2757
