### ISSUE TITLE
revisar se todas as entidades tem short e long description

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2525]
- [x] tanto na edição quanto na visualização
- [x] nas páginas que não tiver previsto no figma o long description, colocar em algum lugar da página e criar uma tarefa para o Patrick corrigir no figma

**Comment by robedj** [comment]
Single do agente coletivo e individual não possuem shortDescription
Single - space: não possui shortDescription
Single  - project : não possui shortDescription, só esta com longDescription

Single - event: não possui shortDescription
