### ISSUE TITLE
criar componente `opportunity-phase-publish-date-config` para a configuração da data de publicação dos resultados das fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2534]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/1d3560e8-1fc2-4a55-8a32-9336a1f9f827)
- [x] o componente deve se chamar `opportunity-phase-publish-date-config`
- [x] o componente recebe uma fase de coleta de dados (opportunity)
- [x] o componente tem 4 props booleanas: hide-button, hide-datepicker, hide-checkbox e hide-description
- [x] se a data de publicação não estiver preenchida, desabilitar o checkbox de publicação automática.
- [x] o botão de publicar resultado deve ficar desabilitado na seguinte situação:
```JS
// se a próxia fase for uma fase de avaliação esta estará em phase.evaluationMethodConfiguration
date = phase.evaluationMethodConfiguration?.evalutionTo || phase.registrationTo;
disable = date.isFuture();
```
- [x] o botão publicar resultado deve ser um `<confirm-button>` que faz um POST para `publishRegistration` da entidade (`phase.POST('publishRegistration'....`) 
- [x] caso o resultado da fase já esteja publicado, substituir toda a interface por um texto dizendo que a fase já está publicada e um botão para "Despublicar o resultado" que faz um POST para `upublishRegistration` (esse endpint ainda não está implementado)
- [x] quando a opção `hide-checkbox` estiver ativa, substituir o checkbox pelo texto `os resultados serão publicados automaticamente`
- [x] quanto a opção `hide-datepicker` estiver ativa, substituir o datepicker pelo texto `os resultados serão publicados em XX/XX/XXXX às XX:XX`
- [x] se ambos (`hide-checkbox`,  `hide-datepicker`) estiverem ativos, substituir o datepicker e o checkbox pelo texto: `os resultados serão publicados automaticamente em XX/XX/XXXX às XX:XX`

**Comment by rohilario** [comment]
- [ ] Quando o resultado da fase já estiver sido publicado, mostrar também a data de publicacao (publishtimestamps);
- [ ] Deixar o checkbox "marcavel" com o label;

**Comment by rohilario** [comment]
- [ ] nos metodos post`s no then, realizar um populate do entity passando a entity.
