### ISSUE TITLE
aplicar componente opportuity-phase-date-config nas abas de configuração de fases e inscrições e resutlados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2535]
- [x] na aba **configuração de fases** não exibir o botão de pubicação do resultado
- [x] na aba **inscrições e resutlados** não exibir o datepicker de configuração do resultado.

**Comment by rohilario** [comment]
- [ ] Na aba de configuracao, qualquer fase de avaliacao, tem que ter a configuracao (mostrar datepicker e o checkbox de publicacao automatica);
- [ ] Na aba de configuracao nas fases de coleta de dados só exibir se phase.evaluationMethodConfiguration == nuil || undefined;
- [ ]
