### ISSUE TITLE
implementar botões para download das planilhas nas páginas de listagem de inscricões e listagem de avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2543]
- ver no BaseV1 as rotas

**Comment by daphnemartinsba** [comment]
Botões implementados, como mostra as imagens a seguir:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6e2db79c-b362-431d-87f1-45fbd27674de)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/792cc9fc-b350-45ee-bc45-f1bf60285cfc)
