### ISSUE TITLE
refatorar condicionalidade de campos do formulário 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2548]
- [x] criar propriedades (com mapeamento para o db) para os campos na entidade `RegistrationFieldConfiguration`: (nome da coluna é com underline, nome da propriedade é camel case)
  - [x] `conditional` - tipo booleano
  - [x] `conditionalField` - string
  - [x] `conditionalValue` - string
- [x] criar db-update (`src/protected/db-updates.php`) para criar as colunas na tabela (registration_field_configuration) - usar o comando `./dev-scripts/dump-db-updates.sh | grep nome_da_coluna` para gerar o SQL 
- [x] refatorar o frontend de acordo com o print abaixo para salvar nos novos campos
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/07d4e7ae-f3c2-4c22-976a-22f82badf3da)
- a condicionalidade não será mais somente para os campos obrigatórios, serão coisas independentes. pode haver um campo condicionado a outro, porém não obrigatório. (no print acima o checkbox de obrigatoriedade poderia estar desmarcado e o segundo marcado.

- [x] refatorar a checagem de obrigatoriedade condicional na entidade `Registration`, método `getSendValidationErrors`
- [x] db-update para adaptar os dados legados pra os novos campos, ou seja, pegar todos os campos da tabela, verificar se dentro da coluna condig está condifigurada a obrigatoriedade condicional da maneira antiga e se estiver, popular os novos campos.

**Comment by rafaelchavesfreitas** [comment]
- [ ] corrigir salvamento da edição do campo
- [ ] criar setter (`setConditional($value)` na entidade `RegistrationFieldConfiguration` para quando receber false, definir os valores de `conditionalField` e `conditionalValue` como nulo.
- [ ] ao desmarcar o checkbox `Condicionar a outro campo`, limpar os valores dos campos conditionalField e conditionalValue
- [ ] remover o checkbox 'Ocultar o campo quando não for obrigatório` por não tem mais sentido.
- [ ] refatorar validação da seleção de campo condicionado. os valores dos campos `conditionalField` e `conditionalValue` são obrigatórios quando o `conditional` for true; (acho que a validação deve ser feita perto da linha 525 do arquivo `ng.entity.module.opportunity.js`, refatorando o código existente)
- [ ] refatorar validação da seleção dos campos disponíveis para o avaliador (perto da linha 953 do arquivo `ng.entity.module.opportunity.js`)
- [ ] refatorar função `showField` perto da linha 1598

obs: após as refatorações não deve mais existir nenhuma referência ao `require.condition` no código

**Comment by erleibiazzio** [comment]
Código rodando na branch `feature/fields-conditional`
