### ISSUE TITLE
criar componente para resumo do avaliador

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2563]
- [x] usar o `init.php` para enviar os dados para o js a partir do `$this->controller->requestedEntity` que será o uma instancia do `EvaluationMethodConfiguration`
- [x] estilizar componente
- [x] adicionar informação de avaliações iniciadas

- pendentes: pegar o número de inscrições que o avaliador tem permissão de avaliar e subtrair o número de avaliações (verificar se é necessário a verificação pelo id da registration vs id na tabela de avaliações [ver se o avaliador continua com permissão de avaliar uma inscrição que ele já iniciou porém que não entre mais na regra de distribuição])
- avaliações iniciadas são aquelas com status = 0;
- avaliações concluidas são aquelas com status = 1;
- avaliações enviadas são aquelas com status = 2

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/93379050-cd23-402b-9175-5a26e23264ae)

**Comment by patricknobre12** [comment]
Segue alterações realizadas e link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A81571&t=eJInZHEfFHEBERFO-1

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/cb2f3aa9-8243-4b66-b819-d5166a0a4075)

**Comment by robedj** [comment]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-81428&t=MPbyrDiWhCKS6Bmj-0
