### ISSUE TITLE
base da página de listagem de avaliações do avaliador

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2564]
- [x] criar rota (evaluationsList) no controller EvaluationMethodConfiguration (a rota receberá o id do evaluationMethodConfigurarion, ou seja, o id da fase de avaliação)
- [x] arquivo de visão `evaluatiomethodconfiguration/evaluations-list.php` na pasta views do módulo Opportunities
- [x] utilizar o componente da issue #2563
- [x] se atentar no breadcramb

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/84209ce0-93dd-4b78-912b-92e1b81dc4f3)

http://localhost/evaluationmethodconfiguration/evaluationList/5/
