### ISSUE TITLE
base da página de avaliação

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2577]
link no figma:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-64688&t=X4d8sgYJrbS5PrhS-0

- [x] criar a rota `registration/evaluation` que recebe o id da inscrição (requesteEntity será a inscrição) no constoller `Registration`
- [x] criar arquivo `views/registration/evaluation.php` para implementar o template da página

- [x] se basear na implementação da aba  **ficha de inscrição** da página de acompanhamento de inscrição para a implementação do "miolo" da página: 
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/bbe611e3-4052-459e-8f97-54eab4a06970)

- [x] utilizar embedtools para o formulário de avaliação:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/e153a157-0a40-4713-abbc-c7caa6804653)

- [x] utilizar embed tools para a lista de inscrições que abre ao lado (essa rota ainda não existe, será criada em outra issue):
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/b02b3335-2cc2-4504-9c2d-840efbc79597)

**Comment by rohilario** [comment]
- [ ] Criar componente "sidebar" para a lista de avaliacoes
 - [ ] Aplicar o componente na página e ter como content o embed tools
 - [ ] Estilizar "sidebar" da lista de avaliacoes conforme figma

**Comment by daphnemartinsba** [comment]
Atualmente, a base da tela foi criada e está assim:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/112fd4df-41ab-400b-80f1-ee7b20650fdc)
A estilização será refatorada na issue #2920
