### ISSUE TITLE
Erro na adição de fase de avaliação: Erro aparece sem as datas estarem preenchidas

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2582]
Adicionar uma fase nova, antes de preencher o período de inscrição aparece o seguinte erro:
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/69ef3180-9dfb-4e82-8b55-bcf26163f46b)

![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/01d23820-e826-47f9-8b82-f4b2530c9273)

**Comment by rohilario** [comment]
Ajustado

**Comment by daphnemartinsba** [comment]
Erro não ocorre mais, como mostra a imagem a seguir:
![2582.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/264c5bb1-cb36-4006-b053-658e4c40293b)
