### ISSUE TITLE
ajustes na modal de criação de ocorrência

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2590]
- [x] na modal de criação de ocorrência, listar todos os espaços, não somente os que o usuário tem permissão.
  - para todos os tipos de usuário. 
  - testar com usuário comum e com admin.
- [x] trocar o label do botão "Selecionar outro espaço"  por "Alterar espaço selecionado"

**Comment by rohilario** [comment]
adicionado um permission="" no select-entity, apareceu os espaços de todos os usuários
