### ISSUE TITLE
adicionar link para o espaço na lista das ocorrências do evento

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2593]
- utilizar o componente mc-link

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/d522dabe-7347-4fce-8068-0b0b19d5a1dc)

**Comment by rohilario** [comment]
![image.png](https://images.zenhubusercontent.com/637f6973f98b3957491b149c/c5dace45-6874-4d94-bbf3-8ac350ecfe63)

**Comment by rohilario** [comment]
[Uploading... image.png]
