### ISSUE TITLE
desenhar e implementar as relações pendentes

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2600]
quando um usuário comum adiciona um agente relacionado que ele não tem permissão, o backend vai retornar um status 202, indicando que foi criada uma requisição e enviada a notificação para o proprietário do agente para que aceite a relação. 

- [x] tem que haver um modo de exibir as relações pendentes
- [x] no momento da vinculação, modificar mensagem informando que a relação está pendente.

as relações podem ficar pendentes nos seguintes componente
- [x] nos agentes relacionados
- [x] nos administradores
- [x] nas ocorrências de eventos
- [x] nos avaliadores
- [x] na mudança de propriedade

**Comment by patricknobre12** [comment]
Tarefa concluída e todas relações lista podem ser vistas na grande seção com o link a seguir: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=6009%3A111083&t=32kWlu7yKbz1Eo2Z-1
