### ISSUE TITLE
fazer com que os links dos embedtools abram fora do embed tools

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2609]
- [ ] emitir postMessage quando clicar em links com href. adicionar um evento utilizando o jQuery mesmo no `embedtools.js`
```
$('body').on('click','a',(event) => {
// aqui o this é a tag `a`
// verificar se tem href e se tiver emitir um postMessage
// event.preventDefault
});
```

- [ ] no componente do embed tools, capturar eventos de click no link e redirecionar a página

**Comment by rohilario** [comment]
1 - Adicionar o jquery no embedtools.js; /src/protected/application/lib/modules/BaseV1EmbedTools/assets/js/embedtools.js
2 - Receber no script do v1-embedtools;
/src/protected/application/lib/modules/BaseV1EmbedTools/components/v1-embed-tool/script.js
3 - Fazer redirect com o JS;
