### ISSUE TITLE
Corrigir link de acesso a avaliação na listagem de avaliações

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2613]
## Problema
Acessar o link `http://localhost/evaluationmethodconfiguration/evaluationList/id_da_avaliação/`

Na listagem de avaliações, tanto para o gestor como para o avaliador ao tentar abrir a avaliação, o link acessa a visualização da inscrição e carrega dentro do ifreme Embedtools. Quando deveria acessar em uma nova página a pagina de avaliação

![Peek 20-04-2023 11-09.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7e9182c2-a3a2-4bff-955f-70bcd6a2df76)

## Tarefas 

- [x] Fazer com que ao clicar na avaliação, abra o link de avaliação

- [x] Ao clicar na avaliação a rota correta a ser acessada é a rota `http://localhost/registration/evaluation/id_da_inscrição`

**Comment by daphnemartinsba** [comment]
Link de acesso direciona para a página da avaliação:
![2613.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/073d73a6-04f6-4828-adec-31fab7f657a9)
