### ISSUE TITLE
Refatorar rota POST_saveEvaluation para atender nova estrutura do BaseV2

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2614]
No controller Registration `src/protected/application/lib/MapasCulturais/Controllers/Registration.php`  a rota `POST_saveEvaluation` hoje recebe e seta os status `1 = STATUS_EVALUATED` e `0 = STATUS_DRAFT`.
Na nova estrutura do BaseV2 devemos fazer com que seja possível setar 3 status diferentes neste endpoint

```
0 = STATUS_DRAFT
1 = STATUS_EVALUATED
2 = STATUS_SENT
```

### Regra dos status
O Auto save deve setar o status  `STATUS_DRAFTSTATUS_DRAFT`
Quado o avaliador clicar em salvar e continuar depois, deve ser setado o status `STATUS_DRAFTSTATUS_DRAFT`
Quando o Avaliador clicar no botão Finalizar Avaliação deve ser setado o status `STATUS_EVALUATED`
Quando o Avaliador clicar no botão Enviar Avaliação deve ser setado o status `STATUS_SENT`

Hoje é possível ver essas telas no figma abaixo
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-81571&t=5GPUpQl4Z7KGhpaJ-0

**Comment by erleibiazzio** [comment]
Falando com Rafa, tivemos um comentário para fazer um novo endpoint que faz exclusivamente o envio de uma avaliação.

então criar um endpoint no arquivo `src/protected/application/lib/MapasCulturais/Controllers/Registration.php` chamado `POST_sendEvaluation()`

O endpoint é bem parecido com um outro que esta no mesmo arquivo veja abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/f4e17f71-186b-4ab0-ad02-9a0e69736d68)

Para executar o endpoint, use o link `http://localhost/registration/sendEvaluation/id_da_iscricao

Dentro do endpoint será necessário da entidade usuário do avaliador, na imagem linha 207. No endpoint de exemplo, ele é pego pelo parametro passado na URL já neste endipoint e possível pegar assim

`$user = $app->user;`

**Comment by LimaSystem** [comment]
- [ ] necessário resolver problema da permissão canUserSendEvaluation. ao tentar executar o endpoint como avaliador, endpoint nega a execução devido a não ter permissão.  @rafaelchavesfreitas
