### ISSUE TITLE
Refatorar endpoint de enviar avaliações para enviar somente as avaliações concluídas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2615]
## Problema
Hoje para o avaliador enviar suas avaliações, ele deve primeiro finalizar todas as avaliações de sua responsabilidade e aguardar o termino da fase de avaliação. Com a nova estrutura do BaseV2, temos que possibilitar que o botão enviar esteja sempre disponível, e que quando o mesmo for clicado, seja enviadas somente as avaliações com status `STATUS_EVALUATED` status 1. 

## Tarefas

- [x] Fazer com que o avaliador consiga enviar as avaliações a qualquer momento, sem depender do término da dase ou sem ter que avaliar todas as avaliações.

- [x] No arquivo src/protected/application/lib/MapasCulturais/Controllers/Opportunity.php refatorar o  endpoint `ALL_sendEvaluations` para que o mesmo só faça o envio das avaliações que estão no status 1

### Obs.:
- Dentro do endpoint tem o método `sendUserEvaluations()` é ele quem faz o processo de envio. Dentro dele ele faz um` $app-repo()...` Tentar refatorar neste ponto a busca das avaliações que devem ser enviadas

**Comment by daphnemartinsba** [comment]
endpoint refatorado:
![image](https://github.com/mapasculturais/mapasculturais/assets/75261677/802955c1-15ed-41aa-8b0b-4203db20e167)
Envio de uma avaliação:
![2615.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9010b134-e668-480c-8fd7-c8d707893ae8)
