### ISSUE TITLE
Criar endpoint que reabre uma única avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2616]
## Problema
Hoje existe uma função que possibilita um gestor reabrir as avaliações de um avaliador. Isso faz com que as avaliações de responsabilidade do avaliador, sejam passatas todas para status 1, `STATUS_EVALUATED`. Agora no BaseV2 deve ser possível fazer o mesmo porem com uma única avaliação.

## Tarefa
No arquivo `src/protected/application/lib/MapasCulturais/Controllers/Registration.php` Criar endpoint  `POST_repopenEvaluation()` que possibilite a abertura da avaliação daquela inscrição

### Obs.:
- O endpoint deve somente permitir a reabertura, se a data de avaliação estiver aberta

**Comment by LimaSystem** [comment]
Para executar o Endpoint enviar um post para `http://localhost/registration/repopenEvaluation/id_inscrição/uid:id_do_usuario_avaliador`

OBS.: Para reabrir a avaliação o usuário logado deve ter a permissão reopenValuerEvaluations e avaliações devem esta abertas
