### ISSUE TITLE
Criar rota no EmbedTools para carregamento da listagem de inscrições de suporte

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2619]
## Tarefa

Para acessar a tela de suporte acesse o link abaixo

`http://v1.localhost/oportunidade/id_da_oportunidade/#/tab=support`

Criar nova rota no EmbedTolls  `GET_sopportlist()` que será possível carregar a listagem de inscrições para o agente de suporte. Segue abaixo Imagem da tela

### Imagem da tela
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/14353881-8111-4bfd-8d02-1ee7e017afb6) 

### Imagem do que deve ser inserido no EmbedTools
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e6df4333-c602-4207-b619-46294798199d)

## Obs.: 
Essa tela tem 2 tipos de visualização. Uma que o agente de suporte tem acesso e outra que o Gestor tem acesso. Se atentar para as permissões.
essa verificação de permissão vai ser bem parecida com o que acontece no método `GET_evaluationlist()` do Controller do embedTools. Veja imagem abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7bdc6e55-100b-4612-b4e9-3d7495d8a417)

`Lembrando que a aba de avaliação so aparece para o agente de suporte se ele for do grupo de suporte.`

**Comment by daphnemartinsba** [comment]
As inscrições são listadas para o agente de suporte:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/30db26b9-5286-4226-829c-72a591af466a)

**Comment by daphnemartinsba** [comment]
**comportamento atual:** dado que estou no perfil do gestor (criador da oportunidade), quando acesso a aba de suporte e clico em realizar suporte, então ocorre um slim application error

**Comportamento desejável:**

- [ ] Ao clicar em realizar suporte, gestor deve acessar a lista de inscrições (de mesmo modo que o agente de suporte, como consta na imagem do comentário anterior) 

Imagem do slim application error:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/64352de9-dd9c-42d6-a8f1-0c36543cd826)

**Comment by erleibiazzio** [comment]
O problema estava na checagem de permissões. Fiz alguns ajustes e consegui fazer carregar

**Comment by daphnemartinsba** [comment]
A lista de inscrições está sendo carregada para gestores (quem cria e/ou gere a oportunidade). Mas quando o gestor acessa a ficha de inscrição listada no suporte, ocorre outro slim application error

- [ ] Ao acessar a ficha de inscrição ocorre slim application error

Gif do comportamento:
![2619.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/79d55e9e-e597-4d7e-a347-499dc2f1c267)

**Comment by erleibiazzio** [comment]
Tambem problema de permissão, estava sendo verificado permissão na inscrição e o correto era na opportunidade

**Comment by daphnemartinsba** [comment]
A lista de inscrições está sendo carregada para gestores e eles conseguem acessar as fichas de inscrições.
Contudo, a aba suporte não aparece mais para o agente adicionado no suporte

- [ ] Disponibilizar aba de suporte para o agente de suporte
- [ ] listar as inscrições para o agente de suporte
- [ ] acesso, edição e alteração da ficha de inscrição pelo agente de suporte

Gif do comportamento:
![abasuporte.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1fbaeda2-8618-48cf-8043-40882775899e)

**Comment by Raul-vlb** [comment]
Nos testes, em ambiente local, pontos indicados estão funcionando normalmente.
