### ISSUE TITLE
Padronizar estilo das listagens de inscrições e de avaliações

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2620]
## Descrição do problema

As listagens de inscrições, avaliações hoje pode ser acessada de duas formas, uma pelo gestou e e outra pelo avaliador. Porem o estilização da listagem de avaliação está diferente da listagem de inscrição. Acesse o link `http://localhost/lista-de-inscricoes/id_da_oportunidade/` e compare com o link `http://localhost/lista-de-avaliacoes/id_da_oportunidade/` Veja que os estilos estão meio diferentes.

Para cessar o CSS do arquivo, vá até
`src/protected/application/lib/modules/BaseV1EmbedTools/assets/css/embedtools.css`

## Tarefas

- [x] Na tela de avaliação, ajustar estilo dos links. Ver imagens abaixo
#### Tela de inscrição
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7e5a8304-6ae1-47a5-b6e4-bc055373dc88)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8c6cd295-cf9b-4eb9-9307-507d5e27a92d)
#### Tela de avaliação
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/c61e557e-3e05-4fbb-b78c-be2b66cc5b4b)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/1181b185-ba43-428f-9701-12d110fe7a58)

- [x] Ajustar tamanho do td que é responsável pelo filtro de categoria na cabeçalho da tabela na tela de listagem de inscrição
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7b19fd5e-b110-4e15-864a-d1add66ea4aa)

**Comment by daphnemartinsba** [comment]
Lista de avaliações:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/3b5aed3d-b9a4-4ae3-a991-63248e90ec7b)

Lista de inscrições:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f172ea38-6afc-4989-9e6e-319613330b10)
