### ISSUE TITLE
Correções no formulário de avaliação EmbedTools

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2623]
## Descrição do problema

Acesse o link `http://localhost/inscricoes/evaluation/id_da_inscricao` como avaliador e tente alterar o status da avaliação e salvar. Em seguida atualize a página.

Note também que a mensagem avaliação salva não é exibida quando se clica no botão finalizar e avançar

![Peek 21-04-2023 14-17.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e81a8d3a-1aab-43ee-9842-5a3322b6a67f)

## Tarefas

- [x] Corrigir e fazer com que seja possível selecionar e salvar o status da avaliação no formulário de avaliação

- [x] Fazer com que a mensagem de avaliação salva seja exibida quando clicar no botão finalizar a avaliação

**Comment by daphnemartinsba** [comment]
Mensagem de avaliação salva está aparecendo e botão finalizar avaliação está funcionando:
![salvaravaliação.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a8761373-7bf6-4082-8689-2e620a667c4a)
