### ISSUE TITLE
Implementar sistema de importar/exportar formulário de inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2627]
## Descrição
Existe a funcionalidade de exportar/importar o formulário de inscrição no BaseV1. A funcionalidade basicamente funciona da seguinte forma.
Ao mandar exportar o formulário da oportunidade de ID X ele gera um arquivo.txt com toda a configuração do formulário de inscrição.

Com esse arquivo em mãos é possível carregar o mesmo formulário com todos os campos configurados na oportunidade de ID X na oporunidade de ID Y. Para isso iremos precisar de 2 componentes

Veja no GIF abaixo, como funciona no BaseV1
![Peek 24-04-2023 12-03.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/68af2dbd-be2e-4399-8bce-20f763f37ac0)

## Tarefas

- [x] Desenhar tela para fazer upload de arquivo @patricknobre12 .

- [x] Criar Base do componente `<opportunity-form-import>`

- [x] Criar base do componente `<opportunity-form-export>`

Obs.: Para essa tela ver figma
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-78965&t=U5Ba3v06CXujzcPA-0

O componente import abrirá uma Modal.

**Comment by patricknobre12** [comment]
Pop over de importação de formulário
Figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=6168%3A101246&t=2hmKXa0QIAgt4iDE-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/0bb266b5-5ac6-48e4-9d5d-a42b2179f581)

**Comment by robedj** [comment]
A base dos componentes esta ok, e o estilo ajustado conforme o figma.

**Comment by daphnemartinsba** [comment]
É possível importar e exportar o formulário, na imagem a seguir, o formulário havia sido exportado de uma oportunidade do mesmo ambiente em que foi importado:
![form.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/00ca533a-95a9-43c2-80ed-23768edad4c4)
