### ISSUE TITLE
Criar rota embedTools para o agente de suporte fazer as alterações

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2628]
## Descrição da tarefa
Quando setamos um agente como agente de suporte, ele deve ter acesso a uma tela que ele consiga fazer as alterações nos campos que está liberado para ele. Seria a tela 

Para acessar a tela no BaseV1: `http://v1.localhost/suporte/inscricao/id_da_inscricao` 

A tela é essa que mostra abaixo na imagem.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/28dcdcb6-0f85-4def-b2d8-85db0c2ec50d)

## Tarefa

- [x] Criar rota embedtools que crie essa tela para ser carregado em um ifreme

quermos desta tela, somente essa parte abaixo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/77b61faf-a19e-4562-839c-9bf87be404fb)

Obs.: So deve ter permissão para acessar essa tela, quem for administrador, dono da entidade ou quem estiver no grupo `@support` Para verificar se a pessoa esta no grupo de suporte, checar com método `$entity->canUser('support')` e para ver se é um dono ou administrador use a permissão `@control` `$entity->canUser('@control')`

- E´ provável que o botão salvar teremos que implementar ele no embedTools

**Comment by daphnemartinsba** [comment]
Agente de suporte não consegue salvar as alterações realizadas:
![salvarsuporte.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f8950ca9-5432-4ff8-bb2d-b6535ac9d746)
