### ISSUE TITLE
Corrigir redirecionamento botão de fazer inscrição quando não esta autenticado

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2629]
## Descrição do problema 

Link para ver a tela: `http://localhost/oportunidade/id_da_oportunidade/`

Ao acessar o uma oportunidade sem estar autenticado, o botão de inscrição aparece na tela para fazer inscrição
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/f0e179ae-9dad-43c7-9eb6-627dd7844839)

Obs.:
Verificar se o usuário autenticado é global.auth.isLoggedIn é usuário guest, se for redirecionar para o login.
Para redirecionar usar
```
let url = MapasCulturais.createUrl('auth', '');
 window.location.href  = url;
```

**Comment by robedj** [comment]
Ajuste realizado.
