### ISSUE TITLE
Criar aba de resultados na single de oportunidades

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2632]

**Comment by patricknobre12** [comment]
Feito: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=6176%3A101920&t=2hmKXa0QIAgt4iDE-1

**Comment by daphnemartinsba** [comment]
Layout não pôde ser implementado atualmente por conta do embedTools
