### ISSUE TITLE
QA: Adição da data e hora no panel-last-edited e Rejuste no card

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2634]
@patricknobre12 
- [x] UX: Ajuste da tela para conter data e hora 
- [x] UX: tamanho do titulo mobile e desktop

O Carrosel é ajustado pelo js, como aumenta o tamanho do card do painel e o estilo muda, ele quebrou e precisa refatorar
Substituir um display grid por flex e refatorar as divs pra separar o avatar e o titulo da tag da entidade.
Adiconar data e hora.
Modificado em

**Comment by robedj** [comment]
link do figma atualizado: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717-82908&t=1r0t8iLtRqM122D6-0

- [ ] Ajustar conforme o figma.

**Comment by patricknobre12** [comment]
Alteração realizada
