### ISSUE TITLE
Implementar/Estilizar aba que permite o avaliador acessar as avaliações de sua responsábilidade

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2636]
## Descrição
Hoje no BaseV1, quando um avaliador tem avaliações sobre sua responsabilidade, ao entrar na oportunidade ele tem uma aba que possibilita ele acessar uma lista com todas as suas avaliações. Porem no BaseV2 ao entrar na Oportunidade, nao temos nada para acessar essa tela de listagem. Veja abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/792b092b-8ab7-4b47-a85e-cbd4585c3597)

## Tarefas

- [x] Desenhar tela que possibilite ver a listagem de avaliações

- [x] Implementar aba que carrega a listagem de avaliações na tela de listagem de avaliação
Implementado tela, e aguardando restante do desenho para estilizar e talvez definir outros componente. Para acesso ver link
`http://localhost/oportunidade/id_da_oportunidade/#evaluations`

- [x] Estilizar aba de listagem de avaliações @robedj 
#### Observações
- Para acessar a tela use o link `http://localhost/oportunidade/id_opportunidade/#evaluations`
- Para estilizar seguir figma
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-104734&t=ETX1QFzZbPREpqq0-0

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/1fd1fa9c-1b59-46b6-9200-0493313eaade)

**Comment by robedj** [comment]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-192928&t=ADIVEBUDSxFy9jkl-0
Link atualizado após alteração realizada pelo @patricknobre12

**Comment by robedj** [comment]
Estilização concluída.

**Comment by daphnemartinsba** [comment]
No momento, se o período da avaliação termina, a avaliação permanece na lista de avaliações abertas ou disponíveis:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2f73d338-5a3a-47b4-9133-23ca81789e1d)
Ajustes:
- [ ] Ao término do período de avaliação, a fase deve ser listada abaixo da label Avaliações Encerradas e o texto "Você ainda não tem avaliações encerradas" deve sumir
- [ ] Caso a oportunidade não tenha mais avaliações, ou não tenha mais avaliações abertas ou disponíveis, abaixo da label Avaliações abertas e disponíveis, colocar o texto "Você não tem avaliações abertas ou disponíveis"

**Comment by robedj** [comment]
Para realizar o QA é preciso dar merge na branch baseV2 na develop para atualizar o ambiente de testes.
