### ISSUE TITLE
Criar componente que exiba os dados de resumo dos agentes vinculados a inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2640]
## Descrição

Nas telas onde existe a exibição da ficha de inscrição, temos um CARD que exibe dados do agente responsável, instituição responsável e agente coletivo. Ver exemplo do BaseV1 abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/557b7432-d32e-4642-95c6-d9250aa505d1)

Hoje no BaseV2 existe um Card que traz somente o Agente responsável. veja na imagem abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/af478800-6bb5-45b2-b0ed-0b052e9cb25a)

## Tarefas

- [x] Implementar base do componente `summary-agents` que ira trazer as informações dos agentes vinculados a inscrição.

- [x] Carregar os dados do agente responsável no componente

- [ ] Carregar os dados da instituição responsável no componente

- [ ] Carregar dados do agente coletivo no componente

**Comment by daphnemartinsba** [comment]
- [ ] Os dados da instituição responsável e do agente coletivo não aparecem na ficha de inscrição antes ou após o envio da ficha
Gif do comportamento:
![resumoagentescoletivo.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/50ea65b6-80cc-4ff7-80e7-02dc4b3fc507)
