### ISSUE TITLE
No painel de controle estilizar card de avaliações disponíveis 

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2642]
## Descrição

Quado acessa o painel de controle, e o agente tem avaliações pendentes em sua responsabilidade, o peinel de avaliações aparece porem esta sem estilizar.

## Tarefa

Acesse o link `http://localhost/painel/#main` com um avaliador que tenha avaliações pendentes
Fazer estilização dos cards segundo o figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?version-id=3401015853&node-id=2701-63581&t=kjGJBjzCmlzRnsNu-0

#### Versão figma
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/06078153-4907-47b6-a6f2-3936fe5d769f)

#### Tela atualmente
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/b4390cb3-6db4-402c-b808-c79f5c175516)

**Comment by daphnemartinsba** [comment]
Card implementado:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8490b04b-dcf1-4dde-ac94-26c6e7f901df)

**Comment by daphnemartinsba** [comment]
Atualmente, estão aparecendo avaliações que já encerraram. O fluxo correto é que apareçam somente avaliações disponíveis: que estejam no período vigente e não tenham sido todas enviadas
- [ ] Mostrar somente avaliações que estão no período vigente 
- [ ] Validar fluxo: Não mostrar avaliações que já foram todas enviadas

**Comment by patricknobre12** [comment]
Link para os cards da avaliação ajustados: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11255%3A25685&mode=design&t=DFO34S98tFuRhlR0-1
