### ISSUE TITLE
revisar todas as descrições curtas e longas das singles das entidades certificando-se de que usarm o v-html e de que o white-space:pre-line esteja funcionando

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2644]
em vez disso:
```
<p>{{entity.longDescription}}</p>
```
usar isso:
```
<p v-html="entity.longDescription"></p>
```

**Comment by Raul-vlb** [comment]
todas as entidades estão injetando o longDescription via `v-html`

foi criada uma nova classe `description` disponível nas telas das entidades, para respeitar a quebra de linha nas descrições curtas e longas
