### ISSUE TITLE
QA: Ajustes dos campos da Gestão da oportunidade - Textos explicativos das avaliações

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2647]

**Comment by robedj** [comment]
- [ ] Ajustar os labels e os campos conforme o figma
- [ ] Ajustar os espaçamentos

**Comment by patricknobre12** [comment]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A79112&t=TjoQJurMvOt8ogAB-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/d4d9ebd5-8130-4d20-a6a7-457ec6efd691)
