### ISSUE TITLE
QA - Cards da listagem do evento - diminuir o gap do title e subtitulo

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2653]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/391cb331-5bea-4aa1-9701-3078ec89aa7d)
.entity-card__header.user-details .user-info

gap: 8px

**Comment by patricknobre12** [comment]
Link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A89773&t=WnEJQd8wptMcbhwF-1
