### ISSUE TITLE
QA: Card do espaço

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2654]
- [x] Falta inserir o endereço
- [x] Metadados padronizar fonte para 14px ex: Acessibilidade etc..

**Comment by patricknobre12** [comment]
Link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=4587%3A91057&t=WnEJQd8wptMcbhwF-1

**Comment by robedj** [comment]
Falei com o @patricknobre12 e ele decidiu pela shortDescription e endereço ficarem com 14px, porém tags e outros seguem com 12 px.
