### ISSUE TITLE
Card das oportunidades: ajustar a posição do avatar e titulo

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2655]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/d515134b-222f-45c8-8568-5398d019f69d)
    display: flex;
    flex-wrap: wrap;
    width: 100%;
    align-items: flex-start;
    gap: 0.25rem 1rem;
    justify-content: flex-start;

**Comment by patricknobre12** [comment]
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2717%3A90975&t=WnEJQd8wptMcbhwF-1
