### ISSUE TITLE
Criar componente que faça a navegação entre as avaliações na tela do avaliador

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2656]
## Descrição
Hoje estamos usando um embedtools para carregar a lista de avaliações sob responsabilidade do avaliador. Porem para melhorar o fluxo e também poder trabalhar a questão de estilo, vamos desenvolver novamente usando vuejs.

**Comment by daphnemartinsba** [comment]
Foi implementado o botão "próxima" e "anterior", na página de avaliações, no perfil do avaliador

**Comment by daphnemartinsba** [comment]
Foi implementado o botão "próxima" e "anterior", na página de avaliações, no perfil do avaliador
