### ISSUE TITLE
implementar aba de suporte na single de oportunidade

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2658]
## Descrição
No modo de edição da oportunidade, criar aba que liste as fases e tenha link que leve a tela de suporte. Ver tala abaixo.

- só exibir na lista as fases de coleta de dados (`phase.__objectType == 'opportunity'`)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/f6c22a81-d881-4458-81bb-4d83c497415d)

Seguir desenho do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=6102-101149&t=sDiBRgKsCf0VjzFt-0

## Tarefas
- [x] Inserir no jsObject as fases que o usuário tem permissão de suporte
Obs.: Essa permissão pode ser verificada da seguinte forma `$opportunity->checkPermission('support')`

- [x] Criar um template part que insere a aba e seu conteudo no template. Usar o componente `tab`
Obs.: Caso não existe nenhuma permissão de suporte, no inicio do template part dar um return, fazendo que não seja exibida a aba.

- [x] Listar as fases na tela, conforme o figma, e fazer com que o botão `Realizar suporte` leve ate a listagem de inscrições de suporte conforme imagem abaixo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/ec2d22a1-2c78-4b61-9d8f-c71ff2e41ae8)
Observações desta tarefa.: 
- Essa tela é um embedtools
- Esta tela pode ser vista no figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=6102-101149&t=sDiBRgKsCf0VjzFt-0

- [x] adicionar header como nas páginas de listagem de inscrições:
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/b87a3601-7581-45a0-ae45-86e54e67e9df)

- [x] Criar tela de execução do suporte pelo agente de suporte.

## Dados importantes da issue
- Para acessar o embedtools que carrega a listagem de inscrição de suporte acessar link
`http://localhost/embedtools/sopportlist/id_da_oportunidade`

- Para acessar o embedtools que leva a tela de execução do suporte pelo agente use o link
`http://localhost/embedtools/supporteditview/id_da_inscricao`

**Comment by daphnemartinsba** [comment]
Aba no perfil de suporte:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e7d2725e-c3c1-4827-a4be-af3bea914131)

**Comment by daphnemartinsba** [comment]
**Comportamento atual:** Dado que estou no perfil do criador da oportunidade, quando acesso a aba suporte na single da oportunidade então _o botão realizar suporte fica disponível na fase publicação final do resultado, sendo que essa fase não é uma coleta de dados, e quando eu clico em realizar suporte na publicação final do resultado, ocorre slim application error._

**Comportamento desejável:** O botão realizar suporte deve constar apenas em fases de coleta de dados. Portanto, a publicação final dos resultados não deve aparecer na aba de suporte

- [ ] Retirar publicação final do resultados da aba suporte
- [ ] Validar com @erleibiazzio ou com @rafaelchavesfreitas : Botão realizar suporte deve aparecer somente para coleta de dados

Imagem de slim application error:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e987f808-53ae-48a0-8f2a-47a8afbe48b8)

**Comment by daphnemartinsba** [comment]
A aba de suporte não possui mais a publicação final do resultado. A listagem da inscrição está funcionando corretamente.

- [ ] slim application error na lista da fase de coleta de dados
- [ ] Error ao clicar em voltar na fase de coleta de dados

Gif do comportamento:

![suportecoletadedados.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/61de2d0d-9f2f-4dc8-b7e7-3fc2efa67191)
