### ISSUE TITLE
Estilizar componente mc-side-menu

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2660]
## Descrição
Antes essa tela era carregada via embedtools, porem desenvolvemos a mesma em vue.
#### Hoje a tela esta assim como mostra imagem abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/ccfbcd67-e7f5-4b94-868c-a29808d31cab)

#### Mas deve ficar assim
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/d5f9229f-f3a7-4d2b-90cb-6d3fd641c5bf)

#Tarefa
Aplicar estilização no componente mc-side-menu conforme figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2701-63581&t=w7QpuW6rpssbRaPJ-0

**Comment by robedj** [comment]
@patricknobre12 se puder verificar, segui o mais próximo do figma.
