### ISSUE TITLE
Estilizar ficha de inscrição na tela de visualização da avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2661]
## Descrição
Foi inserido um embedtools que carrega a ficha de inscrição no modo de visualização para que o avaliador possa acessar os dados e fazer sua avaliação. veja iamegm abaixo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/643ec0f9-ba22-4167-90cc-7ed0eb288726)

Veja essa tena no link: `http://localhost/avaliacao/id_da_inscricao`

## Tarefa
Aplicar estilização o maix proximo do figma possivel.

Link para o figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=2701-63581&t=w7QpuW6rpssbRaPJ-0

**Comment by daphnemartinsba** [comment]
A estilização foi aplicada, mas será revisada/refatorada na issue #2920.
Novo layout: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475-153943&mode=design&t=K99yoEMDpsmwL9C9-0
