### ISSUE TITLE
Inseir botão de voltar no header da tela de avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2663]
## Descrição
Acesse o link `http://localhost/lista-de-avaliacoes/id_da_oportunidade/` e entre em  uma das avaliações.
Note que não existe forma de voltar para tela de listagem de avaliação

## Tarefa
Colocar um botão de voltar no header da avaliação para possibilitar navegar entre as tela sde listagem e single de forma fácil pela aplicação.

Ver exemplo do botão no link na imagem abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/71d3e91e-1220-421b-9fdb-b094e7a0327f)

#### Para acessar a tela que deve trabalhar veja o GIF abaixo
![Peek 01-05-2023 10-11.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/57f726e5-1037-4e57-837a-912767ba9b38)

Obs.: 
- No arquivo `src/protected/application/lib/modules/Opportunities/views/registration/evaluation.php` no componente `opportunity-header` existe um slot chamado `opportunity-header-info-end` use ele para colocar os dados

**Comment by daphnemartinsba** [comment]
A tela de avaliação será alterada pela isso #2920 e esse botão será "Sair". Layout: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475-150749&mode=design&t=kA9sQ4okYZRw92od-0
