### ISSUE TITLE
Criar componente de denuncia/contato

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2664]
## Descrição

Hoje, no BaseV1, temos um componente para fazer denuncia ou entrar em contato. Veja exemplos abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/3593b35f-7599-46fa-9471-2a3847e66f58)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/29381279-62e5-4a09-9e20-ed4b1c813859)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/77919a44-e106-4e30-a98c-9aa026082f97)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/695f8d9e-82fd-4056-8023-962b070d4d76)

## Tarefas

- [x] Criar Base do componente de denuncia
No modulo de componentes `src/protected/application/lib/modules/Components` Criar a base do componente `compliant-suggestion`

Para criar essa base, seguir o componete que temos de exemplo no caminho
`src/protected/application/lib/modules/Components/components/__template__`

E também pode  ver o componente `mc-summary-evaluate` que é um componente funcional e com pouco código
`src/protected/application/lib/modules/Components/components/mc-summary-evaluate`. 

Compare os componentes acima citados para fazer seu componente funcionar

- [ ] Estilizar componente segundo figma @robedj 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&t=ylj6fXf3fM9tmYrQ-0

#### Como esta hoje
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/0f7734ef-708a-451a-ad53-2d182fa2c394)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/abda5eab-bd56-47cc-8835-316c560d90e0)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/59f1375e-ee9a-4e64-8c2d-134baef2ed8e)

#### Como deve ficar
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/df90f88f-a489-4c7f-ad22-e2e09f9f5a95)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/b41e623e-412d-478b-90eb-85af43c2746d)

**Comment by robedj** [comment]
link atualizado: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6814%3A144493&t=y9OD3kV2VBB9YLi3-1
