### ISSUE TITLE
permitir vinculação de agente coletivo, instituição responsável e espaço de outros usuários 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2665]
fazer da mesma maneira que foi feito na issue dos agentes relacionados (#2600), mostrando que a relação está pendente
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/88ae116a-de06-4e9a-a791-fe48c06f2854)

**Comment by daphnemartinsba** [comment]
Ao adicionar o agente coletivo e a instituição responsável foi enviada a solicitação para a proprietária, quando a solicitação foi aceita os agentes foram adicionados à inscrição. O espaço enviou solicitação, mas na ficha de inscrição não consta o aviso de solicitação enviada.

- [ ] Espaço aparece na ficha de inscrição como se tivesse sido adicionado sem enviar solicitação, porque não apareceu o aviso ao adicionar ele na ficha, mas solicitação foi enviada.
- [ ] Não foi possível enviar ficha de inscrição, ao clicar em enviar, os agentes somem, ao atualizar a página, eles aparecem novamente

Gif do comportamento do espaço:

![2665.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/4d0647a5-f76b-4a98-85bb-c3ddd9576824)


Gif do comportamento dos agentes: 

![vinculorelaçãoinscricao.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5eb10fad-c2b0-4b95-a420-14e9852701d9)
