### ISSUE TITLE
Ajustar modais de criação, de formulário e de inputs para ocupar a tela inteira 

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2670]
O formato dos modais impossibilita que os usuários criem ou utilizem modais de forma satisfatória. Imagens em anexo ilustram a questão.
- [x] Ajustar no figma o tamanho dos botões
- [x] Ajuste na versão de produção baseado no 
- [x] Em modais de criação e modais de input, ajustar para tella inteira 
Regras: 
- Modais de formulário e input de dados devem ocupar a tela
- Modais de confirmação **NÃO** ocupam a tela inteira
- Modais que eram popovers **NÃO** ocupam a tela inteira
figma
**No testes:** 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ce14b131-766f-4fba-8692-515ae2410a32)

**No figma**
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/458355d1-d66d-4629-b563-900bc5b67317)

**Comment by robedj** [comment]
link atualizado:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=3909-84633&t=xLsr9weZAl421wTH-0

**Comment by robedj** [comment]
As modais de criaçao já estão em full screen @patricknobre12
