### ISSUE TITLE
Ajustar formatação do texto do bloco de oportunidades na home mobile

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2671]
Os textos desse bloco devem ser ajustados de acordo com a largura da tela, mas estão assim, com o texto quebrado: 

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/4d4c1c71-b603-4ee7-a452-68dc3a930ef0)

**Comment by robedj** [comment]
Ajuste realizado.
