### ISSUE TITLE
Ajustar modais de confirmação de acordo com o figma no mobile

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2675]
No testes tá assim: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ad0f48e0-644d-4654-8433-2fb2e004d7e2)

Mas no figma é assim: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/bf43db39-8dcc-43ba-a66c-5a919dd5918e)

**Comment by robedj** [comment]
Ajustes Realizados
