### ISSUE TITLE
fazer a avaliação documental fucionar no embed tools

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2679]
utilizar postMessage para a comunicação entre os 2 iframes

**Comment by daphnemartinsba** [comment]
A utilização do postMessage: https://github.com/mapasculturais/mapasculturais/commit/ded60fd716a7ac9defd31e48e791b7f4631cdbec
Funcionamento da avaliação documental:
![2679.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/995ba417-66a8-448b-93d5-29569b3f4d91)
