### ISSUE TITLE
Fazer os botões de manipular as avaliações executem suas respectivas ações na tela de avliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2684]
## Descrição
Na tela do avaliador, os botões da imagem abaixo não estão executando as ações que devem. 

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e1d86421-7ab5-49f1-a742-c989e252d12d)

## Tarefas
- [x] Botão `Finalizar avaliação` deve salvar e setar a avaliação com status `evaluated`

- [x] Botão `Salvar e continuar depois` deve salvar e setar a avaliação com status `draft`

- [x]  Botão `Reabrir avaliação`  deve salvar e setar a avaliação com status `draft`

- [x]  Botão `Envia avaliação`  deve salvar e setar a avaliação com status `send`

- [x]  Fazer logica de exibição os botões

**Comment by daphnemartinsba** [comment]
- [ ] Botão Salvar e Continuar depois não está salvando:
[Uploading... 2684.gif]
