### ISSUE TITLE
Ajustar modal de área de atuação na finalização de cadastro

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2687]
Está com o visual bugado, como mostra o print abaixo: 

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/83c7442f-5440-4f3d-8693-39299b10ecfc)

**Comment by robedj** [comment]
Esse ajuste ja foi realizado anteriormente

**Comment by robedj** [comment]
O erro na verdade é na parte de filtragem - no botão filtrar ao selecionar área de atuação na versão mobile.
