### ISSUE TITLE
No cadastro de agentes inserir campos que não estão listados

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2715]
No cadastro do agente, sentimos falta de alguns campos.

- [x] Comunidades tradicionais
- [x] Não encontrou sua comunidade Tradicional
- [x] Pessoa com Deficiência
- [x]  Escolaridade
- [x]  Agente Itinerante
- [x]  Pessoa idosa
- [x]  Implementar issue 2722

**Comment by daphnemartinsba** [comment]
Campos implementados na edit:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/17c6fb8b-0273-4a5a-a82a-de10894fa44b)

Campos implementados na single:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/79462515-80e6-4153-a12f-c5fe23afcd9a)
