### ISSUE TITLE
Ajustar tela do formulário na visualização mobile

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2716]
A tela de formulário está estranha como mostra o print abaixo. Parece que alguns elementos estão maiores que a resolução da tela. Segue print: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/b1bf4114-85a1-4081-a8a0-d922754dc910)

**Comment by Raul-vlb** [comment]
Ajuste feito na issue #2714
