### ISSUE TITLE
Implementar tela de visualização dos campos do agente

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2722]
## Tarefa

- [x] Desenhar tela de visualização dos dados @patricknobre12 

- [x] Fazer com que os campos dos agentes sejam exibidos no modo de visualização. @robedj 
Segue figma com tela desenhada para exibição do modo de visualização

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7043-143241&t=411RIqQqU8tnJa6k-0

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/483b79cc-3c6d-4a37-a411-4498284e93de)

#### Observações.: 
- Os campos sensíveis, devem ser exibidos somente para para o dono do agente e para administradores 
- Pode ser que no figma não tenha todos os campos necessários, sempre confrontar com o BaseV1 para garantir que todos os campos mínimos que lá são exibidos, também sejam exibidos no BaseV2

**Comment by patricknobre12** [comment]
Atualização: telas foram inseridas no documento. 
Obs: os elementos mostrados nas telas são apenas exemplos e podem ter mais ou menos dados. 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7043%3A143241&t=zYHIrxYcWy0mCEfP-1

**Comment by daphnemartinsba** [comment]
Single para usuários comuns ou visitante (sem login):
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/3dc05f51-f6b0-4907-9850-ddd9e08ea45a)
Single para admins ou dono:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/77dc6311-7aa2-4ce1-8350-b41a9ce46a45)
