### ISSUE TITLE
Colocar botões lado a lado em modais de confirmação

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2724]
Os modais de confirmação estão com o seguinte layout: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/44b14edb-a3b9-4548-ad6e-5d608e1b2dac)

Ajustar os botões como no print abaixo, deixando eles lado a lado
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/459f6104-822a-4676-bc4b-feac952dae3c)

**Comment by robedj** [comment]
Ajuste Realizado.
