### ISSUE TITLE
Ajustar como os cards de notificações aparecem no painel

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2725]
Como mostrado na imagem abaixo, os cards estão sem margem à direita
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/0168478c-8832-4c8b-979b-24e6c0eeb70d)

É só colocar uma margem a direita que nem a margem esquerda.

**Comment by robedj** [comment]
Ajuste Realizado
