### ISSUE TITLE
corrigir estilização das imagens dos selos relacionados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2729]
- [x] na listagem das buscas
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/447a78d5-9782-4051-a5b9-5662c6f39dd7)
- [x] na single e edit das entidades
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/27ebbc01-4438-43f3-8710-a6e875285f88)
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/e2161da7-f5e2-4990-834b-0b5481ff39a4)

**Comment by robedj** [comment]
Ajuste realizado
