### ISSUE TITLE
Erro ao visualizar uma entidade recém criada

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2734]
## Descrição
Ao criar uma entidade usando o modal de criação rápida, quando clica em `Completar informações` Quando esta logado como usuário comum a tela de edit não é carregada.

Obs.: Pode ter relação com pcache.

**Comment by rafaelchavesfreitas** [comment]
era por causa do pcache mesmo, a solução foi criar o pcache para o usuário autenticado no momento da criação da entidade, não só enfileirar a entidade para a recriação do pcache em background.
