### ISSUE TITLE
Corrigir erro na aba de relatórios para oportunidades sem fase de avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2735]
## Ao tentar carregar a aba de relatórios de uma oportunidade que não tenha fase de avaliação, o embedTools retorno o erro abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/16c94b81-21dd-4cbc-9fa8-fada4f3633cc)

**Comment by daphnemartinsba** [comment]
Em uma oportunidade com uma inscrição e sem fase de avaliação, a publicação do resultado final na aba relatório consta como na imagem a seguir:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a786f1cd-d220-4474-ab61-b823487fa253)
