### ISSUE TITLE
Criar botões da timeline de acompanhamento da inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2736]
- [ ] Botão "Abrir formulário" em fases de coleta de dados

- Critério: a fase tem que terminar 'naturalmente': não pode concluir a fase editando a data para um horário e dia que já passou.

- [x] Botão de Recurso

**Comment by rafaelchavesfreitas** [comment]
em determinadas situações o botão preencher formulário aparece na primeira fase após o envio
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3460205a-41cc-403c-97ee-eb3883e0da53)

**Comment by daphnemartinsba** [comment]
A questão do botão Preencher Formulário aparecer na timeline foi resolvida na issue #2865

**Comment by daphnemartinsba** [comment]
- [ ] Preencher formulário em fases de coleta de dados

- Critério: a fase tem que terminar 'naturalmente': não pode concluir a fase editando a data para um horário e dia que já passou.

**Comment by daphnemartinsba** [comment]
Para que o recurso fique disponível:

- o recurso precisa ser configurado
- a fase deve ser publicada
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/88af7fab-cbab-4e3d-ab3e-dc35e124a1e3)
