### ISSUE TITLE
Implementar botão de enviar avaliações fora do embedtools e remover o botão do iframe

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2739]
- Inserir botão ao lado de baixar avaliações
![image](https://github.com/mapasculturais/mapasculturais/assets/39862175/31abf27d-36c2-482b-813b-a7979f1b7156)

- Remover os componentes abaixo

![image](https://github.com/mapasculturais/mapasculturais/assets/39862175/dd773cda-18f4-4ead-bde4-17de9bc6984a)

Obs.:
- O endpoint deve recarregar a contagem de inscrições no resumo do mc-summary-evalute. Caso não seja possível fazer via ajax dar reload na página
-  Talvez pegar o a permissão canUserSendEvaluation() da oportunidade e passar ela para o evaluationMethodConfiguration e na oportunidade fazer a checagem da configuração da avaliação

**Comment by daphnemartinsba** [comment]
Como somente o avaliador visualizará o botão enviar avaliação e somente o gestor terá acesso ao botão baixar lista de avaliações, os botões não poderão ficar lado a lado. 
Botão enviar avaliações foi posicionado no mesmo lugar em que fica o botão baixar lista de avaliações:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/54889985-b968-40bc-a17c-9802075679cd)
