### ISSUE TITLE
Corrigir erro de permissão ao tentar enviar a inscrição como usuario comum

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2744]
## Descrição
Ao fazer a inscrição como usuário comum e tentar enviar a inscrição, retorna erro de permissão.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7a7ed045-db52-4aab-9026-926392ce0d5f)

**Comment by rafaelchavesfreitas** [comment]
duplicada
