### ISSUE TITLE
Refatoração da aba avaliação nas oportunidades

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2748]
A Aba Avaliações na oportunidade que contém o componente opportunity-phase-evaluation deve ficar conforme o estilo:
do figma, seguindo a ideia das Minhas avaliações:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-192928&t=ZmYzZ72T4WAYHd3b-0
- [x] Retirar Stepper Vertical
- [x] Background da página mc-gray-100
- [x] adicionar avaliações disponiveis e encerradas

**Comment by daphnemartinsba** [comment]
componente consta como no figma:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/0c0d2e70-cbbe-4c35-80d9-6220a531723b)
