### ISSUE TITLE
Criar EmbedTools que possibilita ver a pré-visualização do formulário de inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2750]
## Descrição

Quando criamos uma oportunidade e configuramos o formulário de inscrição, durante a implementação do formulário é possível visualizar uma prévia do formulário para que possa testar as condicionalidades e comportamento do mesmo. Veja Print's abaixo de exemplo do BaseV1

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/ff466529-7c51-46e3-9660-d61992dd0cb0)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/0c593d7e-73b8-4da0-9811-bce342abffa8)

Para ver essa tela no BaseV1 use o link 

`http://v1.localhost/inscricoes/preview/opportunityId:id_da_oportunidade/`

## Passo 1
- [x] Implementar um embedtools com nome `GET_registrationformpreview` que possa ser carregado esse template part de visualização no BaseV2 via iframe
Obs.:
- ja existe um endpoint que faz isso no BaseV1 e lá ja tem o render de uma view. veja print abaixo do arquivo
`src/protected/application/lib/MapasCulturais/Controllers/Registration.php`
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8eb22e95-fde9-4403-96bf-58ae126d2aa5)

- A área que precisa estar no embedTools é a do print abaixo
- ![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7f81f2ad-403f-4863-a900-273ab87a5007)

- [x] Carregar tela de visualização no BaseV2 com o embedTools utilizado

## Passo 2 @Raul-vlb 
- [x] Estilizar Tela de pre-visualização do formulário  da rota `http://localhost/embedtools/registrationformpreview/id_oportunidade`

- [x] Inserir botão na tela de configuração do formulário para visualizar a pré visualização do formulário 
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/68ec98a9-0c47-44bd-8bdc-e00815028131)

Ver como deve ficar o botão no figma 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-104733&t=Q8h80IOYalFkT8Dp-0

#### Observação do comportamento do botão `Visualizar`
- Ao clicar no botão, deve-se ir para uma rota de visão nova, que irá exibir como uma pre-visualização  de como o formulário será exibido para o proponente. Essa visão deve ter a aparecia de uma ficha de inscrição. Ver print abaixo.
!![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/278093bc-4f9f-4bfa-a409-185ddf45653f)

- Os Botões de ação devem ser exibidos também porem não devem executar ação alguma.

- Tirar Base da edit da inscrição para elaborar a tela, a tela sera basicamente a mesma porem será uma tela apenas de exemplo não executa ação nenhuma

**Comment by daphnemartinsba** [comment]
Dado que as Categorias do formulário foram configuradas, quando clica em visualizar, então, a página de visualização do formulário é carregada com um erro.
Gif do comportamento atual:
![2750.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/da53ad63-3b51-4e8c-ab33-991af53c1a0f)
