### ISSUE TITLE
Criação do componente de avatar pra ser reutilizado no Base V2

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2752]
Cria componente de avatar com todos os tamanhos disponiveis no Figma:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=1038-22161&t=JbTaqE0P5DvIkVDT-0

**Comment by cesardelucca** [comment]
@patricknobre12 para essa tarefa ser realizada precisamos que conste apenas os tamanhos dos avatares que serão utilizados no v2. Hj temos 8 tamanhos no figma. Iremos utilizar todos esses tamanhos mesmo?
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=208-4602&mode=design
Após definir e atualizar o figma, marque o @robedj nessa tarefa, por favor.

**Comment by patricknobre12** [comment]
Atualização e padronização dos tamanhos dos avatares. Segue link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=1038%3A22161&mode=design&t=CE7F2bpOhaYoXWDw-1

**Comment by erleibiazzio** [comment]
- [ ] Criar componente `entity-avatar`
- O componente deve receber 2 props `entity` que receberá a entidade que irá ser carregada o avatar e `size` que definirá o tamanho do avatar a ser carregado.
- O componente deve sempre verificar se existe imagem de avatar vinculado a ela, se não existir inserir imagem padrão da entidade
