### ISSUE TITLE
Evitar que a data de publicação de resultado final, seja anterior as datas da fase de inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2756]
## Descrição
Hoje é possível setar a data de publicação de resultado anterior ao término de inscrição, quando isso ocorre, não é mais possível criar fase de avaliação. ver GIF

![Peek 19-05-2023 16-08.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e783b739-5dfd-45dc-a92b-277df44a4310)

**Comment by rafaelchavesfreitas** [comment]
o ícone do datepicker está aparecendo em todos os campos com erro
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/3c9d1522-9c60-4815-944a-b211a9889fa6)
