### ISSUE TITLE
Inserir nova opção no campo Pessoa com deficiência

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2759]
## Descrição
Atualmente só é positivável setar algum tipo de deficiência no campo, porem se a pessoa não for deficiente não existe uma opção `Não Sou` para definir.

## Tarefa

- [x] Inserir no arquivo agent-types.php a opção `Não Sou` no metadado pessoaDeficiente. como mostra exemplo abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/579d2f5e-056b-405e-a0c9-c9efed99b101)

**Comment by daphnemartinsba** [comment]
Metadado inserido no commit https://github.com/mapasculturais/mapasculturais/commit/faf7d57cfe1260affbe106e10ab8ef5207e1342a:
![image](https://github.com/mapasculturais/mapasculturais/assets/75261677/a612152c-ffe6-46a1-9d08-322f1bce7be7)
