### ISSUE TITLE
Na criação do formulário, campo do tipo `Título da seção` tem como inserir Opções 

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2761]
## Descrição
Ao criar um formulário, se você optar em inserir um campo do tipo `Título da seção` aparece um text-area para setar opções. Ver GIF abaixo

![Peek 22-05-2023 18-53.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/ce916be3-1cab-4f60-8579-e7ee90ce3e6e)

## Tarefa

- [x] Remover o text-area que aparece, pois este tipo de campo não tem opções

**Comment by daphnemartinsba** [comment]
O campo título de seção não possui mais o textarea de opções:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7e352a22-ee5c-4322-913c-29ca2d4d75e0)
