### ISSUE TITLE
Implementar tela de tratamento de exceções e tratamento de erros

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2764]
## Descrição
Hoje quando tentamos acessar uma pagina que não tempos permissão ou uma tela que não existe, no BaseV1 caímos em uma tela que exibe a mensagem de Página não encontrada. No BaseV2 somos redirecionados a tela abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/0695b3c5-a44e-46d9-b05b-d7312b90fc11)

## Tarefas

- [x] Desenha layout da página no figma
- [x] Implementar layout da página conforme figma 500, 403 e 404

Obs.: 
- Para acessar as telas siga os passos abaixo.
1) vá ate o arquivo `compose/local/config.d/0.main.php` e sete o `APP_MODE` para production como mostra imagem abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/222e18f2-7363-49ae-87ca-5d62efccee85)

2) para acessar a tela de permissão Faça login com usuário comum, tente edtitar o lagente saassAdmin, Segue link abaixo. 403
`http://localhost/edicao-de-agente/ (outro agente que nao tenha permissão de editar)`

3) Para acessar a tela de página nao encontrada usar link abaixo 404
`http://localhost/oportunidade/86ghk/#info`

4) Segue abaixo as views que carregam essas telas
`src/protected/application/themes/BaseV2/views/site/error-403.php` e `src/protected/application/themes/BaseV2/views/site/error-404.php`

-Seguir Figma abaixo
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=2717-92363&t=MjOZeuSbcja3CR8y-0

**Comment by robedj** [comment]
As telas foram padronizadas após reunião e foram realizados os ajustes no frontend.

Figma atualizado: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6786-136188&t=Pt4mCONq4ONpsYCP-0

**Comment by rafaelchavesfreitas** [comment]
conferir o link do botão
