### ISSUE TITLE
Com usuário comum não é possível enviar a inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2767]
## Descrição
Ao fazer uma inscrição, preencher o formulário e tentar enviar a inscrição, acontece um erro que impede o envio. Ver GIF Abaixo.
![Peek 23-05-2023 11-30.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/52f0a2ef-7ad1-4123-9b65-a7e97dc20dbd)

## Tarefa

- [ ] Verificar erro de permissão que ocorre ao tentar enviar

**Comment by Raul-vlb** [comment]
Não consegui reproduzir esse erro
