### ISSUE TITLE
Implementar botão para exibir resumo/parecer da avaliação na timeline

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2772]
O comportamento e que quando clicar no botão abre uma modal que mostra o comentário que o avaliador inseriu na avaliação
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7ddd9037-a58c-45a2-9950-7d9699ce2b67)
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/26d5578d-767b-4279-8478-ed637852b12c)

Seguir Figma abaixo para implementar
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-104732&t=9QTFnniiaAvHAUbQ-0

**Comment by erleibiazzio** [comment]
Implementado método para devolver o resumo da avaliação.

Para usar seguir passos abaixo.

```
$registration = $this->controller->requestedEntity;
 $evaluationMethod = $registration->getEvaluationMethod();
 $summary = $evaluationMethod->getEvaluationSummary($registration);
```

O Retorno de `$summary` deve ser algo como abaixo.

```
 [
     "consolidated_result" => "10.00",
     "type" => "Avaliação Técnica",
     "value_to_string" => "10.00",
     0 => {#6763
       +"id": 29585,
       +"evaluation_data": {#6778
         +"c-1685482874603": "10",
         +"obs": "Parecer técnico do avaliador",
       },
       +"avaluator_id": 17362,
       +"avaluator_name": "Avaliador 1",
       +"status": "10",
     },
   ]
```

Em `$summary->evaluation_data`Deve conter os dados de todas as avaliações separadas por avaliador

**Comment by rafaelchavesfreitas** [comment]
já foi feito
