### ISSUE TITLE
Não exibir administradores ou agentes relacionados pendentes para quem não tem permissão de editar a entidade

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2787]

**Comment by daphnemartinsba** [comment]
Dado que o login não foi realizado, ou foi realizado em um agente com permissão comum,  foi possível visualizar grupo de agente ou administrador com requisição pendente em nenhuma das entidades: projetos, agentes, espaços, eventos e oportunidades.
Conforme exemplificado no gif abaixo:
![2787.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/65d5e0f2-85c8-448f-b18d-9ba647b0bb8b)
