### ISSUE TITLE
Remover o campo tipo de seção da lista de campos condicionados

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2789]
## Descrição
Quando estiver criando o formulário e for condicionar um campo a outro. o campo do tipo `Título de seção` esta aparecendo e não deveria ver GIF abaixo.

![Peek 26-05-2023 19-07.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8235ab54-318a-49f2-89fc-c85cd5c5710f)

**Comment by rafaelchavesfreitas** [comment]
já foi feita
