### ISSUE TITLE
Ajustes na tela de avaliação - Tela do avaliador

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2794]
- [x] Fazer com que o sidebar esquerdo fique com a altura alinhada com o direito
- [x] Fazer com que o sidebar esquerdo, quando se trata de uma resolução fullhd `1920`, já venha expandido
- [x] Fazer com que o sidebar esquerdo e direito fique sempre próximo ao header ao scrollar a ficha. O comportamento de ser flutuante se mantem porem sempre fixo proximo ao header.
- [x] Colocar o sidebar esquerdo alinhado com a ficha de inscrição, com mesma margem que existe no sidebar direito
- [x] Remover scroll horizontal do sidebar esquerdo 

Ver abaixo print
![photo_2023-05-29_11-55-13.jpg](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8ea3d306-5869-47ad-a8e6-818f5370f856)

![photo_2023-05-29_11-57-26.jpg](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/f69b5eb7-88c1-44a7-aeeb-ee6c105973a9)

**Comment by erleibiazzio** [comment]
O Scroll esquerdo ainda continua aparecendo. Remover tambem o scroll horizontal do lado direito

## Lado esquerdo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/abf0eefe-8aee-4c9b-9940-273170ca1fd5)

## Lado direito
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/2346a1cf-858c-4f0b-9da1-792bb8aac7ee)

**Comment by daphnemartinsba** [comment]
Os pontos levantados nessa issue está em andamento na issue #2920
