### ISSUE TITLE
Ajustes na single da oportunidade (inscrições)

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2796]
Atualmente a tela da single está assim: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/37f26b5f-e708-4340-9213-f141ce84b19d)

Alguns ajustes devem ser feitos: 
- [x] Ajustar espaçamentos do elemente do período de inscrições como no print abaixo
![image 238.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/1086ed62-f040-40a4-a2d5-ed9279559444)

- [x] Ajustar como aparecem a seleção do agente e da categoria da inscrição no mobile como no figma: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/839d7def-a4eb-446b-8448-ed9e2b2c6491)

**Comment by robedj** [comment]
Ajustes realizados
