### ISSUE TITLE
revisar fluxos de publicação de resultado

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2797]
- [ ] Quando publica o resultado final, sem publicar o resultado da fase, a aba “resultados” fica disponível na single da oportunidade mas sem listar inscrições
- [ ] É possível publicar o resultado final antes do término das inscrições e da avaliação, mas só é possível publicar resultado da fase após o término da fase
- [x] Após publicar resultado da fase é necessário atualizar a página para que o botão despublicar substitua o botão publicar
- [x] Validar: quando publica somente o resultado da fase a aba resultados não fica visível e o proponente não tem acesso ao status da sua inscrição
- [ ] quando publica a fase e o resultado final, ainda assim, a inscrição não é listada na aba resultados

**Comment by daphnemartinsba** [comment]
- [ ] Quando publica o resultado final, sem publicar o resultado da fase, a aba “resultados” fica disponível na single da oportunidade mas sem listar inscrições:

![2797-1.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/18027dbf-26eb-4d62-9893-714440f834ef)

- [ ] É possível publicar o resultado final antes do término das inscrições e da avaliação, mas só é possível publicar resultado da fase após o término da fase:

![2797-2.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/591f3503-29bf-47bb-b311-9dd21516afad)

- Validado: quando publica o resultado da fase o proponente tem acesso ao status da inscrição na aba acompanhar:
![2797-4.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f94b3cde-82e1-4056-a4da-1857b485c9b4)
- Após publicação do resultado da fase **não** é necessário atualizar a página para aparecer que o resultado foi publicado.
- [ ] quando publica a fase e o resultado final, ainda assim, a inscrição não é listada na aba resultados:

![2797-3.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/57f0a4c4-50c9-4812-ac91-9534ed8a77e4)

**Comment by daphnemartinsba** [comment]
Retorno da issue #2493:
- [ ] Não foi possível publicar resultado da fase final automaticamente:

![#2493.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/608b194f-564d-4f15-9056-36e0ec6732c5)
