### ISSUE TITLE
Corrigir exibição da localização indevidamente no mapas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2798]
## Descrição 
Quando se define no perfil do agente para não exibir a localização. Não deveria exibir a localização para pessoas não autorizadas. Porem mesmo assim esta sendo exibido o PIN no mapa. E também quando não existir endereço definido, não deve ser exibido o PIN.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/0110e9b9-f735-45c6-ab5e-97590c3dc6f3)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/46d30d55-ca23-4e83-9c37-218848bbf2d3)

**Comment by Raul-vlb** [comment]
Comportamento é o esperado

Apenas administradores podem visualizar localizações privadas
