### ISSUE TITLE
Ajustar modal do elementos de filtragem

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2800]
Como na imagem abaixo, não tá aparecendo nem o título do modal, nem botão de fechar esse modal (Verificou-se que está para todas as filtragens de todas as entidades)
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/13fd12c3-0f2d-4a4d-a010-9813d832f374)

**Comment by daphnemartinsba** [comment]
- Filtros Eventos:

Classificação etária (feito):

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/235f1a96-cf89-4a9d-970a-13a8bae62cb3)

Linguagens (feito):

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/847555aa-5a5e-48f6-93e1-29f5b19c0cd5)

Espaços:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a7cb126b-8d69-4c22-ba3a-c68bec562e77)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/427f8d5e-80f3-4795-9a2c-265f7ee07e94)

Agentes:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6b80e35b-b5df-43da-973a-14988378547b)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f053b36a-446b-42c0-a466-a89203b70dd7)

Oportunidade:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6ff93c36-7b9c-4e91-bade-cbabeb43587e)

**Comment by daphnemartinsba** [comment]
Projeto:
- [ ] Colocar título do tipo do projeto: "Selecione os tipos"

Imagem atual:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/3ea7dc69-6303-4c2b-89be-920235be150f)

**Comment by robedj** [comment]
Ajuste Realizado

**Comment by daphnemartinsba** [comment]
Projeto: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/600cbc24-2538-4397-9821-0ee014ffd5b9)
