### ISSUE TITLE
Ajustar padding das modais de input de dados

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2801]
Ajustar o padding dos modais de input para serem mais semelhantes ao figma (esse ajuste é mais visual)
Segue print abaixo com os ajustes esperados: 
![image 241.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ce757e5c-e457-4cde-b302-1ba708b04aa9)

**Comment by robedj** [comment]
Ajuste realizado.
