### ISSUE TITLE
Corrigir exibição da quantidade e eventos proximos no PIN dos eventos no mapas

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2805]
## Descrição
Na tela de busca de eventos, quando o PIN do mapas não mostra a quantidade de espaços próximos. ver print abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/9f263a89-9ba6-4ec1-a846-8b0480b6eddb)

Veja o Exemplo em agentes, aparece quantos agentes existem ao ali proximo a marcação do PIN
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/4450478e-04ad-4e61-adaf-4f1bcd4b2734)

**Comment by daphnemartinsba** [comment]
PIN está mostrando a quantidade de espaços (com eventos) próximos:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fd24bb5d-5c00-4c21-92ac-6ca0ff3dd8d0)
