### ISSUE TITLE
Ajustar estillo do formulário de avaliação documental

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2806]
## Descrição
Ao acessar a tela de avaliação documental como avaliador, a tela fica com alguns detalhes quebrados. veja prints Abaixo

##### Antes de avaliar
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/3d5ad56a-a0fb-461f-b308-a7368f47be37)

##### Após avaliar
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/b79be073-342d-4295-9770-fb8ac1da3152)

## Tarefas

- [x] Ajustar os check-box do formulário que ficam quebrados no momento de avaliar
- [x] Remover scroll horizontal após enviar a avaliação e estar no modo view do embedtools

**Comment by daphnemartinsba** [comment]
Formulário de avaliação não quebra ao avaliar e após a finalização da avaliação, a avaliação realizada não possui scroll. Conforme consta no gif abaixo:
![2806.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2972be49-fdcd-483b-bb57-c4844bb5aa76)
