### ISSUE TITLE
correções na página de visualização de avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2807]
- [x] endpoint `findEvaluation` não está retornando as inscrições
- [ ] o resumo das avaliações está ficando sem as informações
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/4f2d4265-9ef4-4d91-b2f8-dd0142b02b6b)

**Comment by daphnemartinsba** [comment]
O resumo de avaliações lista corretamente as avaliações pendentes, concluídas e enviadas, contudo:

- [ ] Resumo de avaliações duplica avaliações iniciadas. Ex: ao salvar uma avaliação e continuar depois, o resumo diz que duas avaliações iniciaram.
Gif do comportamento:

![2807v.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a9ac2744-80f5-4eff-9568-f619485b10fd)
