### ISSUE TITLE
Não é possível pegar o ownerEntity na single da oportunidade

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2809]
## Descrição
O ownerEntity não esta sendo retornado no entity.owenrEntity

**Comment by daphnemartinsba** [comment]
É possível pegar ownerEntity da oportunidade:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2592219d-3559-4f69-953d-f554ba8624d0)
