### ISSUE TITLE
Entidade relacionada não aparece no header da single de entidade

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2810]
## Descrição
Na single de oportunidade deve ser mostrado o nome da entidade relacionada como mostra o figma abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/41a4d0dd-4ed0-4fe1-835f-5194b90ceb90)

## Tarefa

- [x] Fazer com que o header exiba a entidade relacionada conforme figma abaixo
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782-172916&t=tWATAXHioak1DRpl-0

**Comment by daphnemartinsba** [comment]
Header exibe a entidade na qual a oportunidade foi vinculada. Exemplificado na imagem abaixo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d5b127ac-925d-4825-ac9d-ea4143b0b6d7)
