### ISSUE TITLE
Corrigir problema no campo pessoa com deficiência no formulario de inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2812]
Campo PCD impede a inscrição de ser enviada + quando marca não sou em PCD no agente responsável, a informação não é salva

**Comment by daphnemartinsba** [comment]
O preenchimento do campo pcd não barra mais o envio da inscrição.

- [ ] O preenchimento na ficha de inscrição está diferente da edit do agente: Validar qual o comportamento adequado. 

- No agente: É possível marcar mais de uma opção ao mesmo tempo, exemplo, "visual" e "auditiva", mas ao marcar "Não sou" desmarca as demais opções. 

- Na ficha de inscrição: é possível marcar todas as opções ao mesmo tempo.

Gif do comportamento:

![2812.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/26ec4eb3-d7bc-456e-a649-a5a946261f94)
