### ISSUE TITLE
Ajustar tamanho do título dos cards de oportunidades da home 

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2813]
Ajustar título para tamanho de **18px**; a imagem abaixo mostra o estado atual, que tá grande: 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/f8563cff-9671-4471-a01d-f6a10ae79d6e)

**Comment by robedj** [comment]
Ajuste Realizado
