### ISSUE TITLE
Corrigir estilo na tela da ficha de inscrição após a mesma estar enviada

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2818]
Avatar da oportunidade fica em cima da aba acompanhamento

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/318ffd4c-4a47-4fe1-a9ee-0e5d8936b266)

**Comment by robedj** [comment]
Ajuste realizado
