### ISSUE TITLE
Definir posição inicial da lista de avaliações no mobile

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2820]
Hoje a mesma esta sobre pondo alguns componentes na tela de avaliação. 

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/0566b672-7d80-4b7e-8dc9-abee6ebb2ad6)

**Comment by patricknobre12** [comment]
Fiz uma proposta, mas precisa ser validado: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8126%3A147704&t=yFGrBZbSz151xT88-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/70d93ceb-b5d8-470f-93dd-2dd1955ee116)

**Comment by patricknobre12** [comment]
Fiz uma proposta, mas precisa ser validado: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8126%3A147704&t=yFGrBZbSz151xT88-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/70d93ceb-b5d8-470f-93dd-2dd1955ee116)

**Comment by patricknobre12** [comment]
**Definição realizada**
segue link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782%3A192363&mode=design&t=8whMQn744hM5z6M2-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/a44397fe-9f12-4ac1-8b1f-cfaa2d73b3ec)

**Comment by daphnemartinsba** [comment]
A posição inicial da lista de avaliações:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e4ec8282-cc16-456d-8d8d-e593577bad80) 
Foi criada a issue #2900 para tratar da responsividade da lista quando aberta
