### ISSUE TITLE
tornar o status e o parecer da avaliação simplificada como obrigatórios

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2822]
hoje é possível finalizar a avaliação sem ter avaliado.

#### Obs.:
A estrutura de avaliação já tem um método que faz validação de erros, `getValidationErrors()`.
Ver exemplo no Metodo de avaliação `EvaluationMethodQualification`  Arquivo `src/protected/application/lib/modules/EvaluationMethodQualification/Module.php` na linha 22.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/578a3c1d-d025-439a-ba45-4438224f41aa)

Basicamente é retornar um array com os erros encontrados e o sistema já irá exibi-los

**Comment by daphnemartinsba** [comment]
No momento eles são obrigatórios, a avaliação só é salva quando o parecer é preenchido: quando não preenche o parecer aparece um alerta e a avaliação não é salva:
![2822.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ad11ade8-8df8-437d-886f-f76425aeca24)  
![2822part2.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/efb8c177-124d-4b3c-9f7e-7ae9db3c9ac2)

- Comportamento do botão finalizar e avançar e botão enviar agora será resolvido na #2880
