### ISSUE TITLE
Bloquear formulário de avaliação após o avaliador finalizar a mesma

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2823]
## Descrição  
Hoje a avaliação tem 4 status possíveis.

`null = quando ainda não esta avaliada`
`0 = Quando o avaliador salva a avaliação parcialmente para continuar depois`
`1 = Quando a pessoa avaliou e não enviou a avaliação de forma definitiva, que da a possibilidade de reabrir a avaliação para voltar a editar`
`2 = Quando a pessoa enviou definitivamente a avaliação sem possibilidade de editar novamente`

## Tarefa
Quando o avaliador clicar no botão `Finalizar a avaliação`, status 1,  o formulário deve ficar em modo de visualização como mostra print abaixo
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/6c36b22a-2764-4460-836d-918583ccd8cf)

Se ele precisar editar a avaliação, ele deve clicar em `Reabrir avaliação` para que consiga a ter acesso ao modo de edição novamente

**Comment by daphnemartinsba** [comment]
Após finalização da avaliação, o formulário é bloqueado, quando reabre a avaliação ele fica disponível novamente. Conforme gif abaixo:
![2823.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ed5a8add-53bb-45fc-8401-06cded51e392)
