### ISSUE TITLE
Na tela de avaliação verificar querys que fazem a soma do resumo de avaliações e fazer nome do avaliador aparecer no header

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2824]
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/1b2750cc-853d-48be-a870-fe0325dc9aee)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8074156f-1176-4084-9961-0ecfe0f80f88)

**Comment by Raul-vlb** [comment]
Não consegui reproduzir em testes no ambiente local.
A contabilidade nos resumos estão acontecendo de forma esperada.
