### ISSUE TITLE
desenhar alterações no configuração das fases

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2826]
- [x] passar as configurações de limites de inscrições, que estava dentro da página de configuração do formulário, para a aba "configurações das fases" (isso é para TODAS as fases de coleta de dados)
- [x] passar a configuração de categorias, que hoje está na página de configuração de formulário, para a aba de "configuração das fases" (isso é SOMENTE para a primeira fase)

**Comment by patricknobre12** [comment]
Links para a configuração de fase: 
ajuste na primeira fase: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8016%3A147481&t=rilcJ9DI7qUtBItR-1

ajuste em fase de coleta de dados genérica: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8016%3A147612&t=rilcJ9DI7qUtBItR-1

Link para a configuração de formulário: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8016%3A148160&t=rilcJ9DI7qUtBItR-1

**Comment by daphnemartinsba** [comment]
As alterações ja foram implementadas:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d7d98def-30b2-4fd1-bdbe-10cb8288ff7d)
