### ISSUE TITLE
Corrigir redirecionamento ao clicar no botão voltar na aba de avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2830]
### Descrição
Quando a gestora está dentro da inscrição avaliada e clica em voltar, é direcionada para a aba inscrições e resultados dentro do modo de edição, mesmo que tenha acessado a lista de avaliações pela aba avaliação na single. ver GIF

![Peek 12-06-2023 10-51.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/84f606b8-6799-421a-a059-8ab048435003)

### Tarefa
Fazer com que seja redirecionado para a listagem de fases de avaliação.
`http://localhost/oportunidade/id_oportunidade/#evaluations`

**Comment by daphnemartinsba** [comment]
Pelo perfil de gestão, o botão voltar volta para aba de avaliações da single, como mostra o gif a seguir:
![2830.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8394d8fa-033c-4a15-ab1c-b301e9715f1e)
