### ISSUE TITLE
estilização do componente de configuração de categorias da oportunidade

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2831]
- [x] renomear componente para `opportunity-category`
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/98ac7d06-ca4d-49aa-8678-41b3de398525)

**Comment by robedj** [comment]
Ajustes realizados

**Comment by daphnemartinsba** [comment]
No commit https://github.com/mapasculturais/mapasculturais/commit/ad02a23dfb0ca9a58c2e3308e6d75ffd93a1a831:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/481ae9e9-0f49-4bcb-a2c5-cbc4ef47e41f)
O componente de categorias:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b92d62fb-27a4-483d-85b9-c81baef4d951)
