### ISSUE TITLE
Fazer com que o entity-fied interprete os campos multiselect e permita a seleção de vários campos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2834]
Ver exemplo do campo pessoa com deficiência

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/48b5f72c-87c2-45ad-9a09-cd0a60f7efd4)

**Comment by daphnemartinsba** [comment]
As alterações foram realizadas no `entity-fields`, como exposto no commit https://github.com/mapasculturais/mapasculturais/commit/53c8899b8f1e766ef5a48702e05155b78a90c7f0
Ao utilizar o multiselect do campo de pessoa com deficiência, é possível marcar mais de uma opção:
![campomultiselect.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5798abce-88bb-49a1-b5af-df10fff6a32f)
