### ISSUE TITLE
[Oportunidade - Lista de avaliações] Solução de Slim application error na lista de avaliações após publicação do resultado

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2843]
Jornada: **como** avaliador **quero** acessar as avaliações realizadas após seu envio **para** revisar a consistências das informações por motivos de recurso

**Comportamento atual**: Após publicação do resultado de uma fase de avaliação, quando o perfil do **avaliador** acessa a lista de inscrições ocorre slim application error na lista de avaliações, conforme a imagem abaixo. Será realizada uma **solução provisória**, pela issue #2842.  

**Solução:**

- [x]  resolver o slim application error e apresentar a lista de avaliações avaliadas pelo avaliador

**Comment by erleibiazzio** [comment]
De fato o erro ocorria devido a verificação de permissão. Quando o resultado não esta publicado, é verificado se o avaliador tem a permissão `evaluateRegistrations` porem essa permissão apos a publicação retorna sempre false. Fiz uma verificação dentro do embedTools para que verifique se o agente tem permissão de visualização `viewEvaluations`

**Comment by daphnemartinsba** [comment]
Após o encerramento do período da fase de avaliação, ao acessar a lista de avaliações, a lista consta disponível, conforme apresentado no gif abaixo:
![2843.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5b26cbfd-9c66-46ad-851c-9516c4263bbb)
