### ISSUE TITLE
[Oportunidade - Configuração da avaliação] Não é possível excluir o avaliador de uma fase

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2844]
Jornada: **como** gestor **quero** excluir um avaliador das configurações de avaliação **para** apagar da interface as avaliações realizadas pelo avaliador 

**Comportamento atual:** Ao tentar o gestor **não consegue excluir o avaliador da configuração**. 

**Comportamento desejado:**

- [x] Devo conseguir excluir o avaliador da configuração da oportunidade 
- [x] Ao excluir o avaliador, na lista de avaliações, a listagem de inscrições para aquele avaliador também deve ser excluída
- [x] Validar @rafaelchavesfreitas : deve ser excluído mesmo? e se sim, deve ou não serem excluídas da planilha?  
 

Gif do comportamento atual:
![excluiravaliador.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8ca58c03-a8d3-4e01-a651-97ca867cc65e)

**Comment by erleibiazzio** [comment]
Resolvido o problema da avaliação, porem a exibição dos dados na planilha depende dos dados da lista de avaliações, como a mesma é deletada não existe de onde tirar as informações então vai remover  também da planilha

**Comment by daphnemartinsba** [comment]
É possível excluir o avaliador antes da realização das avaliações. Como mostra o gif abaixo:
![excluiravaliador2.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/0b1c2906-0927-45be-9fc9-f282d324c6fe)

Não é possível excluir o avaliador após o envio das avaliações:
![excluiravaliadoraposavaliação.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/25a8e169-34cb-4a93-ad92-47076b70f976)
