### ISSUE TITLE
[Oportunidade - Avaliações] É possível enviar avaliação após publicar o resultado da fase 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2845]
Jornada: **como** gestora **quero** que não seja possível o envio de avaliação após publicação **para** que avaliadores não achem que enviaram a avaliação sendo que o sistema não armazena a informação de envio quando fora do prazo  

**Comportamento atual:** após a publicação do resultado é possível enviar a avaliação, contudo, a avaliação permanece constando como não enviada no painel do gestor

**Comportamento desejável:** 

- [ ] após término da fase de avaliação, ao clicar no botão enviar avaliação deve emitir um alerta justificando a impossibilidade do envio OU o botão enviar avaliação não deve ficar disponível

**Comment by erleibiazzio** [comment]
verificado e não é possivel mais enviar a avaliação após a fase publicada
