### ISSUE TITLE
[Oportunidade - Publicação de fases] Criação de fase de avaliação com resultado publicado

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2846]
Jornada: **como** gestora **quero** excluir uma fase publicada e criar uma nova fase **para** realizar novas avaliações

**Comportamento atual:** Ao excluir uma fase de avaliação que já foi publicada, sem despublicar antes da exclusão, quando cria uma nova fase, essa nova fase já vem com o resultado publicado.

**Comportamento desejável:** 

- [ ] Ao criar uma nova fase de avaliação, ela não deve ser criada como publicada
- [ ] Uma fase só deve ser publicada após o clique no botão publicar resultado

**Gif do comportamento atual:**
![criaçãodefasepublicada.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5858c062-cd52-4770-a450-77b11f7aa8cc)

**Comment by daphnemartinsba** [comment]
- [ ] As avaliações realizadas na fase excluída passam para a nova fase:
![excluirfasemantemavaliaçõesaoadicionarmesmoavaliador.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/20e74c41-1fbd-4999-8149-254a3684a0aa)

![excluirfasecontinuaçãostatusdehabilitaçãonasimplificada.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/4168228e-89b6-442a-9099-b1ef22d30163)

**Comment by rafaelchavesfreitas** [comment]
- [ ] não permitir deletar fase já publicada
- [ ] não permitir deletar fase de coleta de dados que possua avaliadores

- fazer a validação no PHP no `canUserRemove`

**Comment by daphnemartinsba** [comment]
Não é possível deletar fase publicada:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/e2c1c8b0-f2ad-4b75-beed-a7e4b2658d6e)
Não é possível deletar fase que possua avaliações:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/69e5f7d1-8c31-40d0-baba-bfa8eb2f25c4)
