### ISSUE TITLE
[Oportunidades - Avaliação Técnica] Não é possível realizar avaliação técnica 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2847]
Jornada: **como** avaliador **quero** atribuir as notas previstas no edital **para** realizar e finalizar a avaliação em uma ficha de inscrição 

**Comportamento atual**: Ao acessar a página de avaliação de uma inscrição para avaliar, o campo de nota configurado na gestão da oportunidade não fica disponível para inserção de nota, nem o campo para justificar o parecer e ainda, ao habilitar  o criterio de exequibilidade, ele vem pré-setado como inválida.

**Comportamento desejável:**
- [x] Validar @daphnemartinsba : A página de avaliação deve conter os campos para entrada de dados numéricos conforme os itens, critérios e sessões configuradas na configuração da avaliação técnica
- [x] Validar @daphnemartinsba: O campo de exequibilidade deve conter a possibilidade de escolher uma opção entre duas: habilitada ou inabilitada
- [x] Validar @daphnemartinsba: A inabilitação da exequibilidade deve atribuir o status inválido para a ficha de inscrição automaticamente
- [x] Validar @daphnemartinsba: Deve conter um campo de texto para emissão do parecer 

Segue imagens da configuração da avaliação técnica:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/578385a7-a7d1-49d9-8a7c-3e97133416d0)

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/0a252f20-d318-4227-95e8-0b8783151862)

Imagem da página de avaliação pelo perfil do avaliador:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/aa7e832a-37a5-4125-9a7d-3d180e0ed896)

**Comment by erleibiazzio** [comment]
Fiz o teste na mesma oportunidade que comenta.... ID 107.  E tudo funcionou. Podemos parear para alinhar?

## Passos que executei.
1) Entrei com admin@local e defini as datas de avaliação e inscrição para ficarem em período vigente, 'Aberto'
2) Fiz uma inscrição com meu perfil `Erlei`
3) Acessecei com usuario afaliador definido usando o usuario e senha abaixo.
Usuário: daphne+teste@hacklab.com.br
Senha: Senha@123

Abaixo GIF dos comportamentos finais.

![Peek 19-06-2023 13-31.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/210602e9-1111-4639-aeae-ae1d9727ebc1)

**Comment by erleibiazzio** [comment]
Ajustar Estilo do embedTolls da tela de avaliação no SideBar direito.

### Descrição
Após a o avaliador enviar a avaliação, o formulário fica em modo de visualização e essa tela esta com layout quebrado.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8bdd076b-9b69-4700-8248-b20103e3c605)


## Tarefa

- [ ] Ajustar alinhamento dos textos do formulário de avaliação Após a mesma ser finalizada pelo avaliador.

**Comment by daphnemartinsba** [comment]
Alinhamento do texto foi ajustado, conforme consta a imagem abaixo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cbc6b4a9-48cd-4a8b-b8bc-d127a65acc8c)
