### ISSUE TITLE
[Oportunidade - Avaliações] Texto explicativo das avaliações não aparece para avaliador

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2849]
Jornada: **Como** criadora de uma oportunidade **quero** escrever uma mensagem de orientação **para** os avaliadores utilizarem como guia na hora de avaliar as inscrições 

**Comportamento atual:** Dado que uma criadora da oportunidade configurou um texto explicativo para o avaliador, quando o avaliador acessa a ficha de inscrição para avaliá-la _o texto não aparece em nenhum lugar_

**Comportamento desejável:** Dado que uma criadora da oportunidade configurou um texto explicativo para o avaliador, quando o avaliador acessa a ficha de inscrição para avaliá-la _o texto deve ficar disponível_ 
 
Imagem da configuração do texto em uma avaliação documental:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/dd48aae9-c6c8-4505-913c-e2f023f1b25a)

Visualização do avaliador:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cd15420c-2f8b-48cc-b2b9-e5262eb59bbe)

**Comment by erleibiazzio** [comment]
Fiz carregar o texto definido na configuração pelo gestor, porem devemos deixar ele melhor estilizado. Não encontrei no figma estilo para essa caixa de texto. Segue abaixo como ficou.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/79174060-b832-44b9-b443-a01a77971f2c)

Acho que vale repensar esse ponto pois se trata de um embedTolls e a avaliação documental ja carrega um texto bem grande por padrão. ver no print abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/9394acb0-71bd-41ef-9b6d-cc8aa173fe8d)

**Comment by daphnemartinsba** [comment]
- [ ] @patricknobre12 desenhar tela/fluxo do modal do texto explicativo das avaliações

**Comment by patricknobre12** [comment]
Seguem os ajustes: 
link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8492%3A149872&mode=design&t=hbxalZ8reYZoeOZ1-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/cd5205c3-9dde-4576-8335-19336c86a415)

**Comment by daphnemartinsba** [comment]
Quando a categoria configurada no campo dos avaliadores não existem, o avaliador consegue ter acesso a lista de inscrições, mas não consegue visualizar nenhuma inscrição, portanto:
- [ ] Validar fluxo: Impedir avaliador de ter acesso à aba de avaliações OU impedir gestor de configurar uma opção inexistente na configuração da distribuição de inscrições para o avaliador 
Comportamento:
![2849 part2.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/7d0a2f94-dcbd-42d2-bce6-c51f06139f97)
- Validado: o texto explicativo das avaliações ficam visíveis para o avaliador
![2849.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1c733e40-aeb9-4afa-98b7-bed1c917eae0)

**Comment by Raul-vlb** [comment]
A questão da distribuição das avaliações serão adicionadas no BaseV2, quando forem implementadas as funcionalidades fora do embedtools.
