### ISSUE TITLE
[Oportunidade - Configuração da avaliação] Implementar a funcionalidade Reabrir Avaliações 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2850]
**Jornada:** **Como** gestor (criador da oportunidade) **quero** reabrir as avaliações **para** o avaliador retificar uma avaliação que já foi enviada

**Comportamento atual:** Dado que o avaliador enviou as avaliações, quando o gestor acessa a aba configurações da fases e expande a configuração da fase de avaliação, então, no lugar onde o avaliador consta adicionado _não há o botão reabrir avaliações_.
O que quer dizer que depois que o avaliador enviou todas suas avaliações, o dono da oportunidade não consegue reabri-las

**Comportamento desejável:** Dado que o avaliador enviou as avaliações, quando o gestor acessa a aba configurações da fases e expande a configuração da fase de avaliação, então, no lugar onde o avaliador consta adicionado _deve ficar disponível um botão "Reabrir Avaliações"_  

- [x] @robedj - Implementar botão "Reabrir Avaliações"
- [x] @Raul-vlb - Quando o gestor clicar em "Reabrir Avaliações" o avaliador deve conseguir realizar as avaliações e e ter acesso ao botão "Enviar Avaliações" novamente: executar endpoint POST_reopenValuerEvaluations()

**Comment by patricknobre12** [comment]
Ajuste realizado
link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8260%3A147532&t=5eEMQw5nIdI7x4Ee-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/ecb4ea89-954e-43f3-9efb-80cdf80e84e3)

**Comment by robedj** [comment]
O Botão reabrir avaliações já existe.

**Comment by daphnemartinsba** [comment]
- [ ] As avaliações constam como reabertas, mas não é possível reavaliá-las:
 ![2850.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/653ddbf2-a26f-4d03-affc-bbf44d71c1f9)

**Comment by Raul-vlb** [comment]
Após os testes, foi constatado que está tudo funcional.

porém, é necessário seguir a regra do prazo de inscrição estar aberto para o formulário abrir em modo de edição.
