### ISSUE TITLE
[Oportunidade - Multifases] Avaliador não consegue acessar aba avaliações após criação da segunda fase de avaliação

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2852]
**Comportamento atual:** dado que estou no perfil do avaliador, e sou avaliador da primeira fase, quando o gestor adiciona uma segunda fase de avaliação, _a aba "avaliações" some_ 

**Comportamento desejável:** dado que estou no perfil do avaliador, e sou avaliador da primeira fase, quando o gestor adiciona uma segunda fase de avaliação, _o avaliador deve ter acesso a aba avaliações e o botão de acessar a lista de avaliações de ambas as fases_

**Comment by daphnemartinsba** [comment]
Fluxo: criou oportunidade -> criou a primeira fase avaliativa -> criou segunda fase avaliativa -> realizou inscrição -> realizou e enviou avaliação -> alterou a data da inscrição e da primeira fase avaliativa para encerrá-las -> alterou a data da segunda fase avaliativa para ficar em andamento -> avaliadora parou de ter acesso a aba
Foi reproduzido o mesmo comportamento da criação da issues:
![avaliadornãoconsegueveraaba.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/56171776-dd6c-4dd7-b645-760ec12c107a)

**Comment by erleibiazzio** [comment]
Após testes, verificamos que o fluxo estava OK e funcional. Porem percebemos que existia um problema na alteração de datas futuras para datas presentes e criamos a issue #2882

**Comment by daphnemartinsba** [comment]
- [ ] Avaliador não consegue acessar a aba avaliações se for avaliador **somente** da segunda fase
Quando o avaliador é avaliador da primeira e da segunda fase, ele acessa a aba avaliações, como apresentado no gif abaixo:
![avaliadorsóacessaabaavaliaçõesnasegundafaseseéavaliadordaprimeira.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/44fbebef-d8dd-46b4-90e2-dfbde3849c03)

**Comment by daphnemartinsba** [comment]
Acesso às duas fases:
![Captura de tela de 2023-07-18 15-44-40.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/76567c78-8d39-4d1f-b275-5710fa2bce53)
Acesso à primeira fase avaliativa:
![Captura de tela de 2023-07-18 15-45-20.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/cb306a0d-7b3b-494f-899b-e823473628e0)
Acesso à segunda fase avaliativa:
![Captura de tela de 2023-07-18 15-44-55.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5e21ed9c-16ef-4c4f-be4e-22ff6f6f04a4)
