### ISSUE TITLE
[Cadastro do Agente] É possível inserir mais de 400 caracteres na descrição curta

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2854]
**Comportamento atual:** 
Cenário 1: dado que estou criando minha conta, _quando eu preencho a descrição curta com mais de 400 caracteres, o sistema aceita e eu consigo criar minha conta, e meu agente fica com a descrição curta com mais de 400 caracteres_

Cenário 2: dado que o gestor utilizou campos @ do agente responsável na criação do formulário, e que estou preenchendo minha ficha de inscrição, _quando preencho descrição curta com um mais de 400 caracteres, o sistema aceita, então, consigo enviar minha ficha de inscrição e a descrição curta do meu agente fica com mais de 400 caracteres_

**Comportamento desejável**: 

- [x] Barrar preenchimento de descrição curta com mais de 400 caracteres na criação de conta
- [ ] Barrar preenchimento de descrição curta com mais de 400 caracteres no preenchimento dos campos @ na ficha de inscrição

**Comment by daphnemartinsba** [comment]
Preenchimento da descrição curta na criação de conta:
![2854.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8be99b7f-706d-486d-8937-60120442f69b)

- [ ] Barrar preenchimento de descrição curta com mais de 400 caracteres no preenchimento dos campos @ na ficha de inscrição

**Comment by robedj** [comment]
O plugin MultipleLocalAuth não estava atualizado. Só permite a inserção na criação de conta com 400 caracteres. Não é colocado no video os demais caracteres. Somente os 400.

**Comment by robedj** [comment]
No campo @ da descrição curta @erlei seguirá numa validação do backend
