### ISSUE TITLE
[Oportunidade - Relatórios] Botão imprimir não direciona para a página de impressão

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2858]
**Jornada:** **Como** gestora (criadora da oportunidade) **quero** baixar um pdf com os relatórios **para** apresentar a relação de dados preenchidos pelos proponentes em um edital

**Comportamento atual:** **dado** que estou na aba relatórios, dentro do modo de edição de uma oportunidade com inscrições, **quando** clico no botão imprimir, **então** ocorre o direcionamento para uma página em branco

**Comportamento desejável:** **dado** que estou na aba relatórios, dentro do modo de edição de uma oportunidade com inscrições, **quando** clico no botão imprimir, **então** ocorre o direcionamento para a página de impressão, onde um pdf contendo os gráficos pode ser salvo na máquina local

Gif do comportamento atual:
![relatorio.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/822e7e82-d0fd-44b5-917e-16355d6eebdc)

**Comment by rafaelchavesfreitas** [comment]
será resolvida com a estratégia descrita na #2971
