### ISSUE TITLE
[Oportunidade - Header] Alterar label da entidade relacionada

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2859]
**Comportamento atual**: o label consta como "OPPORTUNIDADE DE:"
 
Conforme na imagem abaixo:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c60cbc55-dc25-4b09-9922-8ce34112ec61)

**Comportamento adequado:** o label deveria ser a entidade à qual a oportunidade foi vinculada. 

- [x] [Alterado - ver comentário]Se a entidade for um projeto, deve ficar "Projeto: GT". Se a entidade é um espaço deve ter ficado "Espaço: GT". Se a entidade é um evento deve ter ficado "Evento: GT". Se a entidade é um agente deve ter ficado "Agente: GT".

**Comment by robedj** [comment]
Atualização da issue:
@patricknobre12 atualizará o figma com a seguinte alteração:

"Vinculado com" + "Entidade": "Nome da entidade"
Ex:
"Vinculado com Espaço: Espaço Caverna do dragão"

**Comment by daphnemartinsba** [comment]
Vínculo com Espaço: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/fe56af06-1cab-423c-9ba6-ffd870e3cf34)
Vínculo com Evento:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/38c79651-453a-491f-bb30-cc09b8982a2a)
Vínculo com Projeto:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/ccb5d2bb-b37e-4f86-aa53-f8330dcfae82)
Vínculo com Agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/bb8be785-8248-4604-8c81-879e794eb737)
