### ISSUE TITLE
[Oportunidade - Multifases] Informações da ficha de inscrição da coleta de dados não carregam

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2862]
**Jornada:** **Como** proponente **quero** preencher o formulário de uma fase de coleta de dados **para** enviar a inscrição e ser avaliado 
 
**Comportamento atual:** **dado** que está dentro do prazo da fase de coleta de dados, **e** que está na página de acompanhamento, **quando** clica em preencher formulário, **então**, a ficha de inscrição não é carregada
 
**Comportamento desejável:** **dado** que está dentro do prazo da fase de coleta de dados, **e** que está na página de acompanhamento, **quando** clica em preencher formulário, **então**, a ficha de inscrição deve ser carregada para o preenchimento, por parte do proponente

Gif do comportamento atual:
![2862.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/da759904-25f7-4ed3-a7b8-8733bacbc47d)

**Comment by daphnemartinsba** [comment]
- [ ] Preencher formulário não está disponível para proponente durante fase de coleta de dados:
 ![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8397af79-f1b5-4099-8da5-db7b2d17f360)

**Comment by daphnemartinsba** [comment]
Para validação: é necessário esperar o término da fase para que o job seja rodado e o botão fique disponível, ou seja, a data de término não pode ser alterada para finalizar a fase de coleta de dados.

**Comment by rafaelchavesfreitas** [comment]
@daphnemartinsba esperar o término da primeira fase e o início da segunda.
