### ISSUE TITLE
[Oportunidade - Formulário] opção "não sou" do campo pessoa com deficiência não desmarca as demais opções 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2863]
**Comportamento atual:**
- No agente: É possível marcar mais de uma opção ao mesmo tempo, exemplo, "visual" e "auditiva", mas ao marcar "Não sou" desmarca as demais opções. 

- Na ficha de inscrição: é possível marcar todas as opções ao mesmo tempo.

**Comportamento desejável:**

-  O preenchimento na ficha de inscrição deve ser igual ao preenchimento na edit do agente. 

- [ ] Na ficha de inscrição, deve ser possível marcar mais de uma opção ao mesmo tempo, exemplo, "visual" e "auditiva", mas ao marcar "Não sou" desmarca as demais opções.

Gif do comportamento do agente:

![2812.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/26ec4eb3-d7bc-456e-a649-a5a946261f94)

**Comment by erleibiazzio** [comment]
Testado, e verificado que ja foi implementado
