### ISSUE TITLE
Ocultar botão Preencher formulário na timeline de acompanhamento

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2865]
## Descrição
Após o envio da inscrição, quando cai na tela de acompanhamento, mesmo depois da inscrição enviada aparece o botão de preencher formulário. Ver print abaixo.

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/9b450604-2012-436e-8811-47628875b021)

## Tarefa
O botão não deve ser exibido se a inscrição estiver enviada.

**Comment by daphnemartinsba** [comment]
Ao enviar a ficha de inscrição e clicar em acompanhar, o botão preencher formulário não fica mais disponível:
![2865.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/94b53f3c-2808-4962-81d9-32f86ec2c291)
