### ISSUE TITLE
Correção nas tags na exibição das singles

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2867]
Corrigir espaçamento das tags nas singles, está quebrado:
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/3672bb44-25aa-49b3-859b-84211039118f)

**Comment by robedj** [comment]
Correção Realizada.

**Comment by daphnemartinsba** [comment]
Evento:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1abc515e-bf08-487a-bc74-0f3dc91906d0)
Agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/3954341d-5ca7-4184-a679-7ecffae683da)
Projeto:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/87fcd080-9ec6-4205-b92f-dd0d3a3912b1)

- [ ] Espaço está sem área de atuação na single:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c30737f5-1115-4008-a72b-84d08de54d45)

**Comment by robedj** [comment]
Espaço corrigida exibição e sem espaçamento:
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/7a098132-ce8e-4d59-a29c-24c02020f02c)

**Comment by robedj** [comment]
Tags na single do espaço - Resolvida:
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/9b4ecc12-4a88-4029-8705-2dd904f2ba3a)

**Comment by robedj** [comment]
Evento exibindo tags sem espaçamento na single ![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/d15a8ba6-cdfe-4e63-a27d-925db9902361)

**Comment by robedj** [comment]
Projeto exibindo tags
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/8aa2ff38-61e6-4f9f-a1ea-aba53a86c385)

**Comment by robedj** [comment]
Agente coletivo exibindo tags corretamente e com estilo sem espaçamento
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/228706ce-28aa-4b6b-9b86-f0bd42270a77)
Agente individual  exibindo tags corretamente e com estilo sem espaçamento
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/f97eb5a6-e005-4887-ae2d-a74cc2329f67)

**Comment by robedj** [comment]
Agente coletivo exibindo tags corretamente e com estilo sem espaçamento
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/228706ce-28aa-4b6b-9b86-f0bd42270a77)
Agente individual  exibindo tags corretamente e com estilo sem espaçamento
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/f97eb5a6-e005-4887-ae2d-a74cc2329f67)

**Comment by robedj** [comment]
Correções realizadas.
