### ISSUE TITLE
[Oportunidade - Inscrições e resultados] Estilização das notificações (alert) e do componente de publicação de resultados

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2874]
Link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=2717-78002&mode=design&t=GAfBEySahuFZ8B5j-0
Atualmente o componente está assim:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/70de99fe-e751-4a93-b97e-202172e8ac31)

Ele deve ficar assim:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/19b85afa-4953-42a6-addc-12c88162d2a3)

**Comment by robedj** [comment]
@patricknobre12 atualizou esse estilo no figma:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8383-149070&mode=design&t=qVNJik9FvyNg3qh7-0

**Comment by robedj** [comment]
Os ajustes solicitados nessa issue foram realizados porém ficam algumas sugestões:

Essa issue envolvia a publicação de resultados, com isso, foram realizados ajustes em configuração de fases, implementou-se props para identificar aba nas chamadas dos componentes no opportunity-subscribe, alguns componentes são reutilizados em vários passos do stepper tanto na aba de configuração de fases como na aba de inscrições e resultados, além disso, dois componentes foram criados pra solucionar esse problema, onde um funciona para a exibição das opções de publicação na configuração e outro na publicação de resultados.

- Mapear os principais pontos de melhoria e bugs encontrados no fluxo das oportunidades na configuração de fases
- Mapear os principais pontos de melhoria e bugs encontrados no fluxo das oportunidades na inscrições e resultados

  - Criar issues específicas pra evitar sobrecarga da issue, pra gerenciar melhor o trabalho e poder ser executado em paralelo, também para o tratamento dos erros.

**Comment by daphnemartinsba** [comment]
- [ ] O check box deve ser suprimido:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/617fec22-e0c9-4411-9edb-bf0441525374)

- [ ] Os textos devem ser adicionados conforme o figma:

- No caso da publicação não ter sido configurada e já deu o término da fase:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/18efc70b-cef7-45ae-897f-baafe9390a70)

- No caso da publicação ter sido configurada e já deu o término da fase:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/159d948d-14e4-4a0f-a559-8bb941fc37a0)

- No caso da publicação não ter sido configurada e ainda não deu o término da fase:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/680b94c1-6cce-4db7-a2f4-227c04612c0a)

- No caso da publicação final ter sido configurada e ainda não deu o término da oportunidade:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/d8e6bde4-5912-4bb0-af6c-90a05a9d1f76)

**Comment by patricknobre12** [comment]
Nova atualização da issue e dos alertas: 
Como foi conversado, os alertas aparecem enquanto a fase for corrente (durante a data de início e fim da fase, **confirmar isso com erlei**). Segue prints e links abaixo: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8383%3A149070&mode=design&t=3HM49Mk7I9Bl2aZw-1

![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/07d798b7-62fa-449e-a750-f37989fbe2e0)

**Comment by robedj** [comment]
Sobre a ultima fase de Publicação do resultado no stepper:
o @patrick.nobre e ele vai precisar redesenhar a ultima fase do stepper a publicação de resultados
O estilo está quebrado pois seguimos mudando essa tela toda em outras issues.
