### ISSUE TITLE
[Cadastro de Agente] Mapa aparece na single sem endereço preenchido

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2878]
Dado que estou logada em um usuário comum ou que não realizei meu login, quando acessa a single de um agente que não possuo permissão de edição e cujo endereço não foi preenchido (ou foi preenchido, mas a visualização está marcada como privada), então o mapa fica disponível com o PIN no mar.
 

- [x] Retirar mapa da single quando o endereço é privado ou não foi preenchido

**Comment by robedj** [comment]
Ajuste Realizado
