### ISSUE TITLE
implementar imagens de compartilhamento

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2881]

**Comment by patricknobre12** [comment]
Segue as imagens de compartilhamento no tamanho apontado
[https://app.zenhub.com/files/16917978/8889826f-2584-4e2c-ac5f-2637c44b4158/download](https://app.zenhub.com/files/16917978/8889826f-2584-4e2c-ac5f-2637c44b4158/download)
