### ISSUE TITLE
implementar botões de aplicar avaliações

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2884]
- [x] Colocar um templateHook na página de gestão de inscrições que identifique se há fase de avaliação ou não (`$entity->evaluationMethodConfiguration`)
- [x] No módulo dos métodos de avaliação que possuam o endpoint de aplicar avaliações, criar um componente para o botão de aplicar avaliação. `<evaluation-method-{slug}--apply>` (ex: `<evaluation-method-simple--apply>`)
- [x] No módulo dos métodos de avaliação que possuam o endpoint de aplicar avaliações, utilizar o templateHook para adicionar um teplatePart no hook chamando o componente criado anteriormente

- [x] Desenhar estilo do modal que faz o procedimento de aplicar avaliaçẽos @patricknobre12 (link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8772%3A150514&mode=design&t=iLyDO5IiM9yqFxkM-1) 

Hoje esta assim
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/4424e89f-0a52-4404-88b6-88d4366e46a0)

#### Tarefas de estilização

- [x] Ajustar estilo do botão aplicar avaliações na lista de inscrição

- [x] Estilizar modal  de aplicar avaliações

#### Observações/Regras do Botão e modal

- As inscrições devem estar avaliadas para que sejam exibidas no primeiro select do modal

- O estilo do botão pode ser encontrado no figma 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8732-151070&mode=design&t=AA48tA6CWMWMMJCc-0

- O Botão de aplicar avaliações só será exibido nas avaliações Documental e simplificada

- Para acessar a tela vc deve editar uma oportunidade como administrador ou gestor da oportunidade, ir na aba de inscrições e resultados, expandir a abada da avaliaçõe e clicar em `Listar inscrições da fase` Ver print's abaixo

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/6a95485b-3a5e-4512-b316-ffb0a393f605)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/7be70dbc-bfce-4fe3-817e-c90c3b2d5eaf)

**Comment by daphnemartinsba** [comment]
Aplicação da avaliação:
![2884.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/afc42833-6832-4b5a-88b8-5041462155b9)
