### ISSUE TITLE
Ajuste: colocar letra maiúscula no filtro de ordenamento

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2886]
A imagem abaixo exemplifica a questão, ta estranho com os filtros assim 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/3a461d7c-ceff-4923-bfea-179ad7b43308)

**Comment by daphnemartinsba** [comment]
Agentes:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/4a38f9e0-75ff-4a7f-b107-b97010b03393)

Espaços:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/9d185bb7-604f-4394-9a3c-947458b9352a)

Projetos: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2f67901d-7e67-4688-865a-68782f4452e4)

Oportunidades:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/38148407-f9c4-470f-868e-41a1b1c4afd6)
