### ISSUE TITLE
Ajustar como aparece a configuração de publicação de resultados numa fase

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2889]
Atualmente está assim, com o layout desalinhado. Tentar seguir o figma. 
link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8383%3A149782&mode=design&t=tz1Ql0cHEy1rZWnw-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/1dfdb1f5-f299-48a5-9efa-b9619401bed7)

**Comment by daphnemartinsba** [comment]
- [ ] Como na implementação o campo de data é o mesmo do campo de hora, **alterar para "Data e hora da publicação dos resultados"**, o texto:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/bea9f0f1-0d35-41cc-9cd1-05379fef875e)
