### ISSUE TITLE
Ajustar de forma que os agentes apareçam em todo o modal de seleção (no momento da inscrição)

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2891]
Estender essa lista de acordo com o tamanho da tela, se possível
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/7fa1538c-012c-43f1-8b69-0e21affe1894)

**Comment by robedj** [comment]
Correção Realizada.
