### ISSUE TITLE
Ajustar textos de botões das modais dos botões de "Sair" e "Salvar para depois" no formulário de inscrição

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2892]
Os botões estão com "Enviar agora" como ação principal, como exemplificam os prints abaixo, mas o texto deve ser contextual à ação (links no figma depois das imagens com os textos corretos): 
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/dba3d3fd-b9c8-4533-bb54-24bc37cb1c79)
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/c63ece52-0748-4476-a2f6-3294bddbd746)

Segue os links com as versões corretas: 
Link 1 (Salvar para depois): https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782%3A170188&mode=design&t=iLyDO5IiM9yqFxkM-1

Link 2 (Sair): https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782%3A170221&mode=design&t=iLyDO5IiM9yqFxkM-1

**Comment by daphnemartinsba** [comment]
Modal Link 1:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5c7ec121-bb7a-4b61-b74e-74b51609a76e)
Modal Link 2:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/c022f916-fd17-4414-a0a5-60a8f2022107)
