### ISSUE TITLE
Ajustar: não foi possível excluir inscrição na versão testada

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2894]
Como o vídeo mostra, não foi possível excluir a inscrição. caso ja tenha resolvido, desconsiderar e fechar a issue; 
https://images.zenhubusercontent.com/16917978/284a9143-4a6a-4c6c-965f-3291c67ee073/n_o_da_pra_excluir_inscri__o___feito_com_o_clipchamp.mp4

**Comment by Raul-vlb** [comment]
Botão encontra-se sem a funcionalidade de excluir uma inscrição.

**Comment by Raul-vlb** [comment]
Funcionalidade ainda não foi implementada! 
O botão foi removido até que tal funcionalidade seja implementada.
