### ISSUE TITLE
[Oportunidades - Avaliações] Não é possível acessar todas inscrições na lista de avalições

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2900]
Comportamento atual: Dado que estou logada com o perfil do avaliador e estou na tela da avaliação, quando tento rolar a barra de rolagem para baixo, para acessar as últimas fichas de inscrições, então, não é possível, - provavelmente - por conta da resolução da tela, pois parece que a lista de avaliações está cortada

Comportamento desejável: 

- [x] ter acesso a todas as fichas de inscrições pela lista de avaliação

Print da listagem cortada:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/abf5bac2-8d38-4b10-8a8d-997c784859c1)

**Comment by robedj** [comment]
- Definir com o @patricknobre12 a posição ideal para o botão lista de avaliações não sobrepor os dados da inscrição

**Comment by daphnemartinsba** [comment]
- [ ] Ainda não é possível visualizar a lista inteira de avaliações. Como comprova o gif abaxo, só é possível quando diminui a tela:
![2900.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2312dcc5-5314-4b9b-bdaf-e4beec062657)

- A posição do botão da lista de avaliações no mobile foi definida na issue #2820, caso seja uma outra posição do desktop:

- [ ] Criar issue

**Comment by daphnemartinsba** [comment]
issue será resolvida na #2920
