### ISSUE TITLE
Implementar componente de importação de eventos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2901]
- [x] Estilizar componentes `event-importer-files` e `event-importer-upload`

Seguir figma https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=8927%3A152242&mode=dev

**Comment by Raul-vlb** [comment]
- [ ] desenhar os cards dos arquivos

**Comment by patricknobre12** [comment]
Segue link atualizado com os botões com alguns ícones: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9131%3A156738&mode=design&t=WdEiHj15zYclygSy-1

**Comment by patricknobre12** [comment]
link atualizado: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9147%3A158378&mode=design&t=WdEiHj15zYclygSy-1

**Comment by daphnemartinsba** [comment]
- [ ] Campos da planilha estão diferentes dos campos de inserção de ocorrência
Campo de inserção de ocorrência:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/27764117-e35f-47bb-bd2d-6aa338098c16)
Campo da planilha:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6a0b44bf-4daf-4013-9427-57805d22c5d7)

- [ ] Plataforma não processa planilha:
![2901.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/92a890a3-7bb6-40fd-b387-008746b3acf8)
