### ISSUE TITLE
Ajustar ícones dos botões de ações da tela avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2903]
## Descrição
Na tela de avaliação, foi discutido em reunião a possibilidade de implementar ícones nos botões que controlam a avaliação. Inclusive ja existe alguns implementado.

Abaixo tela de como está no momento

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/1ea6a248-54f5-4029-b18c-78ce2137c2dd)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/ee6efb0b-53c2-4b0b-ab84-f65b9939a216)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/5bd1afce-0df7-4f68-84c0-5302266b2aee)
## Tarefas

- [x] Desenhar no figma botões com ícone

**Comment by erleibiazzio** [comment]
- [ ] Implementar ícones nos botões conforme figma acima @robedj

**Comment by daphnemartinsba** [comment]
- [ ] Alinhar botão Finalizar com botão Finalizar e Avançar:
No figma:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8c5814fc-9e1d-4181-9ca4-328e99b51b3b)
No ambiente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a41dd34d-e3f1-4b75-b041-cecd0c6540bb)

**Comment by robedj** [comment]
Ajuste realizado
