### ISSUE TITLE
Corrigir a exibição do componente de denuncia e contato, esta quebrando o mobile

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2904]

**Comment by daphnemartinsba** [comment]
Componente de contato:
![Captura de tela de 2023-07-20 17-29-47.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/a7e3fded-f304-4033-9ed5-f91f398f1d5a)
Componente de denúncia:
![Captura de tela de 2023-07-20 17-29-52.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/109d30e6-f4aa-4135-ba1c-2d99491c9541)
