### ISSUE TITLE
[Cadastro de entidades] Inserir ID nas singles dos Espaços, Eventos, Projetos e Selos

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2905]
Para utilizar o importador de eventos, o utilizador precisa/pode informar o id dos selos, eventos, projetos e espaços. Atualmente, o id pode ser conseguido pela URL, o que pode não ser intuitivo para o utilizador. Por conta disso:

**Tarefas Design**
- [ ] Estilizar id no cartão de visita do Espaço
- [ ] Estilizar id no cartão de visita do Evento
- [ ] Estilizar id no cartão de visita do Projeto
- [ ] Estilizar id no Selo

**Tarefas Implementações**
- [x] Colocar id no cartão de visita do Espaço
- [x] Colocar id no cartão de visita do Evento
- [x] Colocar id no cartão de visita do Projeto
- [x] Colocar id no Selo

Exemplo do Id no cartão de visita do Agente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/26d7128b-75fb-4795-867f-4f16f13e8927)

**Comment by robedj** [comment]
Ids inseridos.
