### ISSUE TITLE
QA: correção - Ajuste no nome no entity-header - nomes grandes quebram o estilo da pagina. 

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2906]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/c2bae110-fc70-4f50-97ba-10bec5d26b61)

**Comment by daphnemartinsba** [comment]
single do agente com nome grande:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2863c49c-0fa4-42ea-bb14-c97b7309e1ea)
