### ISSUE TITLE
Corrigir  o titulo quebrando  na notificação e no card

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2907]
![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/cb3d7b17-c841-4cce-b05d-9d38fdf4c2a1)

**Comment by daphnemartinsba** [comment]
Card da notificação:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/8e8f1718-5e8d-4425-8d8c-35f413e0a12d)
