### ISSUE TITLE
[Oportunidade - configurações de fases] Ajustar textos da configuração de nome de projetos

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2912]
## Descrição
Como gestor ou administrador ao criar uma oportunidade, quando vamos configurar as fases, dentro da configuração do formulário o CARD que controla a ativação ou desativação da solicitação do nome do projeto está com texto que não reflete exatamente o que a funcionalidade faz. 

#### Situação atual no BaseV2
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/e1131a25-7ee9-49a6-a186-da1883e89e63)

#### Como está no BaseV1
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/18ed7a08-2041-4216-8a5d-755853d30d30)

#### Comportamento esperado
Esse CARD controla se deve ou não ser solicitado o nome do projeto do proponente no momento da inscrição. Os textos atuais se referem como se fosse possível liberar a visualização de várias informações referente ao projeto, porem esse campo só faz solicitar o nome do projeto que o proponente participa. esse campo é um campo de texto aberto que o proponente digita um texto corrido e esse texto é exibido na ficha de inscrição.

#### Tarefas

- [ ] Repensar textos para que reflita o real comportamento do campo

**Comment by patricknobre12** [comment]
Segue ajuste realizado; foi realizado também ajustes nos outros textos, então também devem ser adequados na implementação. 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=8016%3A148160&mode=design&t=UNerpcclEXJIfmdr-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/b5b7d664-3a6b-4b38-a672-f698591f9086)
