### ISSUE TITLE
[Oportunidade - Configuração de fases] - Corrigir compatibilidade da importação de formulário entre BaseV1 e BaseV2

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2913]
#### Descrição
Como gestou ou administrador, quando tento importar no BaseV2 um TXT que seja gerado a partir de um formulário criado no BaseV1, a importação quebra.

#### Tarefas 

- [ ] Fazer com que a importação aceite o TXT que seja gerado no BaseV2.

Obs.:  Foram criados novos campos nas entidades registrationFieldConfiguration e registrationFileConfiguration para controlar a estrutura de condicionais de campos. O importador deve atender interpretar esses novos campos e fazer a importação independente do thema usado.

**Comment by rafaelchavesfreitas** [comment]
Decidimos que não manteremos a compatibilidade com arquivos exportados antes da criação da condicionalidade dos anexos. Nessa situação, o arquivo deve ser exportado novamente.
