### ISSUE TITLE
[Oportunidade - Single] -  Corrigir textos do botão Botão Acompanhar na lista de inscrição na single da Oportunidade e no painel Minhas inscrições

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2914]
#### Descrição
Como proponente, quando me inscrevo em um edital porem não envio a inscrição ou seja, a mesma permanece em rascunho. Na single  da oportunidade e no painel Minhas inscrições na aba `Não enviadas`, a mesma aparece na lista de inscrições como mostra imagens abaixo.
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/545aa52a-4c1e-4b19-b34b-98f55b1122cf)

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/8894c966-ac58-43b9-803b-2070dd099101)

Veja que a inscrição que esta com status de `Não Enviada` tem o botão `Acompanhar`.

#### Tarefas

- [x] Quando a inscrição estiver em Rascunho, no botão deve aparecer o texto `Continuar` uma vez que a mesma ainda nao foi finalizada e depois que enviar sim deve aparecer `Acompanhar`

**Comment by daphnemartinsba** [comment]
- Quando a inscrição está em rascunho, em minhas inscrições ela aparece na aba não enviada com o botão continuar
- Quando a inscrição está em rascunho, na single da oportunidade ela aparece com o botão continuar:

![2914.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/859209f7-2222-42b0-8c05-badfd5f13fce)
