### ISSUE TITLE
[Oportunidade - Acompanhar inscrição] -  Redesenhar tela de acompanhamento de inscrição para visualização dos Gestor

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2917]
#### Descrição
Na tela de acompanhamento de inscrição hoje, temos os dados descritos no print abaixo:
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/cdf4e264-74ea-4524-a777-08964ed2bec4)

Essa tela é a mesma tela para o proponente e para o gestor/admin após o envio da inscrição. Porem, as melhorias aqui descritas, só devem ser feitas para gestor/admin.

Foi identificado que para facilitar o manuseio de status da inscrição após  a o processo de avaliação, essa tela deveria ter mais dados para auxiliar no trabalho do gestor. Abaixo descrevo alguns comentários obtidos em reuniões internas para explicar a ideia da refatoração

1) A tela deve ter um local em que o gestor/admin possa visualizar todos os pareceres de todos os avaliadores, facilitando assim a visualização macro do gestor de todas as avaliações e deixando ele assim tomar a melhor decisão do status que a inscrição deve ter ao fim da avaliação.

2) A tela deve ter, no primeiro card, onde contém o número da inscrição, o status final da avaliação `Status consolidado` Deixando assim claro o resultado que a avaliação se encontra no momento.

3) A tela deve dar a possibilidade ao gestor/admin de alterar o status da inscrição após fazer sua análise sobre os pareceres dos avaliadores.

#### Tarefas

- [x] Redesenhar a tela levando em consideração as colocações citadas acima

**Comment by patricknobre12** [comment]
Segue as telas desse fluxo: 
tela do acompanhamento para o gestor: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A153448&mode=design&t=kcbToJaebarSH6G2-1
tela dos modais:
- avaliação documental: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A153740&mode=design&t=kcbToJaebarSH6G2-1
- avaliação simplificada: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A153870&mode=design&t=kcbToJaebarSH6G2-1
- avaliação técnica: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A154004&mode=design&t=kcbToJaebarSH6G2-1
