### ISSUE TITLE
Criação do box com botões de acesso a lista de inscrições e lista de avaliações para a publicação de resultados

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2918]
os links que antes levavam a lista de inscrições e lista de avaliações agora serão parte de um estilo novo na publicação de resultados:
- [x] @patricknobre12  desenhar o estilo (link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A153233&mode=design&t=kcbToJaebarSH6G2-1)
- [x] @robedj estilizar

**Comment by daphnemartinsba** [comment]
Link do figma: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530-150555&mode=design&t=XOm1iUkC3fDHQ01d-0
- [ ] Alterar mensagem "A publicação do resultado é opcional." conforme figma: 
Critérios para mensagens:
- Quando o período da fase já encerrou, apresentar a mensagem: Você pode publicar o resultado manualmente a qualquer momento utilizando o botão ao lado.
- Quando o período da fase está vigente, colocar a mensagem referente a data de vigência, por exemplo, uma fase que termina 31/07/2023 às 18 horas, colocar a mensagem: Você poderá publicar o resultado manualmente no dia 31/07/2023 às 18:00 utilizando o botão ao lado. 

- [ ] Alterar ícone conforme figma

- atualmente:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/abe32ff9-ecd6-4e21-a046-c8ea3bd87707)

- no figma:

![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/177ea0a2-141a-487a-b6f3-8a740fe49eca)

**Comment by robedj** [comment]
Alterações Realizadas.
