### ISSUE TITLE
Ajustar tela de avaliação com três colunas

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2920]
A tela de avaliação foi ajustada e agora conta com três colunas. Segue o Link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475%3A150749&mode=design&t=zWGBouJTclRaIdEi-1

**Observação importante:** antentar-se para a produção da coluna de lista de avaliações
- a inscrição selecionada aparece destacada
- os status de inscrição agora possuem um novo visual, seguir esse visual

Link do fluxo do completo da avaliação: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9131%3A156738&mode=design&t=zWGBouJTclRaIdEi-1

link da tela de avaliação documental: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475%3A153943&mode=design&t=zWGBouJTclRaIdEi-1
link da tela de avaliação técnica:https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475%3A154240&mode=design&t=kcbToJaebarSH6G2-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/43470542-8335-490a-904c-81321a6916e6)

**Comment by robedj** [comment]
Cores dos status:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=1192-28469&mode=design&t=7Szf4CaQROhRwoeO-0

**Comment by robedj** [comment]
Cores dos status:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=1192-28469&mode=design&t=7Szf4CaQROhRwoeO-0
