### ISSUE TITLE
Desenhar status quando uma entidade está rascunho, arquivada e excluída na página de edição

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2921]
Adicionar mensagens de status na página de edição das entidades quando as entidades estão algum dos estados citados no título

**Comment by patricknobre12** [comment]
Os status desenhados devem aparecer para todas as entidades em rascunho. Segue o link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=10485%3A76591&mode=design&t=cuzLwMFX6UXQm1YQ-1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHRiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c32b566eae2b1a3caa93dee718a36843806d0aaa/image.png)

**Comment by erleibiazzio** [comment]
A mensagem esta permanecendo na tela depois que publicamos a entidade. a mesma so some após dar reload na página.

Ver GIF abaixo

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFhMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81de26fc9bc42e088884b6b421b2e8d68ec00eab/Peek%2022-09-2023%2013-57.gif)

A mensagem deve sair da tela sempre que a entidade for publicada sem a necessidade de reload na pagina
