### ISSUE TITLE
[Oportunidade - Avaliação] - Na tela de avaliação, durante o processo de avaliação identificar a inscrição corrente no sidebar esquerdo

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2924]
#### Descrição
Como avaliador, durante o sidebar esquerdo que lista as avaliações de responsabilidade do avaliador, deve deixar marcado qual a inscrição corrente como mostra figma abaixo.
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9475-153943&mode=design&t=jhP6nBKkr9fdsu3W-0
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/14cbe507-fa4b-401a-ab04-16bdb1bbdb94)

#### Obs.: 
- Para aplicar o CSS no template do componente `mc-side-menu` e destacar esse card, pasta verificar assim
`v-if="entity.id ==  evaluation.registrationid"` se o resultado desta verificação for `true` significa que a inscrição é a mesma carregada na tela

**Comment by robedj** [comment]
Essa issue foi resolvida na issue #2920
