### ISSUE TITLE
Padronizar posição dos botões das modais

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2928]
- [ ] Listar modais do mapas
- [ ] estilizar botões das modais

**Comment by patricknobre12** [comment]
Modais foram padronizados no figma de acordo com o que foi implmentado. Encontrei pelo menos algumas as inconsistências a seguir que precisam ser padronizadas: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWJiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5dd8787907365de04d5592d123bde24f01665d66/image.png)

pois padrão, o botão mais destacado tem aparecido de forma invertida, como na imagem abaixo: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXZiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ce15c628d2e9b58536e5d6cbbca1f923de9f9d6/image.png)
