### ISSUE TITLE
Publicação final dos Resultados Aba de inscrição e resultados - Atualização do estilo

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2929]
- [x] @patricknobre12 Atualizar o estilo no figma e comportamento publicado e não publicado (https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9530%3A150555&mode=design&t=0x6dkDr0957ZNvlT-1)
- [x] @robedj  Estilizar

![image.png](https://images.zenhubusercontent.com/6230839ad1e1c37867774b45/9565c4bf-6c5c-4a37-9281-81932a34f8a9)

**Comment by patricknobre12** [comment]
Segue exemplo. 
Obs: o botão ativado deve ter a cor primária como na imagem abaixo: ![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/09b66409-5549-4e3c-a129-2a335c491efd)
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/a7c8ba8d-a7b6-429b-9b8f-0791f66e31f5)
