### ISSUE TITLE
Redefinir tamanhos dos textos dos títulos das entidades

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2935]
#### Descrição
Nos títulos, devemos adotar uma regra nos tamanhos da fonte. Deve existir 3 tamanhos de fontes seguindo as seguinte regras.

Caso 1: Títulos com 1 linha
Caso 2: Títulos com até 2 linhas
Caso 3: Títulos com mais de 2 linhas

Devemos pensar em tamanho de fontes diferentes para esses casos pensando em melhorar o visual

**Comment by patricknobre12** [comment]
Segue o link com os tamanhos de texto para cada caso: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=9799%3A149484&mode=design&t=hq8eIp8QhFjala6Z-1
