### ISSUE TITLE
Melhoria na tela de recurso utilizando anexos PE

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2936]
#### Descrição
Hoje, para solicitar o recurso, temos um fluxo muito básico. O gestor/Admin configura um e-mail para o gestor/Admin que irá receber a solicitação de recurso dentro da área de configuração da oportunidade e define se a oportunidade terá o sistema de recurso ativo ou não, através de um check-box. Caso esse e-mail esteja configurado e a funcionalidade esteja ativada, ao publicar a fase, aparece para o proponente um botão dentro da tela de acompanhamento da inscrição que abre um Modal com uma caixa de texto para o proponente apresentar sua justificativa e, ao clicar em Solicitar, é enviado um e-mail ao gestor/Admin da oportunidade com o texto.

#### Nova necessidade na funcionalidade
Redesenhar as telas de configuração e solicitação do recurso para que seja possível anexar arquivos juntos à solicitação. Para isso, levar em consideração as regras abaixo:

## Tela de configuração do recurso - Visão do gestor/admin
- Deve existir um check-box que defina se a funcionalidade está ou não ativada na oportunidade.
- Deve haver um check-box para ativar ou desativar a exigência do anexo. Caso esteja ativa, obriga o proponente a anexar um arquivo; caso esteja desativada, só é enviado o texto, como já está implementado.
- Deve existir um campo para definir as datas de abertura e fechamento do período de recurso.
- Deve existir um campo para definir o e-mail que o gestor irá receber o anexo ou mensagem.
- Deve existir um campo que possibilite inserir um documento que sirva de exemplo do anexo que o proponente deve preencher.

## Tela de solicitação do recurso - Visão do proponente
- Deve existir um link ou botão para que o proponente consiga baixar o arquivo de exemplo inserido na configuração.
- Deve haver um texto que informe o período em que o recurso está aberto.
- Deve existir um campo para que o proponente digite uma mensagem de texto.
- Deve existir um campo para que o proponente insira o documento que será enviado como anexo.
- O anexo só deve ser exigido caso esteja ativada a exigência na configuração.
- Depois de enviar um anexo e o mesmo não estiver aceito pelo gestor/Admin, deve ficar um botão para que o proponente possa excluir o anexo e substituí-lo. Esse anexo será sempre avaliado pelo gestor/Admin e pode ser recusado. Depois que o documento é aceito pelo gestor/Admin, o proponente não pode mais deletar ou substituir o anexo.

**Comment by cesardelucca** [comment]
Após avaliação da gestão, essa issue será arquivada pois será necessária um levantamento de requisitos mais detalhado junto dos gestores estaduais q utilizam o Mapa.
