### ISSUE TITLE
Ajustar label de obrigatório nos campos Areá de atuação das entidades

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2937]
#### Tarefa

- [ ] Na edição das entidades Agente, espaços e eventos ajustar posicionamento, cor e fonte da label que indica que a área de atuação é obrigatória

![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/2d7c2008-9790-4b65-a71d-7e9946b6dd10)

**Comment by rafaelchavesfreitas** [comment]
duplicada
