### ISSUE TITLE
[Oportunidade - Acompanhar inscrição] Implementar botão "Exibir o parecer"

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2941]
- Determinar regras:

- [ ] Para o gestor
- [ ] Para o proponente

Layout:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7524-147857&mode=design&t=TU0Hvb50lAim7kAn-0

**Comment by erleibiazzio** [comment]
Ainda falta implementar para as avaliações Simplificada e Habilitação documental

**Comment by israelmelo** [comment]
@Raul-vlb poderia ajustar essa div por gentileza? 

**Problema:** Preciso trocar a tag <template> para <div> pois estou utilizando um v-if="true" na tag <template> para carregar os dois checkbox que possuímos na configuração de fase do tipo avaliação. Quando faço a troca para <div> o layout da uma quebrada, segue o anexo embaixo de como fica utilizando a tag <div>

<img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb9d3c79db90b86959cd196e61245c47c45439d2/image.png" alt="image.png" />

e deveria ficar assim:

<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6af7b56ffe4061c614e2b0fc2973a8037d719fb/image.png" alt="image.png" />

**Obs:**

Branch: feature/publication_results
Arquivo para modificar: template.php do componente opportunity-phase-publish-date-config
