### ISSUE TITLE
[Oportunidade - Acompanhar inscrição] Estilizar botão/texto de recurso e status da inscrição 

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2942]
Tarefas (conforme layout do figma):

- [x] Estilizar status da inscrição

- [x] Estilizar texto e botão de recurso

Atualmente:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/2ac091b1-95a4-48d0-aaa1-5b4337d8ca83)

Layout do figma:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/55616b0b-1350-4257-8ed3-dc867580864e)

Link do layout: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7524-147857&mode=design&t=TU0Hvb50lAim7kAn-0

**Comment by robedj** [comment]
Foi realizado o merge pra develop.
