### ISSUE TITLE
Adicionar datas finais e iniciais aos cards de uma oportunidade

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2946]
As datas de inscrição de devem constar nos cards do edital ou oportunidade **tanto na home como nos cards das buscas**

**Comment by patricknobre12** [comment]
Segue o ajuste feito do card com as datas inseridas:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=6782%3A162073&mode=design&t=F4c6AETzPvBqqez2-1
![image.png](https://images.zenhubusercontent.com/622f2e97d6184bcb65c59942/299f3f91-07c8-4fcb-afac-6fddb37f60e3)

**Comment by robedj** [comment]
Ajuste realizado, merge realizado na develop
