### ISSUE TITLE
Ajustar tamanho de cards na home desktop caso haja um ou apenas dois cards exibidos

### ISSUE THREAD

**Issue by patricknobre12** [mapasculturais/mapasculturais#2950]

**Comment by patricknobre12** [comment]
Caso estejam sendo exibidos apenas dois cards ou um card, eles devem ser responsivos para ocupar o grid e não ficar com espaço "em branco"

**Comment by patricknobre12** [comment]
Segue os links. 

Com um card: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=10112%3A49715&mode=design&t=ulK53QUhkCbhJsPC-1

com dois cards: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=10112%3A49314&mode=design&t=ulK53QUhkCbhJsPC-1

**Comment by rafaelchavesfreitas** [comment]
os títulos estão quebrando a linha quando não é necessário
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUlPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99b4e7be787ea19e3c0f33c23bdcc3de6f1c098d/image.png)

**Comment by robedj** [comment]
Foi feito ajustes no entity-card e nos estilos dos cards em destaque e editados recentemente alem do card da oportunidade da home.

**Comment by cesardelucca** [comment]
@robedj identificamos que os títulos de algumas Oportunidades estão se sobrepondo ao ícone "Inscrições abertas", na listagem das oportunidades.  
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdldOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7c1195fe77e41e5c1d357b2d7f0d8813287c171f/image.png)
Para realizar esse ajuste, teste na home com uma, duas e três oportunidades destacadas (oportunidades com selos e abertas).
Teste tb na listagem da busca para oportunidades abertas e não abertas. Utilize os seguintes títulos de oportunidades:
- PRÊMIO AGIMOS DE PRODUÇÃO MUSICAL
- Edital de Seleção de Profissionais para Comissões Julgadoras do Funcultura - Reabertura de Prazo de Inscrições
- Edital 005/2022 - Serra - Seleção de projetos para grupos das culturas populares e tradicionais do município da Serra - Prêmio Mestre Antônio Rosa - RELANÇAMENTO

IMPORTANTE! Lembrar das classes `without-labels` e `with-labels`

**Comment by Raul-vlb** [comment]
[issue referente a ajuste nos cards das oportunidades](https://github.com/mapasculturais/mapasculturais/commit/efbf538158298747f5e0759764cb99d81c43e90c)
