### ISSUE TITLE
melhorar indicação de obrigatoriedade no campo nome do projeto

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2957]
a versão do Figma não pode ser implementada ainda pq hoje só temos um dos campos, o título do projeto, mas ficou muito estranho o layout com um só campo
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcllZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--871a09cb1a4d529c08d7cdd1cd23f9308de80b0d/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclFZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e995c5b132de5e2dd9afb568778b747ad6a07a2c/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmNZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c004401421c2d4c2ca204becf96496d7c2e89554/Screenshot%20from%202023-08-18%2008-49-15.png)

então refatorar para enquanto não implementamos os campos de descrição curta e tipo do projeto, parecer mais um campo simples, tipo assim:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjhZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87eee14e377adfcf78a0965dbab36ac08116f130/Screenshot%20from%202023-08-18%2009-00-49.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0FZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--827d9f74bbaab6ed934a6b99cd44a9e569fb3eab/Screenshot%20from%202023-08-18%2009-01-07.png)

**Comment by robedj** [comment]
Ajuste Realizado
