### ISSUE TITLE
os links não estão aparecendo em nenhuma das entidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2963]
para verificar o problema basta criar um link em algum agente, espaço, projeto, oportunidade ou evento e sair do modo de edição.

**Comment by robedj** [comment]
Resolvido, alteração ja esta na develop

**Comment by rafaelchavesfreitas** [comment]
nos eventos continua sem exibir, acho que falta importar o componente
