### ISSUE TITLE
verificar os botões de contato e denúncia

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2969]
As ferramentas de contato não estão funcionando para agentes individuais. Além disso, nas páginas de oportunidades, eventos e espaços, estas ferramentas abrem uma caixa de envio de mensagens, no entanto não geram nenhum resultado quando acionadas, permanecendo a página trancada e sem envio.

- verificar nas versões 6 e 7 utilizando o mailhog

**Comment by Raul-vlb** [comment]
Foram feitos ajustes no front do componente. 
Falta verificar envio de email geral (enviando apenas quando o checkbox `Enviar somente para o responsável` está marcado)
