### ISSUE TITLE
[Oportunidades - Recurso] - Ajustar textos das telas de recurso

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2975]
## Descrição
Hoje os textos da tela de recurso utilizando o anexo, utiliza os jargões que estão dando a entender que quando o gestor fazer o aceite do arquivo ele esteja dando o resultado final do recurso. Porem isso não funciona bem assim.
veja na tela abaixo, tela onde o gestou faz o aceite do arquivo os botões dizem `Aceitar recurso` e `Recusar recurso` porem esses botões só fazem o aceite do arquivo enviado.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnR6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--770a1320e172fe7b273afbb77695ac6a7d7bd5d7/image.png)

Nas telas posteriores ao aceite de arquivo, também deve ser corrigido os textos. Os textos devem sempre fazer referência ao aceitar ou recusar o arquivo

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjV6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc1357f30628e25220d86795b9cbfa3c7561327e/image.png)

**Comment by patricknobre12** [comment]
Fluxo do proponente: https://www.figma.com/file/OcFH0ClVW0KbeGn7Oh3LUw/Redesign---PERNAMBUCO---Entregas-(FINAIS)?type=design&node-id=7522%3A1970&mode=design&t=reLC8xSxY5UGtLa0-1

Fluxo do gestor: https://www.figma.com/file/OcFH0ClVW0KbeGn7Oh3LUw/Redesign---PERNAMBUCO---Entregas-(FINAIS)?type=design&node-id=7756%3A7329&mode=design&t=reLC8xSxY5UGtLa0-1
