### ISSUE TITLE
Design das telas de FAQ

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#2987]
Link da planilha de perguntas e respostas
https://docs.google.com/spreadsheets/d/1-ku0gskJbzUupDQ79zXtBvTYX4TnoEXa9ftu85KNh8Q/edit#gid=0

Link do figma:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11465%3A52496&mode=design&t=ennhpvwPgybQqsv9-1

[ ] home do FAQ
[ ] Interna do FAQ
[ ] resultado da busca

**Comment by patricknobre12** [comment]
segue link das telas de resultado da busca. 
mobile: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11129%3A16685&mode=design&t=0HRTotRnyHoXuOV9-1

desk: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11129%3A16686&mode=design&t=0HRTotRnyHoXuOV9-1
