### ISSUE TITLE
[Agente - Edição] - Corrigir validações ao inserir links de shorts na galeria de vídeo

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#2991]
## Descrição
Para testar inserir a URL `https://www.youtube.com/shorts/iJe93jCNxzw` na galeria de vídeo do agente.
A galeria ira quebrar apresentando um erro parecido com erro abaixo.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTYwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8880414d59b07ba9a710dc66bf071faca083575a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaSswIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--82dc8d071b56345d875e51d5f811b2a6ad455f81/image.png)

**Comment by Raul-vlb** [comment]
Correção aplicada no Mapas7
