### ISSUE TITLE
Desenhar as telas para configuração das labels

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#2997]
Tipos de status: Rascunho, Pendente, Inválido, Não selecionado, Suplente e Selecionado

**Comment by patricknobre12** [comment]
Seguem as telas sobre a configuração das labels para **validar**: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11355%3A21619&mode=design&t=iME0cUq4XrLF6Gy5-1
