### ISSUE TITLE
Desenhar e Implementar a tela de edição de oportunidade, opção de editar projeto vinculado e reorganizar a posição das redes sociais

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3001]
Desenhar na edit das oportunidades a tela de edição do projeto (ou outra entidade) vinculado, para que os admins da oportunidade possam editá-la. Talvez próximo aos admins da entidade
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63c1937b153747dff50ef5546e21fafad2e75fdf/image.png)
 
Avaliar a posição dos campos das redes sociais na edit da oportunidade, visando evidenciar  as informações dos Selos, Tags e Propriedade

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e80c724285dc8593caea29087b896cd0438f8b51/image.png)

**Comment by robedj** [comment]
O Frontend ja esta pronto, falta corrigir o backend

**Comment by rafaelchavesfreitas** [comment]
resolvi a questão do backend.

@robedj, diferentemente do comentário acima, falta mutos ajustes no frontend, os select-entities não estavam funcionando e já corrigi, porém a estilização ainda está bem quebrada.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1UQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a151d033c70896e034748db0b90b13616335ff7c/image.png)

**Comment by rafaelchavesfreitas** [comment]
- [ ] renomear o componente para `select-opportunity-owner-entity`
