### ISSUE TITLE
Desenhar no footer link para acessar o suporte via email

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3005]
No base v1 existia uma frase com o link para acionar o suporte via email, que ficava localizado no rodapé da home. Isso corria por conta do plugin Aldir Blanc.

A demanda é desenhar no footer um local onde cada instalação poderá disponibilizar um link para acessar o suporte via email.

Como exemplo, segue como está disponibilizado hj, no Mapa do PA, via um novo plugin.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzB6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a232ca22a6e765faf93d260c1794bb231664192/image.png)

**Comment by patricknobre12** [comment]
Seguem alguns exemplos de padronização deste elemento: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11540%3A33230&mode=dev&t=OQGbDc5jy34s4xji-1
