### ISSUE TITLE
Desenhar alguma referência de como identificar o agente de cadastro do agente cultural, na tela Gestão de Usuários

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3006]
No base v1, era possível identificar o agente principal por conta do ícone de agente q aparecia de uma forma diferente dos outros sub agentes.
Hj, no base v2, não é possível identificar qual agente é o agente de cadastro.

É desejável que pensemos em como essa visualização pode aparecer em outras telas. como na busca  de agentes

**Comment by patricknobre12** [comment]
eu sugiro que o card que aparece na gestão de usuário possa ser semelhante ao exibido no print abaixo, com um label indicando que é o agente principal: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK00xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7087935e853d6a19d12ef070e588985ea328a5c8/image.png)
