### ISSUE TITLE
adicionar tamanho máximo de arquivo de upload em todas as caixas de upload de arquivo

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3007]
- avatar
- header
- downloads
- galeria
- etc

no BaseV1 tinha assim:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0UxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bff6503aa1ce126c8d29e003ddaf8db27b07a8a/image.png)

**Comment by patricknobre12** [comment]
Segue o link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11554%3A48392&mode=dev&t=OQGbDc5jy34s4xji-1
