### ISSUE TITLE
Alterar o fluxo de criação de cadastro

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3009]
Atualmente qdo um usuário cria um cadastro no Mapas, ele passa por 5 etapas. Ao final, sua conta é criada e ele precisa fazer o login no sistema.
Ao fazer o login, ele cai na tela de edição do perfil e precisa publicar seu agente.
Porém, nesse fluxo do redesign, a ideia é que o cadastro já seja publicado ao final do processo de criação de cadastro. 

Tarefa:
- Ajustar esse fluxo após a criação de cadastro
- Caso a pessoa chegue no Mapa através do link de uma oportunidade, ele precisará criar o  cadastro e depois ser redirecionado para a tela de onde ele veio.

**Comment by rafaelchavesfreitas** [comment]
o primeiro item é uma configuração do plugin e o segundo ítem já foi implementado
