### ISSUE TITLE
Minhas avaliações - Implementar telas no Painel de Controle

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3012]
Implementar tela Minhas avaliações, no painel de controle.

Somente deve aparecer para quem é ou já foi avaliador

Link go Figma:
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7779-149923&mode=design

**Comment by Raul-vlb** [comment]
Duplicada da issue [#2876](https://app.zenhub.com/workspaces/mapasculturais-641b3ab7a65901001ab857af/issues/gh/mapasculturais/mapasculturais/2876)
