### ISSUE TITLE
[Inscrições - Processo de avaliação] - Ajustar estilo do componente opportunity-evaluations-list

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3015]
## Descrição
No componente, as labels estão com o estilo diferente do figma. e falta um botão de acessar, que leva o avaliador para a tela de avaliação

#### Como está atualmente
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1oxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8733052e668171a58d582a5a67a08ea2ef1af332/image.png)

#### Figma
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjkxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e0a4d4d99315af9a6241b2bcbe160b32230aa39/image.png)

## Tarefas

- [x]  Ajustar estilo conforme o figma, segue link abaixo
- [x]  Inserir Botão `acessar` e fazer com que o mesmo de acesso a avaliação

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=9475%3A150918&mode=dev

**Comment by robedj** [comment]
Ajuste Realizado
