### ISSUE TITLE
[Inscrições - Processo de avaliação] - Fazer com que os sidebar esquerdo e direito da tela de avaliação fixe no topo da pagina ao scrollar

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3016]
## Descrição
Quando o avaliador esta na tela de avaliação, ao scrollar a tela os dois sidebar's rolam junto e somem da tela. isso dificulta a avaliação em alguns tipos por exemplo a documental.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWgxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82d625ee20d1643c174ea07d4e119fd7bcb224eb/WhatsApp%20Image%202023-10-26%20at%2010.26.43.jpeg)

## Tarefa

- [x] Fazer com que ao scrollar a página os dois sidebar's  rolem somente ate o header e fiquem sempre visíveis, melhorando a experiencia do avaliador.

Objs.: `Em CSS me parece que seja o position: stick`

**Comment by erleibiazzio** [comment]
O sidebar esquerdo esta com comportamento esperado, porem o direito ainda scrolla com a tela ate sumir.

**Comment by robedj** [comment]
Ajuste Realizado.
