### ISSUE TITLE
Criar componente de tabela de entidade

### ISSUE THREAD

**Issue by robedj** [mapasculturais/mapasculturais#3019]
Modulo entity
nome do componente: entity-table

- [x] Tabela deve conter um select de colunas habilitadas 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2445778e8ecbdf77f987551a7c67d16ce554690/image.png)
- O componente deve receber uma listagem de colunas existentes
- Listagem de colunas opcionais.
- Listagem de colunas selecionadas por padrão.

- slot header:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a595f2c1f82d85a347cfa6061bfa4f6006e88380/image.png)

- slot item :
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c653e237bc0b43ae1d7643a25a10268fd4e6bc70/image.png)

- slot itemName:
valor padrão que pode ser substituída, similar ao nome do panel-entity-card:
 `{{ entity.name || entity.email || entity.number || entity.id }}`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b02e7c84c80c099811e4c11c2c5fc2d23bbc0e5/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5065d8af4d2261197bb0b2f22285c384f4fbb7e1/image.png)

- Criar propriedade de lista de opções de operação em massa

``` 
[
    {label : 'apagar', slug : ' delete'},
    {label : 'selecionar', slug: 'selected'},
    {label: 'invalidar' , slug: 'invalided'}
]

```
- Quando uma pessoa selecionar uma opção e clicar em aplicar, disparar um evento enviando o slug
Se nenhuma operação for enviada, lista vazia, não exibir os checkbox e nem o select e nem o botão.

- classe para aplicar na linha conforme status da entidade
exemplo:
```
{
'0' : 'draft',
'1' : 'sent',
'10' : 'selected',
...
 }
```

**Comment by rafaelchavesfreitas** [comment]
definição das colunas existentes, quais são obrigatórias (não podem ser desativadas), quais são opcionais e quais são exibidas por padrào.
```JS
        [
            { // sempre ficará visível, não aparece no select de seleção de coluna
                prop: 'id',
                label: '#',
                required: true
            },
            { // será exibido por padrão
                prop: 'name',
                label: 'Nome',
                visible: true,
            },
            { // ficará oculto por padrão
                prop: 'nomeSocial',
                label: 'Nome Social'
            }
        ]
```

a coluna será exibida se `item.required || item.visible`
