### ISSUE TITLE
Colocar a msg de suporte dentro do Grid

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3023]
Tarefas
[] @patricknobre12 : Ajustar o texto padrão que ficará ao final da home do FAQ
[] @robedj: Estilizar os textos dentro do grid, conforme o ajuste qque o Patrick fará.

**Comment by patricknobre12** [comment]
Seguem exemplos e link sobre: 
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=11465%3A52496&mode=dev&t=9Qi1V25EUKdSKrHJ-1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--883aadd0bb1df78d5e6943315f92aad572addebc/image.png)
