### ISSUE TITLE
Ajustes na tela Minhas Inscrições

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3027]
Tarefas:
- [x] Adicionar uma aba Lixeira

- Na gestão de usuários ter também as mesmas abas de Minhas inscrições 
- Obs:  manter tudo que vai para a lixeira e se precisar excluir permanentemente, tem que entrar em contato com responsáveis (confirmar isso futuramente)

**Comment by patricknobre12** [comment]
Segue link: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=7779%3A149920&mode=dev&t=IzuDsa4A4HKYKwr5-1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdcf2bffe8742d266e59c8c27af5d62f176a3008/image.png)
