### ISSUE TITLE
[Inscrição - Tela de acompanhamento] - Exibir botão de preencher fomulario se existir uma fase de coleta de dados pendente de preenchimento

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3037]
## Descrição

Hoje, quando existe mais de uma fase de coleta de dados na oportunidade, na aba `Acompanhamento`, na timeline da inscrição é possível ver o botão de `Preencher formulário` Como mostra na imagem abaixo.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e05010ed6b8f9ee08f24d2bedc4ec0a3f32ed89/image.png)

Este botão tambem deve ser exibido na aba de acompanhamento deixando claro ali que o Agente tem que preencher dados na fase em questão. um exemplo da ideia seria isso abaixo

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee2518e3fafbbb59358903d50c4cf23b4db4e19d/image.png)

#### Observações
- Se a fase nao estiver vigente, nada deve ser exibido
- Se a inscrição nesta segunda fase ja foi enviada, nao deve ser exibido nem o botão e nem a mensagem e sim os dados que o proponente forneceu. Como na Fase 1

## Tarefas

- [ ] Fazer desenho no figma para prototipar esses layouts
- [ ] Implementar ações no front para atender os comportamentos

**Comment by patricknobre12** [comment]
Segue o link do ajuste realizado: https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?type=design&node-id=12422%3A59986&mode=dev&t=EY1gsQLDkahENMx7-1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc9b53ea03bf80fad2336226f5afc17fed3c3e14/image.png)
