### ISSUE TITLE
Desenhar fluxo das cotas nos editais

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3039]
Elaborar as formas como as regras de cotas para editais estarão na interface da gestão de oportunidades.
[ ] Desenhar Fluxograma no figjam (cotas, território e faixas)
[ ] Desenhar as telas de interface

Proposta de cronograma:
- Apresentação da conceituação - 17/01
- Devolutiva da v1 das telas - 22/01

**Comment by PabloNicolela** [comment]
Finalizei os ajustes ontem, mas ainda falta a validação para colocar na pagina do fluxo de configuração de fases.
Pagina do figma >>> entrega 7/02/24
