### ISSUE TITLE
Desenhar fluxo do Plugin de Pagamento

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/mapasculturais#3047]

**Comment by PabloNicolela** [comment]
Eu, Erlei e Welington tivemos uma conversa sobre perfis e plugin de pagamentos, para endimento do fluxo.

**Comment by erleibiazzio** [comment]
## Imagem 1 - Status de pagamentos existentes
<img width="843" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUY0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12f997838b272bc214d420781c76f2c1c079f30f/image.png" alt="image.png" />

## Imagem 2 - Botões das opções
<img width="106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXA0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b71117e5146391bc140b13953ec0cc6079aa525/image.png" alt="image.png" />

### Lista de colunas existentes na tabela
- Inscrição => Campo de texto Ex.: on-561465857
- Previsão de pagamento => Campo de data Ex.: 20/12/2023
- Valor => Campo monetário Ex.: 	R$ 1.535,00
- Status => Campo de seleção com todos os status da imagem 1
- Opções => Campos com botões de ações rápidas Imagem 2 (Editar, ver histórico e excluir)
- Categoria => Campo de seleção que pode conter textos aleatórios
- CPF/CNPJ => Campo de texto que exibe o documento do agente
- Nome do proponente => Campo de texto que exibe o Nome do proponente

### Filtros da tabela
- Campo de filtro entre data, com data inicial e final
- Campo de filtro por palavra chave, Que será um campo de texto que recebe qualquer texto e faz a pesquisa

**Comment by PabloNicolela** [comment]
Ajustes solicitados que consegui finalizar no dia 22/12:
- Inserir opção de "Gestão de pagamentos pela plataforma?" na primeira fase de infos obrigatórias:
- Criar aviso de "Os campos de pagamento não foram preenchidos corretamente"
- Transformar 2 botões em 1 na tela de Pagamentos
- Colocar botão "limpar" nas caixas de seleção com checkbox
- Inserir ícones nos botões
- Inserir botão de Download da tabela filtrada

Ajustes pendentes:
-Modal para o preenchimento dos dados de pagamentos (leventar mais informações)

**Comment by PabloNicolela** [comment]
Ontem Finalizei o desenho das telas e de todos os modais para o fluxo de pagamento. Precisamos ver o prazo para fazer essas telas na versão mobile, pois nessa parte do figma não tem nenhum tela feita nessa versão.
