### ISSUE TITLE
[Oportunidade - Listagem Inscrições] - Ajustar carregamento de colunas na tabela de inscrição

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3055]
## Descrição
Com a nova implementação do componente de tabela `entity-table`, precisamos começar a dar vida para a tabela de listagem de inscrições. A tabela deve exibir várias colunas. As colunas no componente `entity-table` podem ter 3 estados diferentes:
1) `Obrigatórias` => onde elas ficam fixas e não podem ser removidas da tabela.
2) `Não obrigatórias mas sempre visíveis` => onde elas podem ser ocultadas, porém sempre estão visíveis no primeiro carregamento.
3) `Não obrigatórias e ocultas` => onde no primeiro carregamento elas não são exibidas, mas o usuário pode exibir as mesmas quando desejar através das opções avançadas.

Os dados que devem ser exibidos na tabela de inscrições são:
- Número da inscrição (Obrigatório)
- Categoria (Não obrigatórias mas sempre visíveis)
- Nome do agente (Não obrigatórias mas sempre visíveis)
- Resultado final da avaliação (Não obrigatórias mas sempre visíveis)
- Status (Não obrigatórias mas sempre visíveis)

#### Abaixo forma de acessar os dados dentro do objeto `entity`

- Número da inscrição => `entity.number`
- Categoria => `entity.category`
- Nome do agente => `entity.owner.name`
- Resultado final da avaliação => `entity.consolidatedResult`
- Status -> `entity.status`

Obs.:
- Para uma coluna ser obrigatória, basta definir ela na propriedade `required` do componente `entity-table`. Ex.:
`required="number,status,options"` As colunas number, status e options serão sempre fixas e não podem ser removidas da tabela.

- Para não ser obrigatória mas ficar sempre visível, basta definir a propriedade `visible` do componente `entity-table`. Ex.:
`visible="number,status,options"` As colunas number, status e options não são obrigatórias mas estão sempre visíveis no primeiro carregamento.

Veja print abaixo com exemplo:
<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkd5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b7bb357d88a239d856d176e5e91b32deefdb429/image.png" alt="image.png" />

## Tarefas
- [x] Fazer com que todos os dados sejam exibidos na tabela.
- [x] Ajustar exibição da coluna status.
  - A coluna status deve ser feita via slot pois o back-end devolve um número para o status. 
  - Devemos fazer no `init.php` do componente `opportunity-entity-table` uma estrutura de dados que passe todos os status possíveis das Inscrições para o javascript usando `jsObject`. 
  - Para isso usar o método estático `Registration::getStatusesNames()`. O mesmo devolve um array com todos os status possíveis que uma inscrição pode ter, sendo a chave o número do status e o valor o texto do status. Ex.:
  ```php
  ['1' => 'Pendente', '10' => 'Selecionado']
Imagino que a estrutura de dados a ser montada deva devolver um objeto semelhante a esse abaixo:

```
[
    {label: "Selecionado", value: 10},
    {label: "Pendente", value: 1}
]
```

# Atenção
- Usar branch `feature/opportunity-registration-table` do mapas

**Comment by LimaSystem** [comment]
Quando fomos fazer a alteração do status, não estava salvando. Qual foi a abordagem adotada para corrigir isso? Comentamos uma parte do código dentro de Registration.php, a função // function setStatus($status){ // do nothing // }. Após esse procedimento, o salvamento automático foi iniciado.

**Comment by erleibiazzio** [comment]
Será necessário alguns ajustes na tabela de listagem de inscrições

- [ ] Evitar que colunas que nao possuam text definido, sejam exibidas no filtro de colunas
- Para definir as colunas que a tabela terá, temos que enviar um atributo header para o componente `entity-tabe`. Porem Pode exitir casos que a coluna existe um valor mas nao existe um nome na coluna, que é o caso dessa tabela de listagem de inscrições. Ver print abaixo a coluna do botão `Conferir inscrições` não tem nome.
<img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2403d302cfd8d53ac0bc348d29923539dde1286e/image.png" alt="image.png" /> 

Porem no filtro de colunas esta ficando um checkbox sem label veja abaixo
<img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb9270ddde02803bd6b8844bf5d0fbf54fbe59da/image.png" alt="image.png" />

- [ ]  Coluna de `Inscrição` Inserir um link no texto, que leve para o mesmo local que o botão `Conferir inscrição`

- [ ]  Coluna `Resultado final da avaliação`
- Essa coluna deve exibir o status referênte a cada avaliação. Seguir exemplo abaixo.
Avaliação Técnica => Nota final Ex.: 78.0
Avaliação Documental => Válida ou Inválida
Avaliação Simplificada => Selecionada ou Não selecionada
Avaliação Habilitação Documental => Válida ou Inválida

- Criar uma estrutura de dasos no init.php que envia via jsObject um dicionario de status Exemplo.

```
$data['evaluationStatusDict'] = [
    'simple' => [
        '2'  => i::__('Inválida'),
        '3'  => i::__('Não selecionada'),
        '8'  => i::__('Suplente'),
        '10' => i::__('Selecionada')
    ],
    'documentary' => [
        '1' => i::__('Válida'),
        '-1' => i::__('Inválida'),
    ],
    'qualification' => [
        '1' => i::__('Válida'),
        '-1' => i::__('Inválida'),
    ]
];
```
# Atenção
A variavel $data ja esta em uso, para seguir o exemplo e usar ela, deve ser analisado o impacto

**Comment by erleibiazzio** [comment]
# Implementação dos filtros da lista de inscrições

## Descrição
Iremos implementar agora os filtros que a tabela de inscrições irá ter. Hoje o figma mostra 4 filtros.

1) Por palavra chave => Input onde digitamos um texto e ele filtra as inscrições da tabela que correspondem com texto.
2) Resultados das avaliações => Select que contem todos os resultados de avaliações agrupados e ao selecionar ele traz na tela todas as inscrições relacinadas aos resultados selecionados
3) Status da inscrições =>  Select que contem todos os status das inscrições possíveis e ao selecionar um ou mais status ela filtra todos as inscrições daqueles status.
4) Categoria =>  Select que contem todos as categorias da opportunidade possíveis e ao selecionar um ou mais categorias ela filtra todos as inscrições daquelas categorias.

Para ver os filtros ver o figma abaixo
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?node-id=9530%3A153527&mode=dev

## Tarefas

- [ ] Inpmentar filtro por categoria
- [ ] Implementar filtro por status
- [ ] Implementar filtro pelo resultado das avaliações

Obs.:
- Para pegar todas as categorias da oportunidade basta usar `this.phase.registrationCategories`
- Para pegar os filtros das inscrições, basta usar a mesma estrutura usada no status das inscrições na tabela.

**Comment by erleibiazzio** [comment]
Precisamos agora, estilizar a tabela de de inscrições. ja temos a mesma rodando na branch `feature/opportunity-registration-table`. 

Obs.:
- Seguir o mesmo figma citado acima na issue
