### ISSUE TITLE
[Oportunidade - Configurar avaliadores] - Componente para definir comite de avaliação

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3059]
## Descrição
Logado como administrador, quero configurar todas as pessoas que terá permissão para avaliar em um edital. Ao acessar a oportunidade em modo de edição, acessar a aba configuração de fases e abrir uma fase de avaiação, o gestor/administrador deve ter a opção de listar os agentes e selecionar qual agente ira efetuar as avaliações daquele edital.

Hoje temos uma estrutura igual a mostrada abaixo no print.
<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d35dcb472f5bbb5f240cbae4fed372db1eb7cc50/image.png" alt="image.png" />

Essa estrutura hoje funciona com o componente embedTools e precisamos trazer ela para a nova estrutura do BaseV2. Os desenhos que motram essa funcionalidade está disponível no figma abaixo.

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?node-id=6782%3A183557&mode=dev

## Tarefas

- [ ] Criar um componente chamado `opportunity-evaluation-committee`  dentro da pasta componente do modulo `Opportunity`

Obs.: 
- O componente deve utilizar os mesmos endpoints que ja existem. Basta fazer a configuração pelo embedTolls para ver os endpoits utilizados. Mater os mesmos parametros no requeste que tudo deve funcionar.
-  Como sugestão tulizar os componentes mc-tag-list para fazer a listagemd e categorias mostradas no print abaixo
<img width="586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--436e7e6dd5a8b2ea615024a31618dd6b4893bd95/image.png" alt="image.png" />
- Ao clicar no botão `Adicionar pessoa avaliadora` sugiro utilizar o componente `select-entity`

**Comment by israelmelo** [comment]
Componente criado, falta apenas o front @Raul-vlb

**Comment by erleibiazzio** [comment]
# Problemas de Front-End Encontrados @Raul-vlb 

- [ ] O campo `Categorias a serem avaliadas` está sem estilização. Ver print/GIF abaixo
<img width="258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--839bd3f4f04423500a8bc5f0349d77f46166372a/image.png" alt="image.png" />


- [ ] Ao clicar pela segunda vez no botão `Adicionar pessoa avaliadora` para adicionar um segundo avaliador, os dados digitados anteriormente continuam presentes no campo de pesquisa. Corrigir para que, ao fechar o modal e abri-lo novamente, o campo esteja vazio. Ver print/GIF abaixo

<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2216b99a372efffffaf996a873fb5d50af81fdc2/Peek%2029-01-2024%2015-25.gif" alt="Peek 29-01-2024 15-25.gif" />

- [ ] O componente `mc-tag-list` não está estilizado conforme o Figma quando uma ou mais categorias são definidas no campo `Categorias a serem avaliadas`. Ver print/GIF abaixo

<img width="310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a89d5dd628cafe83ed2e48f62044bde795148fb2/image.png" alt="image.png" />


- [ ] Os estilos dos botões `Desabilitar` e `Excluir` não estão de acordo com o Figma. Ver print/GIF abaixo

<img width="294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66174f84a94a10f69c4759eff48bf216192e423e/image.png" alt="image.png" />

<img width="182" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--831fa5fd5ae65a26625c5a97e043242af2991ce9/image.png" alt="image.png" />


- [ ] O texto exibido acima dos cards foi baseado em uma avaliação técnica no Figma e está meramente ilustrativo. No entanto, o texto não faz sentido em outras fases. Alinhar com @cesardelucca os textos a serem exibidos em cada avaliação. Ver print/GIF abaixo

<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--982a4931977d50a54adb85448113ecdcb1adc95e/image.png" alt="image.png" />

- [ ] Falta implementar mensagem de sucesso ou erro ao executar o autosave nos campos `Distribuição` e `Categorias a serem avaliadas`.

**Comment by Raul-vlb** [comment]
Estilização e comportamento do componente foi alterado de acordo com as modificações no figma
