### ISSUE TITLE
[Inscrições / Oportunidades] - Criar novas colunas nas entidades Registration e Opportnity

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3079]
## Descrição
Para a implementação da funcionalidade de cotas, precisaremos criar novas colunas nas entoidades Registration e Opportunity.

#### db-updates
- [x] Criar db-update para criar coluna `proponent_type` na tabela Registration
- A coluna é do tipo `string`

- [x] Criar db-update para criar coluna `range` na tabela Registration
- A coluna é do tipo `string`

#### Mapeamentos para o Banco
- [x] Criar Mapeamento da coluna `proponentType` na entidade  Registration.php
- [x] Criar Mapeamento da coluna `range` na entidade  Registration.php

## Opportunity
- [x] Criar db-update para criar coluna `registration_proponent_types` na tabela Opportunity
- A coluna é do tipo `text`

- [x] Criar db-update para criar coluna `registration_ranges na tabela Opportunity
- A coluna é do tipo `text`

#### Mapeamentos para o Banco
- [x] Criar Mapeamento da coluna `registrationProponentTypes` na entidade  Opportunity.php
- [x] Criar Mapeamento da coluna `registrationRanges` na entidade  Opportunity.php

## Atenção
- Caso faça o mapeamento primeiro usar o comando `./dev-scripts/dump-db-updates.sh | grep nome_da_coluna` para gerar o SQL
- Criar branch `feature/affirmative-policies-tiebreaker` apartir da `develop`

**Comment by rafaelchavesfreitas** [comment]
- [ ] refatorar o campo que salva as faixas para ser do tipo JSON do Doctrine (alterar o db-update)
