### ISSUE TITLE
[Oportunidades - Edição] - Implementar componente para definir faixas disponíveis no edital

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3084]
- [x] Implementar componente `opportunity-ranges-config`
- [x] os valores devem ser salvos na oportunidade na propriedade `registrationRages` na seguinte estrutura:
```JS
opportunity.registrationRanges = [
    {
        label: "Atividades formativas com 10 horas",
        limit: 70,
        value: 10000,00
    },
    {
        label: "Atividades formativas com carga horária mínima de 20 horas",
        limit: 80,
        value: 15000,00
    },
]
```
- [x] fazer um autosave com um delay de 300 milisegundos após a perda de foco de qualquer campo desde de que a linha tenha ao menos o label preenchido.
- [x] número de vagas e valor são opcionais
- [x] para a máscara do campo de valor, utilizar a configuração de moeda (`$MAPAS.config.currency`)
<img width="1877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09f6d0e038fcf46fa2144d1732469825ad484332/image.png" alt="image.png" />

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=13859-48525&mode=design&t=MtRSX4YBDi66e8y8-0

**Comment by israelmelo** [comment]
@carolinasouza0 

Obs:

**Branch:** feature/affirmative-policies-tiebreaker
**Componente:** opportunity-ranges-config (src/Modules/Opportunities/components/opportunity-ranges-config)

Caso precise alterar o novo componente currency input: (src/modules/Components/components/mc-currency-input)

**Comment by LimaSystem** [comment]
**Melhoria:**
1)  Ao salvar uma faixa(linha) com a descrição vazia, dar algum erro ou aviso.

<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--590a7453a61af70928add7a182524e3901bd45a0/image.png" alt="image.png" />
