### ISSUE TITLE
adicionar configuração da moeda (currency)

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3085]
- [x] colocar a cofiguração no arquivo 0.main.php
- [x] adicionar a configuração ao `jsObject['config']['currency']`  no arquivo `Modules/Components/Module.php` (buscar pela configuração de locale para colocar próximo)

**Comment by israelmelo** [comment]
@rafaelchavesfreitas o locale está sendo adicionado no src/core/Theme.php, coloquei a config do currency no mesmo lugar.

<img width="412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODVBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7891d1a044609a3236c8989e7326650dbeeb756/image.png" alt="image.png" />

Caso tenha que ser no Module.php mesmo, me avise que eu altero

**Comment by rafaelchavesfreitas** [comment]
@israelmelo ok, perfeito
