### ISSUE TITLE
criar componente Vue para a configuração das cotas 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3095]
- [x] implementar no módulo `EvaluationMethodTechnical`
- [x] registrar via hook o metadado `quotaConfiguration` do tipo `json` na entidade `evaluationMethodConfiguration`
- [x] chamar o componente de `affirmative-policies--quota-configuration`
- [x] os campos que aparecem no select são os da `phase.affirmativePoliciesEligibleFields`
- [x] nos campos de seleção ou seleção múltipla, exibir checkboxes com os valores
- [x] nos campos boleanos, exibir 2 radios (marcado/verdadeiro e desmarcado/falso)

- Obs.: Não será salvo a porcentagem, somente número de vagas. 
```JS
{
    vacancies: 90,
    rules: [
        {
            fieldName: 'field_33',
            vacancies: 30,
            eligibleValues: [
                'Mulher Cis',
                'Mulher Trans/Travesti',
                'Homem Trans'
            ]
        },
        {
            fieldName: 'field_55',
            vacancies: 30,
            eligibleValues: [
                'Negro',
                'Pardo'
            ]
        },
        {
            fieldName: 'field_57', // campo boolean
            vacancies: 30,
            eligibleValues: true
        }
    ]
}
```

<img width="1054" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2404a1b71d59960227cd75f09212943c4aeb7ce4/image.png" alt="image.png" />

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=14599-22938&mode=design&t=EZKPnrVXW9riV0gP-0

**Comment by rafaelchavesfreitas** [comment]
@carolinasouza0 precisamos estilizar esse componente

**Comment by rafaelchavesfreitas** [comment]
refatorar para possibilitar a configuração de mais de um campo para a mesma cota.

a interface ficará algo asism:
```
[
    descrição da cota [ Cota para negros e pardos ]   porcentage [ 20% ]   número de vagas [ 50 ]

    [campos]
        [ #33233 Raça / cor do agente responsável ]
            [ ] amerelo   [x] preto   [x] pardo   [ ] branco   [ ] indígena 

        [ #33255 Raça / cor do representante do coletivo ]
            [ ] amerelo   [x] preto   [x] pardo   [ ] branco   [ ] indígena 

        [ #33280 declaro que o representante do coletivo é preto ou pardo ]
            [ marcado \/]


    [ adicionar campo +]
]
[
    descrição da cota [ Cota para indígenas ]   porcentage [ 10% ]   número de vagas [ 25 ]

    [campos]
        [ #33233 Raça / cor do agente responsável ]
            [ ] amerelo   [ ] preto   [ ] pardo   [ ] branco   [x] indígena 

        [ #33255 Raça / cor do representante do coletivo ]
            [ ] amerelo   [ ] preto   [ ] pardo   [ ] branco   [x] indígena 



    [ adicionar campo +]
]
```

a estrutura de dados salva pelo componente ficará algo assim:
```
{
    vacancies: 90,
    rules: [
        {
            vacancies: 50,
            fields: [
                {
                    fieldName: 'field_33233',
                    eligibleValues: [
                        'preto',
                        'pardo',
                    ]
                },

                {
                    fieldName: 'field_33255',
                    eligibleValues: [
                        'preto',
                        'pardo',
                    ]
                },

                { // campo booleano
                    fieldName: 'field_33280',
                    eligibleValues: [true]
                }
            ]
        },
        {
            vacancies: 25,
            fields: [
                {
                    fieldName: 'field_33233',
                    eligibleValues: [
                        'indígena',
                    ]
                },

                {
                    fieldName: 'field_33255',
                    eligibleValues: [
                        'indígena'
                    ]
                }
            ]
        }
    ]
}

**Comment by rafaelchavesfreitas** [comment]
@Raul-vlb o campo de seleção fica vazio após recarregar a página

**Comment by LimaSystem** [comment]
**Erro:**
1) Ao configurar um formulário da coleta de dados, e não atualizar a página, ao clicar em “+ Configurar cotas”, ocorre o seguinte erro da imagem abaixo. O mesmo erro acontece se não tiver nenhum campo configurado:

_**Passos para causar o erro:**_ Criar uma oportunidade -> Configurar formulário da coleta de dados -> Criar uma avaliação técnica -> Criar configuração de cota.

_**Obs:**_ Fazer os passos sem atualizar a página
<img width="421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a8ef266882484ce48fafa36a21bf9305e045782/image.png" alt="image.png" />
