### ISSUE TITLE
criar componente Vue para a configuração das vagas/cotas por região

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3096]
- [x] implementar no módulo `EvaluationMethodTechnical`
- [x] registrar no método register do módulo o metadado `geoQuotaConfiguration` do tipo `json` na entidade `evaluationMethodConfiguration`
- [x] chamar o componente de `affirmative-policies--geo-quota-configuration`
- [x] adicionar as divisões geográficas para o jsObject no init.php. Estão em `$app->config['app.geoDivisionsHierarchy']`
- [x] os campos que aparecem no select são os da configuração de divisões geográficas da instalação (geoDivisions)
- [ ] se o número total de vagas do edital não tiver sido preenchido ainda, desabilitar os campos de percentual.

não serão salvas as porcentagens, somente o número de vagas.
```JS
{
    geoDivision: 'mesorregiao',
    distribution: {
        'Sertão': 30,
        'Agreste': 30
    }
}
```

<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97e555dad97ee0fe8dccb70a57c565f5d90e796b/image.png" alt="image.png" />

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=13859-48525&mode=design&t=pH9cPdkwX9LEJhjY-0

**Comment by Raul-vlb** [comment]
@cesardelucca o metadado foi criado com a 'titulo' de "Configuração territorial", posso manter esse texto ou achas melhor altera-lo?

**Comment by Raul-vlb** [comment]
Parte visual do componente está feita.
Falta puxar a lista de regiões de cada divisão territorial para listagem e manipulação.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0oxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e81596f85f2ff395081b5ee0fff8d11ed29751a3/Grava%C3%A7%C3%A3o%20de%20tela%20de%202024-02-20%2018-24-20.webm)

**Comment by Raul-vlb** [comment]
Falta ajustes de estilização e calculo caso seja digitado a quantidade de vagas (para saber a porcentagem referente ao total de vagas)
