### ISSUE TITLE
criar componente Vue para a configuração dos critérios de desempate

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3103]
- [x] deve ser implementado no módulo `EvaluationMethodTechnical`
- [x] registrar metadado na entidade `evaluationMethodConfiguration`
- [x] no primeiro select da configuração de um critério de desempate, exibir os campos de seleção, booleanos, data e numéricos (#3100), além das opções
  - Nota de um critério de avaliação
  - Média de uma seção de critérios de avaliação
 

- [x] para campos numéricos e data exibir um select com 2 opções
  - dar preferência ao menor valor
  - dar preferência ao maior valor
- [x] para campos booleanos exibir um select com 2 opções
  - dar preferência para o valor marcado
  - dar preferência para o valor desmarcado
- [x] para campos de seleção ou seleção múltipla, exibir as opções com checkboxes abaixo do label "Dar preferência a:"
- [x] se estiver selecionado "nota de um critério de avaliação" exibir um select com a lista de todos os critérios de avaliação em `optionsgroups` com o label da seção
- [x] se estiver selecionando "média de uma seção", deve exibir um select com  a lista das seções

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=14182-19017&mode=design&t=XeqNoAtgzznlP0M9-0

**Comment by LimaSystem** [comment]
@rafaelchavesfreitas 

O componente esta salvando normalmente. Porem ele deveria salvar como um array ou não? É assim que esta sendo salvo no banco de dados: 

<img width="458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e09c047cfad1cf2d8cd05f0fe930c02cf84ea175/image.png" alt="image.png" />
