### ISSUE TITLE
ao consolidar o resultado da avaliação técnica, definir o valor da coluna score

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3107]
na ação de consolidar o resultado das avaliações técnicas de uma inscrição:
- [x] definir/atualizar o valor da coluna score
- [x] propagar o valor para as `registration` das próximas fases

**Comment by LimaSystem** [comment]
**Problema:** 

- O valor da coluna score esta sendo salvo normalmente. Porem não esta propagando o valor para proxima fases
