### ISSUE TITLE
definir o valor da coluna eligible das registrations da fase de avaliação técnica

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3108]
- [ ] definir vaor da coluna
- [ ] propagar o valor para as inscrições da fase seguinte

usar o método criado na issue #3109

### tem duas situações possíveis:
1. fase de avaliação técnica precedida por uma fase de coleta de dados
  - definir o valor da coluna `eligible` no envio da inscrição ou no update quando o status for maior que zero (pensando no suporte)
2. fase de avaliação técnica precedida por outra fase de avaliação
  - definir o valor da coluna `eligible` na criação da registration

**Comment by LimaSystem** [comment]
**BUG**:

1) Quando habilitada a pergunta e configurado uma cota, no proponente quando está marcada ou desmarcada opção “Deseja concorrer por cotas ou participar das políticas afirmativas” o campo eligible ainda continua retornando null ao invés de true ou false.
