### ISSUE TITLE
Criar componente Vue para a confuguração dos critérios de avaliação técnica 

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3122]
- [x]  estilizar
- deve usar a mesma estrutura de dados utilizada pelo angular
- a implementação será a mesma que existe atualmente, ou seja:
    - ainda não terá configuração do peso da seção
    - ainda não terá configuração da categoria da seção

<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fc7af6e45537de08450dfa447daae60f497e73c/image.png" alt="image.png" />

https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=14224-14726&mode=design&t=YIWoBUs4agPMRCtX-0

**Comment by erleibiazzio** [comment]
## QA - Validação funcional

# Ambiente para simular [Criar uma oportunidade com uma fase de coleta de dados e uma avaliação técnica]

- [ ] Quando se cria um fase de avaliação técnica, o componente de configuração de critérios so é exebido após o reload da página. 
- P comportamento esperado e que quando se crie a fase e em seguida clicar em expandir, o componente ja esteja disponível para configurações sem reload. 
<img width="1107" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXl0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7948261dbefb76eb3cadf58da104626d81c30f85/reatividade.gif" alt="reatividade.gif" />
