### ISSUE TITLE
aplicar avaliações da fase de avaliação técnica considerando as cotas - implementar a possibilidade de mudar de status por ranking da inscrição

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3130]
deve ter os botões:
-  **selecionar os primeiros** com um campo para informar um número, que já deve vir preenchido com o valor do total de vagas no edital e um checkbox já marcado  `[ ] considerar as cotas`
- **eliminar as inscrições com nota inferior a nota de corte**
- **marcar como suplente as inscrições com nota acima da nota de corte mas que não foram selecionados** (posição inferior ao máximo de vagas)

**Comment by israelmelo** [comment]
**Erros:**

1) [ ] Quando selecionado as opções “Selecionar os primeiros” e  “Considerar cotas”, está selecionando inscritos que não são cotista e com nota bem inferior da nota de corte.
2) [ ] Quando selecionado as opções “Marcar como suplente” e  “Considerar cotas”, está selecionando inscritos que não são cotista e com nota bem inferior da nota de corte.
3) [x] Eliminar inscrições está eliminando até quem está como suplente (caso for um cotista) - Fazer operação apenas quando status for igual a pendente:

**Comment by rafaelchavesfreitas** [comment]
## Refatoração
- [ ] colocar 2 abas: "Por pontuação" e "Por classificação"
- [ ] o botão aplicar deve enviar o tipo de aplicação (por pontuaçãou ou por classificação)
- [ ] o botão aplicar deve enviar somente as informações necessárias para o tipo de aplicação selecionado
- [ ] o componente `mc-tabs` tem um evento `@changed` que pode ser usado para obter a aba ativa
- [ ] no init.php do componente adicionar a informação `$data['isAffirmativePoliciesActive'] = $phase->isAffirmativePoliciesActive();` ao jsObject para utilizar na verificação se as quotas estão ativas.
- [ ] só exibir o checkbox "considerar cotas" se as cotas estiverem ativas
- [ ] a informação do **total de vagas** deve ser obtida da primeira fase da oportunidade (pode passar essa informação no init.php se for mais fácil)
- [ ] a intormação **nota de corte** deve ser obtida da fase atual

<img width="434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f9cd546e21b29390cfb15df3f779cbb48ae904e/image.png" alt="image.png" />
<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7556e7552596713af4ca562bf9b04d0dd4d3ad44/image.png" alt="image.png" />
