### ISSUE TITLE
implementar função de desempate de inscrição

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3136]
- a função será usada para ordenar as inscrições que tiveram o mesmo score. 
- usaremos a função usort do PHP passando a função criada como parâmetro (https://www.php.net/manual/en/function.usort.php)
- a função deve receber 2 inscrições e retornar os valores 1 ou -1
- a função deve considerar os critérios de desempate configurados no componente da issue #3103
- se mesmo considerando os critérios de avaliação as inscrições permanecerem empatadas, utiliza o sentTimestamp como critério de desempate, dando prioridade para quem enviou primeiro

**Comment by LimaSystem** [comment]
**Erros:**

1) Na lista de inscrições quando seleciona os registros por “pontuação final CONSIDERANDO AS COTAS”, ocorre o seguinte erro da imagem abaixo (pois não tem nenhuma cota configurada):
	
	<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1hQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3154ffd82bf4f847866e2dd6f2b827fdfc84e8df/image.png" alt="image.png" />

	
2) Quando criado o “quotaConfiguration” e carrega a lista, aparece um inscrito a menos no ranqueamento.
 
**Melhoria:**

1) Caso não tenha nenhuma cota configurada, a opção de ordenação “pontuação final CONSIDERANDO AS COTAS” não aparecer.

**Comment by rafaelchavesfreitas** [comment]
- [ ] implementar desempate por média de nota de um critério de avaliação
- [ ] implementar desempate por média de nota de uma seção de critérios de avaliação
