### ISSUE TITLE
substituir a tabela de resultado publicado na single de oportunidade pelo componente opportunity-registrations-table

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#3160]
deixar disponível somente as colunas `number, owner, category, proponentType, range, score e status`

**Comment by israelmelo** [comment]
## Problemas

- [x] Resultado final não tem tradução e está retornando erro no console
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35c5d2309cdbf1e786c9532157141f30375c3084/image.png" alt="image.png" />

- [x] Coluna agent/owner não aparece como visível por padrão
