### ISSUE TITLE
Criar nova view para configuração do suporte

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3168]
## Descrição
Atualmente para configurar um agente de suporte, devemos acessar a aba de `Inscrições e resultados`, ir até a fase de Coleta de dados desejada e ao clicar no suporte, é aberto um modal que carrega um embedtolls para selecionar um agente. Ver Gif abaixo.

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1461f4dc4bbb4556d1f0fd674d36beed2c75dafc/Peek%2025-04-2024%2010-23.gif" alt="Peek 25-04-2024 10-23.gif" />

Porem hoje no figma devemos ter um view que faz essa configuração.

## Tarefas

- [x] No módulo de suporter criar nova view `support-config.php`
- [x] Criar endpoint `GET_suportConfig` que carregue a view
- [x] Criar endpoint `GET_suportConfig` no controller do Módulo
- [x] Criar alias para rota de suporte no arquivo routes.php para usar Url amigável `'suporte/configuracao'  => ['support', 'suportConfig']` com isso será possivel chamar o endpoint com `http://localhost/suporte/configuracao`
- [x] Na aba de `Inscrições e resultados` ajustar para que ao invéz de abir o modal ao clicar no suporte, abrir a nova view
- [x] Criar componente ´opportunity-support-config´ que sera responsável por gerênciar todas as partes da configuração

## Observações
- Criar branch `feature/new-support-structure` apartir da develop
-  Para implementar, usar como referência o figma abaixo
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=6782-184398&mode=design&t=9QT6DE3oXOJQ4jWV-0

**Comment by LimaSystem** [comment]
Parte funcional da implementação esta pronto. Agora so falta a parte da estilização seguir o figma abaixo https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=6782-184398&mode=design&t=9QT6DE3oXOJQ4jWV-0

**Comment by erleibiazzio** [comment]
# Testes Front-end

- [ ] Quando entramos na view de suporte, pelo figma a tela deveria ficar toda centralizada e a mesma se encontra ocupando 100% da tela. Ver print1s abaixo.

## Como está
<img width="1679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5514ce7e00dfce57571c0f781401570b4b1e7a35/image.png" alt="image.png" />

<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekhKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60cd342138bfed1d3aa6e7de6aac216a06dfbd8c/image.png" alt="image.png" />


## Como deveria ser
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7f8abce1445444db79150aec02d6117c861791d/image.png" alt="image.png" />

- [ ] Ao clicar no botão Adicionar agente, o select de agentes aparece no centro da tela ver GIF abaixo. Fazer com que ele apareça proximo ao botão do lado direito. 
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b562cee5c679855c55c213fea865816e0e41bdd/Peek%2009-05-2024%2009-00.gif" alt="Peek 09-05-2024 09-00.gif" />

- [ ] O Botão de voltar no Header nao esta conforme o Figma

## Como está
<img width="1790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6c8eae3e07207ef04ac2c93f5d814090fea476f/image.png" alt="image.png" />

## Como deveria ser
<img width="1217" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18a016e1e6015aec0849a746a7a08f92ab22ab34/image.png" alt="image.png" />

- [ ] Ajustar espaçamentos dos selects para usar o padrão do Mapas

## Como esta no Suporte
<img width="205" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25f588f301262695f9f76f4dfc6664050f2bcbab/image.png" alt="image.png" />


# Testes Funcionais

- [ ] Ao clicar no botão de voltar, devemos voltar para edit da oportunidade e não pra single. Ver GIF abaixo

<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ad653574e43d5cece141deb636b9525df5143af/Peek%2009-05-2024%2009-06.gif" alt="Peek 09-05-2024 09-06.gif" />

- [ ] Falta TIPO do campo no modal de permissões

## Como está
<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae6436caf2609b1049318cfe6177a34a9e03e5e7/image.png" alt="image.png" />

## Como deveria ser
<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6a271fced438536ffc58a971e2f5e25a8163572/image.png" alt="image.png" />

**Comment by erleibiazzio** [comment]
## Descrição
Durante reunião com Rafa, decidimos que o modal de permissões irá ter alguns filtros para filtrar os campos por
`Categoria`, `Faixa` e `Tipo de proponente`

## Tarefa

- [ ] Implementar no figma desenhos dos filtros @PabloNicolela 
- [ ] Implementar no Componente filtros conforme o figma @Raul-vlb

**Comment by PabloNicolela** [comment]
FIltros aplicados.
