### ISSUE TITLE
Aplicar correções no entity-table

### ISSUE THREAD

**Issue by Raul-vlb** [mapasculturais/mapasculturais#3172]
Correção nos filtros por status:

- [x] Criar novo dict para os status de pagamentos
- [x] Corrigir listagem de filtros aplicados na tabela de pagamentos
- [x] Remover da listagem de filtros os ids das oportunidades vinculadas à tabela de pagamentos

**Comment by carolinasouza0** [comment]
- [ ] Acrescenta ícone de configurar colunas na tabela do plugin de pagamento
- [ ] Acrescenta prop identifier na tabela do plugin de pagamento.
- [ ] Ajuste mudança da propriedade checked do checkbox dos filtros de status para que mudem ao limpar filtros
