### ISSUE TITLE
Gestor da oportunidade não consegue ver a mesma quando ela esta como Rascunho

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3176]
## Descrição
Com perfil administrativo, criei uma oportunidade e coloquei um agente comum como gestor da mesma. Porem o gestor não consegue ver ou acessar a oportunidade antes de que eu publique

**Comment by rafaelchavesfreitas** [comment]
essa issue é a mesma que a #2954
