### ISSUE TITLE
[Inscrições] - Implementar cookie que salva as colunas selecionadas no entity-tabe

### ISSUE THREAD

**Issue by erleibiazzio** [mapasculturais/mapasculturais#3206]
## Descrição
Hoje quando escolhemos as colunas que devm ser exibidas no entity-tabe e posterior a isso atualizamos a página (refresh), a seleção que foi feita se perde.

A ideia é que esse estado seja guardado em um cookie e recuperado sempre.

## Tarefa
- [x] Criar cookie que salve o status das colunas exibidas no entity-tabe
- [x] Fazer com que o entity-tabe leia o cookie e carrega as colunas conforme esta salvo

Obs.:
- Salvar colunas separadas por oportunidade e tipo de lista, para isso o cookie deve ter a seguinte estrutura
```
{
    'id_portunidade': {
        registrations: {
            visible: {},
        },
        evaluations: {
            visible: {},
        },
        payments: {
            visible: {},
        }
    }
}
```

**Comment by Raul-vlb** [comment]
Dados estão sendo salvos no localStorage

ex.: 
```
localStorage[controller:id:endpoint] = "coluna1,coluna2,coluna7,coluna10..."
```
