### ISSUE TITLE
refatorar agenda das singles das entidades

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#325]
NA SINGLES AGENTEM, EPAPAÇO E PROJETO, ao clicar na aba agenda, temos apenas um filtro por período, seria necessário um filtro linguagem

**Comment by rafaelchavesfreitas** [comment]
- Na agenda de **projeto** vir filtrado pela data em que acontece o projeto (depende do novos campos de data nos projetos)
- adicionar filtros por palavra-chave, linguagens
- adicionar link ver no mapa (exceto para a agenda de espaço), que leva para o mapa da busca filtrado para exibir os eventos da agenda
- usar scroll infinito
- refatorar a lista de eventos para exibir agrupados por dia e ordenados pela hora, repetindo os eventos em cada dia que ele aparece, exemplo (no casi de ser um agenda de espaço, não mostra o nome do espaço :
  
- sexta-feira, 26 de junho de 2015
    - 11:00 - Nome do evento X
descrição curta do evento X
Theatro Municipal, gratuito.
    - 12:00 - Nome do evento Y
descrição curta do evento Y
Matilha Cultural, gratuito
Cine Sesc, R$ 10,00
- sábado, 27 de junho de 2015
  - 11:00 - Nome do evento X
descrição curta do evento X
Theatro Municipal, gratuito.
