### ISSUE TITLE
Melhorar "copy"

### ISSUE THREAD

**Issue by seufelipe** [mapasculturais/mapasculturais#403]
acho que esse é um trabalho constante. são vários detalhes, em diferentes frentes:
- maiúsculas/minúsculas: alguns textos de botões em minúsculas outros em minúsculas; temos entidades sempre começando com maiúsculas e outras vezes não;
- redundâncias: desde "adicionar ~~nova~~ entidade" em botões até "url: adicione a url do seu site" nos campos editáveis;
- pouco úteis: no caso da "descrição curta", por exemplo, podemos ter: "é a descrição que vai aparecer nas listagens e quando alguém compartilhar no facebook. é diferente da descrição longa por..." ou algo assim;
- rude: temos um "primeiro salve" ali num botão!

como fazemos isso? eu posso ficar responsável e ir alterando, ou discutimos cada alteração antes?

**Comment by rafaelchavesfreitas** [comment]
precisa levantar todas as alterações necessárias.
