### ISSUE TITLE
Atribuição de indicação de data nos arquivos gerados pelo botão EMCARTAZ

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#486]
solicito tb avaliação de vcs se as notificações cumpririam esse papel. Haverá um ambiente de adm das notificações (entidade notificações confere?)

Luíza da EM CARTAZ
## "Há alguma forma de, no próprio arquivo, sair uma indicação de quando ele foi gerado? Tipo: “Arquivo gerado em 24/09/2014”, no próprio corpo do texto? Assim evitamos problemas relativos a discussões sobre as datas em que os eventos foram inseridos."

"Acho que só o dia em que o arquivo foi gerado. Porque daí eu chego no dia 5 e gero o arquivo, e ele vai apontar a data.
Com isso, todo evento que entrar depois dessa data não será incluído na Em Cartaz e, caso digam que inseriram o evento na data prevista mas isso não foi realmente feito, tenho o arquivo gerado pelo sistema para comprovação.
Se fosse possível acho que poderia ter nos eventos, apenas na plataforma, um aviso de “evento gerado em 12/02 e modificado pela última vez em 15/02”, mas algo pequeno, só para visualização na página.
O que acha?"

**Comment by daphnemartinsba** [comment]
Funcionalidade "Em Cartaz" era do SPCultura. Não é mais utilizada nos Mapas atualizados.
