### ISSUE TITLE
NA SINGLE PENDENTE ASSINALAR A PENDÊNCIA tem a ver com a issue #249

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#489]
isso seria para tudo, espaços, agentes e eventos.

Quando houvesse uma requisição de troca deixar claro na single que aquele "post" está pendente. Com poucas notificaçõe não seria necessário mas pensando num volume de requisições e trocas, seria massa além de no painel (onde vc pode filtrar por notificações pendentes) vc tb poder ver que a publicação x está pendente com algum tipo de sinalização.

**Comment by rafaelchavesfreitas** [comment]
isso deve entrar numa futura refatoração das notificações
