### ISSUE TITLE
Exportar dados das abas de agendas das entidades. Ter essa possibilidade (botão) na barra dos filtro de tempo

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#491]

**Comment by rafaelchavesfreitas** [comment]
relacionada a #325

**Comment by daphnemartinsba** [comment]
Na versão v5.1.47, no ambiente do PA, o botão supracitado consta na barra dos filtros de tempo. Como segue na imagem abaixo: 
![image](https://user-images.githubusercontent.com/75261677/153208528-647d4f83-17b9-40ee-a8ae-1e104f7348a6.png)
