### ISSUE TITLE
Ao excluir um espaço filho migrar ocorrências dos eventos para o espaço pai.

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#492]
Olá,
isso aqui será um problema pelo seguinte.
Se por um acaso um equipamento cultural sofrer reforma algum sub-espaço pode desaparecer. Uma pessoa desavisada pode por a perder anos de informações sobre o espaço pai. Por padrão seria interessante que ao excluir um filho, os eventos continuem vinculados (migrados) ao espaço pai como a interface já nos apresenta (quando ainda existe o filho).

**Comment by daphnemartinsba** [comment]
Entra no escopo da issue #504.
