### ISSUE TITLE
PAINEL ::  ao apagar agentes, espaços, eventos ou projeros a contagem não retrata a realidade

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#520]
mesmo quando excluído definifivamente

**Comment by rafaelchavesfreitas** [comment]
o problema foi resolvido parcialmente, agora há um cache que dura o tempo configurado no config.php
uma solução possível é implementar um modo de consultar a api falando pra não utilizar o cache (não é uma boa ideia que essa opção esteja disponívell via http)
