### ISSUE TITLE
"checkbox" usar opções de inscrições

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#598]

**Comment by rafaelchavesfreitas** [comment]
colocar um checkbox na seção **3. Opções** para ligar (habilitar) ou desligar o uso das opções (categorias) nas inscrições

**Comment by daphnemartinsba** [comment]
Na versão v5.1.47 a falta de configuração das Opções tem o comportamento de Opções desabilitadas e para habilitá-las basta configurá-las. Portanto, um checkbox pode ser apenas uma burocratização do fluxo.
