### ISSUE TITLE
botão regulamento ter nome editável

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#608]

**Comment by marylly** [comment]
@ariadnemelo, poderia transformar a palavra "Regulamento" do sistema num conteúdo do método getText, por favor?

**Comment by rafaelchavesfreitas** [comment]
@ariadnemelo e @marylly na verdade a ideia é que o nome seja editável no formulário de edição do projeto...

**Comment by marylly** [comment]
para que cada projeto possa ter seu próprio label do botão onde é "regulamento" @rafaelchavesfreitas ? E a palavra regulamento é utilizada em várias partes do projeto, faz sentido isso ser só no botão do formulário da inscrição do projeto?

**Comment by rafaelchavesfreitas** [comment]
não, é para todos os lugares onde aparece a palavra regulamento

**Comment by daphnemartinsba** [comment]
Implementado na ESP. Será atualizada na versão 5.2.0 do Mapas Culturais.
