### ISSUE TITLE
Generalizar o nome dos papeis de usuários e botar uma opção por tema para definir esses nomes

### ISSUE THREAD

**Issue by leogermani** [mapasculturais/mapasculturais#620]

**Comment by marylly** [comment]
@leogermani seria algo parecido com o Text dos temas onde existe um texto padrão, mas pode ser substituído por outro texto?

**Comment by leogermani** [comment]
Nem lembrava disso. Mas sim.

Acho que essa demanda existia muito mais por conta do papel "membro da equipe", e que aí de instalação pra instalação podia mudar bastante... (pq tava equipe SP Cultura fixo).

Não sei se agora com a coisa dos selos, com esse papel caindo em desuso... se isso ainda é necessário

**Comment by marylly** [comment]
Qual aspecto do selos que pode fazer a questão dos papéis cair em desuso @leogermani ?

**Comment by leogermani** [comment]
dos papéis não, do papel "membro da equipe".

hoje temos:
usuario comum
membro da equipe
admin
superadmin

a única coisa que o membro da equipe faz é poder botar o selo verificado.

Com o novo esquema de selos, essa permissão vai ser por selo, e não geral para o site. então esse papel específico não faz mais sentido.

Então na real, além do usuário comum, vamos ter admin e superadmin (não sei como ficou com o lance do Saas). Mas não sei se tem necessidade de ter nomes customizáveis.

**Comment by marylly** [comment]
Eu acredito que isso são coisas distintas, porque a atribuição do selo não é pelo papel, e sim pela permissão de edição concedida ao agente. 
Acredito que podemos manter, porque existem novos papéis com a entrada do SaaS.

**Comment by marylly** [comment]
@ariadnemelo acredito que você pode iniciar com as atividades pelo core com esta issue. Vamos agendar um HangOut, ok?
