### ISSUE TITLE
REFACTOR PAINEL: opção de ordenação das entidades

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#623]

**Comment by donsalvatore** [comment]
Como padrão

Em meus agentes: 
1 - o agente padrão deve ser sempre o primeiro de lista
2 - os demais em ordem alfabética

Em minhas incrição
1 - sempre a última inscrição em primeiro

Em meus eventos
1 - o mais recente em primeiro

Em meus espaços
1 - ordem alfabética

Em meus projetos
1 - ordem alfabético

**Comment by marylly** [comment]
@nreek avaliar este, se estiver ok, só encerrar, ok?
