### ISSUE TITLE
Responsivo: fazer a div.descricao-do-agente aparecer no clique ao invés do hover

### ISSUE THREAD

**Issue by catkit** [mapasculturais/mapasculturais#637]
Na sidebar direita, nos agentes relacionados, quando passa o mouse sobre o avatar aparece uma div.descricao-do-agente. Fazer um js pra aparecer no clique pra funcionar em mobile.

**Comment by ariadnemelo** [comment]
@marylly esse componente só aparece na página de edição do projeto, entretanto no mobile a barra para acessar a edição não aparece, não sei se precisamos rever isso primeiro? pois se a idéia é que o usuário não possa editar em dispositivos mobile essa funcionalidade não faz sentido

**Comment by marylly** [comment]
@ariadnemelo vou avaliar a funcionalidade, se não faz sentido, a gente pode encerrar, dou retorno ainda hoje!

**Comment by marylly** [comment]
@ariadnemelo aparece sim, se você scrollar até o final, a sessão de agentes é exibida no final no app, ao clicar no agente para ver os dados, ele exibe a div para esquerda cortada. Se não conseguir exibir, posso te mostrar.

**Comment by marylly** [comment]
@ariadnemelo não está mais exibindo o info-box no mobile :/
