### ISSUE TITLE
Conteúdo da aba inscrições e da mensagem com a data na aba 'sobre' após encerramento

### ISSUE THREAD

**Issue by catkit** [mapasculturais/mapasculturais#654]
Atualmente, depois que um edital é encerrado o conteúdo da aba inscrições está vazio e o da mensagem com as datas na aba 'sobre' permanece o mesmo.

Acho que isso está muito estranho. Minha sugestão é:
- Modo de visualização:
  - ocultar a aba "inscrições";
  - trocar a mensagem com as datas por:
  - quando os resultados ainda não foram publicados: "Inscrições encerradas. Aguarde os resultados que serão publicados neste site" e ocultar o botão "inscrições online".
  - quando os resultados forem publicados: "Inscrições encerradas" e um botão "ver resultados" que direciona pra aba de resultados.
- Modo de edição:
  - na aba inscrições manter vazia, mas mostrar a mensagem: "As inscrições para esse projeto já foram encerradas e os resultados publicados. Não é mais possível editar o formulário de inscrições online."
  - idem ao modo de visualização.

**Comment by leogermani** [comment]
Ta perfeito Catia. Apenas tire o "Aguarde os resultados que serão publicados neste site", deixa só "Inscrições encerradas" nesse caso e o botão para ver resultados quando forem publicados.

**Comment by catkit** [comment]
Precisa de programação que eu não sei fazer

**Comment by marylly** [comment]
@nreek avalia e verifica o que precisa ser feito, por gentileza. 
Se precisar de ajudar, me chama!

**Comment by rafaelchavesfreitas** [comment]
não faz mais sentido
