### ISSUE TITLE
Na HOME botão da busca utilizando enter não funciona

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#676]

**Comment by leandrodb** [comment]
No firefox

**Comment by marylly** [comment]
@ariadnemelo poderia testar esse item? é na página principal do mapas.

**Comment by marylly** [comment]
@ariadnemelo poderia testar esta situação, por gentileza? É na primeira página do Mapas quando acessado a url do sistema.

**Comment by ariadnemelo** [comment]
@marylly aqui não está funcionando nem no Chrome e nem no Firefox, mas pelo o que entendi a pessoa precisa escolher uma das opções de busca? a busca com o enter seria algo geral no site, coisa que não existe atualmente?
