### ISSUE TITLE
Cadastro de endereço fora do perímetro do shapefile da cidade ou região

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#678]
O mapa tem ficado sujo por conta da desatenção dos usuários. 

Sugestão comentada com @leandrodb seria a seguinte.

Depois de cadastrado o endereço e ao clicar salvar, o sistema deveria responder com um alerta tal qual a dos campos obrigatórios (levando o usuário até o problema).

O alerta seria: você cadastrou um pin fora da área do município x você deseja deixar o pin fora desta região assim mesmo? (algo assim)

relacionada às issues #495, #528 e #658

**Comment by leandrodb** [comment]
Relacionada também à branch [devel geocoding](https://github.com/hacklabr/mapasculturais/commits/devel-geocoding)

**Comment by rafaelchavesfreitas** [comment]
com a refatoração dos endereços e consulta na api de CEP este problema deve ter diminuido bastante, mas o alerta é legal! :)
