### ISSUE TITLE
Configurar o Google Analytics para os diferentes domínios

### ISSUE THREAD

**Issue by leandrodb** [mapasculturais/mapasculturais#679]

**Comment by leandrodb** [comment]
[Tracking Multiple Domains - Web Tracking (ga.js)](https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingSite)

**Comment by marylly** [comment]
Isso parece ser uma sugestão de solução, certo @rafaelchavesfreitas @brunosmartin ?

**Comment by rafaelchavesfreitas** [comment]
o lance é criar uma configuração para definir as chaves do analytics que hoje estão hardcoded.

**Comment by leogermani** [comment]
Se ajudar, já tem um plugin feito: https://github.com/LibreCoopUruguay/mapasculturais-googleanalytics

**Comment by leogermani** [comment]
Isso foi feito? Usaram o plugin?

Lembrando que tem um tempo já que tiramos o Google Analytics do core.
