### ISSUE TITLE
criar encurtador para o share da busca

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#691]
não está funcionando o compartilhamentono facebook

**Comment by leandrodb** [comment]
No Telegram funciona parcialmente. Por exemplo este link deveria mostrar resultados de Espaços filtrados próximos a um endereço http://spcultura.prefeitura.sp.gov.br/busca/##(global:(enabled:(space:!t),filterEntity:space,locationFilters:(address:(center:(lat:-23.59561,lng:-46.64879429999996),text:'Rua%20Diogo%20de%20Faria%201247'),enabled:address),map:(center:(lat:-23.59561011802129,lng:-46.64889335632324),zoom:13))) 

Funciona ao postar aqui no GitHub, mas no Telegram `##` é substituído por `#%23` e o router do Angular parece redirecionar para a busca padrão de Agente com um novo `#` ao final.

Não sei se é caso de criar um encurtador ou de corrigir esses pequenos problemas enquanto o encurtador não fica pronto.

**Comment by leogermani** [comment]
Hoje no master o campo da URL para share ta vazio. Ia ver esse bug mas achei essa issue aqui.

Qual é a ideia de fazer um encurtador? criar um hash e salvar no banco? mas aí tem q "registrar" a url, o cara não poderia simplesmente copiar e colar ali daquele campinho... me parece chato...

alguma outra ideia?

**Comment by uira** [comment]
O registro da url não pode ser automático/transparente?
