### ISSUE TITLE
necessidade notificação de evento em espaço sem restrição de publicação

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#695]
Os espaços sem restrição de publicação devem gerar para os seus criadores (agentes que criaram o espaço) uma notificação de que o agente x criou o evento "z" do projeto "k" no espaço "y" no dia tal e hora tal... assim o painel vira o espaço de gestão da informação e de acompanhamento do que tem sido feito ainda que isso apareça na aba agenda do espaço.

Essa issue pode ajudar no fato de envio de mails... o dono do espaço recebe um mail com a criação desta atividade.

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.47](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.47) do Mapas, no ambiente de teste do PA, o comportamento atual é semelhante ao descrito acima, contudo, o projeto foi trocado pela data e hora. 
Segue a imagem da solicitação:
![image](https://user-images.githubusercontent.com/75261677/153662356-2f8a9941-e8c0-4d13-8dfa-0dd9f549eecc.png)
