### ISSUE TITLE
atribuição de espaço à um agente de um agente

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#713]
Desculpem pelo título mas encontrei o seguinte caso.

 a agente Jo Freitas id 1131 ( http://spcultura.prefeitura.sp.gov.br/espaco/814/) assina por estes espaço. 
Mas esse agente deve ter sido deletado.

Acontece que a Jô freitas existe ( http://spcultura.prefeitura.sp.gov.br/agente/1207/ ) ela deve ter criado o agente 1131 e depois o apagou. O sistema deveria atribuir o espaço ao agente padrão do log, no caso o agente 1207.

**Comment by marylly** [comment]
@donsalvatore eu acredito que o melhor para resolver essa situação é validar a deleção do agente. Informando que existe registros de entidades em poder do agente que está sendo deletado, e que precisa ser mudado antes da deleção do mesmo.

**Comment by leogermani** [comment]
Essa deve ir para 3.1?

**Comment by daphnemartinsba** [comment]
Na versão [v5.1.47](https://github.com/mapasculturais/mapasculturais/releases/tag/v5.1.47) do Mapas Culturais, ao deletar um Agente é possível escolher que um outro Agente no Mapas receba suas entidades:
![image](https://user-images.githubusercontent.com/75261677/153667450-f4943bf2-e5e0-4a9f-9cf3-e5a752584262.png)
