### ISSUE TITLE
PROJETOS :: EDITAIS inscrições visualiação de inscrição não enviada pelo adm e/ou agente criador

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#719]
O agente que criou o edital é incapaz de ver quem se inscreveu e não enviou.

Essa informação seria interesse pois pode servir para avisar sobre a pendência e que o prazo está terminando e.ou para criar mailing de divulgação para outros editais da mesma natureza. Tb é um indicativo do interesse e/ou procura pelo edital.

**Comment by donsalvatore** [comment]
complementa a issue #726

**Comment by marylly** [comment]
@donsalvatore acredito que agora isso aconteça, o gestor consegue visualizar as inscrições iniciadas, porém, que não foram enviadas. Poderia checar essa situação, por gentileza?
