### ISSUE TITLE
Ceder propriedade de agentes ::  possível falha

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#723]
Pelas regras do sistema, se eu tenho um "agente coletivo x" e dou poder a outro agente, este pode editar o perfil desse meu "coletivo x" ou publicar por ele. isso ok!

Ele tb, não pode alterar quem publicou "esse agente x", em outras palavras, ele não pode mudar o proprietário ou criador desse agente coletivo. isso ok! para não dar a possibilidade de rapto do agente.

Porém encontrei o que pode ser uma brecha. Esse outro agente ao qual dei poderes pode "ceder a propriedade" para qualquer outro agente, forma de ludibriar o impedimento de alteração.

**Comment by rafaelchavesfreitas** [comment]
Não entendi bem Miguel. Me mostra isso amanhã? Você vai no hacklab?
Em 03/05/2015 21:45, "Miguel Salvatore" <notifications@github.com> escreveu:

**Comment by donsalvatore** [comment]
opa!! pode deixar.
vou sim... depois do almoço

Em 3 de maio de 2015 22:12, rafaelchavesfreitas <notifications@github.com>
escreveu:

> Não entendi bem Miguel. Me mostra isso amanhã? Você vai no hacklab?
> Em 03/05/2015 21:45, "Miguel Salvatore" <notifications@github.com>
> escreveu:
>
> > Pelas regras do sistema, se eu tenho um "agente coletivo x" e dou poder a
> > outro agente, este pode editar o perfil desse meu "coletivo x" ou
> publicar
> > por ele. isso ok!
> >
> > Ele tb, não pode alterar quem publicou "esse agente x", em outras
> > palavras, ele não pode mudar o proprietário ou criador desse agente
> > coletivo. isso ok! para não dar a possibilidade de rapto do agente.
> >
> > Porém encontrei o que pode ser uma brecha. Esse outro agente ao qual dei
> > poderes pode "ceder a propriedade" para qualquer outro agente, forma de
> > ludibriar o impedimento de alteração.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hacklabr/mapasculturais/issues/723>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/mapasculturais/issues/723#issuecomment-98562960>
> .
>



-- 
Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502

**Comment by donsalvatore** [comment]
Avaliar a questão

o sistema dá permissão negada mas não dá feedback nenhum.
avaliar se extraimos o botão ou pensamos num texto.
