### ISSUE TITLE
ENTIDADE PROJETO :: botão de publicar resultado quando incompleta gera confusão

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#757]
Depois de preencher uma ficha de edital incompleta, ao clicar sobre o botão de publicar resultado, o sistema parece não responder pq nenhuma mensagem é indicada e o brower não faz o scroll para os campos com os  sinais de alerta em vermelhos (exclamação).

**Comment by marylly** [comment]
@nreek se precisar de ajuda para verificar este item, pode me chamar. Se não estiver com problema, só encerrar esta issue.
