### ISSUE TITLE
PROBLEMA EM CARTAZ :: gestão da info da revista em cartaz inviável

### ISSUE THREAD

**Issue by donsalvatore** [mapasculturais/mapasculturais#758]
A revista é mensal. Mas como o spcultura puxa na single evento as ocorrências de todos os meses, ao fazê-lo acontece que em eventos que ocorrem em mais de um mês, rola uma funça de ficar pescando no arquivo .doc (em cartaz) esses eventos e deletar os meses anteriores. Totalemmte anti funcional.

 Exemplo. Mostra de março a junho. No arquivo em cartaz de maio eles não tem como saber quais os eventos começaram em março/abril pra poder deletar. Pois a info do passado não pode sair na revista impressa.

A prioridade é alta pq o sistema está engordando e faz parte da rotina dos funcionários. Mensalmente eles terão este problema.

**Comment by daphnemartinsba** [comment]
Funcionalidade "Em Cartaz" era do SPCultura. Não é mais utilizada nos Mapas atualizados.
