### ISSUE TITLE
Inserir o tipo “inscrições” na tipologia de Projetos

### ISSUE THREAD

**Issue by thaisrigolon** [mapasculturais/mapasculturais#957]
Fica faltando inserir o tipo “inscrições” na tipologia de Projetos, uma vez que o módulo serve para realizar a gestão de inscrições de workshops.

**Comment by daphnemartinsba** [comment]
A inserção foi realizada:
![image](https://user-images.githubusercontent.com/75261677/151600111-da06f134-8d12-463e-bcb3-3de7650adc58.png)
